-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Server/Command/BattleProtocolToRoom.lua

local BattleProtocolToRoom = {
	RESP_JOIN_GAME_IN_ZONE = 421,
	RESP_BEGIN_GAME_LOADING = 412,
	REQ_MATCH_GAME = 400,
	REQ_CONFIRM_ENTER_GAME = 404,
	RESP_CONFIRM_HERO = 411,
	RESP_MATCHED_PLAYER_LIST = 403,
	RESP_REMATCH_GAME = 416,
	RESP_CHOOSE_HERO = 409,
	REQ_UPDATE_ROOM_INFO_TO_SEARCH = 424,
	REQ_UPLOAD_ROOM_INFOS_TO_SEARCH = 419,
	RESP_CHAT_IN_ROOM = 428,
	RESP_MATCH_GAME_IN_PROGRESS = 422,
	REQ_USER_LEAVE_GAME_IN_ZONE = 423,
	RESP_MATCH_GAME_IN_ZONE = 418,
	REQ_CHECK_IS_IN_ZONE = 425,
	REQ_MATCH_GAME_IN_ZONE = 417,
	REQ_CHAT_IN_ROOM = 427,
	REQ_CLIENT_LOADING_UPDATE = 413,
	REQ_REJOIN_GAME = 401,
	RESP_KICK_OUT_UNCONFIRMED_USER = 406,
	RESP_CONFIRM_ENTER_GAME = 405,
	REQ_BATTLE_RESULT = 429,
	RESP_CHECK_IS_IN_ZONE = 426,
	REQ_CANCEL_MATCH_GAME = 402,
	RESP_START_GAME = 415,
	REQ_JOIN_GAME_IN_ZONE = 420,
	RESP_BATTLE_RESULT = 430,
	RESP_CLIENT_LOADING_UPDATE = 414,
	RESP_BEGIN_CHOOSING_HERO = 407,
	REQ_CONFIRM_HERO = 410,
	REQ_CHOOSE_HERO = 408
}

return BattleProtocolToRoom
