-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Server/Command/BattleProtocolToSystem.lua

local BattleProtocolToSystem = {
	RESP_COMMON = 7,
	RESP_TCP_LOGIN = 3,
	REQ_LOGIN_GAME = 11,
	RESP_LOGOFF_GAME = 13,
	PING = 5,
	REQ_LOGIN_GAME_TO_SEARCH = 14,
	RESP_LOGIN_GAME = 12,
	HEART_BEAT = 22,
	REQ_LOGIN_GAME_TO_GLOBAL = 20,
	RESP_USER_ONLINE = 10,
	PONG = 6,
	RESP_LOGIN_GAME_TO_GLOBAL = 21,
	REQ_LOGIN_BATTLE_TO_SEARCH = 16,
	RESP_HEART_BEAT = 23,
	RESP_LOGIN_GAME_TO_CHAT = 25,
	REQ_UDP_LOGIN = 4,
	RESP_LOGIN_GAME_TO_SEARCH = 15,
	RESP_LOGIN_BATTLE_TO_SEARCH = 17,
	RESP_LOGOFF_BATTLE = 8,
	TCP_CONNECT = 0,
	REQ_TCP_LOGIN = 2,
	RESP_USER_OFFLINE = 9,
	REQ_USER_OFFLINE_TO_BATTLE = 19,
	REQ_LOGIN_GAME_TO_CHAT = 24,
	UDP_CONNECT = 1,
	REQ_USER_OFFLINE_TO_SEARCH = 18
}

return BattleProtocolToSystem
