-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/SettingCfgEpic.lua

SettingCfg = {
	Layers = {
		"Settings1",
		"Settings2",
		"Settings3",
		"Settings4",
		"Settings5",
		"Settings6",
		"InputConfig1",
		"InputConfig2",
		"InputConfig3",
		"KMConfig",
		"GPConfig",
		"NNConfig",
		"InputDiagram",
		"AccountLogin",
		"AccountRegister"
	},
	UiName = {
		"Settings1",
		"Settings2",
		"Settings3",
		"Settings4",
		"Settings6",
		"Settings5"
	},
	EnTabs = {
		true,
		true,
		true,
		true,
		true,
		true
	},
	InGame = {
		{
			"QuitToTitle",
			"",
			""
		}
	},
	Nav = {
		"Setting_NavBar_BtnBasic",
		"Setting_NavBar_BtnSounds",
		"Setting_NavBar_BtnControl",
		"Setting_NavBar_BtnGameplay",
		"Setting_NavBar_BtnSave",
		"Setting_NavBar_BtnGuide"
	},
	Pnl = {
		Gameplay = 4,
		Guide = 6,
		Control = 3,
		Basic = 1,
		SaveData = 5,
		Sounds = 2
	},
	Idx = {
		{
			GraphicsFrameRate = 4,
			Resolution = 2,
			GraphicsQuality = 7,
			GraphicsReflection = 9,
			GraphicsAmbientOcclusion = 10,
			GraphicsVignette = 11,
			Count = 11,
			Screen = 1,
			GraphicsAntiAliasing = 8,
			GraphicsVSync = 3,
			GraphicsFieldOfView = 6,
			GraphicsBrightness = 5
		},
		{
			SfxVolume = 3,
			Count = 4,
			BgmVolume = 2,
			VoiceVolume = 4,
			MasVolume = 1
		},
		{
			ReverseCameraAxisY = 5,
			Vibration = 3,
			ReverseCameraAxisX = 4,
			CamSensitivity = 1,
			InputConfiguration = 2,
			Count = 5
		},
		{
			Language = 1,
			GameMode = 3,
			Count = 4,
			Subtitle = 2,
			TimeAndScore = 4
		},
		{
			Account = 1,
			Count = 2,
			CloudData = 2
		},
		{
			GuideBook = 1,
			Count = 0
		}
	},
	Tab = {
		{
			{
				1,
				"Graphics1_Blank",
				"OnSelectScreen",
				{
					{
						"Graphics1_Screen_BtnExclusiveFullScreen",
						true
					},
					{
						"Graphics1_Screen_BtnFullScreen",
						true
					},
					{
						"Graphics1_Screen_BtnWindow",
						true
					}
				},
				{
					"fullscreen"
				}
			},
			{
				1,
				"Graphics2_Blank",
				"OnChangeResolution",
				{},
				{},
				{
					"Graphics2_Resolution_BtnL",
					"Graphics2_Resolution_BtnR",
					"Graphics2_Resolution_Value_Text"
				}
			},
			{
				1,
				"Graphics3_Blank",
				"OnChangeVSync",
				{
					{
						"Graphics3_VSyncOff",
						true
					},
					{
						"Graphics3_VSyncOn",
						true
					}
				},
				{
					"graphics",
					"vsync"
				}
			},
			{
				1,
				"Graphics4_Blank",
				"OnSelectFrameRate",
				{
					{
						"Graphics4_FPS1",
						true
					},
					{
						"Graphics4_FPS2",
						true
					},
					{
						"Graphics4_FPS3",
						true
					},
					{
						"Graphics4_FPS4",
						true
					}
				},
				{
					"graphics",
					"framerate"
				}
			},
			{
				2,
				"Graphics5_Blank",
				"OnSldrBrightness",
				{
					"Graphics5_Brightness_Value",
					"Graphics5_Brightness_Slider"
				},
				{
					"graphics",
					"brightness"
				}
			},
			{
				2,
				"Graphics6_Blank",
				"OnSldrFov",
				{
					"Graphics6_Fov_Value",
					"Graphics6_Fov_Slider"
				},
				{
					"graphics",
					"fov"
				}
			},
			{
				1,
				"Graphics7_Blank",
				"OnSelectGQuality",
				{
					{
						"Graphics7_GQ1",
						true
					},
					{
						"Graphics7_GQ2",
						true
					},
					{
						"Graphics7_GQ3",
						true
					}
				},
				{
					"graphics",
					"quality"
				}
			},
			{
				1,
				"Graphics8_Blank",
				"OnChangeAA",
				{
					{
						"",
						true,
						"UI_GRAPHICS_ANTIALIASING0"
					},
					{
						"",
						true,
						"UI_GRAPHICS_ANTIALIASING1"
					},
					{
						"",
						true,
						"UI_GRAPHICS_ANTIALIASING2"
					},
					{
						"",
						true,
						"UI_GRAPHICS_ANTIALIASING3"
					}
				},
				{
					"graphics",
					"antialiasing"
				},
				{
					"Graphics8_AA_BtnL",
					"Graphics8_AA_BtnR",
					"Graphics8_AA_Value_Text"
				}
			},
			{
				1,
				"Graphics9_Blank",
				"OnChangeAA",
				{
					{
						"",
						true,
						"UI_GRAPHICS_REFLECTION0"
					},
					{
						"",
						true,
						"UI_GRAPHICS_REFLECTION1"
					}
				},
				{
					"graphics",
					"reflection"
				},
				{
					"Graphics9_Rflct_BtnL",
					"Graphics9_Rflct_BtnR",
					"Graphics9_Rflct_Value_Text"
				}
			},
			{
				1,
				"Graphics10_Blank",
				"OnChangeAA",
				{
					{
						"",
						true,
						"UI_GRAPHICS_AMBIENTOCCLUSION0"
					},
					{
						"",
						true,
						"UI_GRAPHICS_AMBIENTOCCLUSION1"
					}
				},
				{
					"graphics",
					"ambientocclusion"
				},
				{
					"Graphics10_AO_BtnL",
					"Graphics10_AO_BtnR",
					"Graphics10_AO_Value_Text"
				}
			},
			{
				1,
				"Graphics11_Blank",
				"OnChangeVignette",
				{
					{
						"Graphics11_VignetteOff",
						true
					},
					{
						"Graphics11_VignetteOn",
						true
					}
				},
				{
					"graphics",
					"vignette"
				}
			}
		},
		{
			{
				2,
				"Settings_Sound_Mas_Blank",
				"OnSldrMasterVolume",
				{
					"Setting_Basic_Mas_Value",
					"Settings_Basic_Mas_Slider"
				},
				{
					"sound"
				}
			},
			{
				2,
				"Settings_Sound_Bgm_Blank",
				"OnSldrBgmVolume",
				{
					"Setting_Basic_Bgm_Value",
					"Settings_Basic_Bgm_Slider"
				},
				{
					"bgm"
				}
			},
			{
				2,
				"Settings_Sound_Sfx_Blank",
				"OnSldrSfxVolume",
				{
					"Setting_Basic_Sfx_Value",
					"Settings_Basic_Sfx_Slider"
				},
				{
					"sfx"
				}
			},
			{
				2,
				"Settings_Sound_Voice_Blank",
				"OnSldrVoiceVolume",
				{
					"Setting_Basic_Voice_Value",
					"Settings_Basic_Voice_Slider"
				},
				{
					"voice"
				}
			}
		},
		{
			{
				2,
				"Settings_Control_CamS_Blank",
				"OnSldrSensitivity",
				{
					"",
					"Setting_Basic_CameraSensitivity_Slider"
				},
				{
					"sensitivity"
				}
			},
			{
				1,
				"Settings_Control_Input_Blank",
				"OnSelectControllers",
				{
					{
						"Settings_Control_Input_Keyboard_Button",
						true
					},
					{
						"Settings_Control_Input_TouchPad_Button",
						false
					},
					{
						"Settings_Control_Input_GamePad_Button",
						true
					}
				}
			},
			{
				1,
				"Settings_Control_Vib_Blank",
				"OnSetVibration",
				{
					{
						"Settings_Control_Vib_ButtonOff",
						true
					},
					{
						"Settings_Control_Vib_ButtonOn",
						true
					}
				},
				{
					"vibration"
				}
			},
			{
				1,
				"Settings_Control_ReverseX_Blank",
				"OnSetRevCameraX",
				{
					{
						"Settings_Control_ReverseX_ButtonPos",
						true
					},
					{
						"Settings_Control_ReverseX_ButtonNeg",
						true
					}
				},
				{
					"camera",
					"horizontal"
				}
			},
			{
				1,
				"Settings_Control_ReverseY_Blank",
				"OnSetRevCameraY",
				{
					{
						"Settings_Control_ReverseY_ButtonPos",
						true
					},
					{
						"Settings_Control_ReverseY_ButtonNeg",
						true
					}
				},
				{
					"camera",
					"vertical"
				}
			}
		},
		{
			{
				1,
				"Gameplay1_Blank",
				"OnSelectLanguage",
				{
					{
						"",
						true,
						"us"
					},
					{
						"",
						true,
						"zhs"
					},
					{
						"",
						true,
						"zht"
					},
					{
						"",
						true,
						"jp"
					},
					{
						"",
						true,
						"de"
					},
					{
						"",
						true,
						"ru"
					},
					{
						"",
						true,
						"kr"
					},
					{
						"",
						true,
						"it"
					},
					{
						"",
						true,
						"fr"
					},
					{
						"",
						true,
						"es"
					},
					{
						"",
						true,
						"pt"
					}
				},
				{
					"lang"
				},
				{
					"Settings_Basic_Language_BtnL",
					"Settings_Basic_Language_BtnR",
					"Settings_Basic_Language_Text"
				}
			},
			{
				1,
				"Gameplay2_Blank",
				"OnSubtitle",
				{
					{
						"Settings_Basic_Subtitle_ButtonShow",
						true
					},
					{
						"Settings_Basic_Subtitle_ButtonHide",
						true
					}
				},
				{
					"subtitle"
				}
			},
			{
				1,
				"Gameplay3_Blank",
				"OnSelectGameMode",
				{
					{
						"Settings_Basic_GameMode_ButtonCasual",
						true
					},
					{
						"Settings_Basic_GameMode_ButtonNormal",
						true
					},
					{
						"Settings_Basic_GameMode_ButtonHardcore",
						false
					}
				}
			},
			{
				1,
				"Gameplay4_Blank",
				"OnSetShowTimeAndScore",
				{
					{
						"Settings_Basic_ShowTimeScore_ButtonShow",
						true
					},
					{
						"Settings_Basic_ShowTimeScore_ButtonHide",
						true
					}
				},
				{
					"showTimeAndScore"
				}
			}
		},
		{
			{
				1,
				"Settings_Save_Account_Blank",
				"OnSelectAccount",
				{
					{
						"Settings_Save_Account_Button_SignInWithApple",
						true,
						"OnButtonSignInWithApple"
					},
					{
						"Settings_Save_Account_Button_SignInWithAccount",
						true,
						"OnButtonSignInWithAccount"
					},
					{
						"Settings_Save_Account_Button_SignOut",
						true,
						"OnButtonSignOut"
					}
				}
			},
			{
				1,
				"Settings_Save_SaveData_Blank",
				"OnSelectCloudData",
				{
					{
						"Settings_Save_CloudData_Button_Upload",
						true,
						"OnBtnUpload"
					},
					{
						"Settings_Save_CloudData_Button_Download",
						true,
						"OnBtnDownload"
					}
				}
			}
		},
		{
			{
				3,
				nil,
				"OnSelectPage"
			}
		}
	},
	Sub = {
		{
			"InputConfig1"
		},
		{
			"InputConfig2"
		},
		{
			"InputConfig3"
		}
	},
	Binding = {
		{
			"WeChat",
			false
		},
		{
			"QQ",
			false
		},
		{
			"Google",
			false
		},
		{
			"Facebook",
			false
		},
		{
			"Twitter",
			false
		},
		{
			"Line",
			false
		}
	},
	Additions = {
		Recovery = false
	}
}
