-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_Achievement.lua

ES_Achievement = {
	{
		Text = "获得所有《帕斯卡契约》的成就",
		AchievementId = 12014,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10041,
		isAlwaysOpen = 1,
		Title = "帕斯卡契约",
		Sort = 1,
		Type = 0,
		Level = 4,
		Tab = 1,
		Max = 42
	},
	{
		Text = "击败疯狂的苦修者",
		AchievementId = 10001,
		leastUnlockDiff = 2,
		Quest = "11003",
		Icon = 10001,
		isAlwaysOpen = 0,
		Title = "疯狂的序幕",
		Sort = 2,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败圣父",
		AchievementId = 10002,
		leastUnlockDiff = 2,
		Quest = "21006",
		Icon = 10002,
		isAlwaysOpen = 0,
		Title = "父女情深",
		Sort = 3,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败伊瑟流姆的珍妮",
		AchievementId = 10003,
		leastUnlockDiff = 2,
		Quest = "31002",
		Icon = 10003,
		isAlwaysOpen = 0,
		Title = "月下婚礼",
		Sort = 4,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败融合的司布伦格",
		AchievementId = 10004,
		leastUnlockDiff = 2,
		Quest = "51001",
		Icon = 10004,
		isAlwaysOpen = 0,
		Title = "平庸之恶",
		Sort = 5,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败伊迪斯",
		AchievementId = 10005,
		leastUnlockDiff = 2,
		Quest = "41001",
		Icon = 10005,
		isAlwaysOpen = 0,
		Title = "弑神",
		Sort = 6,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败教宗希金斯",
		AchievementId = 10006,
		leastUnlockDiff = 2,
		Quest = "61001",
		Icon = 10006,
		isAlwaysOpen = 0,
		Title = "叛教",
		Sort = 7,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败篡夺者",
		AchievementId = 10007,
		leastUnlockDiff = 2,
		Quest = "71001",
		Icon = 10007,
		isAlwaysOpen = 0,
		Title = "狂言之徒",
		Sort = 8,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败异化的特蕾莎",
		AchievementId = 10008,
		leastUnlockDiff = 2,
		Quest = "81001",
		Icon = 10008,
		isAlwaysOpen = 0,
		Title = "吾爱",
		Sort = 9,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败蔷薇骑士帕特里克",
		AchievementId = 10009,
		leastUnlockDiff = 2,
		Quest = "31004",
		Icon = 10009,
		isAlwaysOpen = 0,
		Title = "骑士精神",
		Sort = 10,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败弗罗洛",
		AchievementId = 10011,
		leastUnlockDiff = 2,
		Quest = "41003",
		Icon = 10011,
		isAlwaysOpen = 0,
		Title = "丧钟",
		Sort = 11,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败审判庭内疯狂的德慕格",
		AchievementId = 10016,
		leastUnlockDiff = 2,
		Quest = "41007",
		Icon = 10043,
		isAlwaysOpen = 0,
		Title = "逃离疯狂",
		Sort = 12,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "击败伊琳娜",
		AchievementId = 10012,
		leastUnlockDiff = 2,
		Quest = "61004",
		Icon = 10012,
		isAlwaysOpen = 0,
		Title = "德慕格的覆灭",
		Sort = 13,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "不懈地坚持下，终于得到了希冀的结局",
		AchievementId = 10019,
		leastUnlockDiff = 1,
		Quest = "85018",
		Icon = 10038,
		isAlwaysOpen = 0,
		Title = "执着",
		Sort = 14,
		Type = 1,
		Level = 3,
		Tab = 1,
		Max = 1
	},
	{
		Text = "怀疑催生真正的理性",
		AchievementId = 10020,
		leastUnlockDiff = 1,
		Quest = "85019",
		Icon = 10039,
		isAlwaysOpen = 0,
		Title = "超验",
		Sort = 15,
		Type = 1,
		Level = 3,
		Tab = 1,
		Max = 1
	},
	{
		Text = "完成维奥拉的故事",
		AchievementId = 10013,
		leastUnlockDiff = 1,
		Quest = "75059",
		Icon = 10013,
		isAlwaysOpen = 0,
		Title = "血脉相连",
		Sort = 30,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "完成诺伍德的故事",
		AchievementId = 10014,
		leastUnlockDiff = 1,
		Quest = "75054",
		Icon = 10014,
		isAlwaysOpen = 0,
		Title = "棺中之手",
		Sort = 31,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "完成贝妮塔的故事",
		AchievementId = 10015,
		leastUnlockDiff = 1,
		Quest = "75049",
		Icon = 10015,
		isAlwaysOpen = 0,
		Title = "救赎",
		Sort = 32,
		Type = 1,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "完成蔷薇骑士、文森特、埃莉诺的任务",
		AchievementId = 10017,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10042,
		isAlwaysOpen = 0,
		Title = "乱世佳人",
		Sort = 33,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 3
	},
	{
		Text = "首次让贝妮塔祝福药水",
		AchievementId = 10010,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10010,
		isAlwaysOpen = 1,
		Title = "祝福",
		Sort = 34,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "首次进入崩溃状态",
		AchievementId = 11001,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10016,
		isAlwaysOpen = 1,
		Title = "丧失理智",
		Sort = 35,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "首次镶嵌秽石",
		AchievementId = 11002,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10017,
		isAlwaysOpen = 1,
		Title = "初学者",
		Sort = 36,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "首次探索黑雾区域",
		AchievementId = 11003,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10018,
		isAlwaysOpen = 1,
		Title = "黑雾旅人",
		Sort = 37,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "首次使用祭坛进行炼金",
		AchievementId = 11004,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10019,
		isAlwaysOpen = 1,
		Title = "炼金学徒",
		Sort = 38,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "首次在崩溃状态下击败强大的执念者",
		AchievementId = 11005,
		leastUnlockDiff = 2,
		Quest = "0",
		Icon = 10020,
		isAlwaysOpen = 1,
		Title = "恶梦",
		Sort = 39,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 1
	},
	{
		Text = "累积炼成80药水",
		AchievementId = 11006,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10021,
		isAlwaysOpen = 1,
		Title = "药剂师",
		Sort = 40,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 80
	},
	{
		Text = "累积炼成30次攻击道具",
		AchievementId = 11007,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10022,
		isAlwaysOpen = 1,
		Title = "战争商人",
		Sort = 41,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 30
	},
	{
		Text = "累积炼成20次战利品",
		AchievementId = 11008,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10023,
		isAlwaysOpen = 1,
		Title = "铁匠",
		Sort = 42,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 20
	},
	{
		Text = "累积获得1000个珊瑚虫骨",
		AchievementId = 11009,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10024,
		isAlwaysOpen = 1,
		Title = "幻觉",
		Sort = 43,
		Type = 0,
		Level = 1,
		Tab = 1,
		Max = 1000
	},
	{
		Text = "累计死亡50次",
		AchievementId = 11010,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10025,
		isAlwaysOpen = 1,
		Title = "苦修者",
		Sort = 29,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 50
	},
	{
		Text = "通过强化获得3件+5品质的战利品",
		AchievementId = 12001,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10026,
		isAlwaysOpen = 1,
		Title = "匠心",
		Sort = 28,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 3
	},
	{
		Text = "找到所有黑精",
		AchievementId = 12002,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10027,
		isAlwaysOpen = 1,
		Title = "捉迷藏",
		Sort = 17,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 14
	},
	{
		Text = "找到所有文献",
		AchievementId = 12003,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10028,
		isAlwaysOpen = 1,
		Title = "博学",
		Sort = 18,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 86
	},
	{
		Text = "满足所有赫吉",
		AchievementId = 12004,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10029,
		isAlwaysOpen = 1,
		Title = "自然学家",
		Sort = 19,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 35
	},
	{
		Text = "获得陨日的梅洛斯瓶",
		AchievementId = 12005,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10030,
		isAlwaysOpen = 0,
		Title = "全副武裝",
		Sort = 20,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 1
	},
	{
		Text = "获得所有炼金配方",
		AchievementId = 12006,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10031,
		isAlwaysOpen = 1,
		Title = "炼金大师",
		Sort = 21,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 17
	},
	{
		Text = "镶嵌5枚秽石宝钻",
		AchievementId = 12007,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10032,
		isAlwaysOpen = 1,
		Title = "大师",
		Sort = 22,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 5
	},
	{
		Text = "探索所有的黑雾区域",
		AchievementId = 12008,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10033,
		isAlwaysOpen = 1,
		Title = "黑雾领主",
		Sort = 23,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 5
	},
	{
		Text = "完成所有轶闻",
		AchievementId = 12009,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10034,
		isAlwaysOpen = 1,
		Title = "见证者",
		Sort = 24,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 11
	},
	{
		Text = "累积5小时的理智异常状态",
		AchievementId = 12010,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10035,
		isAlwaysOpen = 1,
		Title = "痴狂",
		Sort = 25,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 1
	},
	{
		Text = "以崩溃状态击杀所有强大的执念者",
		AchievementId = 12011,
		leastUnlockDiff = 2,
		Quest = "0",
		Icon = 10036,
		isAlwaysOpen = 1,
		Title = "真相",
		Sort = 26,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 1
	},
	{
		Text = "完成所有同伴的契约",
		AchievementId = 12012,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 10037,
		isAlwaysOpen = 1,
		Title = "侧耳倾听",
		Sort = 27,
		Type = 0,
		Level = 2,
		Tab = 1,
		Max = 3
	},
	{
		Text = "完成游戏时，祭坛的赐福等级保持为1",
		AchievementId = 12013,
		leastUnlockDiff = 2,
		Quest = "0",
		Icon = 10040,
		isAlwaysOpen = 1,
		Title = "挑战",
		Sort = 16,
		Type = 0,
		Level = 3,
		Tab = 1,
		Max = 1
	},
	{
		Text = "不使用负重者之卵的情况下，完成第四轮游戏或者之后的某一轮游戏",
		AchievementId = 20005,
		leastUnlockDiff = 2,
		Quest = "0",
		Icon = 20005,
		isAlwaysOpen = 1,
		Title = "传奇先驱者",
		Sort = 1,
		Type = 0,
		Level = 3,
		Tab = 2,
		Max = 1
	},
	{
		Text = "通过强化获得6件+5品质的战利品",
		AchievementId = 20003,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 20003,
		isAlwaysOpen = 1,
		Title = "名匠",
		Sort = 3,
		Type = 0,
		Level = 2,
		Tab = 2,
		Max = 3
	},
	{
		Text = "激活所有天赋的最高等级",
		AchievementId = 20004,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 20004,
		isAlwaysOpen = 1,
		Title = "超人",
		Sort = 4,
		Type = 0,
		Level = 2,
		Tab = 2,
		Max = 1
	},
	{
		Text = "获得不灭的梅洛斯瓶",
		AchievementId = 20002,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 20002,
		isAlwaysOpen = 1,
		Title = "不灭",
		Sort = 5,
		Type = 0,
		Level = 2,
		Tab = 2,
		Max = 1
	},
	{
		Text = "开启第二轮游戏",
		AchievementId = 20001,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 20001,
		isAlwaysOpen = 1,
		Title = "新的旅程",
		Sort = 2,
		Type = 0,
		Level = 1,
		Tab = 2,
		Max = 1
	},
	{
		Text = "在黑雾尽头战胜强大的执念",
		AchievementId = 30001,
		leastUnlockDiff = 2,
		Quest = "4991005",
		Icon = 30005,
		isAlwaysOpen = 1,
		Title = "黑雾之主",
		Sort = 1,
		Type = 1,
		Level = 3,
		Tab = 3,
		Max = 1
	},
	{
		Text = "战胜黑雾之穴中所有的恐怖执念",
		AchievementId = 30002,
		leastUnlockDiff = 2,
		Quest = "4991004",
		Icon = 30003,
		isAlwaysOpen = 1,
		Title = "黑雾守望者",
		Sort = 2,
		Type = 1,
		Level = 2,
		Tab = 3,
		Max = 1
	},
	{
		Text = "战胜黑雾腹地中所有的恐怖执念",
		AchievementId = 30003,
		leastUnlockDiff = 2,
		Quest = "4991003",
		Icon = 30004,
		isAlwaysOpen = 1,
		Title = "黑雾远征者",
		Sort = 3,
		Type = 1,
		Level = 1,
		Tab = 3,
		Max = 1
	},
	{
		Text = "战胜黑雾內域中所有的恐怖执念",
		AchievementId = 30004,
		leastUnlockDiff = 2,
		Quest = "4991002",
		Icon = 30002,
		isAlwaysOpen = 1,
		Title = "黑雾探险者",
		Sort = 4,
		Type = 1,
		Level = 1,
		Tab = 3,
		Max = 1
	},
	{
		Text = "战胜黑雾边境中所有的恐怖执念",
		AchievementId = 30005,
		leastUnlockDiff = 2,
		Quest = "4991001",
		Icon = 30001,
		isAlwaysOpen = 1,
		Title = "黑雾游荡者",
		Sort = 5,
		Type = 1,
		Level = 1,
		Tab = 3,
		Max = 1
	},
	{
		Text = "击败亨德尔公爵",
		AchievementId = 40001,
		leastUnlockDiff = 2,
		Quest = "99103",
		Icon = 40001,
		isAlwaysOpen = 0,
		Title = "迷失的英雄",
		Sort = 1,
		Type = 1,
		Level = 3,
		Tab = 4,
		Max = 1
	},
	{
		Text = "击败守门人·古德里安",
		AchievementId = 40002,
		leastUnlockDiff = 2,
		Quest = "99101",
		Icon = 40002,
		isAlwaysOpen = 0,
		Title = "仇恨的傀儡",
		Sort = 2,
		Type = 1,
		Level = 2,
		Tab = 4,
		Max = 1
	},
	{
		Text = "击败盗宝者",
		AchievementId = 40003,
		leastUnlockDiff = 2,
		Quest = "99104",
		Icon = 40003,
		isAlwaysOpen = 0,
		Title = "夺宝奇兵",
		Sort = 3,
		Type = 1,
		Level = 1,
		Tab = 4,
		Max = 1
	},
	{
		Text = "发现所有埋藏在伊西索亚深处的上古记忆",
		AchievementId = 40004,
		leastUnlockDiff = 2,
		Quest = "0",
		Icon = 40004,
		isAlwaysOpen = 0,
		Title = "记忆残片",
		Sort = 4,
		Type = 0,
		Level = 1,
		Tab = 4,
		Max = 28
	},
	{
		Text = "帮助布沃尔找到最终的归处",
		AchievementId = 40005,
		leastUnlockDiff = 2,
		Quest = "95229",
		Icon = 40005,
		isAlwaysOpen = 0,
		Title = "深海少年",
		Sort = 5,
		Type = 1,
		Level = 1,
		Tab = 4,
		Max = 1
	},
	{
		Text = "打开静默之墙，让浸灵河恢复奔流",
		AchievementId = 40006,
		leastUnlockDiff = 2,
		Quest = "93008",
		Icon = 40006,
		isAlwaysOpen = 0,
		Title = "长河奔流",
		Sort = 5,
		Type = 1,
		Level = 1,
		Tab = 4,
		Max = 1
	},
	{
		Text = "在旅程的最后找到一直追寻的答案",
		AchievementId = 40007,
		leastUnlockDiff = 2,
		Quest = "85025",
		Icon = 40007,
		isAlwaysOpen = 0,
		Title = "答案",
		Sort = 5,
		Type = 1,
		Level = 1,
		Tab = 4,
		Max = 1
	},
	{
		Text = "激活杰洛尔德所有天赋的最高等级",
		AchievementId = 40008,
		leastUnlockDiff = 2,
		Quest = "0",
		Icon = 40008,
		isAlwaysOpen = 0,
		Title = "异乡剑圣",
		Sort = 5,
		Type = 0,
		Level = 1,
		Tab = 4,
		Max = 1
	},
	{
		Text = "找到伊西索亚的所有黑精",
		AchievementId = 40009,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 40009,
		isAlwaysOpen = 1,
		Title = "买卖无界",
		Sort = 5,
		Type = 0,
		Level = 1,
		Tab = 4,
		Max = 4
	},
	{
		Text = "取悦伊西索亚所有的赫吉，获赐宝库大门的钥匙",
		AchievementId = 40010,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 40011,
		isAlwaysOpen = 1,
		Title = "支配者的狂欢",
		Sort = 5,
		Type = 0,
		Level = 1,
		Tab = 4,
		Max = 5
	},
	{
		Text = "在「挑战执念」的任意模式中无伤击败所有本篇的强大执念者",
		AchievementId = 50001,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 50001,
		isAlwaysOpen = 1,
		Title = "毫发无伤",
		Sort = 1,
		Type = 0,
		Level = 3,
		Tab = 5,
		Max = 1
	},
	{
		Text = "在「挑战执念」的标准模式中击败所有本篇的强大执念者",
		AchievementId = 50002,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 50002,
		isAlwaysOpen = 1,
		Title = "执念之人",
		Sort = 2,
		Type = 0,
		Level = 1,
		Tab = 5,
		Max = 1
	},
	{
		Text = "在「挑战执念」自选模式的巨像难度下击败所有本篇的强大执念者",
		AchievementId = 50003,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 50003,
		isAlwaysOpen = 1,
		Title = "巨像永生",
		Sort = 3,
		Type = 0,
		Level = 1,
		Tab = 5,
		Max = 1
	},
	{
		Text = "在「挑战执念」中使用泰伦斯之外的任一角色击败第一信使",
		AchievementId = 50004,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 50004,
		isAlwaysOpen = 0,
		Title = "致特蕾莎",
		Sort = 4,
		Type = 0,
		Level = 1,
		Tab = 5,
		Max = 1
	},
	{
		Text = "在「皇座之舞」中找到并击败所有来自噩梦的执念之人",
		AchievementId = 60001,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 60001,
		isAlwaysOpen = 0,
		Title = "传承",
		Sort = 1,
		Type = 0,
		Level = 3,
		Tab = 6,
		Max = 7
	},
	{
		Text = "在「皇座之舞」中解锁伊琳娜「攻击」、「特殊」、「炼金」天赋分支中的所有天赋",
		AchievementId = 60002,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 60002,
		isAlwaysOpen = 1,
		Title = "德幕格舞者",
		Sort = 4,
		Type = 0,
		Level = 2,
		Tab = 6,
		Max = 1
	},
	{
		Text = "在「皇座之舞」中首次通关",
		AchievementId = 60003,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 60003,
		isAlwaysOpen = 1,
		Title = "梦之初醒",
		Sort = 3,
		Type = 0,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "在「皇座之舞」中使用伊琳娜通关困难难度",
		AchievementId = 60004,
		leastUnlockDiff = 2,
		Quest = "0",
		Icon = 60004,
		isAlwaysOpen = 1,
		Title = "无间梦魇",
		Sort = 2,
		Type = 0,
		Level = 2,
		Tab = 6,
		Max = 1
	},
	{
		Text = "击败【海格姆】的执念之人",
		AchievementId = 60005,
		leastUnlockDiff = 1,
		Quest = "10014901",
		Icon = 60005,
		isAlwaysOpen = 0,
		Title = "深影之月",
		Sort = 6,
		Type = 1,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "击败【阿达米亚】的执念之人",
		AchievementId = 60006,
		leastUnlockDiff = 1,
		Quest = "10024901",
		Icon = 60006,
		isAlwaysOpen = 0,
		Title = "苦难之路",
		Sort = 7,
		Type = 1,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "击败【伊瑟流姆】的执念之人",
		AchievementId = 60007,
		leastUnlockDiff = 1,
		Quest = "10034901",
		Icon = 60007,
		isAlwaysOpen = 0,
		Title = "云烟过眼",
		Sort = 8,
		Type = 1,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "击败【基塔布】的执念之人",
		AchievementId = 60008,
		leastUnlockDiff = 1,
		Quest = "10054901",
		Icon = 60008,
		isAlwaysOpen = 0,
		Title = "永恒争斗",
		Sort = 9,
		Type = 1,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "击败【伊迪斯】的执念之人",
		AchievementId = 60009,
		leastUnlockDiff = 1,
		Quest = "10044901",
		Icon = 60009,
		isAlwaysOpen = 0,
		Title = "德幕格的祈愿",
		Sort = 10,
		Type = 1,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "击败【赐福之地】的执念之人",
		AchievementId = 60010,
		leastUnlockDiff = 1,
		Quest = "10064901",
		Icon = 60010,
		isAlwaysOpen = 0,
		Title = "终局",
		Sort = 11,
		Type = 1,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "击败【地下溶洞】的执念之人",
		AchievementId = 60011,
		leastUnlockDiff = 1,
		Quest = "10074901",
		Icon = 60011,
		isAlwaysOpen = 0,
		Title = "真理之路",
		Sort = 12,
		Type = 1,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "获得「皇座之舞」困难难度全流程的S评价",
		AchievementId = 60012,
		leastUnlockDiff = 2,
		Quest = "0",
		Icon = 60012,
		isAlwaysOpen = 1,
		Title = "长夜女皇",
		Sort = 5,
		Type = 0,
		Level = 3,
		Tab = 6,
		Max = 1
	},
	{
		Text = "在10秒内反弹十次敌人的远程攻击",
		AchievementId = 60013,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 60013,
		isAlwaysOpen = 0,
		Title = "以牙还牙",
		Sort = 13,
		Type = 0,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "在一段连续的进攻中使用「剑舞·只影」回避三次敌人的攻击",
		AchievementId = 60014,
		leastUnlockDiff = 1,
		Quest = "0",
		Icon = 60014,
		isAlwaysOpen = 0,
		Title = "致命优雅",
		Sort = 14,
		Type = 0,
		Level = 1,
		Tab = 6,
		Max = 1
	},
	{
		Text = "在赐福之地获得神秘的道具",
		AchievementId = 60015,
		leastUnlockDiff = 1,
		Quest = "10062310",
		Icon = 60015,
		isAlwaysOpen = 1,
		Title = "失心于梦",
		Sort = 15,
		Type = 1,
		Level = 1,
		Tab = 6,
		Max = 1
	}
}
