-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_BufferData.lua

ES_BufferData = {
	{
		Attribute_3 = 0,
		BufferType = 1,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_life",
		Attribute_6 = 0,
		BufferId = 107,
		BufferInfo = "生命等级提升1",
		Attribute_1 = 10,
		Attribute_2 = 0,
		BufferName = "生命祝福"
	},
	{
		Attribute_3 = 0,
		BufferType = 2,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_attack",
		Attribute_6 = 0,
		BufferId = 108,
		BufferInfo = "攻击等级提升1",
		Attribute_1 = 0,
		Attribute_2 = 20,
		BufferName = "攻击祝福"
	},
	{
		Attribute_3 = 10,
		BufferType = 3,
		Attribute_4 = 10,
		Attribute_5 = 10,
		Icon = "main_soul_defence",
		Attribute_6 = 10,
		BufferId = 109,
		BufferInfo = "防御等级提升1",
		Attribute_1 = 0,
		Attribute_2 = 0,
		BufferName = "防御祝福"
	},
	{
		Attribute_3 = 0,
		BufferType = 4,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_tenacity",
		Attribute_6 = 0,
		BufferId = 110,
		BufferInfo = "坚韧等级提升1",
		Attribute_1 = 0,
		Attribute_2 = 0,
		BufferName = "坚韧祝福"
	},
	{
		Attribute_3 = 0,
		BufferType = 5,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_energy",
		Attribute_6 = 0,
		BufferId = 111,
		BufferInfo = "精力等级提升1",
		Attribute_1 = 0,
		Attribute_2 = 0,
		BufferName = "活力祝福"
	},
	{
		Attribute_3 = 0,
		BufferType = 6,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_home",
		Attribute_6 = 0,
		BufferId = 112,
		BufferInfo = "圣坛等级提升1",
		Attribute_1 = 0,
		Attribute_2 = 0,
		BufferName = "圣坛恢复"
	},
	{
		Attribute_3 = 0,
		BufferType = 1,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_life",
		Attribute_6 = 0,
		BufferId = 101,
		BufferInfo = "生命等级提升2",
		Attribute_1 = 20,
		Attribute_2 = 0,
		BufferName = "生命之源"
	},
	{
		Attribute_3 = 0,
		BufferType = 2,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_attack",
		Attribute_6 = 0,
		BufferId = 102,
		BufferInfo = "攻击等级提升2",
		Attribute_1 = 0,
		Attribute_2 = 40,
		BufferName = "攻击之源"
	},
	{
		Attribute_3 = 20,
		BufferType = 3,
		Attribute_4 = 20,
		Attribute_5 = 20,
		Icon = "main_soul_defence",
		Attribute_6 = 20,
		BufferId = 103,
		BufferInfo = "防御等级提升2",
		Attribute_1 = 0,
		Attribute_2 = 0,
		BufferName = "防御之源"
	},
	{
		Attribute_3 = 0,
		BufferType = 4,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_tenacity",
		Attribute_6 = 0,
		BufferId = 104,
		BufferInfo = "坚韧等级提升2",
		Attribute_1 = 0,
		Attribute_2 = 0,
		BufferName = "坚韧之源"
	},
	{
		Attribute_3 = 0,
		BufferType = 5,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_energy",
		Attribute_6 = 0,
		BufferId = 105,
		BufferInfo = "精力等级提升2",
		Attribute_1 = 0,
		Attribute_2 = 0,
		BufferName = "活力之源"
	},
	{
		Attribute_3 = 0,
		BufferType = 6,
		Attribute_4 = 0,
		Attribute_5 = 0,
		Icon = "main_soul_home",
		Attribute_6 = 0,
		BufferId = 106,
		BufferInfo = "圣坛等级提升2",
		Attribute_1 = 0,
		Attribute_2 = 0,
		BufferName = "圣坛重铸"
	}
}
