-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_StoryWall.lua

ES_StoryWall = {
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1,
		WallId = 1001,
		EntranceId = 2,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_301",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "14001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1,
		WallId = 1002,
		EntranceId = 1,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_340",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "14001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_363",
		ToStoryId = 101,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "15040",
		NotReboundDialogId = "",
		StoryId = 1,
		WallId = 1004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "19008",
		WallName = "wall_box_408",
		ToStoryId = 0,
		Comment = "",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "15040",
		NotReboundDialogId = "",
		StoryId = 1,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "19008",
		WallName = "wall_box_409",
		ToStoryId = 0,
		Comment = "",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "13004",
		NotReboundDialogId = "",
		StoryId = 1,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "11007",
		WallName = "wall_box_302",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "13004",
		NotReboundDialogId = "",
		StoryId = 1,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "11007",
		WallName = "wall_box_369",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 2,
		WallId = 1001,
		EntranceId = 1,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_185",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "24001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 2,
		WallId = 1002,
		EntranceId = 2,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_148",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "24001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 2,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_204",
		ToStoryId = 102,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 2,
		WallId = 1004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "22202",
		WallName = "wall_box_205",
		ToStoryId = 0,
		Comment = "boss平时墙",
		DialogId = "24049"
	},
	{
		Rebound = 0,
		ShowQuestId = "23002",
		NotReboundDialogId = "",
		StoryId = 2,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "21007",
		WallName = "wall_box_183",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "33001",
		NotReboundDialogId = "",
		StoryId = 3,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "31002",
		WallName = "wall_box_117",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "33001",
		NotReboundDialogId = "",
		StoryId = 3,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "31002",
		WallName = "wall_box_118",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 3,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_123",
		ToStoryId = 103,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 3,
		WallId = 1002,
		EntranceId = 2,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_122",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "34001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 3,
		WallId = 1003,
		EntranceId = 4,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_120",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "34001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 3,
		WallId = 1004,
		EntranceId = 1,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_121",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "34001"
	},
	{
		Rebound = 0,
		ShowQuestId = "35035",
		NotReboundDialogId = "",
		StoryId = 3,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "31004",
		WallName = "wall_box_112",
		ToStoryId = 0,
		Comment = "骑士墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "35035",
		NotReboundDialogId = "",
		StoryId = 3,
		WallId = 1006,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "31004",
		WallName = "wall_box_119",
		ToStoryId = 0,
		Comment = "骑士墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 4,
		WallId = 1001,
		EntranceId = 1,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_101",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "44001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 4,
		WallId = 1002,
		EntranceId = 2,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_102",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "44001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 4,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_103",
		ToStoryId = 104,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "45036",
		NotReboundDialogId = "",
		StoryId = 4,
		WallId = 1004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "41003",
		WallName = "wall_box_1194",
		ToStoryId = 0,
		Comment = "敲钟哥墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 4,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "41001",
		WallName = "wall_box_1191",
		ToStoryId = 0,
		Comment = "桥前墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 4,
		WallId = 1006,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "41001",
		WallName = "wall_box_12",
		ToStoryId = 0,
		Comment = "沙滩墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 4,
		WallId = 1007,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "41001",
		WallName = "wall_box_13",
		ToStoryId = 0,
		Comment = "沙滩墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "43001",
		NotReboundDialogId = "",
		StoryId = 4,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "41001",
		WallName = "wall_capsule_21",
		ToStoryId = 0,
		Comment = "BOSS碰撞体",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "53001",
		NotReboundDialogId = "",
		StoryId = 5,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "51001",
		WallName = "wall_box_104",
		ToStoryId = 0,
		Comment = "塔顶boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "53001",
		NotReboundDialogId = "",
		StoryId = 5,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "51001",
		WallName = "wall_box_105",
		ToStoryId = 0,
		Comment = "塔顶boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "53001",
		NotReboundDialogId = "",
		StoryId = 5,
		WallId = 2003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "51001",
		WallName = "wall_box_106",
		ToStoryId = 0,
		Comment = "塔顶boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "53001",
		NotReboundDialogId = "",
		StoryId = 5,
		WallId = 2004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "51001",
		WallName = "wall_box_107",
		ToStoryId = 0,
		Comment = "塔顶boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "53001",
		NotReboundDialogId = "",
		StoryId = 5,
		WallId = 2005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "51001",
		WallName = "wall_box_108",
		ToStoryId = 0,
		Comment = "塔底boss墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 5,
		WallId = 1001,
		EntranceId = 1,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_101",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "54001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 5,
		WallId = 1002,
		EntranceId = 2,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "91201",
		HideQuestId = "",
		WallName = "wall_box_102",
		ToStoryId = 499,
		Comment = "黑幕墙",
		DialogId = "54001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 5,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_103",
		ToStoryId = 105,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "63707",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "61005",
		WallName = "wall_box_20",
		ToStoryId = 0,
		Comment = "嬷嬷2墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "63702",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "63014",
		WallName = "wall_box_1018",
		ToStoryId = 0,
		Comment = "嬷嬷1墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "63702",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "63014",
		WallName = "wall_box_27",
		ToStoryId = 0,
		Comment = "嬷嬷1墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 1004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "65063",
		WallName = "wall_box_1032",
		ToStoryId = 0,
		Comment = "狗洞1",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "63704",
		WallName = "wall_box_26",
		ToStoryId = 0,
		Comment = "圣剑",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 1006,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "65059",
		WallName = "wall_box_2026",
		ToStoryId = 0,
		Comment = "敲门声的墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 1007,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "65057",
		WallName = "wall_box_2027",
		ToStoryId = 0,
		Comment = "敲门声的墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 1008,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "65058",
		WallName = "wall_box_2028",
		ToStoryId = 0,
		Comment = "敲门声的墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "63001",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "61001",
		WallName = "wall_box_2",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "63001",
		NotReboundDialogId = "",
		StoryId = 6,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "63710;61001",
		WallName = "wall_box_1015",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "73001",
		NotReboundDialogId = "",
		StoryId = 7,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 7,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "3021005;99999",
		WallName = "wall_box_3",
		ToStoryId = 0,
		Comment = "眼球墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "73010",
		NotReboundDialogId = "",
		StoryId = 7,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "71004",
		WallName = "wall_box_2",
		ToStoryId = 0,
		Comment = "苦修者墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "73010",
		NotReboundDialogId = "",
		StoryId = 7,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "71004",
		WallName = "wall_box_4",
		ToStoryId = 0,
		Comment = "苦修者墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "81001",
		NotReboundDialogId = "",
		StoryId = 8,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1",
		ToStoryId = 0,
		Comment = "桌子",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "83001",
		NotReboundDialogId = "",
		StoryId = 8,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "81001",
		WallName = "wall_box_2",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "81001",
		NotReboundDialogId = "",
		StoryId = 8,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_31",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93011",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_5001",
		ToStoryId = 0,
		Comment = "心动",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93008",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_6112",
		ToStoryId = 0,
		Comment = "大坝机关",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "99101",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_6113",
		ToStoryId = 0,
		Comment = "守门人电梯",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93014",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_6114",
		ToStoryId = 0,
		Comment = "守门人铁链",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93001",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "99101",
		WallName = "wall_box_6111",
		ToStoryId = 0,
		Comment = "守门人墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93008",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1006,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1111",
		ToStoryId = 0,
		Comment = "大坝后船飘",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "95137",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1007,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_2111",
		ToStoryId = 0,
		Comment = "搁浅船修好",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "95191",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1008,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_6115",
		ToStoryId = 0,
		Comment = "清道夫尸体",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93008",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1009,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_6116",
		ToStoryId = 0,
		Comment = "水",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93011",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1010,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_5112",
		ToStoryId = 0,
		Comment = "互动球和尸体",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "95137",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1011,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1112",
		ToStoryId = 0,
		Comment = "坛子水满",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1012,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "99103",
		WallName = "wall_box_5113",
		ToStoryId = 0,
		Comment = "密室墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "95128",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1013,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_3111",
		ToStoryId = 0,
		Comment = "奇怪的声音",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1014,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "99101",
		WallName = "wall_box_6117",
		ToStoryId = 0,
		Comment = "守门人1",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1015,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "99101",
		WallName = "wall_box_6118",
		ToStoryId = 0,
		Comment = "守门人2",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93016",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1016,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_5114",
		ToStoryId = 0,
		Comment = "BOSS武器",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "99104",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1017,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_4111",
		ToStoryId = 0,
		Comment = "黑精王武器",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1018,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "93011",
		WallName = "wall_box_5555",
		ToStoryId = 0,
		Comment = "心动声",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 1019,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "93011",
		WallName = "wall_box_4444",
		ToStoryId = 0,
		Comment = "心动声",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "93003",
		NotReboundDialogId = "",
		StoryId = 9,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "99103",
		WallName = "wall_box_5111",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 101,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1001",
		ToStoryId = 2,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 101,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 1,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 101,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 2,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1032",
		ToStoryId = 1,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 101,
		WallId = 1004,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1054",
		ToStoryId = 1,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 102,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1404",
		ToStoryId = 3,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 102,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1401",
		ToStoryId = 2,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 102,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 2,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1407",
		ToStoryId = 2,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 103,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1001",
		ToStoryId = 5,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 103,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 2,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1002",
		ToStoryId = 3,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 103,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1003",
		ToStoryId = 3,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 104,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1403",
		ToStoryId = 4,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 104,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1402",
		ToStoryId = 4,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 104,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 4,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1401",
		ToStoryId = 3,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 105,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 2,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1403",
		ToStoryId = 4,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 105,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 2,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1402",
		ToStoryId = 5,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 105,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 3,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1401",
		ToStoryId = 5,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "33015",
		NotReboundDialogId = "",
		StoryId = 301,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1601",
		ToStoryId = 0,
		Comment = "水墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 401,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 401,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 401,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 402,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 402,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 402,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 403,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 403,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 403,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 404,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 404,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 404,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 405,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 405,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 405,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 406,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 406,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 406,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 407,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 407,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 407,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 408,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 408,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 408,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 409,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 409,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 409,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 410,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 410,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 410,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 411,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 411,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 411,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 412,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 412,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 412,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 413,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 413,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 413,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 414,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1041",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 414,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1042",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 414,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1043",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 499,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1",
		ToStoryId = 1,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 499,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 1,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_2",
		ToStoryId = 401,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "4992301",
		NotReboundDialogId = "",
		StoryId = 499,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1101",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10013001",
		NotReboundDialogId = "",
		StoryId = 1001,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_302",
		ToStoryId = 0,
		Comment = "Boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10013001",
		NotReboundDialogId = "",
		StoryId = 1001,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_369",
		ToStoryId = 0,
		Comment = "Boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10021001",
		NotReboundDialogId = "",
		StoryId = 1002,
		WallId = 1004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10023003",
		WallName = "wall_box_205",
		ToStoryId = 0,
		Comment = "boss平时墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10023001",
		NotReboundDialogId = "",
		StoryId = 1002,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_183",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10033001",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_117",
		ToStoryId = 0,
		Comment = "Boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10033001",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_118",
		ToStoryId = 0,
		Comment = "Boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10033001",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10031001",
		WallName = "wall_box_112",
		ToStoryId = 0,
		Comment = "骑士墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10033001",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 1006,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10031001",
		WallName = "wall_box_119",
		ToStoryId = 0,
		Comment = "骑士墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10043001",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10041001",
		WallName = "wall_box_1191",
		ToStoryId = 0,
		Comment = "桥前墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10043001",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10041001",
		WallName = "wall_capsule_21",
		ToStoryId = 0,
		Comment = "BOSS碰撞体",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10053001",
		NotReboundDialogId = "",
		StoryId = 1005,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10051001",
		WallName = "wall_box_104",
		ToStoryId = 0,
		Comment = "塔顶boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10053001",
		NotReboundDialogId = "",
		StoryId = 1005,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10051001",
		WallName = "wall_box_105",
		ToStoryId = 0,
		Comment = "塔顶boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10053001",
		NotReboundDialogId = "",
		StoryId = 1005,
		WallId = 2003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10051001",
		WallName = "wall_box_106",
		ToStoryId = 0,
		Comment = "塔顶boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10053001",
		NotReboundDialogId = "",
		StoryId = 1005,
		WallId = 2004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10051001",
		WallName = "wall_box_107",
		ToStoryId = 0,
		Comment = "塔顶boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10053001",
		NotReboundDialogId = "",
		StoryId = 1005,
		WallId = 2005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_108",
		ToStoryId = 0,
		Comment = "塔底boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10063001",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_2",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10063001",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10061001",
		WallName = "wall_box_1015",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10073001",
		NotReboundDialogId = "",
		StoryId = 1007,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10053001",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10051001",
		WallName = "wall_box_20",
		ToStoryId = 0,
		Comment = "嬷嬷2墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10073010",
		NotReboundDialogId = "",
		StoryId = 1007,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10071004",
		WallName = "wall_box_2",
		ToStoryId = 0,
		Comment = "苦修者墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10073010",
		NotReboundDialogId = "",
		StoryId = 1007,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10071004",
		WallName = "wall_box_4",
		ToStoryId = 0,
		Comment = "苦修者墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10063001",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10061001",
		WallName = "wall_box_1018",
		ToStoryId = 0,
		Comment = "嬷嬷1墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10063001",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10061001",
		WallName = "wall_box_27",
		ToStoryId = 0,
		Comment = "嬷嬷1墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10041001",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 1006,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10043003",
		WallName = "wall_box_12",
		ToStoryId = 0,
		Comment = "沙滩墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10041001",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 1007,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10043003",
		WallName = "wall_box_13",
		ToStoryId = 0,
		Comment = "沙滩墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10033004",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 1007,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10031003",
		WallName = "wall_box_301",
		ToStoryId = 0,
		Comment = "骑士墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10033004",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 1008,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10031003",
		WallName = "wall_box_302",
		ToStoryId = 0,
		Comment = "骑士墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10043001",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 1008,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10041001",
		WallName = "wall_box_1194",
		ToStoryId = 0,
		Comment = "敲钟哥墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10045036",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 1009,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10041003",
		WallName = "wall_box_1308",
		ToStoryId = 0,
		Comment = "敲钟哥墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10043001",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 1010,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1309",
		ToStoryId = 0,
		Comment = "伊迪斯墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1007,
		WallId = 2002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10073902",
		WallName = "wall_box_1172",
		ToStoryId = 0,
		Comment = "棺材哥墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10063008",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 1002,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10063007",
		WallName = "wall_box_1018",
		ToStoryId = 0,
		Comment = "嬷嬷1墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10063008",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 1003,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "10063007",
		WallName = "wall_box_27",
		ToStoryId = 0,
		Comment = "嬷嬷1墙",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1001,
		WallId = 1001,
		EntranceId = 2,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_301",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "14001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1001,
		WallId = 1002,
		EntranceId = 1,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_340",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "14001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1002,
		WallId = 1001,
		EntranceId = 1,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_185",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "24001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1002,
		WallId = 1002,
		EntranceId = 2,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_148",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "24001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 1002,
		EntranceId = 2,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_122",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "34001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 1003,
		EntranceId = 4,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_120",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "34001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1003,
		WallId = 1004,
		EntranceId = 1,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_121",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "34001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 1001,
		EntranceId = 1,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_101",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "44001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1004,
		WallId = 1002,
		EntranceId = 2,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_102",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "44001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1005,
		WallId = 1001,
		EntranceId = 1,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_101",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "54001"
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1005,
		WallId = 1002,
		EntranceId = 2,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_102",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "54001"
	},
	{
		Rebound = 0,
		ShowQuestId = "10063901",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_26",
		ToStoryId = 0,
		Comment = "圣剑",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "10063915",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 1006,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "10063916",
		WallName = "wall_box_1054",
		ToStoryId = 0,
		Comment = "三圣所",
		DialogId = ""
	},
	{
		Rebound = 1,
		ShowQuestId = "",
		NotReboundDialogId = "",
		StoryId = 1006,
		WallId = 1007,
		EntranceId = 1,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1016",
		ToStoryId = 0,
		Comment = "黑幕墙",
		DialogId = "64001"
	},
	{
		Rebound = 0,
		ShowQuestId = "20021301",
		NotReboundDialogId = "",
		StoryId = 2002,
		WallId = 1005,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_6111",
		ToStoryId = 0,
		Comment = "守门人墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "20023003",
		NotReboundDialogId = "",
		StoryId = 2004,
		WallId = 2001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_5111",
		ToStoryId = 0,
		Comment = "boss墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "20019990",
		NotReboundDialogId = "",
		StoryId = 2001,
		WallId = 1001,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 2,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_1001",
		ToStoryId = 0,
		Comment = "掘墓人墙",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "20022101",
		NotReboundDialogId = "",
		StoryId = 2003,
		WallId = 1017,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_4111",
		ToStoryId = 0,
		Comment = "黑精王武器",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "20023016",
		NotReboundDialogId = "",
		StoryId = 2004,
		WallId = 1016,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_5114",
		ToStoryId = 0,
		Comment = "BOSS武器",
		DialogId = ""
	},
	{
		Rebound = 0,
		ShowQuestId = "20021301",
		NotReboundDialogId = "",
		StoryId = 2002,
		WallId = 1004,
		EntranceId = 0,
		ToEntranceId = 0,
		Type = 1,
		NotReboundQuestId = "",
		HideQuestId = "",
		WallName = "wall_box_6114",
		ToStoryId = 0,
		Comment = "守门人铁链",
		DialogId = ""
	}
}
