-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_SkillComboData.lua

ES_SkillComboData = {
	{
		SkillComboPre = 1,
		SkillNamePre = "剑士轻轻轻1",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 4,
		SkillNameNext = "剑士战技轻",
		SkillComboNext = 1,
		SkillIndexPre = 1
	},
	{
		SkillComboPre = 2,
		SkillNamePre = "剑士轻轻轻2",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 4,
		SkillNameNext = "剑士战技轻",
		SkillComboNext = 1,
		SkillIndexPre = 1
	},
	{
		SkillComboPre = 3,
		SkillNamePre = "剑士轻轻轻3",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 4,
		SkillNameNext = "剑士战技轻",
		SkillComboNext = 1,
		SkillIndexPre = 1
	},
	{
		SkillComboPre = 1,
		SkillNamePre = "剑士轻轻轻1",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 3,
		SkillNameNext = "剑士战技轻满",
		SkillComboNext = 1,
		SkillIndexPre = 1
	},
	{
		SkillComboPre = 2,
		SkillNamePre = "剑士轻轻轻2",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 3,
		SkillNameNext = "剑士战技轻满",
		SkillComboNext = 1,
		SkillIndexPre = 1
	},
	{
		SkillComboPre = 3,
		SkillNamePre = "剑士轻轻轻3",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 3,
		SkillNameNext = "剑士战技轻满",
		SkillComboNext = 1,
		SkillIndexPre = 1
	},
	{
		SkillComboPre = 1,
		SkillNamePre = "剑士重重重1",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 6,
		SkillNameNext = "剑士战技重",
		SkillComboNext = 1,
		SkillIndexPre = 2
	},
	{
		SkillComboPre = 2,
		SkillNamePre = "剑士重重重2",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 6,
		SkillNameNext = "剑士战技重",
		SkillComboNext = 1,
		SkillIndexPre = 2
	},
	{
		SkillComboPre = 3,
		SkillNamePre = "剑士重重重3",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 6,
		SkillNameNext = "剑士战技重",
		SkillComboNext = 1,
		SkillIndexPre = 2
	},
	{
		SkillComboPre = 1,
		SkillNamePre = "剑士重重重1",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 5,
		SkillNameNext = "剑士战技重满",
		SkillComboNext = 1,
		SkillIndexPre = 2
	},
	{
		SkillComboPre = 2,
		SkillNamePre = "剑士重重重2",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 5,
		SkillNameNext = "剑士战技重满",
		SkillComboNext = 1,
		SkillIndexPre = 2
	},
	{
		SkillComboPre = 3,
		SkillNamePre = "剑士重重重3",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 5,
		SkillNameNext = "剑士战技重满",
		SkillComboNext = 1,
		SkillIndexPre = 2
	},
	{
		SkillComboPre = 1,
		SkillNamePre = "闪避",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 1,
		SkillNameNext = "剑士轻轻轻1",
		SkillComboNext = 1,
		SkillIndexPre = 102
	},
	{
		SkillComboPre = 2,
		SkillNamePre = "闪避",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 1,
		SkillNameNext = "剑士轻轻轻1",
		SkillComboNext = 1,
		SkillIndexPre = 102
	},
	{
		SkillComboPre = 1,
		SkillNamePre = "闪避",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 7,
		SkillNameNext = "剑士闪接重",
		SkillComboNext = 1,
		SkillIndexPre = 102
	},
	{
		SkillComboPre = 2,
		SkillNamePre = "闪避",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 7,
		SkillNameNext = "剑士闪接重",
		SkillComboNext = 1,
		SkillIndexPre = 102
	},
	{
		SkillComboPre = 1,
		SkillNamePre = "剑士闪接重",
		SkillOffset = 1,
		SkillComboEnd = 1,
		SkillExit = 1,
		SkillComboStart = 1,
		SkillBlend = 1,
		HeroId = 10001,
		SkillIndexNext = 2,
		SkillNameNext = "剑士重重重1",
		SkillComboNext = 1,
		SkillIndexPre = 7
	}
}
