-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_StoryTimeLineSubtitle.lua

ES_StoryTimeLineSubtitle = {
	{
		Begin = "4.5",
		End = "8.5",
		StoryId = "1",
		Context_us = "The world becomes light.",
		Context_kr = "세상의 무게가 가벼워졌습니다.",
		Context_ru = "Мир станет светлее.",
		Context_fr = "Le monde s'illumine.",
		TimeLineId = "2",
		Context_zht = "整個世界變輕了。",
		Context_it = "Il mondo diventa leggero.",
		Context_zhs = "整个世界变轻了。",
		MovieId = "2002",
		Context_pt = "O mundo se faz luz.",
		Context_es = "El mundo se vuelve ligero.",
		PanelIndex = "3",
		Context_de = "Die Welt wird Licht.",
		Context_jp = "世界は軽くなった。"
	},
	{
		Begin = "4.5",
		End = "8.5",
		StoryId = "1",
		Context_us = "The world returns to normal.",
		Context_kr = "세상의 무게가 무거워졌습니다.",
		Context_ru = "Мир вернется к тому, что было.",
		Context_fr = "Le monde revient à la normale.",
		TimeLineId = "3",
		Context_zht = "整個世界變重了。",
		Context_it = "Il mondo ritorna normale.",
		Context_zhs = "整个世界变重了。",
		MovieId = "2003",
		Context_pt = "O mundo volta ao normal.",
		Context_es = "El mundo vuelve a la normalidad.",
		PanelIndex = "3",
		Context_de = "Die Welt wird wieder normal.",
		Context_jp = "世界は重くなった。"
	},
	{
		Begin = "2",
		End = "3.9",
		StoryId = "6",
		Context_us = "Look! Teresa!",
		Context_kr = "저기 봐! 테레사야!",
		Context_ru = "Смотри! Тереза!",
		Context_fr = "Regarde ! Teresa !",
		TimeLineId = "2",
		Audio = "6_2002_1",
		Context_zht = "看！德蕾莎！",
		Context_it = "Guarda! Teresa!",
		Context_zhs = "看！特蕾莎！",
		MovieId = "2002",
		Context_pt = "Teresa! Olha!",
		Context_es = "¡Mira! ¡Es Teresa!",
		PanelIndex = "3",
		Context_de = "Da! Teresa!",
		Context_jp = "見ろ！テレサだ ！"
	},
	{
		Begin = "0.36",
		End = "5",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "7",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2007",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "5.67",
		End = "7.67",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "7",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2007",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "8.67",
		End = "11",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "7",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2007",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "13",
		End = "18",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "7",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2007",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "1.6",
		End = "3.43",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "9",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2009",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "3.93",
		End = "6.36",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "9",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2009",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "1.3",
		End = "4",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "10",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2010",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "4.33",
		End = "7.33",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "10",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2010",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "23.5",
		End = "24.5",
		StoryId = "301",
		Context_us = "Liar!",
		Context_kr = "이 사기꾼!",
		Context_ru = "Лжец!",
		Context_fr = "Menteur !",
		TimeLineId = "1",
		Audio = "301_2001_1",
		Context_zht = "騙子！",
		Context_it = "Bugiardo!",
		Context_zhs = "骗子！",
		MovieId = "2001",
		Context_pt = "Mentira!",
		Context_es = "¡Mentiroso!",
		PanelIndex = "3",
		Context_de = "Lügner!",
		Context_jp = "噓つき！"
	},
	{
		Begin = "29",
		End = "30",
		StoryId = "301",
		Context_us = "Teresa?",
		Context_kr = "테레사?",
		Context_ru = "Тереза?",
		Context_fr = "Teresa ?",
		TimeLineId = "1",
		Audio = "301_2001_2",
		Context_zht = "德蕾莎？",
		Context_it = "Teresa?",
		Context_zhs = "特蕾莎？",
		MovieId = "2001",
		Context_pt = "Teresa?",
		Context_es = "¿Teresa?",
		PanelIndex = "3",
		Context_de = "Teresa?",
		Context_jp = "テレサ？"
	},
	{
		Begin = "13",
		End = "18",
		StoryId = "99",
		Context_us = "",
		Context_kr = "",
		Context_ru = "",
		Context_fr = "",
		TimeLineId = "7",
		Context_zht = "",
		Context_it = "",
		Context_zhs = "",
		MovieId = "2007",
		Context_pt = "",
		Context_es = "",
		PanelIndex = "3",
		Context_de = "",
		Context_jp = ""
	},
	{
		Begin = "2",
		End = "4",
		StoryId = "301",
		Context_us = "I trusted you so much!",
		Context_kr = "내가 얼마나 당신을 믿었는데!",
		Context_ru = "Я так тебе доверяла!",
		Context_fr = "J'avais confiance en toi !",
		TimeLineId = "3",
		Audio = "301_2003_1",
		Context_zht = "我是那麼的相信你 ！",
		Context_it = "Mi fidavo così tanto di te!",
		Context_zhs = "我是那么的相信你 ！",
		MovieId = "2003",
		Context_pt = "Eu confiei tanto em você!",
		Context_es = "¡Confiaba en ti con todo mi corazón!",
		PanelIndex = "3",
		Context_de = "Ich habe dir so sehr vertraut!",
		Context_jp = "信じてたのに…！"
	},
	{
		Begin = "2",
		End = "7",
		StoryId = "301",
		Context_us = "Everything flows to a doomed end... You knew this all along...",
		Context_kr = "운명은 정해져 있습니다…당신도 처음부터 알았을 터…",
		Context_ru = "Все обречено на погибель... Ты знал это все время...",
		Context_fr = "Tout a une fin inexorable... Tu le savais depuis le départ...",
		TimeLineId = "4",
		Audio = "301_2004_1",
		Context_zht = "結果早已註定……你從一開始就知道……",
		Context_it = "Tutto scorre verso un tragico destino... L'hai sempre saputo...",
		Context_zhs = "结果早已注定……你从一开始就知道……",
		MovieId = "2004",
		Context_pt = "Tudo flui para um final condenado... você sempre soube disso...",
		Context_es = "Todo se dirige hacia un final condenado a la perdición... Siempre lo supiste...",
		PanelIndex = "3",
		Context_de = "Alles mündet in ein dem Untergang geweihten Ende ... Und du wusstest es die ganze Zeit ...",
		Context_jp = "結果は決まってた……お前は最初から知ってた……"
	},
	{
		Begin = "2",
		End = "4.9",
		StoryId = "301",
		Context_us = "Do you think with that, you would be forgiven?",
		Context_kr = "당신이 이런다고 용서받을 것 같아요?",
		Context_ru = "Думаешь, что будешь прощен за то, что натворил?",
		Context_fr = "Pensais-tu que ça suffirait pour te faire pardonner ?",
		TimeLineId = "5",
		Audio = "301_2005_1",
		Context_zht = "你以為這樣，就能獲得原諒了嗎？",
		Context_it = "E con questo credi di farti perdonare?",
		Context_zhs = "你以为这样，就能获得原谅了吗？",
		MovieId = "2005",
		Context_pt = "Você acha que, com isso, haverá perdão?",
		Context_es = "¿Crees que haciendo eso recibirás el perdón que buscas?",
		PanelIndex = "3",
		Context_de = "Dachtest du wirklich, man würde dir vergeben?",
		Context_jp = "そんなんで許せるとでも思ったの？"
	},
	{
		Begin = "5",
		End = "10",
		StoryId = "301",
		Context_us = "You could have saved her, but instead, you betrayed her!",
		Context_kr = "그녀를 구할 수 있었으면서, 그녀를 배신하다니!",
		Context_ru = "Ты мог ее спасти, но вместо этого предал!",
		Context_fr = "Tu aurais pu la sauver, mais tu l'as trahie !",
		TimeLineId = "5",
		Audio = "301_2005_2",
		Context_zht = "你本來可以救她，可你卻背叛了她！",
		Context_it = "Avresti potuto salvarla, invece l'hai tradita!",
		Context_zhs = "你本来可以救她，可你却背叛了她！",
		MovieId = "2005",
		Context_pt = "Você podia tê-la salvado mas, em vez disso, a traiu!",
		Context_es = "¡Podrías haberla salvado, pero en su lugar, decidiste traicionarla!",
		PanelIndex = "3",
		Context_de = "Du hättest sie retten können, doch stattdessen hat du sie verraten!",
		Context_jp = "彼女を救えるのに、あなたは裏切った！"
	},
	{
		Begin = "20.5",
		End = "21.5",
		StoryId = "301",
		Context_us = "You! You are full of lies!",
		Context_kr = "전부 거짓말!",
		Context_ru = "Ты! Ты – лжец до мозга костей!",
		Context_fr = "Toi ! Tu n'es qu'un menteur !",
		TimeLineId = "5",
		Audio = "301_2005_3",
		Context_zht = "充斥謊言！",
		Context_it = "Tu! Sei solo un bugiardo!",
		Context_zhs = "充斥谎言！",
		MovieId = "2005",
		Context_pt = "Você! Só mentiras!",
		Context_es = "¡No eres más que un mentiroso!",
		PanelIndex = "3",
		Context_de = "Du! Du bist voller Lügen!",
		Context_jp = "いつもいつも噓ばっかり！"
	},
	{
		Begin = "33",
		End = "36",
		StoryId = "301",
		Context_us = "Terrence, you have never failed God.",
		Context_kr = "테런스, 자네는 이제껏 신을 실망시킨 적이 없잖은가!",
		Context_ru = "Терренс, ты никогда не отступал от Бога.",
		Context_fr = "Terrence, tu n'as jamais failli à Dieu.",
		TimeLineId = "5",
		Audio = "301_2005_4",
		Context_zht = "泰倫斯，你從未令神失望！",
		Context_it = "Terrence, non hai mai deluso Dio.",
		Context_zhs = "泰伦斯，你从未令神失望！",
		MovieId = "2005",
		Context_pt = "Terrence, você nunca falhou perante Deus.",
		Context_es = "Terrence, nunca has fallado ante Dios.",
		PanelIndex = "3",
		Context_de = "Terrence, du hast Gott nie enttäuscht.",
		Context_jp = "テレンス。君は神に失望されなかったのだ！"
	},
	{
		Begin = "4",
		End = "6",
		StoryId = "302",
		Context_us = "Viola?",
		Context_kr = "비올라?",
		Context_ru = "Виола?",
		Context_fr = "Viola ?",
		TimeLineId = "1",
		Context_zht = "薇奧拉？",
		Context_it = "Viola?",
		Context_zhs = "维奥拉？",
		MovieId = "2001",
		Context_pt = "Viola?",
		Context_es = "¿Viola?",
		PanelIndex = "3",
		Context_de = "Viola?",
		Context_jp = "ビオラ？"
	},
	{
		Begin = "0",
		End = "3.5",
		StoryId = "302",
		Context_us = "Oh look! It's the daughter of a traitor...",
		Context_kr = "글쎄, 저 아이가 반역자의 딸이래요...",
		Context_ru = "О, глядите! Дочь предателя...",
		Context_fr = "Oh regardez ! C'est la fille d'un traître...",
		TimeLineId = "2",
		Context_zht = "看！那個叛徒的女兒……",
		Context_it = "Oh, guarda! È la figlia di un traditore...",
		Context_zhs = "看！那个叛徒的女儿……",
		MovieId = "2002",
		Context_pt = "Veja! É a filha do traidor...",
		Context_es = "¡Mira! Es la hija de un traidor...",
		PanelIndex = "3",
		Context_de = "Sieh an! Die Tochter eines Verräters ...",
		Context_jp = "見ろ！あの裏切り者の娘だ……"
	},
	{
		Begin = "0",
		End = "6",
		StoryId = "302",
		Context_us = "Her father made a deal with the Devil as he wanted to destroy the Blessedland...",
		Context_kr = "저 아이 아빠가 축복의 땅을 파괴하려고 악마랑 거래했다더군.",
		Context_ru = "Ее отец заключил сделку с Дьяволом, а все из-за того, что хотел уничтожить Святую Землю...",
		Context_fr = "Son père a passé un accord avec le diable, car il voulait détruire Terrebénie...",
		TimeLineId = "3",
		Context_zht = "她的父親和惡魔做了交易，想要毀滅賜福之地……",
		Context_it = "Suo padre ha fatto un patto col Diavolo per distruggere la Terra benedetta...",
		Context_zhs = "她的父亲和恶魔做了交易，想要毁灭赐福之地……",
		MovieId = "2003",
		Context_pt = "O pai dela fez um acordo com o Diabo para destruir as Terras Abençoadas...",
		Context_es = "Su padre hizo un trato con el demonio para destruir Tierrabendita...",
		PanelIndex = "3",
		Context_de = "Ihr Vater hat sich mit dem Teufel eingelassen. Er wollte das Seligenland vernichten ...",
		Context_jp = "父親が悪魔と取引をして、恵みの地を滅ぼそうとした……"
	},
	{
		Begin = "0",
		End = "2",
		StoryId = "302",
		Context_us = "What about her mother?",
		Context_kr = "아이 엄마는요?",
		Context_ru = "А кто ее мать?",
		Context_fr = "Et sa mère ?",
		TimeLineId = "4",
		Context_zht = "她的母親呢？",
		Context_it = "E sua madre?",
		Context_zhs = "她的母亲呢？",
		MovieId = "2004",
		Context_pt = "E a mãe dela?",
		Context_es = "¿Y qué pasó con su madre?",
		PanelIndex = "3",
		Context_de = "Und ihre Mutter?",
		Context_jp = "彼女、母親は？"
	},
	{
		Begin = "2.1",
		End = "7.5",
		StoryId = "302",
		Context_us = "She's missing but nobody seems to know a thing. I'm guessing she was killed by her husband.",
		Context_kr = "실종돼서 아무도 몰라. 그렇지만 내가 보기엔 쟤 아빠가 죽인 것 같아.",
		Context_ru = "Она пропала, кажется, никто ничего о ней не знает. Предполагаю, что она была убита своим мужем.",
		Context_fr = "Elle a disparu, mais personne ne semble rien savoir. J'imagine que son mari l'aura tuée.",
		TimeLineId = "4",
		Context_zht = "失蹤了，沒人知道，不過我猜是被她的父親殺死了。",
		Context_it = "È scomparsa, ma a quanto pare nessuno sa nulla. Secondo me l'ha uccisa suo marito.",
		Context_zhs = "失踪了，没人知道，不过我猜是被她的父亲杀死了。",
		MovieId = "2004",
		Context_pt = "Ela desapareceu e ninguém sabe de nada. Eu imagino que o marido a tenha matado.",
		Context_es = "Desapareció y nadie sabe nada de ella. Imagino que la habrá matado su marido.",
		PanelIndex = "3",
		Context_de = "Sie ist verschwunden, aber niemand weiß Näheres. Ich schätze, ihr Gemahl hat sie getötet ...",
		Context_jp = "行方不明だよ。旦那に殺されたってとこかな。"
	},
	{
		Begin = "2.76",
		End = "8",
		StoryId = "302",
		Context_us = "Maybe, maybe not. She is just a kid after all.",
		Context_kr = "그렇지 않을 수도 있죠. 어찌 됐든 아직 어린아이니까요.",
		Context_ru = "Может, а может и нет. Она же всё-таки ребенок.",
		Context_fr = "Peut-être. Mais ce n'est qu'une enfant, après tout.",
		TimeLineId = "5",
		Context_zht = "也許會，也許不會，她畢竟還只是個孩子。",
		Context_it = "Forse, o forse no. Dopotutto è solo una bambina.",
		Context_zhs = "也许会，也许不会，她毕竟还只是个孩子。",
		MovieId = "2005",
		Context_pt = "Talvez sim, talvez não... afinal, ela é só uma criança.",
		Context_es = "Puede, o puede que no. Al fin y al cabo, solo es una niña.",
		PanelIndex = "3",
		Context_de = "Mag sein, mag nicht sein. Schließlich ist sie noch ein Kind.",
		Context_jp = "どうだろう。まだガキだからな。"
	},
	{
		Begin = "0",
		End = "7",
		StoryId = "302",
		Context_us = "Banish her from the Blessedland or just make her a Courier. You could also just let it be.",
		Context_kr = "그냥 축복의 땅에서 추방하고 선구자가 되게 하는 건 어떨까? 알아서 살라고 하는 거지.",
		Context_ru = "Да изгнать ее из Благословенной земли или просто сделать Курьером. А можно просто оставить все как есть.",
		Context_fr = "Bannissez-la de Terrebénie ou faites-en un Héraut. Vous pouvez aussi ne rien faire.",
		TimeLineId = "6",
		Context_zht = "把她逐出賜福之地，讓她成為先驅者，自生自滅吧。",
		Context_it = "Bandiscila dalla Terra benedetta o falla diventare una Guida. Oppure non fare niente.",
		Context_zhs = "把她逐出赐福之地，让她成为先驱者，自生自灭吧。",
		MovieId = "2006",
		Context_pt = "Exile-a das Terras Abençoadas ou faça dela uma mensageira. Você também pode apenas ignorar.",
		Context_es = "Puedes desterrarla de Tierrabendita o convertirla en mensajera. O puedes dejarla tranquila.",
		PanelIndex = "3",
		Context_de = "Verbannt sie aus dem Seligenland oder macht sie einfach zur Kurierin. Ihr könntet die Sache auch auf sich beruhen lassen.",
		Context_jp = "恵みの地から放り出して、先駆者にさせりゃいいだろ。"
	},
	{
		Begin = "0",
		End = "7",
		StoryId = "302",
		Context_us = "Don't let her kind looks fool you, one's kindness is always taken advantage of by the Devil.",
		Context_kr = "겉모습에 속으면 안 돼요. 악마의 특기가 사람의 호의를 갖고 이용하는 거라잖아요.",
		Context_ru = "Не дай ей себя обмануть, чья-то добродетель всегда искушает Дьявола.",
		Context_fr = "Ne vous laissez pas duper par son genre, la gentillesse est toujours exploitée par le diable.",
		TimeLineId = "7",
		Context_zht = "別被她的外表所欺騙，惡魔最善於利用人們善意。",
		Context_it = "Non farti ingannare dal suo aspetto, il Diavolo si approfitta sempre della gentilezza delle persone.",
		Context_zhs = "别被她的外表所欺骗，恶魔最善于利用人们善意。",
		MovieId = "2007",
		Context_pt = "Não deixe a aparência dócil dela lhe enganar.  O Diabo se aproveita da gentileza.",
		Context_es = "No dejes que su apariencia te engañe, el demonio siempre se aprovecha de nuestra bondad.",
		PanelIndex = "3",
		Context_de = "Lass dich von ihrer freundlichen Art nicht täuschen. Der Teufel nutzt eine jede Freundlichkeit für sich.",
		Context_jp = "子どもだからと言って信用しちゃいけないからね。悪魔は人の善意を簡単に利用するもの。"
	},
	{
		Begin = "4",
		End = "12",
		StoryId = "302",
		Context_us = "If you wish to see your father and know the whereabouts of your mother, just do what I said. End of discussion. ",
		Context_kr = "네 아비를 다시 만나고 어미의 행방을 알고 싶다면, 군말 말고 내가 시키는 대로 해라.",
		Context_ru = "Если ты хочешь увидеть своего отца и узнать местонахождение своей матери, просто делай, что говорят. Конец обсуждений. ",
		Context_fr = "Si tu souhaites voir ton père et savoir où se trouve ta mère, fais ce que je te dis. Fin de la discussion.",
		TimeLineId = "9",
		Context_zht = "如果你想再見到你的父親，如果你想知道你母親的下落，就得照我說的去做，沒有商量的餘地。",
		Context_it = "Se desideri vedere tuo padre e sapere dove si trova tua madre, fai quello che ti ho detto. Fine della discussione. ",
		Context_zhs = "如果你想再见到你的父亲，如果你想知道你母亲的下落，就得照我说的去做，没有商量的余地。",
		MovieId = "2009",
		Context_pt = "Se você quer ver seu pai e saber o paradeiro de sua mãe, faça o que eu falei. Fim de conversa.",
		Context_es = "Si quieres ver a tu padre y descubrir el paradero de tu madre, haz lo que te diga. Fin de la discusión.",
		PanelIndex = "3",
		Context_de = "Wenn du deinen Vater sehen und wissen möchtest, wo deine Mutter sich befindet, tu einfach was ich sage. Ende der Diskussion.",
		Context_jp = "お父さんと再会し、お母さんの行方を知りたければ、俺の言う通りにするしかねえぞ。"
	},
	{
		Begin = "17",
		End = "21.5",
		StoryId = "302",
		Context_us = "Forgive me please, I just have to do this.",
		Context_kr = "이렇게 할 수밖에 없는 날 용서해 줘요.",
		Context_ru = "Прости меня, мне придется сделать это.",
		Context_fr = "Pardonne-moi, mais je dois le faire.",
		TimeLineId = "9",
		Context_zht = "原諒我，我必須這麼做。",
		Context_it = "Perdonami, ti prego. Devo farlo.",
		Context_zhs = "原谅我，我必须这么做。",
		MovieId = "2009",
		Context_pt = "Me perdoe, por favor... eu preciso fazer isso.",
		Context_es = "Por favor, perdóname, pero tengo que hacerlo.",
		PanelIndex = "3",
		Context_de = "Vergib mir, bitte, ich muss es einfach tun.",
		Context_jp = "許して……こうするしかなかったの。"
	},
	{
		Begin = "23",
		End = "28",
		StoryId = "302",
		Context_us = "I can't... just can't... get rid of this now!",
		Context_kr = "난... 도저히... 이 모든 것에서 벗어날 수 없어요!",
		Context_ru = "Я не могу... просто не могу... избавиться от этого сейчас!",
		Context_fr = "Je ne peux pas... je ne peux juste pas... m'en débarrasser !",
		TimeLineId = "9",
		Context_zht = "我沒法……沒法……擺脫這一切！",
		Context_it = "Ora non... non posso... sbarazzarmene!",
		Context_zhs = "我没法……没法……摆脱这一切！",
		MovieId = "2009",
		Context_pt = "Eu não consigo... não dá... faça sumir agora!",
		Context_es = "¡No... puedo... deshacerme de toda esta carga!",
		PanelIndex = "3",
		Context_de = "Ich ... ich werde sie einfach nicht los!",
		Context_jp = "私は……もう……逃げられないの！"
	},
	{
		Begin = "0",
		End = "2.7",
		StoryId = "302",
		Context_us = "Will the Church have her executed then?",
		Context_kr = "그럼 교회에서 저 아이도 처형하려나?",
		Context_ru = "Тогда церковь казнит ее?",
		Context_fr = "L'Église va-t-elle la faire exécuter, alors ?",
		TimeLineId = "5",
		Context_zht = "教會會處死她嗎？",
		Context_it = "Verrà giustiziata dalla Chiesa, allora?",
		Context_zhs = "教会会处死她吗？",
		MovieId = "2005",
		Context_pt = "A igreja vai executá-la?",
		Context_es = "Entonces, ¿es posible que la Iglesia la vaya a ejecutar?",
		PanelIndex = "3",
		Context_de = "Wird die Kirche sie also hinrichten lassen?",
		Context_jp = "教会は彼女を処刑するのか？"
	},
	{
		Begin = "29",
		End = "41.5",
		StoryId = "302",
		Context_us = "Oh... Viola, poor Viola, the lonely night is now over. I shall protect you from your pain once again!",
		Context_kr = "아아… 비올라, 가엾은 비올라여. 외로운 밤은 이제 끝났단다. 내가 다시 이 모든 아픔에서 널 지켜 주마!",
		Context_ru = "О... Виола, бедная Виола, одинокая ночь закончилась. В моих силах защитить тебя от боли еще раз!",
		Context_fr = "Oh... Viola, pauvre Viola, la nuit de solitude est enfin terminée. Je te protégerai de la douleur à nouveau !",
		TimeLineId = "9",
		Context_zht = "哦……薇奧拉，可憐的薇奧拉，孤獨的黑夜已經結束，我將再次保護你免於一切的傷痛！",
		Context_it = "Oh, Viola, povera Viola, la notte solitaria è giunta al termine. Ti proteggerò di nuovo dal dolore!",
		Context_zhs = "哦……维奥拉，可怜的维奥拉，孤独的黑夜已经结束，我将再次保护你免于一切的伤痛！",
		MovieId = "2009",
		Context_pt = "Ah, Viola... pobre Viola, a noite solitária acabou. Eu a protegerei da dor mais uma vez!",
		Context_es = "Oh, Viola... pobre Viola, tu solitaria noche ha terminado. ¡Yo te volveré a proteger del dolor!",
		PanelIndex = "3",
		Context_de = "Oh ... Viola, arme Viola, die einsame Nacht ist nun vorüber. Ich werde dich erneut vor Leid bewahren!",
		Context_jp = "ああ……可哀想なビオラよ。もう孤独な夜は終わった。私がすべて苦痛から守ってあげる！"
	},
	{
		Begin = "0",
		End = "12",
		StoryId = "302",
		Context_us = "Do you think you've really saved her or did you just push her deeper into the abyss?",
		Context_kr = "당신은 정말 그녀를 구했다고 생각하나요? 더 괴로운 심연 속으로 몰아넣은 건 아닐까요?",
		Context_ru = "Ты думаешь, что действительно спас ее или просто толкнул ее еще глубже в бездну?",
		Context_fr = "Tu penses vraiment l'avoir sauvée ou l'as-tu poussée encore plus loin dans l'abysse ?",
		TimeLineId = "10",
		Context_zht = "你真的覺得自己救了她嗎？還是把她推入更加痛苦的深淵？",
		Context_it = "Pensi di averla salvata davvero, o l'hai spinta ancor più a fondo nell'abisso?",
		Context_zhs = "你真的觉得自己救了她吗？还是把她推入更加痛苦的深渊？",
		MovieId = "2010",
		Context_pt = "Você acha que a salvou ou você apenas a empurrou ainda mais para o fundo do abismo?",
		Context_es = "¿De verdad crees que la has salvado, o le has dado un último empujón hacia el abismo?",
		PanelIndex = "3",
		Context_de = "Glaubst du, du hast sie wirklich gerettet, oder hast du sie nur tiefer an den Abgrund gedrängt?",
		Context_jp = "自分なら彼女を救えるとでも思ったか？さらに苦しませるだけではないのか？"
	}
}
