-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_StoryCarriage.lua

ES_StoryCarriage = {
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 1,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "14020"
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 1,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = "14020"
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 2,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "24002"
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 2,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "24002"
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 3,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 3,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 3,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 3,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 4,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 4,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 3,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 4,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 5,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 5,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 3,
		ShowQuestId = "",
		AreaId = 2,
		StoryId = 5,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 1,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 6,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 6,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 7,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 1,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 7,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 1,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 3,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 7,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 1,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 4,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 7,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 1,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 8,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 8,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = "34002"
	},
	{
		CarriageId = 3,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 8,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 1,
		DialogId = "34002"
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 2,
		StoryId = 9,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = ""
	},
	{
		CarriageId = 2,
		ShowQuestId = "",
		AreaId = 2,
		StoryId = 9,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 0,
		Direction = 2,
		DialogId = ""
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 99,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 1,
		Direction = 1,
		DialogId = ""
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 301,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 1,
		Direction = 1,
		DialogId = ""
	},
	{
		CarriageId = 1,
		ShowQuestId = "",
		AreaId = 1,
		StoryId = 302,
		OpenItemId = 0,
		HideQuestId = "",
		CompleteQuestId = "",
		Transfer = 1,
		Direction = 1,
		DialogId = ""
	}
}
