-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_StoryTimeLine.lua

ES_StoryTimeLine = {
	{
		HideQuestId = "33013",
		ShowQuestId = "",
		CompleteQuestId = "33013",
		StoryId = 301,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "33014",
		ShowQuestId = "33013",
		CompleteQuestId = "33014",
		StoryId = 301,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "33015",
		ShowQuestId = "33014",
		CompleteQuestId = "33015;33019",
		StoryId = 301,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "33016",
		ShowQuestId = "33015",
		CompleteQuestId = "33016",
		StoryId = 301,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 4,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "33017",
		ShowQuestId = "33016",
		CompleteQuestId = "33017;33021",
		StoryId = 301,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 5,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "13701",
		ShowQuestId = "",
		CompleteQuestId = "13701",
		StoryId = 1,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "13702",
		StoryId = 1,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "13703",
		StoryId = 1,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "23701",
		ShowQuestId = "",
		CompleteQuestId = "23701;23702",
		StoryId = 2,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "43701",
		StoryId = 4,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 4,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 0,
		CompleteQuestPreId = "43702"
	},
	{
		HideQuestId = "43703;45057",
		ShowQuestId = "45033",
		CompleteQuestId = "43703",
		StoryId = 4,
		InteractType = 3,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "43704",
		ShowQuestId = "",
		CompleteQuestId = "43704",
		StoryId = 4,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 4,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "43705",
		StoryId = 4,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 5,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "53701",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "53702",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "53703",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "53704",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 4,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "53705",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 5,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "53706",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 6,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "53707;53006",
		ShowQuestId = "53708",
		CompleteQuestId = "53707",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 7,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "53006",
		ShowQuestId = "",
		CompleteQuestId = "53708",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 8,
		ToArea = 3,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "53709",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 9,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "53710",
		ShowQuestId = "",
		CompleteQuestId = "53710",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 10,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "53711",
		ShowQuestId = "",
		CompleteQuestId = "53711;53713",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 11,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "53712",
		StoryId = 5,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 12,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "63701",
		ShowQuestId = "",
		CompleteQuestId = "63701",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "63702;63014",
		ShowQuestId = "",
		CompleteQuestId = "63702",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "63703",
		ShowQuestId = "",
		CompleteQuestId = "63703",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "63704",
		ShowQuestId = "",
		CompleteQuestId = "63704;62301;62303",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 4,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "63705",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 5,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "63706",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 6,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "63707;61005",
		ShowQuestId = "",
		CompleteQuestId = "63707;63712",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 7,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "63708",
		ShowQuestId = "61001",
		CompleteQuestId = "63708;63709;63710;63714",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 8,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "63711",
		ShowQuestId = "",
		CompleteQuestId = "63711;63713",
		StoryId = 6,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 9,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "73714",
		StoryId = 7,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73715",
		ShowQuestId = "",
		CompleteQuestId = "73715",
		StoryId = 7,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "73717",
		StoryId = 7,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "73002",
		CompleteQuestId = "73716;71003;63018;73718",
		StoryId = 7,
		InteractType = 0,
		RevertQuestId = "73719;16017",
		TimeLineId = 4,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "73002",
		CompleteQuestId = "73719",
		StoryId = 7,
		InteractType = 0,
		RevertQuestId = "71003;73716;63018",
		TimeLineId = 5,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "83701",
		ShowQuestId = "",
		CompleteQuestId = "83701",
		StoryId = 8,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "93007",
		ShowQuestId = "95106",
		CompleteQuestId = "93007",
		StoryId = 9,
		InteractType = 1,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "93008",
		ShowQuestId = "92504;92505",
		CompleteQuestId = "93008",
		StoryId = 9,
		InteractType = 1,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "93019",
		ShowQuestId = "",
		CompleteQuestId = "93019",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 120,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 130,
		ToArea = 3,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "93002",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 210,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "93017",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 230,
		ToArea = 3,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 260,
		ToArea = 6,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 310,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "93017",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 320,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 4,
		RevertQuestId = "",
		TimeLineId = 340,
		ToArea = 4,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 360,
		ToArea = 6,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 4,
		RevertQuestId = "",
		TimeLineId = 430,
		ToArea = 3,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 4,
		RevertQuestId = "",
		TimeLineId = 450,
		ToArea = 5,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 460,
		ToArea = 6,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 4,
		RevertQuestId = "",
		TimeLineId = 540,
		ToArea = 4,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 620,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 630,
		ToArea = 3,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "93006",
		StoryId = 9,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 640,
		ToArea = 4,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73701",
		ShowQuestId = "",
		CompleteQuestId = "73701",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73702",
		ShowQuestId = "73701",
		CompleteQuestId = "73702",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73703",
		ShowQuestId = "73702",
		CompleteQuestId = "73703",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73704",
		ShowQuestId = "73703",
		CompleteQuestId = "73704",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 4,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73705",
		ShowQuestId = "73704",
		CompleteQuestId = "73705",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 5,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73706",
		ShowQuestId = "73705",
		CompleteQuestId = "73706",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 6,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73707",
		ShowQuestId = "73706",
		CompleteQuestId = "73707",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 7,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73708",
		ShowQuestId = "73707",
		CompleteQuestId = "73708",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 8,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73709",
		ShowQuestId = "3021006",
		CompleteQuestId = "73709",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 9,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73710",
		ShowQuestId = "",
		CompleteQuestId = "73710",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 10,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73711",
		ShowQuestId = "3021005",
		CompleteQuestId = "73711",
		StoryId = 302,
		InteractType = 1,
		RevertQuestId = "",
		TimeLineId = 11,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73712;3021006",
		ShowQuestId = "3025004",
		CompleteQuestId = "73712",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 12,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "73713;3021005",
		ShowQuestId = "3025005",
		CompleteQuestId = "73713",
		StoryId = 302,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 13,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1005,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 1,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1005,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1005,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1005,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 4,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1005,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 5,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1005,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 6,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1006,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 5,
		ToArea = 2,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1006,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 6,
		ToArea = 1,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1002,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 2,
		ToArea = 0,
		CompleteQuestPreId = ""
	},
	{
		HideQuestId = "",
		ShowQuestId = "",
		CompleteQuestId = "",
		StoryId = 1002,
		InteractType = 0,
		RevertQuestId = "",
		TimeLineId = 3,
		ToArea = 0,
		CompleteQuestPreId = ""
	}
}
