-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_StoryStair.lua

ES_StoryStair = {
	{
		DialogId = 0,
		ShowQuestId = "12501",
		StoryId = 1,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "22501",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "22502",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 4,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 2,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 3,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 4,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 3,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 3,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 6,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 3,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 3,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "42501",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 3,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "42502",
		StoryId = 4,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 5,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "52501",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "52502",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 14,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 15,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 16,
		HideQuestId = "",
		ReverbId = 5,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 17,
		HideQuestId = "",
		ReverbId = 5,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 18,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 19,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 20,
		HideQuestId = "",
		ReverbId = 5,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 21,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 22,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 23,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 24,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 25,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 28,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "52503",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 29,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 30,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "52505",
		StoryId = 5,
		CompleteQuestId = "",
		StairId = 31,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 7,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 7,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "62502",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 6,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 9,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 14,
		HideQuestId = "",
		ReverbId = 9,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 15,
		HideQuestId = "",
		ReverbId = 1,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 16,
		HideQuestId = "",
		ReverbId = 2,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 17,
		HideQuestId = "",
		ReverbId = 10,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "62501",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 18,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 19,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 6,
		CompleteQuestId = "",
		StairId = 20,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 8,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 5,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 7,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 2,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "72501",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 6,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 7,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 6,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "92501",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "92502",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "92507",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 14,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 15,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 16,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 17,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 18,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "92503",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 19,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 20,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 21,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 22,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 23,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 24,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 25,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "92506",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 26,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 27,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 28,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 29,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "92509",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 30,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 31,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 32,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 33,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 34,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 35,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 9,
		CompleteQuestId = "",
		StairId = 36,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 402,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 402,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 403,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 403,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 403,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 403,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 403,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 403,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 404,
		CompleteQuestId = "",
		StairId = 14,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 405,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 405,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 406,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 406,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 407,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 407,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 408,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 409,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 409,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 409,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 409,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 409,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 409,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 410,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 411,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 411,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 411,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 411,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 411,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 411,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 412,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 412,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 413,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 413,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 413,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 414,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 414,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1001,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1001,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 4,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 1,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1002,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1003,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 4,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1003,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1003,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 6,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1003,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1003,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 3,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1004,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 5,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 14,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 15,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 16,
		HideQuestId = "",
		ReverbId = 5,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 17,
		HideQuestId = "",
		ReverbId = 5,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 18,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 19,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 20,
		HideQuestId = "",
		ReverbId = 5,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 21,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 22,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 23,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 24,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 25,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 28,
		HideQuestId = "",
		ReverbId = 4,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 29,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 30,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1005,
		CompleteQuestId = "",
		StairId = 31,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 7,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 7,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 0,
		Type = 2,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 12,
		HideQuestId = "",
		ReverbId = 6,
		Type = 1,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 13,
		HideQuestId = "",
		ReverbId = 9,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 14,
		HideQuestId = "",
		ReverbId = 9,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 15,
		HideQuestId = "",
		ReverbId = 1,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 16,
		HideQuestId = "",
		ReverbId = 2,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 17,
		HideQuestId = "",
		ReverbId = 10,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 18,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 19,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1006,
		CompleteQuestId = "",
		StairId = 20,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 1,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 2,
		HideQuestId = "",
		ReverbId = 8,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 5,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 4,
		HideQuestId = "",
		ReverbId = 7,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 5,
		HideQuestId = "",
		ReverbId = 2,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 6,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 7,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 8,
		HideQuestId = "",
		ReverbId = 6,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 9,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 10,
		HideQuestId = "",
		ReverbId = 3,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 11,
		HideQuestId = "",
		ReverbId = 6,
		Type = 2,
		AreaType = 1
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1001,
		CompleteQuestId = "",
		StairId = 3,
		HideQuestId = "",
		ReverbId = 0,
		Type = 1,
		AreaType = 2
	},
	{
		DialogId = 0,
		ShowQuestId = "",
		StoryId = 1007,
		CompleteQuestId = "",
		StairId = 21,
		HideQuestId = "",
		ReverbId = 2,
		Type = 1,
		AreaType = 2
	}
}
