-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_SiteInfo.lua

ES_SiteInfo = {
	{
		Description = "覆盖整个地图的黑雾",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "马车",
		PortalId = 0,
		SiteId = 99,
		SiteIcon = 0
	},
	{
		Description = "言语无法描绘的巨像，目光无从传递的仰望，蝼蚁般的人类依附在神秘的光环之下，夜以继日地追赶，日月同辉的光芒，无名的遗迹终于让海格姆停下了沉重的脚步，追随者们享受着片刻的静息，为继续无尽的旅途稍作停留。",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "海格姆",
		PortalId = 0,
		SiteId = 100,
		SiteIcon = 1
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "离岸孤村(南)",
		PortalId = 1,
		SiteId = 101,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "13010",
		ToPortal = "201",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "13010",
		Name = "离岸孤村(西)",
		PortalId = 2,
		SiteId = 102,
		SiteIcon = 0
	},
	{
		Description = "神早已抛弃了他们，似乎唯有对着阿达米亚不断地虔诚祈祷，才可以延续游丝般微弱的血脉。不计代价地抓住这不知何时就会熄灭的微光。",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "阿达米亚",
		PortalId = 0,
		SiteId = 200,
		SiteIcon = 2
	},
	{
		Description = "",
		ShowQuestId = "25055",
		ToPortal = "102",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "25055",
		Name = "渡鸦古道",
		PortalId = 1,
		SiteId = 201,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "25057",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "25057",
		Name = "新生之地",
		PortalId = 2,
		SiteId = 202,
		SiteIcon = 0
	},
	{
		Description = "天火坠落，击碎了伊瑟流姆锈迹斑斑的誓言，昔日的战神驻地如今爬满荒草。孤魂野鬼在悲泣，而意志消沉的无名者对残生已无所求。",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "伊瑟流姆",
		PortalId = 0,
		SiteId = 300,
		SiteIcon = 3
	},
	{
		Description = "",
		ShowQuestId = "21006",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "21006",
		Name = "放逐之径",
		PortalId = 1,
		SiteId = 301,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "35037",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "35037",
		Name = "风熄谷",
		PortalId = 2,
		SiteId = 302,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "35038",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "35038",
		Name = "逆光之峡",
		PortalId = 3,
		SiteId = 303,
		SiteIcon = 0
	},
	{
		Description = "罪孽深重的流亡者，用仇恨将这无光的空城从沉睡中唤醒。猩红的伊迪斯啊，你在为谁的命运哭泣？",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "伊迪斯",
		PortalId = 0,
		SiteId = 400,
		SiteIcon = 4
	},
	{
		Description = "",
		ShowQuestId = "35022",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "35022",
		Name = "荒城关口",
		PortalId = 1,
		SiteId = 401,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "45039",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "45039",
		Name = "审判圣庭",
		PortalId = 2,
		SiteId = 402,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "41001",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "41001",
		Name = "复明海岸",
		PortalId = 3,
		SiteId = 403,
		SiteIcon = 0
	},
	{
		Description = "参天古树覆盖的幽暗密林，基塔布模糊的记忆里或许依然回响着古老文明的呐喊声。世代传承的仪式无力挽救，毁灭的种子早已生根。",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "基塔布",
		PortalId = 0,
		SiteId = 500,
		SiteIcon = 5
	},
	{
		Description = "",
		ShowQuestId = "35022",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "35022",
		Name = "血雾林地",
		PortalId = 1,
		SiteId = 501,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "55034",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "55034",
		Name = "黑羊岭",
		PortalId = 2,
		SiteId = 502,
		SiteIcon = 0
	},
	{
		Description = "受神眷顾的赐福之地，昔日的光荣和鼎盛正日复一日地衰落。在贤者汇聚的圣殿里，阴影踏着细碎的脚步，逼近那至高的信仰。",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "赐福之地",
		PortalId = 0,
		SiteId = 600,
		SiteIcon = 6
	},
	{
		Description = "",
		ShowQuestId = "41001",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "41001",
		Name = "净灵之途",
		PortalId = 1,
		SiteId = 601,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "65064",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "65064",
		Name = "弗拉梅尔圣教廷",
		PortalId = 2,
		SiteId = 602,
		SiteIcon = 0
	},
	{
		Description = "先民鬼斧神工造就的地下世界，被放逐的灵魂低诉着哀伤的秘密，洞悉的人沉入回忆的荒坟，与厄运拥眠。",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "地下溶洞",
		PortalId = 0,
		SiteId = 700,
		SiteIcon = 7
	},
	{
		Description = "",
		ShowQuestId = "55032",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "71003",
		EnableQuestId = "55032",
		Name = "圣塔密道",
		PortalId = 1,
		SiteId = 701,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "73002",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "71003",
		EnableQuestId = "73002",
		Name = "先民遗迹",
		PortalId = 2,
		SiteId = 702,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "巨像墓地",
		PortalId = 0,
		SiteId = 800,
		SiteIcon = 8
	},
	{
		Description = "沉睡于深海的上古巨兽，无人勘破的千年记忆在此彷徨。灵魂的长河带来永恒的安宁，诅咒的宿命早已被人们遗忘。",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "伊西索亚",
		PortalId = 0,
		SiteId = 900,
		SiteIcon = 9
	},
	{
		Description = "",
		ShowQuestId = "95137;41001",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "95163;41001",
		Name = "石鳍浅滩",
		PortalId = 1,
		SiteId = 901,
		SiteIcon = 0
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "海格姆 - 秘窟",
		PortalId = 0,
		SiteId = 10100,
		SiteIcon = 101
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "阿达米亚 - 秘窟",
		PortalId = 0,
		SiteId = 10200,
		SiteIcon = 102
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "伊瑟流姆 - 秘窟",
		PortalId = 0,
		SiteId = 10300,
		SiteIcon = 103
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "伊迪斯 - 秘窟",
		PortalId = 0,
		SiteId = 10400,
		SiteIcon = 104
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "基塔布 - 秘窟",
		PortalId = 0,
		SiteId = 10500,
		SiteIcon = 105
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "恐惧之源",
		PortalId = 0,
		SiteId = 30100,
		SiteIcon = 301
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "噩梦之末",
		PortalId = 0,
		SiteId = 30200,
		SiteIcon = 302
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40100,
		SiteIcon = 401
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40200,
		SiteIcon = 402
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40300,
		SiteIcon = 403
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40400,
		SiteIcon = 404
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40500,
		SiteIcon = 405
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40600,
		SiteIcon = 406
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40700,
		SiteIcon = 407
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40800,
		SiteIcon = 408
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 40900,
		SiteIcon = 409
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 41000,
		SiteIcon = 410
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 41100,
		SiteIcon = 411
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 41200,
		SiteIcon = 412
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 41300,
		SiteIcon = 413
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 41400,
		SiteIcon = 414
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 41500,
		SiteIcon = 415
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 49900,
		SiteIcon = 499
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 50100,
		SiteIcon = 501
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 50200,
		SiteIcon = 502
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 50300,
		SiteIcon = 503
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 50400,
		SiteIcon = 504
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 50500,
		SiteIcon = 505
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 50600,
		SiteIcon = 506
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 50700,
		SiteIcon = 507
	},
	{
		Description = "",
		ShowQuestId = "",
		ToPortal = "",
		CompleteQuestId = "",
		HideQuestId = "",
		EnableQuestId = "",
		Name = "黑雾",
		PortalId = 0,
		SiteId = 59900,
		SiteIcon = 599
	}
}
