-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_StoryTutorial.lua

ES_StoryTutorial = {
	{
		TutorialId = 1001,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16001",
		DescriptionKeyboard = "{51}{52}{53}{54}移动\n{97}控制视角",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{98}移动\n{97}控制视角",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "<color=#C7AE6EFF>屏幕左区域</color> 移动\n<color=#C7AE6EFF>屏幕右区域</color> 控制视角",
		ShowQuestId = "15001",
		Forward = 0,
		HideQuestId = "16001;17001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1002,
		ImageId = 10001,
		IsCenter = 0,
		CompleteQuestId = "15052",
		DescriptionKeyboard = "{99}锁定目标\n轻攻击{31}：速度快，威力小\n重攻击{21}：速度慢，威力大，容易打断敌人的动作\n闪避{00}：回避，可连按两次\n格挡{11}：格挡，长按维持防御",
		MazeOnly = 0,
		OpenRage = 1,
		DescriptionJoystick = "{99}锁定目标\n轻攻击{31}：速度快，威力小\n重攻击{21}：速度慢，威力大，容易打断敌人的动作\n闪避{00}：回避，可连按两次\n格挡{11}：格挡，长按维持防御",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "{99}锁定目标\n轻攻击{31}：速度快，威力小\n重攻击{21}：速度慢，威力大，容易打断敌人的动作\n闪避{00}：回避，可连按两次\n格挡{11}：格挡，长按维持防御",
		ShowQuestId = "17001",
		Forward = 0,
		HideQuestId = "15052",
		Title = "锁定与攻击",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1003,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "19001",
		DescriptionKeyboard = "{99}锁定目标\n{31}轻攻击 {21}重攻击",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{99}锁定目标\n{31}轻攻击 {21}重攻击",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "{99}锁定目标\n{31}轻攻击 {21}重攻击",
		ShowQuestId = "15052",
		Forward = 0,
		HideQuestId = "16002;19001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1004,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "19002",
		DescriptionKeyboard = "{00}闪避或突进\n按住{11}进行格挡",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{00}闪避或突进\n按住{11}进行格挡",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "{00}闪避或突进\n按住{11}进行格挡",
		ShowQuestId = "19001",
		Forward = 0,
		HideQuestId = "16003;19002",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1005,
		ImageId = 10018,
		IsCenter = 0,
		CompleteQuestId = "15062;19008;15076",
		DescriptionKeyboard = "与污染者战斗，角色的理智会遭到侵蚀。\n理智大幅降低后，角色会进入异常状态，遭受异常影响。在属性菜单可查看异常影响的详情。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "与污染者战斗，角色的理智会遭到侵蚀。\n理智大幅降低后，角色会进入异常状态，遭受异常影响。在属性菜单可查看异常影响的详情。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "与污染者战斗，角色的理智会遭到侵蚀。\n理智大幅降低后，角色会进入异常状态，遭受异常影响。在属性菜单可查看异常影响的详情。",
		ShowQuestId = "15074",
		Forward = 1006,
		HideQuestId = "15062;15076",
		Title = "理智与异常「1」",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1006,
		ImageId = 10024,
		IsCenter = 0,
		CompleteQuestId = "19008",
		DescriptionKeyboard = "在祭坛休息，或者使用理智药水，可恢复理智。\n快捷道具栏已装备理智药水，按{94} 使用，恢复理智。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "在祭坛休息，或者使用理智药水，可恢复理智。\n快捷道具栏已装备理智药水，按{94} 使用，恢复理智。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "在祭坛休息，或者使用理智药水，可恢复理智。\n快捷道具栏已装备理智药水，点击快捷栏使用，恢复理智。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "19008",
		Title = "理智与异常「2」",
		Delay = 0,
		Backward = 1005
	},
	{
		TutorialId = 1007,
		ImageId = 10012,
		IsCenter = 0,
		CompleteQuestId = "15053",
		DescriptionKeyboard = "按{91}使用生命药水，回复生命。\n生命药水数量有限，在祭坛休息可补充生命药水。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "按{91}使用生命药水，回复生命。\n生命药水数量有限，在祭坛休息可补充生命药水。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "点击{91}使用生命药水，回复生命。\n生命药水数量有限，在祭坛休息可补充生命药水。",
		ShowQuestId = "19013",
		Forward = 0,
		HideQuestId = "15053;25055",
		Title = "生命药水",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 1008,
		ImageId = 10002,
		IsCenter = 0,
		CompleteQuestId = "15054",
		DescriptionKeyboard = "轻攻击{31}{90}重攻击{21}，施展战技：突刺。可快速接近敌人进行攻击。\n需要消耗30怒气 。攻击敌人，可以积攒怒气。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "轻攻击{31}{90}重攻击{21}，施展战技：突刺。可快速接近敌人进行攻击。\n需要消耗30怒气 。攻击敌人，可以积攒怒气。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "轻攻击{31}{90}重攻击{21}，施展战技：突刺。可快速接近敌人进行攻击。\n需要消耗30怒气 。攻击敌人，可以积攒怒气。",
		ShowQuestId = "17002",
		Forward = 0,
		HideQuestId = "15054",
		Title = "使用战技",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1009,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "19003",
		DescriptionKeyboard = "{31}{90}{21}突刺",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{31}{90}{21}突刺",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "{31}{90}{21}突刺",
		ShowQuestId = "15054",
		Forward = 0,
		HideQuestId = "16006;19003",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1010,
		ImageId = 10025,
		IsCenter = 0,
		CompleteQuestId = "15055",
		DescriptionKeyboard = "面对高处、远处的敌人，可使用飞刀进行攻击。\n{99}锁定目标，按{94}即可投掷飞刀。\n飞刀现已装备在快捷栏。在背包菜单中，可以编辑快捷栏。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "面对高处、远处的敌人，可使用飞刀进行攻击。\n{99}锁定目标，按{94}即可投掷飞刀。\n飞刀现已装备在快捷栏。在背包菜单中，可以编辑快捷栏。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "面对高处、远处的敌人，可使用飞刀进行攻击。\n{99}锁定目标，点击快捷栏，即可投掷飞刀。\n飞刀现已装备在快捷栏。在背包菜单中，可以编辑快捷栏。",
		ShowQuestId = "15080",
		Forward = 0,
		HideQuestId = "15055",
		Title = "使用飞刀",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1011,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16012",
		DescriptionKeyboard = "{99}锁定目标\n按{94}投掷飞刀",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{99}锁定目标\n按{94}投掷飞刀",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "{99}锁定目标\n点击{71}投掷飞刀",
		ShowQuestId = "15055",
		Forward = 0,
		HideQuestId = "16012",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1012,
		ImageId = 10004,
		IsCenter = 0,
		CompleteQuestId = "15056",
		DescriptionKeyboard = "面对危险的敌人\n可以通过轻推{98}缓行绕开",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "面对危险的敌人\n可以通过轻推{98}缓行绕开",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "面对危险的敌人\n可以通过轻推{98}缓行绕开",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15056",
		Title = "缓行",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1013,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16013",
		DescriptionKeyboard = "按{94}使用理智药水",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "按{94}使用理智药水",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "点击{72}使用理智药水",
		ShowQuestId = "19008",
		Forward = 0,
		HideQuestId = "16013",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1014,
		ImageId = 10007,
		IsCenter = 0,
		CompleteQuestId = "15064",
		DescriptionKeyboard = "{99}锁定目标\n左右移动{97}切换锁定目标",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{99}锁定目标\n左右移动{97}切换锁定目标",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "{99}锁定目标\n<color=#C7AE6EFF>屏幕右区域</color> 切换锁定目标",
		ShowQuestId = "15063",
		Forward = 0,
		HideQuestId = "15064",
		Title = "切换目标",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1015,
		ImageId = 10008,
		IsCenter = 0,
		CompleteQuestId = "15057",
		DescriptionKeyboard = "跳下的同时按{31}或{21}\n可以从上方攻击敌人",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "跳下的同时按{31}或{21}\n可以从上方攻击敌人",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "跳下的同时按{31}或{21}\n可以从上方攻击敌人",
		ShowQuestId = "13701",
		Forward = 0,
		HideQuestId = "15057",
		Title = "跃下攻击",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1016,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16008",
		DescriptionKeyboard = "跳下的同时按{31}或{21}\n可以从上方攻击敌人",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "跳下的同时按{31}或{21}\n可以从上方攻击敌人",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "跳下的同时按{31}或{21}\n可以从上方攻击敌人",
		ShowQuestId = "15057",
		Forward = 0,
		HideQuestId = "16008",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1017,
		ImageId = 10005,
		IsCenter = 0,
		CompleteQuestId = "15058",
		DescriptionKeyboard = "访问祭坛，即可保存当前游戏进度。\n在祭坛，可以献祭污秽遗留物、提升角色属性、炼金合成道具。\n死亡后，会回到最近一次访问的祭坛。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "访问祭坛，即可保存当前游戏进度。\n在祭坛，可以献祭污秽遗留物、提升角色属性、炼金合成道具。\n死亡后，会回到最近一次访问的祭坛。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "访问祭坛，即可保存当前游戏进度。\n在祭坛，可以献祭污秽遗留物、提升角色属性、炼金合成道具。\n死亡后，会回到最近一次访问的祭坛。",
		ShowQuestId = "15031",
		Forward = 0,
		HideQuestId = "15058",
		Title = "祭坛",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 1018,
		ImageId = 10016,
		IsCenter = 0,
		CompleteQuestId = "15059",
		DescriptionKeyboard = "秽石碎片、秽石等物品只能在祭坛使用，用于激活天赋，获得新的战技和能力。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "秽石碎片、秽石等物品只能在祭坛使用，用于激活天赋，获得新的战技和能力。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "秽石碎片、秽石等物品只能在祭坛使用，用于激活天赋，获得新的战技和能力。",
		ShowQuestId = "12017",
		Forward = 0,
		HideQuestId = "15059",
		Title = "秽石与天赋",
		Delay = 2,
		Backward = 0
	},
	{
		TutorialId = 1019,
		ImageId = 10006,
		IsCenter = 0,
		CompleteQuestId = "15066",
		DescriptionKeyboard = "打败敌人后可能掉落战利品，在祭坛炼金也可制作战利品。\n战利品会提供强大的力量。\n按{93} 打开菜单战利品界面，装备战利品。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "打败敌人后可能掉落战利品，在祭坛炼金也可制作战利品。\n战利品会提供强大的力量。\n按{93} 打开菜单战利品界面，装备战利品。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "打败敌人后可能掉落战利品，在祭坛炼金也可制作战利品。\n战利品会提供强大的力量。\n点击 {93} 打开菜单战利品界面，装备战利品。",
		ShowQuestId = "12301",
		Forward = 0,
		HideQuestId = "15066",
		Title = "战利品",
		Delay = 2,
		Backward = 0
	},
	{
		TutorialId = 1020,
		ImageId = 10014,
		IsCenter = 0,
		CompleteQuestId = "15060",
		DescriptionKeyboard = "污秽感染者死后的遗留物，可用于祭坛奉献，提升等级，也可用于购买道具。强大的感染者会掉落更高级的遗留物。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "污秽感染者死后的遗留物，可用于祭坛奉献，提升等级，也可用于购买道具。强大的感染者会掉落更高级的遗留物。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "污秽感染者死后的遗留物，可用于祭坛奉献，提升等级，也可用于购买道具。强大的感染者会掉落更高级的遗留物。",
		ShowQuestId = "15073",
		Forward = 0,
		HideQuestId = "15060",
		Title = "污秽遗留物",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1021,
		ImageId = 10015,
		IsCenter = 0,
		CompleteQuestId = "15061",
		DescriptionKeyboard = "战斗中按{00}来躲避来自敌人的攻击",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "战斗中按{00}来躲避来自敌人的攻击",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "战斗中按{00}来躲避来自敌人的攻击",
		ShowQuestId = "19014",
		Forward = 1022,
		HideQuestId = "15061",
		Title = "善用闪避",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1022,
		ImageId = 10004,
		IsCenter = 0,
		CompleteQuestId = "15077",
		DescriptionKeyboard = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		ShowQuestId = "15000",
		Forward = 1023,
		HideQuestId = "15077",
		Title = "善用格挡",
		Delay = 0,
		Backward = 1021
	},
	{
		TutorialId = 1023,
		ImageId = 10023,
		IsCenter = 0,
		CompleteQuestId = "15078",
		DescriptionKeyboard = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15078",
		Title = "注意精力",
		Delay = 0,
		Backward = 1022
	},
	{
		TutorialId = 1024,
		ImageId = 10015,
		IsCenter = 0,
		CompleteQuestId = "15061",
		DescriptionKeyboard = "战斗中按{00}来躲避来自敌人的攻击",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "战斗中按{00}来躲避来自敌人的攻击",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 1,
		DescriptionTouch = "战斗中按{00}来躲避来自敌人的攻击",
		ShowQuestId = "19014",
		Forward = 1025,
		HideQuestId = "15061",
		Title = "善用闪避",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1025,
		ImageId = 10004,
		IsCenter = 0,
		CompleteQuestId = "15077",
		DescriptionKeyboard = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 1,
		DescriptionTouch = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		ShowQuestId = "15000",
		Forward = 1026,
		HideQuestId = "15077",
		Title = "善用格挡",
		Delay = 0,
		Backward = 1024
	},
	{
		TutorialId = 1026,
		ImageId = 10023,
		IsCenter = 0,
		CompleteQuestId = "15078",
		DescriptionKeyboard = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 1,
		DescriptionTouch = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15078",
		Title = "注意精力",
		Delay = 0,
		Backward = 1025
	},
	{
		TutorialId = 1027,
		ImageId = 10015,
		IsCenter = 0,
		CompleteQuestId = "15061",
		DescriptionKeyboard = "战斗中按{00}来躲避来自敌人的攻击",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "战斗中按{00}来躲避来自敌人的攻击",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "战斗中按{00}来躲避来自敌人的攻击",
		ShowQuestId = "19014",
		Forward = 1028,
		HideQuestId = "15061",
		Title = "善用闪避",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1028,
		ImageId = 10004,
		IsCenter = 0,
		CompleteQuestId = "15077",
		DescriptionKeyboard = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		ShowQuestId = "15000",
		Forward = 1029,
		HideQuestId = "15077",
		Title = "善用格挡",
		Delay = 0,
		Backward = 1027
	},
	{
		TutorialId = 1029,
		ImageId = 10023,
		IsCenter = 0,
		CompleteQuestId = "15078",
		DescriptionKeyboard = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15078",
		Title = "注意精力",
		Delay = 0,
		Backward = 1028
	},
	{
		TutorialId = 1030,
		ImageId = 10015,
		IsCenter = 0,
		CompleteQuestId = "15061",
		DescriptionKeyboard = "战斗中按{00}来躲避来自敌人的攻击",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "战斗中按{00}来躲避来自敌人的攻击",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 1,
		DescriptionTouch = "战斗中按{00}来躲避来自敌人的攻击",
		ShowQuestId = "19014",
		Forward = 1031,
		HideQuestId = "15061",
		Title = "善用闪避",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1031,
		ImageId = 10004,
		IsCenter = 0,
		CompleteQuestId = "15077",
		DescriptionKeyboard = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 1,
		DescriptionTouch = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		ShowQuestId = "15000",
		Forward = 1032,
		HideQuestId = "15077",
		Title = "善用格挡",
		Delay = 0,
		Backward = 1030
	},
	{
		TutorialId = 1032,
		ImageId = 10023,
		IsCenter = 0,
		CompleteQuestId = "15078",
		DescriptionKeyboard = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 1,
		DescriptionTouch = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15078",
		Title = "注意精力",
		Delay = 0,
		Backward = 1031
	},
	{
		TutorialId = 1033,
		ImageId = 10010,
		IsCenter = 0,
		CompleteQuestId = "15083",
		DescriptionKeyboard = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		ShowQuestId = "13017",
		Forward = 0,
		HideQuestId = "15083",
		Title = "崩溃",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1034,
		ImageId = 10010,
		IsCenter = 0,
		CompleteQuestId = "15083",
		DescriptionKeyboard = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 1,
		DescriptionTouch = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		ShowQuestId = "13017",
		Forward = 0,
		HideQuestId = "15083",
		Title = "崩溃",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1035,
		ImageId = 10010,
		IsCenter = 0,
		CompleteQuestId = "15083",
		DescriptionKeyboard = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		ShowQuestId = "13017",
		Forward = 0,
		HideQuestId = "15083",
		Title = "崩溃",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1036,
		ImageId = 10010,
		IsCenter = 0,
		CompleteQuestId = "15083",
		DescriptionKeyboard = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 1,
		DescriptionTouch = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		ShowQuestId = "13017",
		Forward = 0,
		HideQuestId = "15083",
		Title = "崩溃",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1037,
		ImageId = 10028,
		IsCenter = 0,
		CompleteQuestId = "29001;29009",
		DescriptionKeyboard = "马车内有以下功能：\n与桌上地图互动，选择目的地。\n与其他角色、猫头鹰对话，购买道具。\n马车专用祭坛，提升角色属性，激活天赋等。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "马车内有以下功能：\n与桌上地图互动，选择目的地。\n与其他角色、猫头鹰对话，购买道具。\n马车专用祭坛，提升角色属性，激活天赋等。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "马车内有以下功能：\n与桌上地图互动，选择目的地。\n与其他角色、猫头鹰对话，购买道具。\n马车专用祭坛，提升角色属性，激活天赋等。",
		ShowQuestId = "25055;91001",
		Forward = 0,
		HideQuestId = "29001",
		Title = "马车",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1038,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "19005",
		DescriptionKeyboard = "{99}锁定目标\n{31}挥打 {21}射击",
		MazeOnly = 0,
		OpenRage = 1,
		DescriptionJoystick = "{99}锁定目标\n{31}挥打 {21}射击",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "{99}锁定目标\n{31}挥打 {21}射击",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "19005",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1039,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "19011",
		DescriptionKeyboard = "长按{11}全弹发射",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "长按{11}全弹发射",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "长按{11}全弹发射",
		ShowQuestId = "29004;17007",
		Forward = 0,
		HideQuestId = "19011;16014",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1040,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "19006",
		DescriptionKeyboard = "{31}{90}{21}或\n{21}{90}{31}\n使用战技",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{31}{90}{21}或\n{21}{90}{31}\n使用战技",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "{31}{90}{21}或\n{21}{90}{31}\n使用战技",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "19006",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1041,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "19007",
		DescriptionKeyboard = "{95}切换子弹\n长按{21}进行狙击",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{95}切换子弹\n长按{21}进行狙击",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "{95}切换子弹\n长按{22}或{23}进行狙击",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "19007",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1042,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16002",
		DescriptionKeyboard = "按{96}切换角色",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "按{96}切换角色",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "{96}切换角色",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "16002",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1043,
		ImageId = 10028,
		IsCenter = 0,
		CompleteQuestId = "29001;29010",
		DescriptionKeyboard = "马车内有以下功能：\n与桌上地图互动，选择前往目的地。\n与其他角色、猫头鹰对话，购买道具。\n马车专用祭坛，提升角色属性，激活天赋等。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "马车内有以下功能：\n与桌上地图互动，选择前往目的地。\n与其他角色、猫头鹰对话，购买道具。\n马车专用祭坛，提升角色属性，激活天赋等。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "马车内有以下功能：\n与桌上地图互动，选择前往目的地。\n与其他角色、猫头鹰对话，购买道具。\n马车专用祭坛，提升角色属性，激活天赋等。",
		ShowQuestId = "25055",
		Forward = 0,
		HideQuestId = "29001;91001",
		Title = "马车",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1044,
		ImageId = 10009,
		IsCenter = 0,
		CompleteQuestId = "29002",
		DescriptionKeyboard = "摇响马铃，可以呼唤格伦，回到马车。\n吹响马哨，就能回到马铃边，但需要支付一些费用。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "摇响马铃，可以呼唤格伦，回到马车。\n吹响马哨，就能回到马铃边，但需要支付一些费用。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "摇响马铃，可以呼唤格伦，回到马车。\n吹响马哨，就能回到马铃边，但需要支付一些费用。",
		ShowQuestId = "25073",
		Forward = 0,
		HideQuestId = "29002",
		Title = "马铃和哨子",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1045,
		ImageId = 10011,
		IsCenter = 0,
		CompleteQuestId = "29003",
		DescriptionKeyboard = "接下来的冒险，将有两名角色一起进行。\n按{96}切换角色。\n只有在安全状态下才能切换角色，战斗时无法切换。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "接下来的冒险，将有两名角色一起进行。\n按{96}切换角色。\n只有在安全状态下才能切换角色，战斗时无法切换。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "接下来的冒险，将有两名角色一起进行。\n点击屏幕右上角的头像，切换角色。\n只有在安全状态下才能切换角色，战斗时无法切换。",
		ShowQuestId = "25056",
		Forward = 0,
		HideQuestId = "29003",
		Title = "切换角色",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1046,
		ImageId = 10031,
		IsCenter = 0,
		CompleteQuestId = "29004",
		DescriptionKeyboard = "轻攻击{31}：用刺刀挥击\n重攻击{21}：火枪射击\n{11}：装填子弹。\n与敌人距离越远，火枪射击的威力越低。\n在天赋页面，可查看更多维奥拉的战斗技巧。",
		MazeOnly = 0,
		OpenRage = 1,
		DescriptionJoystick = "轻攻击{31}：用刺刀挥击\n重攻击{21}：火枪射击\n{11}：装填子弹。\n与敌人距离越远，火枪射击的威力越低。\n在天赋页面，可查看更多维奥拉的战斗技巧。",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 1,
		DescriptionTouch = "轻攻击{31}：用刺刀挥击\n重攻击{21}：火枪射击\n{11}：装填子弹。\n与敌人距离越远，火枪射击的威力越低。\n在天赋页面，可查看更多维奥拉的战斗技巧。",
		ShowQuestId = "17004",
		Forward = 1047,
		HideQuestId = "29004",
		Title = "维奥拉「1」",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1047,
		ImageId = 10032,
		IsCenter = 0,
		CompleteQuestId = "29004",
		DescriptionKeyboard = "按{95}切换子弹效果：\n普通子弹{66}：威力较低，数量无限。\n特殊子弹·冲击{67}：近距离射击时有极高威力，数量有限。\n特殊子弹·流血{68}：多次射击可使敌人陷入流血状态，数量有限。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "按{95}切换子弹效果：\n普通子弹{66}：威力较低，数量无限。\n特殊子弹·冲击{67}：近距离射击时有极高威力，数量有限。\n特殊子弹·流血{68}：多次射击可使敌人陷入流血状态，数量有限。",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 1,
		DescriptionTouch = "点击{95}切换子弹效果：\n普通子弹{66}：威力较低，数量无限。\n特殊子弹·冲击{67}：近距离射击时有极高威力，数量有限。\n特殊子弹·流血{68}：多次射击可使敌人陷入流血状态，数量有限。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "29004",
		Title = "维奥拉「2」",
		Delay = 0,
		Backward = 1046
	},
	{
		TutorialId = 1048,
		ImageId = 10033,
		IsCenter = 0,
		CompleteQuestId = "29005",
		DescriptionKeyboard = "贝妮塔的武器名为「净血圣座」，使用时会消耗她的生命,转化为净血，贮存在她身后的血瓶中。\n用「净血圣座」攻击敌人，也可获得净血。\n消耗净血，可释放战技。",
		MazeOnly = 0,
		OpenRage = 1,
		DescriptionJoystick = "贝妮塔的武器名为「净血圣座」，使用时会消耗她的生命,转化为净血，贮存在她身后的血瓶中。\n用「净血圣座」攻击敌人，也可获得净血。\n消耗净血，可释放战技。",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "贝妮塔的武器名为「净血圣座」，使用时会消耗她的生命,转化为净血，贮存在她身后的血瓶中。\n用「净血圣座」攻击敌人，也可获得净血。\n消耗净血，可释放战技。",
		ShowQuestId = "17005",
		Forward = 1049,
		HideQuestId = "29005",
		Title = "贝妮塔「1」",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1049,
		ImageId = 10034,
		IsCenter = 0,
		CompleteQuestId = "29005",
		DescriptionKeyboard = "按{11}，贝妮塔使用魔药强化自身。\n通过变质{95}，可改变魔药的效果：\n魔药·圣魂{69}：为贝妮塔提供护盾；\n魔药·风息{70}：提升贝妮塔的精力回复速度。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "按{11}，贝妮塔使用魔药强化自身。\n通过变质{95}，可改变魔药的效果：\n魔药·圣魂{69}：为贝妮塔提供护盾；\n魔药·风息{70}：提升贝妮塔的精力回复速度。",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "点击{11}，贝妮塔使用魔药强化自身。\n通过变质{95}，可改变魔药的效果：\n魔药·圣魂{69}：为贝妮塔提供护盾；\n魔药·风息{70}：提升贝妮塔的精力回复速度。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "29005",
		Title = "贝妮塔「2」",
		Delay = 0,
		Backward = 1048
	},
	{
		TutorialId = 1050,
		ImageId = 10035,
		IsCenter = 0,
		CompleteQuestId = "29007",
		DescriptionKeyboard = "长按{31}，消耗30净血，恢复贝妮塔的生命。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "长按{31}，消耗30净血，恢复贝妮塔的生命。",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "长按{31}，消耗30净血，恢复贝妮塔的生命。",
		ShowQuestId = "29008",
		Forward = 0,
		HideQuestId = "29007",
		Title = "贝妮塔「3」",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1051,
		ImageId = 10029,
		IsCenter = 0,
		CompleteQuestId = "29006",
		DescriptionKeyboard = "轻攻击{31}可长按蓄力，蓄力完成后松开按键，可打出更强的一拳。\n诺伍德不善于翻滚回避，但他的防御{11}可以挡住大部分攻击。",
		MazeOnly = 0,
		OpenRage = 1,
		DescriptionJoystick = "轻攻击{31}可长按蓄力，蓄力完成后松开按键，可打出更强的一拳。\n诺伍德不善于翻滚回避，但他的防御{11}可以挡住大部分攻击。",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 1,
		DescriptionTouch = "轻攻击{31}可长按蓄力，蓄力完成后松开按键，可打出更强的一拳。\n诺伍德不善于翻滚回避，但他的防御{11}可以挡住大部分攻击。",
		ShowQuestId = "17006",
		Forward = 1052,
		HideQuestId = "29006",
		Title = "诺伍德「1」",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1052,
		ImageId = 10030,
		IsCenter = 0,
		CompleteQuestId = "29006",
		DescriptionKeyboard = "轻攻击{31}会积蓄「秽灵」。\n消耗「秽灵」，诺伍德才能使用缚灵木柩{21}战斗，并积攒怒气。\n缚灵木柩的攻击威力非常高，且攻击动作不容易被敌人打断。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "轻攻击{31}会积蓄「秽灵」。\n消耗「秽灵」，诺伍德才能使用缚灵木柩{21}战斗，并积攒怒气。\n缚灵木柩的攻击威力非常高，且攻击动作不容易被敌人打断。",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 1,
		DescriptionTouch = "轻攻击{31}会积蓄「秽灵」。\n消耗「秽灵」，诺伍德才能使用缚灵木柩{21}战斗，并积攒怒气。\n缚灵木柩的攻击威力非常高，且攻击动作不容易被敌人打断。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "29006",
		Title = "诺伍德「2」",
		Delay = 0,
		Backward = 1051
	},
	{
		TutorialId = 1053,
		ImageId = 10002,
		IsCenter = 0,
		CompleteQuestId = "15054",
		DescriptionKeyboard = "按下{21}{90}{31}或{31}{90}{21}施展战技，需要消耗怒气 。\n攻击敌人，可以积攒怒气。\n在天赋菜单，可查看战技详情。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "按下{21}{90}{31}或{31}{90}{21}施展战技，需要消耗怒气 。\n攻击敌人，可以积攒怒气。\n在天赋菜单，可查看战技详情。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "按下{21}{90}{31}或{31}{90}{21}施展战技，需要消耗怒气 。\n攻击敌人，可以积攒怒气。\n在天赋菜单，可查看战技详情。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15054",
		Title = "使用战技",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1054,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "16015",
		DescriptionKeyboard = "诺伍德加入队伍，将一起旅行。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "诺伍德加入队伍，将一起旅行。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "诺伍德加入队伍，将一起旅行。",
		ShowQuestId = "29003",
		Forward = 0,
		HideQuestId = "16015",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1055,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "16016",
		DescriptionKeyboard = "贝妮塔加入队伍，将一起旅行。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "贝妮塔加入队伍，将一起旅行。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "贝妮塔加入队伍，将一起旅行。",
		ShowQuestId = "35054",
		Forward = 0,
		HideQuestId = "16016",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1056,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "16016",
		DescriptionKeyboard = "贝妮塔加入队伍，将一起旅行。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "贝妮塔加入队伍，将一起旅行。",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "贝妮塔加入队伍，将一起旅行。",
		ShowQuestId = "35054",
		Forward = 0,
		HideQuestId = "16016",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1057,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "16016",
		DescriptionKeyboard = "贝妮塔加入队伍，将一起旅行。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "贝妮塔加入队伍，将一起旅行。",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "贝妮塔加入队伍，将一起旅行。",
		ShowQuestId = "35054",
		Forward = 0,
		HideQuestId = "16016",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1058,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "16017",
		DescriptionKeyboard = "维奥拉、诺伍德、贝妮塔回到队伍。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "维奥拉、诺伍德、贝妮塔回到队伍。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "维奥拉、诺伍德、贝妮塔回到队伍。",
		ShowQuestId = "73719",
		Forward = 0,
		HideQuestId = "16017;95162",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1059,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "16025",
		DescriptionKeyboard = "维奥拉加入队伍，将一起旅行。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "维奥拉加入队伍，将一起旅行。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "维奥拉加入队伍，将一起旅行。",
		ShowQuestId = "25035",
		Forward = 0,
		HideQuestId = "16025",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1060,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "16025",
		DescriptionKeyboard = "维奥拉加入队伍，将一起旅行。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "维奥拉加入队伍，将一起旅行。",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "维奥拉加入队伍，将一起旅行。",
		ShowQuestId = "25035",
		Forward = 0,
		HideQuestId = "16025",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1061,
		ImageId = 10038,
		IsCenter = 0,
		CompleteQuestId = "15094",
		DescriptionKeyboard = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		ShowQuestId = "15093",
		Forward = 0,
		HideQuestId = "15094",
		Title = "负重者的怜悯",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 1062,
		ImageId = 10038,
		IsCenter = 0,
		CompleteQuestId = "15094",
		DescriptionKeyboard = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 1,
		DescriptionTouch = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		ShowQuestId = "15093",
		Forward = 0,
		HideQuestId = "15094",
		Title = "负重者的怜悯",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 1063,
		ImageId = 10038,
		IsCenter = 0,
		CompleteQuestId = "15094",
		DescriptionKeyboard = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		ShowQuestId = "15093",
		Forward = 0,
		HideQuestId = "15094",
		Title = "负重者的怜悯",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 1064,
		ImageId = 10038,
		IsCenter = 0,
		CompleteQuestId = "15094",
		DescriptionKeyboard = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 1,
		DescriptionTouch = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		ShowQuestId = "15093",
		Forward = 0,
		HideQuestId = "15094",
		Title = "负重者的怜悯",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 1065,
		ImageId = 10037,
		IsCenter = 0,
		CompleteQuestId = "75061",
		DescriptionKeyboard = "完成同伴的契约后，同伴会拿出秘藏的物品与你交换。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "完成同伴的契约后，同伴会拿出秘藏的物品与你交换。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "完成同伴的契约后，同伴会拿出秘藏的物品与你交换。",
		ShowQuestId = "75060",
		Forward = 0,
		HideQuestId = "75061",
		Title = "契约",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 1066,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16019",
		DescriptionKeyboard = "维奥拉的收藏更新了。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "维奥拉的收藏更新了。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "维奥拉的收藏更新了。",
		ShowQuestId = "75056",
		Forward = 0,
		HideQuestId = "16019",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1067,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16020",
		DescriptionKeyboard = "维奥拉的收藏更新了。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "维奥拉的收藏更新了。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "维奥拉的收藏更新了。",
		ShowQuestId = "75057",
		Forward = 0,
		HideQuestId = "16020",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1068,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16021",
		DescriptionKeyboard = "维奥拉的收藏更新了。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "维奥拉的收藏更新了。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "维奥拉的收藏更新了。",
		ShowQuestId = "75058",
		Forward = 0,
		HideQuestId = "16021",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1069,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16022",
		DescriptionKeyboard = "诺伍德的杂物更新了。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "诺伍德的杂物更新了。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "诺伍德的杂物更新了。",
		ShowQuestId = "75051",
		Forward = 0,
		HideQuestId = "16022",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1070,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16023",
		DescriptionKeyboard = "诺伍德的杂物更新了。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "诺伍德的杂物更新了。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "诺伍德的杂物更新了。",
		ShowQuestId = "75052",
		Forward = 0,
		HideQuestId = "16023",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1071,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "16024",
		DescriptionKeyboard = "诺伍德的杂物更新了。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "诺伍德的杂物更新了。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "诺伍德的杂物更新了。",
		ShowQuestId = "75053",
		Forward = 0,
		HideQuestId = "16024",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1072,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "4995018",
		DescriptionKeyboard = "已献出幻灵菇，黑雾中的污染者变强了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "已献出幻灵菇，黑雾中的污染者变强了",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "已献出幻灵菇，黑雾中的污染者变强了",
		ShowQuestId = "4995017",
		Forward = 0,
		HideQuestId = "4995018",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1073,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "4995018",
		DescriptionKeyboard = "已献出幻灵菇，黑雾中的污染者变强了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "已献出幻灵菇，黑雾中的污染者变强了",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "已献出幻灵菇，黑雾中的污染者变强了",
		ShowQuestId = "4995017",
		Forward = 0,
		HideQuestId = "4995018",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1074,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "4995018",
		DescriptionKeyboard = "已献出幻灵菇，黑雾中的污染者变强了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "已献出幻灵菇，黑雾中的污染者变强了",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 0,
		DescriptionTouch = "已献出幻灵菇，黑雾中的污染者变强了",
		ShowQuestId = "4995017",
		Forward = 0,
		HideQuestId = "4995018",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1075,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "4995018",
		DescriptionKeyboard = "已献出幻灵菇，黑雾中的污染者变强了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "已献出幻灵菇，黑雾中的污染者变强了",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "已献出幻灵菇，黑雾中的污染者变强了",
		ShowQuestId = "4995017",
		Forward = 0,
		HideQuestId = "4995018",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1076,
		ImageId = 10039,
		IsCenter = 0,
		CompleteQuestId = "4995019",
		DescriptionKeyboard = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		MazeOnly = 1,
		OpenRage = 0,
		DescriptionJoystick = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		ShowQuestId = "4992301",
		Forward = 0,
		HideQuestId = "4995019",
		Title = "深入黑霧",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1077,
		ImageId = 10039,
		IsCenter = 0,
		CompleteQuestId = "4995019",
		DescriptionKeyboard = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		MazeOnly = 1,
		OpenRage = 0,
		DescriptionJoystick = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		StoryId = 1,
		HeroId = 10002,
		IsPause = 1,
		DescriptionTouch = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		ShowQuestId = "4992301",
		Forward = 0,
		HideQuestId = "4995019",
		Title = "深入黑霧",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1078,
		ImageId = 10039,
		IsCenter = 0,
		CompleteQuestId = "4995019",
		DescriptionKeyboard = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		MazeOnly = 1,
		OpenRage = 0,
		DescriptionJoystick = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		StoryId = 1,
		HeroId = 10003,
		IsPause = 1,
		DescriptionTouch = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		ShowQuestId = "4992301",
		Forward = 0,
		HideQuestId = "4995019",
		Title = "深入黑霧",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1079,
		ImageId = 10039,
		IsCenter = 0,
		CompleteQuestId = "4995019",
		DescriptionKeyboard = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		MazeOnly = 1,
		OpenRage = 0,
		DescriptionJoystick = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		StoryId = 1,
		HeroId = 10004,
		IsPause = 1,
		DescriptionTouch = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		ShowQuestId = "4992301",
		Forward = 0,
		HideQuestId = "4995019",
		Title = "深入黑霧",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1080,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "95164",
		DescriptionKeyboard = "杰洛尔德加入队伍，将一起旅行。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "杰洛尔德加入队伍，将一起旅行。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "杰洛尔德加入队伍，将一起旅行。",
		ShowQuestId = "95163",
		Forward = 0,
		HideQuestId = "95164",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1081,
		ImageId = 10040,
		IsCenter = 0,
		CompleteQuestId = "95184",
		DescriptionKeyboard = "杰洛尔德是一名敏捷的剑士，他可以连续快速地做出最多4次回避动作。\n杰洛尔德在 {11} 「污秽淬炼」充能后，攻击敌人时可对敌人施加污秽标记，然后用「浸灵之剑」战技攻击敌人可造成额外伤害。污秽标记层数越多，额外伤害越高。\n在「天赋」菜单可查看杰洛尔德的更多战斗技巧。",
		MazeOnly = 0,
		OpenRage = 1,
		DescriptionJoystick = "杰洛尔德是一名敏捷的剑士，他可以连续快速地做出最多4次回避动作。\n杰洛尔德在 {11} 「污秽淬炼」充能后，攻击敌人时可对敌人施加污秽标记，然后用「浸灵之剑」战技攻击敌人可造成额外伤害。污秽标记层数越多，额外伤害越高。\n在「天赋」菜单可查看杰洛尔德的更多战斗技巧。",
		StoryId = 1,
		HeroId = 10005,
		IsPause = 1,
		DescriptionTouch = "杰洛尔德是一名敏捷的剑士，他可以连续快速地做出最多4次回避动作。\n杰洛尔德在 {11} 「污秽淬炼」充能后，攻击敌人时可对敌人施加污秽标记，然后用「浸灵之剑」战技攻击敌人可造成额外伤害。污秽标记层数越多，额外伤害越高。\n在「天赋」菜单可查看杰洛尔德的更多战斗技巧。",
		ShowQuestId = "17008",
		Forward = 0,
		HideQuestId = "95184",
		Title = "杰洛尔德",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1082,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "16017",
		DescriptionKeyboard = "维奥拉、诺伍德、贝妮塔、杰洛尔德回到队伍。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "维奥拉、诺伍德、贝妮塔、杰洛尔德回到队伍。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "维奥拉、诺伍德、贝妮塔、杰洛尔德回到队伍。",
		ShowQuestId = "73719;95162",
		Forward = 0,
		HideQuestId = "16017",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1083,
		ImageId = 10015,
		IsCenter = 0,
		CompleteQuestId = "15061",
		DescriptionKeyboard = "战斗中按{00}来躲避来自敌人的攻击",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "战斗中按{00}来躲避来自敌人的攻击",
		StoryId = 1,
		HeroId = 10005,
		IsPause = 1,
		DescriptionTouch = "战斗中按{00}来躲避来自敌人的攻击",
		ShowQuestId = "19014",
		Forward = 1031,
		HideQuestId = "15061",
		Title = "善用闪避",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1084,
		ImageId = 10004,
		IsCenter = 0,
		CompleteQuestId = "15077",
		DescriptionKeyboard = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		StoryId = 1,
		HeroId = 10005,
		IsPause = 1,
		DescriptionTouch = "面对敏捷的敌人，可以用格挡{11}先挡住攻击，然后寻找机会反击。",
		ShowQuestId = "15000",
		Forward = 1032,
		HideQuestId = "15077",
		Title = "善用格挡",
		Delay = 0,
		Backward = 1030
	},
	{
		TutorialId = 1085,
		ImageId = 10023,
		IsCenter = 0,
		CompleteQuestId = "15078",
		DescriptionKeyboard = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		StoryId = 1,
		HeroId = 10005,
		IsPause = 1,
		DescriptionTouch = "攻击、闪避都会消耗精力，精力耗尽时无法做出以上动作。战斗时须注意精力消耗。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15078",
		Title = "注意精力",
		Delay = 0,
		Backward = 1031
	},
	{
		TutorialId = 1086,
		ImageId = 10010,
		IsCenter = 0,
		CompleteQuestId = "15083",
		DescriptionKeyboard = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		StoryId = 1,
		HeroId = 10005,
		IsPause = 1,
		DescriptionTouch = "挑战首领级敌人时，若角色彻底失去理智，进入崩溃状态，他眼前的敌人会变得更强大。\n此时只有打败敌人才能结束崩溃状态，使用理智药水无效。",
		ShowQuestId = "13017",
		Forward = 0,
		HideQuestId = "15083",
		Title = "崩溃",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1087,
		ImageId = 10038,
		IsCenter = 0,
		CompleteQuestId = "15094",
		DescriptionKeyboard = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		StoryId = 1,
		HeroId = 10005,
		IsPause = 1,
		DescriptionTouch = "你吞下了负重者之卵，从此获得负重者的怜悯，对你而言，世界将不再残酷艰险，任何苦难都可以轻松克服。如果某一天，你无法继续承受负重者的怜悯，请你回到负重者神像面前。",
		ShowQuestId = "15093",
		Forward = 0,
		HideQuestId = "15094",
		Title = "负重者的怜悯",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 1088,
		ImageId = 0,
		IsCenter = 1,
		CompleteQuestId = "4995018",
		DescriptionKeyboard = "已献出幻灵菇，黑雾中的污染者变强了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "已献出幻灵菇，黑雾中的污染者变强了",
		StoryId = 1,
		HeroId = 10005,
		IsPause = 0,
		DescriptionTouch = "已献出幻灵菇，黑雾中的污染者变强了",
		ShowQuestId = "4995017",
		Forward = 0,
		HideQuestId = "4995018",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1089,
		ImageId = 10039,
		IsCenter = 0,
		CompleteQuestId = "4995019",
		DescriptionKeyboard = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		MazeOnly = 1,
		OpenRage = 0,
		DescriptionJoystick = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		StoryId = 1,
		HeroId = 10005,
		IsPause = 1,
		DescriptionTouch = "你已进入真正的黑雾世界。你的理智将持续受到侵蚀，只有不断战斗，加深执念，你才能保持理智。\n当你的执念达到临界，黑雾中的恐怖执念将向你发出邀请……据说战胜恐怖执念的人可以获得秘宝，但几乎无人能做到。\n黑雾死地，无处葬身，无路回头。先驱者，莫要迷失在这里啊！",
		ShowQuestId = "4992301",
		Forward = 0,
		HideQuestId = "4995019",
		Title = "深入黑霧",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1994,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "15089",
		DescriptionKeyboard = "维奥拉收藏了许多小玩意儿，如果你有赫吉赠送的支配者结晶，她会很愿意和你交换。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "维奥拉收藏了许多小玩意儿，如果你有赫吉赠送的支配者结晶，她会很愿意和你交换。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "维奥拉收藏了许多小玩意儿，如果你有赫吉赠送的支配者结晶，她会很愿意和你交换。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15089",
		Title = "维奥拉的收藏",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1995,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "15090",
		DescriptionKeyboard = "诺伍德拥有一些神秘的物品，但他并不十分看重它们，你可以用珊瑚虫骨和他交易。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "诺伍德拥有一些神秘的物品，但他并不十分看重它们，你可以用珊瑚虫骨和他交易。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "诺伍德拥有一些神秘的物品，但他并不十分看重它们，你可以用珊瑚虫骨和他交易。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15090",
		Title = "诺伍德的杂物",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1996,
		ImageId = 10036,
		IsCenter = 0,
		CompleteQuestId = "15086",
		DescriptionKeyboard = "贝妮塔凭借信仰，可以对各种药水施加祝福，提升药水的效果，还可能会发现药水的制作方法。但信仰并非一定带来实际回报，贝妮塔的祝福也有失效的时候。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "贝妮塔凭借信仰，可以对各种药水施加祝福，提升药水的效果，还可能会发现药水的制作方法。但信仰并非一定带来实际回报，贝妮塔的祝福也有失效的时候。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "贝妮塔凭借信仰，可以对各种药水施加祝福，提升药水的效果，还可能会发现药水的制作方法。但信仰并非一定带来实际回报，贝妮塔的祝福也有失效的时候。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15086",
		Title = "贝妮塔的祝福",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1997,
		ImageId = 10027,
		IsCenter = 0,
		CompleteQuestId = "15084",
		DescriptionKeyboard = "赫吉是索拉斯大陆上一种神秘的生物，没有人真正了解它。遇到过赫吉的人，有人失去了生命，有人丧失了理智，也有人博得赫吉的欢心，获得了意想不到的奖励。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "赫吉是索拉斯大陆上一种神秘的生物，没有人真正了解它。遇到过赫吉的人，有人失去了生命，有人丧失了理智，也有人博得赫吉的欢心，获得了意想不到的奖励。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "赫吉是索拉斯大陆上一种神秘的生物，没有人真正了解它。遇到过赫吉的人，有人失去了生命，有人丧失了理智，也有人博得赫吉的欢心，获得了意想不到的奖励。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15084",
		Title = "赫吉",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1998,
		ImageId = 10017,
		IsCenter = 0,
		CompleteQuestId = "15085",
		DescriptionKeyboard = "按{21}切换菜单，前往角色属性页面，提升角色属性。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "按{21}切换菜单，前往角色属性页面，提升角色属性。",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "点击右上角导航按钮，前往角色属性页面，提升角色属性。",
		ShowQuestId = "15000",
		Forward = 0,
		HideQuestId = "15085",
		Title = "祭坛升级",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 1999,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "",
		DescriptionKeyboard = "获得",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "获得",
		StoryId = 1,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "获得",
		ShowQuestId = "",
		Forward = 0,
		HideQuestId = "",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9001,
		ImageId = 10001,
		IsCenter = 0,
		CompleteQuestId = "",
		DescriptionKeyboard = "",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "",
		StoryId = 1001,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1测试1",
		ShowQuestId = "99999999",
		Forward = 9002,
		HideQuestId = "",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9002,
		ImageId = 10001,
		IsCenter = 0,
		CompleteQuestId = "",
		DescriptionKeyboard = "",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "",
		StoryId = 1001,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2测试2",
		ShowQuestId = "99999999",
		Forward = 0,
		HideQuestId = "",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9100,
		ImageId = 11001,
		IsCenter = 0,
		CompleteQuestId = "",
		DescriptionKeyboard = "",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "",
		StoryId = 1008,
		HeroId = 10001,
		IsPause = 1,
		DescriptionTouch = "测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测试3测",
		ShowQuestId = "99999999",
		Forward = 0,
		HideQuestId = "",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9101,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10019001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1001,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10012027",
		Forward = 0,
		HideQuestId = "10019001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9102,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10029001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1002,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10022043",
		Forward = 0,
		HideQuestId = "10029001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9103,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10039001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1003,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10033906",
		Forward = 0,
		HideQuestId = "10039001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9104,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10049001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1004,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10042070",
		Forward = 0,
		HideQuestId = "10049001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9105,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10059001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1005,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10052083",
		Forward = 0,
		HideQuestId = "10059001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9106,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10069001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1006,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10062074",
		Forward = 0,
		HideQuestId = "10069001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9107,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10079001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1007,
		HeroId = 10001,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10072085",
		Forward = 0,
		HideQuestId = "10079001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9108,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10019001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1001,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10012027",
		Forward = 0,
		HideQuestId = "10019001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9109,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10029001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1002,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10022043",
		Forward = 0,
		HideQuestId = "10029001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9110,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10039001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1003,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10033906",
		Forward = 0,
		HideQuestId = "10039001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9111,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10049001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1004,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10042070",
		Forward = 0,
		HideQuestId = "10049001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9112,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10059001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1005,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10052083",
		Forward = 0,
		HideQuestId = "10059001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9113,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10069001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1006,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10062074",
		Forward = 0,
		HideQuestId = "10069001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9114,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10079001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1007,
		HeroId = 10002,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10072085",
		Forward = 0,
		HideQuestId = "10079001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9115,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10019001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1001,
		HeroId = 10003,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10012027",
		Forward = 0,
		HideQuestId = "10019001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9116,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10029001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1002,
		HeroId = 10003,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10022043",
		Forward = 0,
		HideQuestId = "10029001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9117,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10039001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1003,
		HeroId = 10003,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10033906",
		Forward = 0,
		HideQuestId = "10039001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9118,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10049001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1004,
		HeroId = 10003,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10042070",
		Forward = 0,
		HideQuestId = "10049001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9119,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10059001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1005,
		HeroId = 10003,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10052083",
		Forward = 0,
		HideQuestId = "10059001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9120,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10069001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1006,
		HeroId = 10003,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10062074",
		Forward = 0,
		HideQuestId = "10069001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9121,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10079001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1007,
		HeroId = 10003,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10072085",
		Forward = 0,
		HideQuestId = "10079001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9122,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10019001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1001,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10012027",
		Forward = 0,
		HideQuestId = "10019001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9123,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10029001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1002,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10022043",
		Forward = 0,
		HideQuestId = "10029001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9124,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10039001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1003,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10033906",
		Forward = 0,
		HideQuestId = "10039001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9125,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10049001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1004,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10042070",
		Forward = 0,
		HideQuestId = "10049001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9126,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10059001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1005,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10052083",
		Forward = 0,
		HideQuestId = "10059001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9127,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10069001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1006,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10062074",
		Forward = 0,
		HideQuestId = "10069001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9128,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10079001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1007,
		HeroId = 10004,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10072085",
		Forward = 0,
		HideQuestId = "10079001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9129,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10019001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1001,
		HeroId = 10005,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10012027",
		Forward = 0,
		HideQuestId = "10019001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9130,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10029001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1002,
		HeroId = 10005,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10022043",
		Forward = 0,
		HideQuestId = "10029001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9131,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10039001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1003,
		HeroId = 10005,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10033906",
		Forward = 0,
		HideQuestId = "10039001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9132,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10049001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1004,
		HeroId = 10005,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10042070",
		Forward = 0,
		HideQuestId = "10049001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9133,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10059001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1005,
		HeroId = 10005,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10052083",
		Forward = 0,
		HideQuestId = "10059001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9134,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10069001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1006,
		HeroId = 10005,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10062074",
		Forward = 0,
		HideQuestId = "10069001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9135,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10079001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1007,
		HeroId = 10005,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10072085",
		Forward = 0,
		HideQuestId = "10079001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9136,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10019001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1001,
		HeroId = 10007,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10012027",
		Forward = 0,
		HideQuestId = "10019001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9137,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10029001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1002,
		HeroId = 10007,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10022043",
		Forward = 0,
		HideQuestId = "10029001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9138,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10039001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1003,
		HeroId = 10007,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10033906",
		Forward = 0,
		HideQuestId = "10039001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9139,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10049001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1004,
		HeroId = 10007,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10042070",
		Forward = 0,
		HideQuestId = "10049001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9140,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10059001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1005,
		HeroId = 10007,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10052083",
		Forward = 0,
		HideQuestId = "10059001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9141,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10069001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1006,
		HeroId = 10007,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10062074",
		Forward = 0,
		HideQuestId = "10069001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9142,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10079001",
		DescriptionKeyboard = "某处主角小队的封印被打开了",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "某处主角小队的封印被打开了",
		StoryId = 1007,
		HeroId = 10007,
		IsPause = 0,
		DescriptionTouch = "某处主角小队的封印被打开了",
		ShowQuestId = "10072085",
		Forward = 0,
		HideQuestId = "10079001",
		Title = "",
		Delay = 0,
		Backward = 0
	},
	{
		TutorialId = 9143,
		ImageId = 10054,
		IsCenter = 0,
		CompleteQuestId = "10092001",
		DescriptionKeyboard = "伊琳娜的武器「复仇之刃」可变换为单刃、双刃两种形态。\n长按{31}，可变换武器的形态。\n单刃形态时，按{11}可施展格挡。\n双刃形态时，长按{11}可施展强力攻击。\n更多战斗技巧，可在天赋页面查看。",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "伊琳娜的武器「复仇之刃」可变换为单刃、双刃两种形态。\n长按{31}，可变换武器的形态。\n单刃形态时，按{11}可施展格挡。\n双刃形态时，长按{11}可施展强力攻击。\n更多战斗技巧，可在天赋页面查看。",
		StoryId = 1001,
		HeroId = 10007,
		IsPause = 1,
		DescriptionTouch = "伊琳娜的武器「复仇之刃」可变换为单刃、双刃两种形态。\n长按{31}，可变换武器的形态。\n单刃形态时，按{11}可施展格挡。\n双刃形态时，长按{11}可施展强力攻击。\n更多战斗技巧，可在天赋页面查看。",
		ShowQuestId = "10091001",
		Forward = 0,
		HideQuestId = "10092001",
		Title = "伊琳娜",
		Delay = 1,
		Backward = 0
	},
	{
		TutorialId = 9144,
		ImageId = 0,
		IsCenter = 0,
		CompleteQuestId = "10016001;10093001",
		DescriptionKeyboard = "{31}轻攻击\n{21}重攻击\n长按{31}武器变形\n{00}回避",
		MazeOnly = 0,
		OpenRage = 0,
		DescriptionJoystick = "{31}轻攻击\n{21}重攻击\n长按{31}武器变形\n{00}回避",
		StoryId = 1001,
		HeroId = 10007,
		IsPause = 0,
		DescriptionTouch = "{31}轻攻击\n{21}重攻击\n长按{31}武器变形\n{00}回避",
		ShowQuestId = "10092001",
		Forward = 0,
		HideQuestId = "10016001;10093001",
		Title = "",
		Delay = 0,
		Backward = 0
	}
}
