-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_StatusType.lua

ES_StatusType = {
	{
		Param4 = 5,
		Time = 8,
		AttackType = 1,
		Param1 = 5,
		StatusType = 101,
		LogicType = 104,
		Effect = "vfx_status_10001",
		Name = "流血",
		IsRefresh = 1,
		Param5 = 0,
		EffectRoot = 1,
		Param2 = 125,
		IsDebuffer = 1,
		DefenceType = 1,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 1,
		Param3 = 1000
	},
	{
		Param4 = 10,
		Time = 20,
		AttackType = 3,
		Param1 = 5,
		StatusType = 102,
		LogicType = 104,
		Effect = "vfx_status_10002",
		Name = "中毒",
		IsRefresh = 1,
		Param5 = 0,
		EffectRoot = 1,
		Param2 = 500,
		IsDebuffer = 1,
		DefenceType = 3,
		StackSubDelay = 0.2,
		StackSubPer = 7,
		IsShow = 1,
		Param3 = 1000
	},
	{
		Param4 = 0,
		Time = 15,
		AttackType = 1,
		Param1 = 10,
		StatusType = 103,
		LogicType = 102,
		Effect = "vfx_status_10003",
		Name = "腐蚀",
		IsRefresh = 1,
		Param5 = 500,
		EffectRoot = 1,
		Param2 = 0,
		IsDebuffer = 1,
		DefenceType = 1,
		StackSubDelay = 0.2,
		StackSubPer = 7,
		IsShow = 1,
		Param3 = 0
	},
	{
		Param4 = 0,
		Time = 5,
		AttackType = 1,
		Param1 = 5,
		StatusType = 104,
		LogicType = 104,
		Effect = "",
		Name = "负伤(枪手)",
		IsRefresh = 1,
		Param5 = 200,
		EffectRoot = 1,
		Param2 = 0,
		IsDebuffer = 1,
		DefenceType = 1,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 1,
		Param3 = 0
	},
	{
		Param4 = 0,
		Time = 30,
		AttackType = 1,
		Param1 = 5,
		StatusType = 105,
		LogicType = 103,
		Effect = "",
		Name = "回血",
		IsRefresh = 1,
		Param5 = 20,
		EffectRoot = 1,
		Param2 = 0,
		IsDebuffer = 0,
		DefenceType = 1,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 1,
		Param3 = 0
	},
	{
		Param4 = 0,
		Time = 30,
		AttackType = 1,
		Param1 = 10,
		StatusType = 106,
		LogicType = 101,
		Effect = "",
		Name = "石肤",
		IsRefresh = 1,
		Param5 = 5000,
		EffectRoot = 1,
		Param2 = 0,
		IsDebuffer = 0,
		DefenceType = 1,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 1,
		Param3 = 0
	},
	{
		Param4 = 200,
		Time = 30,
		AttackType = 1,
		Param1 = 23,
		StatusType = 107,
		LogicType = 101,
		Effect = "",
		Name = "火抗",
		IsRefresh = 1,
		Param5 = 0,
		EffectRoot = 1,
		Param2 = 0,
		IsDebuffer = 0,
		DefenceType = 1,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 1,
		Param3 = 0
	},
	{
		Param4 = 5,
		Time = 8,
		AttackType = 1,
		Param1 = 5,
		StatusType = 108,
		LogicType = 104,
		Effect = "vfx_status_10004",
		Name = "燃烧",
		IsRefresh = 1,
		Param5 = 0,
		EffectRoot = 1,
		Param2 = 125,
		IsDebuffer = 1,
		DefenceType = 1,
		StackSubDelay = 0.2,
		StackSubPer = 7,
		IsShow = 1,
		Param3 = 1000
	},
	{
		Param4 = 4,
		Time = 15,
		AttackType = 1,
		Param1 = 8,
		StatusType = 109,
		LogicType = 103,
		Effect = "",
		Name = "回SAN",
		IsRefresh = 1,
		Param5 = 0,
		EffectRoot = 1,
		Param2 = 0,
		IsDebuffer = 0,
		DefenceType = 1,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 1,
		Param3 = 0
	},
	{
		Param4 = 10,
		Time = 15,
		AttackType = 1,
		Param1 = 5,
		StatusType = 901,
		LogicType = 104,
		Effect = "",
		Name = "无表现通用DOT",
		IsRefresh = 1,
		Param5 = 0,
		EffectRoot = 0,
		Param2 = 500,
		IsDebuffer = 1,
		DefenceType = 1,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 0,
		Param3 = 1000
	},
	{
		Param4 = 0,
		Time = 5,
		AttackType = 1,
		Param1 = 0,
		StatusType = 902,
		LogicType = 105,
		Effect = "",
		Name = "无表现通用晕眩",
		IsRefresh = 1,
		Param5 = 0,
		EffectRoot = 0,
		Param2 = 0,
		IsDebuffer = 1,
		DefenceType = 1,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 0,
		Param3 = 0
	},
	{
		Param4 = 0,
		Time = -1,
		AttackType = 0,
		Param1 = 0,
		StatusType = 903,
		LogicType = 106,
		Effect = "",
		Name = "无逻辑通用表现",
		IsRefresh = 1,
		Param5 = 0,
		EffectRoot = 0,
		Param2 = 0,
		IsDebuffer = 1,
		DefenceType = 0,
		StackSubDelay = 0,
		StackSubPer = 0,
		IsShow = 1,
		Param3 = 0
	}
}
