-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_StoryMazeStatue.lua

ES_StoryMazeStatue = {
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10091,
		Title = "",
		GetRate = 0,
		StatueId = 1,
		Description = "获得净秽圣徒的加护，一段时间内攻击力提升",
		GetProperty = 0,
		Index = 1
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10092,
		Title = "",
		GetRate = 0,
		StatueId = 1,
		Description = "获得净秽圣徒的加护，一段时间内防御力提升",
		GetProperty = 0,
		Index = 2
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10093,
		Title = "",
		GetRate = 0,
		StatueId = 1,
		Description = "获得净秽圣徒的加护，一段时间内精力恢复速度提升",
		GetProperty = 0,
		Index = 3
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10094,
		Title = "",
		GetRate = 0,
		StatueId = 1,
		Description = "获得净秽圣徒的加护，一段时间内敌人掉落幻灵菇的数量增加",
		GetProperty = 0,
		Index = 4
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10095,
		Title = "",
		GetRate = 0,
		StatueId = 1,
		Description = "获得净秽圣徒的加护，一段时间内攻击敌人可恢复生命",
		GetProperty = 0,
		Index = 5
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10096,
		Title = "",
		GetRate = 0,
		StatueId = 1,
		Description = "获得净秽圣徒的加护，一段时间内理智被侵蚀的速度下降50%",
		GetProperty = 0,
		Index = 6
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10091,
		Title = "",
		GetRate = 0,
		StatueId = 2,
		Description = "获得净秽圣徒的加护，一段时间内攻击力提升",
		GetProperty = 0,
		Index = 1
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10092,
		Title = "",
		GetRate = 0,
		StatueId = 2,
		Description = "获得净秽圣徒的加护，一段时间内防御力提升",
		GetProperty = 0,
		Index = 2
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10093,
		Title = "",
		GetRate = 0,
		StatueId = 2,
		Description = "获得净秽圣徒的加护，一段时间内精力恢复速度提升",
		GetProperty = 0,
		Index = 3
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10094,
		Title = "",
		GetRate = 0,
		StatueId = 2,
		Description = "获得净秽圣徒的加护，一段时间内敌人掉落幻灵菇的数量增加",
		GetProperty = 0,
		Index = 4
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10095,
		Title = "",
		GetRate = 0,
		StatueId = 2,
		Description = "获得净秽圣徒的加护，一段时间内攻击敌人可恢复生命",
		GetProperty = 0,
		Index = 5
	},
	{
		UseItemId = 0,
		UseProperty = 0,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 10096,
		Title = "",
		GetRate = 0,
		StatueId = 2,
		Description = "获得净秽圣徒的加护，一段时间内理智被侵蚀的速度下降50%",
		GetProperty = 0,
		Index = 6
	},
	{
		UseItemId = 20001,
		UseProperty = 0,
		UseItemNum = 1,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 0,
		Title = "",
		GetRate = 0.3,
		StatueId = 3,
		Description = "献出1瓶生命药水，可获得食秽圣徒的遗惠，恢复30%理智",
		GetProperty = 8,
		Index = 1
	},
	{
		UseItemId = 0,
		UseProperty = 8,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 10,
		GetNum = 0,
		GetStatusId = 0,
		Title = "",
		GetRate = 0.7,
		StatueId = 3,
		Description = "献出10点理智，可获得食秽圣徒的遗惠，恢复70%生命",
		GetProperty = 5,
		Index = 2
	},
	{
		UseItemId = 0,
		UseProperty = 5,
		UseItemNum = 0,
		GetItemId = 40031,
		UseValue = 250,
		GetNum = 20,
		GetStatusId = 0,
		Title = "",
		GetRate = 0,
		StatueId = 3,
		Description = "献出250点生命，可获得食秽圣徒的遗惠，得到20颗幻灵菇",
		GetProperty = 0,
		Index = 3
	},
	{
		UseItemId = 40031,
		UseProperty = 0,
		UseItemNum = 5,
		GetItemId = 20001,
		UseValue = 0,
		GetNum = 1,
		GetStatusId = 0,
		Title = "",
		GetRate = 0,
		StatueId = 3,
		Description = "献出5颗幻灵菇 ，可获得食秽圣徒的遗惠，得到1瓶生命药水",
		GetProperty = 0,
		Index = 4
	},
	{
		UseItemId = 0,
		UseProperty = 5,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 250,
		GetNum = 0,
		GetStatusId = 0,
		Title = "",
		GetRate = 0.3,
		StatueId = 3,
		Description = "献出250点生命，可获得食秽圣徒的遗惠，恢复30%理智",
		GetProperty = 8,
		Index = 5
	},
	{
		UseItemId = 0,
		UseProperty = 8,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 20,
		GetNum = 0,
		GetStatusId = 10090,
		Title = "",
		GetRate = 0,
		StatueId = 3,
		Description = "献出20点理智，可获得食秽圣徒的遗惠，得到一次受到致命伤害后可幸存的效果。这种效果可多次叠加。",
		GetProperty = 0,
		Index = 6
	},
	{
		UseItemId = 20001,
		UseProperty = 0,
		UseItemNum = 1,
		GetItemId = 0,
		UseValue = 0,
		GetNum = 0,
		GetStatusId = 0,
		Title = "",
		GetRate = 0.3,
		StatueId = 4,
		Description = "献出1瓶生命药水，可获得食秽圣徒的遗惠，恢复30%理智",
		GetProperty = 8,
		Index = 1
	},
	{
		UseItemId = 0,
		UseProperty = 8,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 10,
		GetNum = 0,
		GetStatusId = 0,
		Title = "",
		GetRate = 0.7,
		StatueId = 4,
		Description = "献出10点理智，可获得食秽圣徒的遗惠，恢复70%生命",
		GetProperty = 5,
		Index = 2
	},
	{
		UseItemId = 0,
		UseProperty = 5,
		UseItemNum = 0,
		GetItemId = 40031,
		UseValue = 250,
		GetNum = 20,
		GetStatusId = 0,
		Title = "",
		GetRate = 0,
		StatueId = 4,
		Description = "献出250点生命，可获得食秽圣徒的遗惠，得到20颗幻灵菇",
		GetProperty = 0,
		Index = 3
	},
	{
		UseItemId = 40031,
		UseProperty = 0,
		UseItemNum = 5,
		GetItemId = 20001,
		UseValue = 0,
		GetNum = 1,
		GetStatusId = 0,
		Title = "",
		GetRate = 0,
		StatueId = 4,
		Description = "献出5颗幻灵菇 ，可获得食秽圣徒的遗惠，得到1瓶生命药水",
		GetProperty = 0,
		Index = 4
	},
	{
		UseItemId = 0,
		UseProperty = 5,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 250,
		GetNum = 0,
		GetStatusId = 0,
		Title = "",
		GetRate = 0.3,
		StatueId = 4,
		Description = "献出250点生命，可获得食秽圣徒的遗惠，恢复30%理智",
		GetProperty = 8,
		Index = 5
	},
	{
		UseItemId = 0,
		UseProperty = 8,
		UseItemNum = 0,
		GetItemId = 0,
		UseValue = 20,
		GetNum = 0,
		GetStatusId = 10090,
		Title = "",
		GetRate = 0,
		StatueId = 4,
		Description = "献出20点理智，可获得食秽圣徒的遗惠，得到一次受到致命伤害后可幸存的效果。这种效果可多次叠加。",
		GetProperty = 0,
		Index = 6
	}
}
