-- chunkname: @f:/unity/pascalswager_steam1/assets/GameData/StructData/ExportData/ES_UIQuest.lua

ES_UIQuest = {
	{
		Description = "",
		ShowQuestId = "13014",
		DLCQuest = 0,
		CompleteQuestId = "23701",
		QuestId = 10101,
		Name = "海格姆",
		QuestSort = 1,
		QuestType = 1,
		NextQuestId = ""
	},
	{
		Description = "众所周知，先驱者的职责是在黑雾中寻找巨像墓地——一处只存于传说的地方，那里是巨像最终的归宿，也是困于黑雾之中人类最后的希望。然而泰伦斯成为先驱者的目的似乎和黑雾中的污秽一样不可捉摸。作为先驱者，泰伦斯早已习惯与「污染者」作战，但数月之前，在黑雾中他救出另一名先驱者维奥拉，在那场战斗中，他第一次意识到，虽然技巧早已印刻在肌肉的记忆中，但身手体力却都不复往日。\n不久之前，两人获悉海格姆巨像突然开始迁徙，或许这是某种征兆。然而来到海格姆之后，令他们意想不到的是，部落的外围居然出现了遭到污秽感染的「污染者」。海格姆究竟遭遇了什么？泰伦斯加快脚步，开始了调查。",
		ShowQuestId = "13014",
		DLCQuest = 0,
		CompleteQuestId = "13003",
		QuestId = 10102,
		Name = "击败污染者",
		QuestSort = 10,
		QuestType = 2,
		NextQuestId = "10103"
	},
	{
		Description = "唯一可以预见的是，海格姆巨像的光芒已经无法抵御污秽的侵袭，很快这个原本宁静的村庄就将被吞噬殆尽，陷入永远的黑暗。索拉斯大陆上的遗民虽然早已习惯了居无定所，但由于巨像衰弱而导致的迁徙却是十分罕见。在线索尚不明朗的情况下，泰伦斯决定先追上维奥拉，再做下一步打算。当然前提是，他能迅速地解决掉眼前这些变异的「污染者」。",
		ShowQuestId = "13003",
		DLCQuest = 0,
		CompleteQuestId = "15043",
		QuestId = 10103,
		Name = "与维奥拉汇合",
		QuestSort = 11,
		QuestType = 2,
		NextQuestId = "10104"
	},
	{
		Description = "根据维奥拉的描述，污秽已经彻底入侵，举目望去只有四处徘徊的「污染者」。她唯一的收获是一本特殊的手札，上面记录着用赐福之地的文字所撰写的「女巫」炼金配方，泰伦斯似乎隐约猜到了手札的主人，但面对维奥拉的追问，泰伦斯再次选择了回避。命运的齿轮在海格姆开始转动了起来，现在唯有找到幸存的遗民，才能获悉更多的信息。前往距离巨像光源最近的山顶，似乎是一个最好的选择。",
		ShowQuestId = "15043",
		DLCQuest = 0,
		CompleteQuestId = "15067",
		QuestId = 10104,
		Name = "前往山顶",
		QuestSort = 12,
		QuestType = 2,
		NextQuestId = "10105"
	},
	{
		Description = "令人失望的是海格姆的山顶，只剩下一名被污秽彻底腐化的苦修者，他不断地鞭挞着自己，用痛苦维持着仅存的意志。他咆哮着誓要守护海格姆，但可悲的是这一切已经毫无意义。面对被污秽扭曲的怪物，泰伦斯惟有举起手中的利剑。",
		ShowQuestId = "15067",
		DLCQuest = 0,
		CompleteQuestId = "25072",
		QuestId = 10105,
		Name = "击败苦修者",
		QuestSort = 13,
		QuestType = 2,
		NextQuestId = "10106"
	},
	{
		Description = "利刃终结了苦修者的生命，然而却难以根除寄生的污秽，好在戴面具的神秘人再次现身，化险为夷。然而泰伦斯却因为某种原因突然晕厥，挥之不去的噩梦再次浮现。醒来后，他已经身处马车之中，面具人早已不知去向，海格姆发生的事情，最终仍是毫无头绪。只有在苦修者留下的笔记中提到了一名红发巫女，似乎是在她离开之后，海格姆便发生了灾变。泰伦斯怀疑那名红发巫女便是自己失散多年的妻子——特蕾莎，笔记中提到，红发女巫正在找寻阿达米亚巨像。",
		ShowQuestId = "25072",
		DLCQuest = 0,
		CompleteQuestId = "23701",
		QuestId = 10106,
		Name = "前往阿达米亚",
		QuestSort = 14,
		QuestType = 2,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "15006",
		DLCQuest = 0,
		CompleteQuestId = "15007",
		QuestId = 20101,
		Name = "寻子的妇人",
		QuestSort = 101,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "泰伦斯在海格姆部落外遇到一位幸存的妇人，她偷拿了矿洞中驱散污秽的宝贝，冒险出来寻找自己失踪的孩子，杰瑞。\n杰瑞是个贪玩的孩子，溜出矿洞去找约翰三兄弟玩，至今未归。虽然海格姆已经到处是「污染者」，但寒风中担心的母亲依然没有放弃希望。",
		ShowQuestId = "15006",
		DLCQuest = 0,
		CompleteQuestId = "12018",
		QuestId = 20102,
		Name = "寻找杰瑞",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20103"
	},
	{
		Description = "在矿洞外偏僻角落，泰伦斯找到了一件少年穿的外套。或许悲剧已经发生，黑雾笼罩的世界中，悲剧每时每刻都在发生，泰伦斯见过太多这样的事情。普通的遗民已经受尽苦难，是否该将悲剧真相告知他们……每一次抉择，泰伦斯只能从自己内心寻找答案。",
		ShowQuestId = "12018;15006",
		DLCQuest = 0,
		CompleteQuestId = "15007",
		QuestId = 20103,
		Name = "归还外套",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "15023",
		DLCQuest = 0,
		CompleteQuestId = "15009",
		QuestId = 20201,
		Name = "海格姆之泪",
		QuestSort = 102,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "泰伦斯在海格姆发现一颗会说话的蛋。似乎有一名海格姆遗民被封在了巨蛋中……他说自己见过一名红发女巫，并和雷蒙斯大人一起接待了女巫。\n为了获得更多关于女巫的消息，泰伦斯决定救出被困的人，为此需要海格姆的稀有矿石：泪石。据说矿洞的雕像边便存放着一枚。",
		ShowQuestId = "15023",
		DLCQuest = 0,
		CompleteQuestId = "12002",
		QuestId = 20202,
		Name = "寻找泪石",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20203"
	},
	{
		Description = "在击败了矿洞中强大的「污染者」后，泰伦斯终于在雕像边拿到了泪石。此刻，他无比期望那个被封在巨蛋中的遗民，会给他带来哪怕一点点有关红发女巫的消息，对他来说这至关重要。",
		ShowQuestId = "12002;15023",
		DLCQuest = 0,
		CompleteQuestId = "15009",
		QuestId = 20203,
		Name = "解救巨蛋中的家伙",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "23701",
		DLCQuest = 0,
		CompleteQuestId = "35003",
		QuestId = 10201,
		Name = "阿达米亚",
		QuestSort = 2,
		QuestType = 1,
		NextQuestId = ""
	},
	{
		Description = "格伦驾驶着马车在黑雾中疾驰，然而临近阿米达亚，泰伦斯一行遇见了一位正被污染者围困的女孩。虽然先驱者没有义务帮助任何人，但见死不救并不在泰伦斯的字典里。",
		ShowQuestId = "23701",
		DLCQuest = 0,
		CompleteQuestId = "25036",
		QuestId = 10202,
		Name = "救出女孩",
		QuestSort = 20,
		QuestType = 2,
		NextQuestId = "10203"
	},
	{
		Description = "可怜的女孩，母亲被怪物抓走，父亲则贪生怕死离她而去。为了避免一场悲剧的发生，泰伦斯和维奥拉即刻向山坡上的地牢进发。",
		ShowQuestId = "25036",
		DLCQuest = 0,
		CompleteQuestId = "25037",
		QuestId = 10203,
		Name = "解救母亲",
		QuestSort = 21,
		QuestType = 2,
		NextQuestId = "10204"
	},
	{
		Description = "神秘的面具人自称诺伍德，凑巧的是他也在追寻巨像衰落以及红发女巫的线索。他告诉泰伦斯，阿达米亚的「圣父」是个丧心病狂的家伙，为了让血脉得以延续，他将污秽注入遗民的体内。而被抓走的维奥拉，极有可能遭受同样的下场。现在唯一的办法，就是前往神谕之地找到圣父，阻止这一切的发生。令人奇怪的是，诺伍德似乎对阿达米亚的情况十分了解，为了解救维奥拉，半信半疑的泰伦斯决定暂时与诺伍德一起去寻找圣父。",
		ShowQuestId = "25037",
		DLCQuest = 0,
		CompleteQuestId = "25015",
		QuestId = 10204,
		Name = "寻找圣父",
		QuestSort = 22,
		QuestType = 2,
		NextQuestId = "10205"
	},
	{
		Description = "女孩的母亲的确被抓走了，但并不是被怪物而是圣父。为了再一次见到自己的母亲，她只能被迫作为诱饵完成所谓的「狩戒」。出乎意料的是，掳走维奥拉的可怕女人，正是女孩口中保护了她，并且把她关在这里的艾尔玛。女孩愿意告诉泰伦斯圣父在哪里，但前提是先帮她离开地牢，让她可以去寻找自己的母亲。而地牢上方出口的钥匙就在艾尔玛手中。不过，艾尔玛最近变得难以控制情绪，很可能做出可怕的事情。\n",
		ShowQuestId = "25015",
		DLCQuest = 0,
		CompleteQuestId = "22018",
		QuestId = 10205,
		Name = "找到艾尔玛",
		QuestSort = 23,
		QuestType = 2,
		NextQuestId = "10206"
	},
	{
		Description = "没有什么难以控制的情绪，只有无法抑制的污秽。「善良」的艾尔玛最终也难逃污秽的侵蚀，彻底失去理智。在击败了艾尔玛后，泰伦斯从她的身上发现了女孩所说的地牢钥匙。时间紧迫，维奥拉依然身处危险，所幸泰伦斯在战斗现场附近找到一条捷径，可以快速去往山顶的地牢出口。",
		ShowQuestId = "22018",
		DLCQuest = 0,
		CompleteQuestId = "22201",
		QuestId = 10206,
		Name = "打开地牢出口",
		QuestSort = 24,
		QuestType = 2,
		NextQuestId = "10207"
	},
	{
		Description = "泰伦斯打开地牢后，女孩按照约定，把「神谕水晶」交给了泰伦斯。有了它，就可以进入神谕之地，找到圣父。泰伦斯立即赶往神谕之地，希望维奥拉还没有遭遇不测。",
		ShowQuestId = "22201",
		DLCQuest = 0,
		CompleteQuestId = "23020",
		QuestId = 10207,
		Name = "前往神谕之地",
		QuestSort = 25,
		QuestType = 2,
		NextQuestId = "10208"
	},
	{
		Description = "万幸，维奥拉还没有成为圣父的新娘。\n让泰伦斯惊讶的是，特蕾莎真的出现在了阿达米亚，并且夺走了某样圣父极其珍视的宝物。有太多问题找不到答案，然而泰伦斯也没有办法去追问，因为眼前他还有必须要做的事——打败圣父，解救维奥拉。",
		ShowQuestId = "23020",
		DLCQuest = 0,
		CompleteQuestId = "25070",
		QuestId = 10208,
		Name = "打败圣父",
		QuestSort = 26,
		QuestType = 2,
		NextQuestId = "10209"
	},
	{
		Description = "怀着极度的愤怒，泰伦斯结束了圣父堕落的生命，被诅咒的阿达米亚血脉或许就此彻底终结，但这又何尝不是一种救赎呢？但是在索拉斯，命运总是弄人，随着圣父的逝去，阿达米亚的光芒也开始渐渐衰弱，可怜的遗民们即将面临的是更为残酷的绝境。然而，没人能改变什么，所以继续留在阿达米亚已经没有意义，泰伦斯一行三人返回马车，准备去往下一个目的地。",
		ShowQuestId = "25070",
		DLCQuest = 0,
		CompleteQuestId = "25071",
		QuestId = 10209,
		Name = "回到马车",
		QuestSort = 27,
		QuestType = 2,
		NextQuestId = "10210"
	},
	{
		Description = "诺伍德是个难缠的家伙，维奥拉也对他抱有极强的敌意。虽然泰伦斯强烈的感觉到，在诺伍德的面具背后不光只有秘密。但为了找到特蕾莎，他愿意冒险前往伊瑟流姆去见一位老朋友。",
		ShowQuestId = "25071",
		DLCQuest = 0,
		CompleteQuestId = "35003",
		QuestId = 10210,
		Name = "前往伊瑟流姆",
		QuestSort = 28,
		QuestType = 2,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "25022",
		DLCQuest = 0,
		CompleteQuestId = "25074",
		QuestId = 20301,
		Name = "母女",
		QuestSort = 103,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "在阿达米亚的山顶，泰伦斯遇见了五名待产的母亲，诡异的情景让人作呕，这就是圣父所谓的血脉延续之道，阿达米亚的新生之地，却充斥着死亡的气息。\n而在她们之中，一名母亲似乎还保留着一些意识，她非常担心自己的女儿。因为在此待产，她已经离开女儿很久了，听闻泰伦斯见过她的女儿之后，母亲将女儿最心爱的布偶转交给了泰伦斯。希望他能转告自己的女儿，重聚之日即将来到。",
		ShowQuestId = "25022",
		DLCQuest = 0,
		CompleteQuestId = "25028",
		QuestId = 20302,
		Name = "布偶",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20303"
	},
	{
		Description = "思母心切的女孩，在见到母亲赠与的布偶后，焦急地离开了地牢，前往新生之所。考虑到阿达米亚的现状，也许只有泰伦斯才能促成母女平安的团圆。",
		ShowQuestId = "25022;25028",
		DLCQuest = 0,
		CompleteQuestId = "25074",
		QuestId = 20303,
		Name = "团圆",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "25049",
		DLCQuest = 0,
		CompleteQuestId = "25053",
		QuestId = 20601,
		Name = "新生的痛苦",
		QuestSort = 104,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "阿达米亚的产妇们为了延续血脉承受了难以想象的痛苦，一位老妇人日夜为她们熬制草药，用于缓解她们的痛苦。但老妇人手边的药材越来越少，药炉又必须一刻不停地搅拌，才能保证药品的效力。现在，只要再给她五棵阿达米亚药草，痛苦的母亲们就能再撑一段时间。",
		ShowQuestId = "25049",
		DLCQuest = 0,
		CompleteQuestId = "25052",
		QuestId = 20602,
		Name = "阿达米亚草",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20603"
	},
	{
		Description = "老妇人的药剂，除了阿达米亚草，还需要一份活性污染体。既然答应了老妇人的第一次请求，半途而废，可能不是最好的选择。",
		ShowQuestId = "25052",
		DLCQuest = 0,
		CompleteQuestId = "25053",
		QuestId = 20603,
		Name = "活性污染体",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "35003",
		DLCQuest = 0,
		CompleteQuestId = "55035",
		QuestId = 10301,
		Name = "伊瑟流姆",
		QuestSort = 3,
		QuestType = 1,
		NextQuestId = ""
	},
	{
		Description = "伊瑟流姆，先驱者的流放之地，教会所属的荒蛮边陲，大量「污染者」盘踞于此，据传一颗神秘红星击中了巨像，致其陨落。自此之后，伊瑟流姆彻底沦为死亡之地。\n现在这里唯一能供人停留的地方，只有海边受过祝福的圣所，而贝妮塔也许就在那里。",
		ShowQuestId = "35003",
		DLCQuest = 0,
		CompleteQuestId = "35019",
		QuestId = 10302,
		Name = "前往圣所",
		QuestSort = 30,
		QuestType = 2,
		NextQuestId = "10303"
	},
	{
		Description = "长久以来，贝妮塔一直陷在深深的自责之中，她仍然不敢相信特蕾莎还活着。更为讽刺的是，击垮巨像的红星却维持住了伊瑟流姆最后的光芒。而它与特蕾莎在阿达米亚取走的圣物有着相似的气息，两者之间究竟有着怎样的联系？唯有找到巨像头部遗留下的红星碎片，才能解开所有人的心结。",
		ShowQuestId = "35019",
		DLCQuest = 0,
		CompleteQuestId = "32041",
		QuestId = 10303,
		Name = "去山顶寻找红星碎片",
		QuestSort = 31,
		QuestType = 2,
		NextQuestId = "10304"
	},
	{
		Description = "身披婚纱的女人幻化作晶莹，消散在空中。一瞬间，泰伦斯心中突然泛起难忍的忧伤，然而他知道自己必须遏制住这种情绪的蔓延。自从决定成为先驱者之后，他就早已做好最坏的打算。虽然面前的这条线索犹如丝线一般的，他也只能尽力抓住，深怕转瞬即逝。泰伦斯收拾心情，准备返回圣所，请贝妮塔重组红星碎片。如果贝妮塔无法顺利重组碎片，或许泰伦斯就将放弃一切，包括自己的生命。",
		ShowQuestId = "32041",
		DLCQuest = 0,
		CompleteQuestId = "35050",
		QuestId = 10304,
		Name = "重回圣所",
		QuestSort = 32,
		QuestType = 2,
		NextQuestId = "10305"
	},
	{
		Description = "贝妮塔成功重组了红星碎片，竟与教会一直珍藏的圣物「耶库伯之印」别无二致。传说中，「耶库伯之印」是打开巨像墓地的钥匙。但为什么特蕾莎想要打开巨像墓地？原本希冀的答案，却牵扯出更为巨大的谜团。贝妮塔提议一同前往基塔布，因为曾有传闻，那里发现过巨像墓地的入口。虽然这样的传闻，在索拉斯时有发生，并不足信，但泰伦斯明白贝妮塔另有所指。",
		ShowQuestId = "35050",
		DLCQuest = 0,
		CompleteQuestId = "55035",
		QuestId = 10305,
		Name = "前往基塔布",
		QuestSort = 33,
		QuestType = 2,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "35010",
		DLCQuest = 0,
		CompleteQuestId = "31004",
		QuestId = 20401,
		Name = "无头骑士",
		QuestSort = 105,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "伊瑟流姆的残垣断壁上，失去了头颅的骑士，等待着未婚妻的归来，爱是甜蜜的，同时也是残酷的。然而誓言从未改变，等到重逢之时，骑士依然希望为新娘戴上早已准备的婚戒。然而命运弄人，何时他才能寻回新婚之夜遗失的婚戒。",
		ShowQuestId = "35010",
		DLCQuest = 0,
		CompleteQuestId = "35006",
		QuestId = 20402,
		Name = "寻找婚戒",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20403"
	},
	{
		Description = "泰伦斯从一名来自赐福之地的忏悔者手中获得了帕特里克的戒指。在把戒指交还给主人之后，无头骑士的诅咒即将迎来终结，然而他的爱人仍未归来……",
		ShowQuestId = "35010;35006",
		DLCQuest = 0,
		CompleteQuestId = "32042",
		QuestId = 20403,
		Name = "交还婚戒",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20404"
	},
	{
		Description = "珍妮至死抱着爱人的头颅，即便成了污秽的傀儡，她也没有忘记对爱人的承诺。\n泰伦斯找到了帕特里克失去已久的头颅，但同时也要击碎一颗跳动的心脏。",
		ShowQuestId = "35010;35006;32042",
		DLCQuest = 0,
		CompleteQuestId = "31004",
		QuestId = 20404,
		Name = "终结诅咒",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "55035",
		DLCQuest = 0,
		CompleteQuestId = "45001",
		QuestId = 10501,
		Name = "基塔布",
		QuestSort = 4,
		QuestType = 1,
		NextQuestId = ""
	},
	{
		Description = "神秘莫测的马吉安文明一夜之间灰飞烟灭，而基塔布盎然的生机早已掩埋了过去的一切，只有空气中淡淡的血腥依旧无法散去。为了查明特蕾莎的真正意图，泰伦斯进入了这片回忆之地。",
		ShowQuestId = "55035",
		DLCQuest = 0,
		CompleteQuestId = "55023",
		QuestId = 10502,
		Name = "调查基塔布森林",
		QuestSort = 40,
		QuestType = 2,
		NextQuestId = "10503"
	},
	{
		Description = "基塔布森林中到处是奇特的生物，包括一株会说话并且自称是教会祭司的植物。他似乎对基塔布的过去十分了解。\n他告诉泰伦斯，眼前的剧毒黑雾其实是马吉安人布下的小把戏。马吉安人相信生命永远迁流变化，只有经历过去、现在和未来，才能找到真理所在。想要通过黑雾，泰伦斯必须从马吉安人的信仰中找到答案。",
		ShowQuestId = "55023",
		DLCQuest = 0,
		CompleteQuestId = "55021",
		QuestId = 10503,
		Name = "寻找过去、现在和未来",
		QuestSort = 41,
		QuestType = 2,
		NextQuestId = "10504"
	},
	{
		Description = "泰伦斯一行在马吉安人的废墟中找到了三颗奇怪的石头：过去之石、现在之石和未来之石，上面刻着神秘预言。或许这就是马吉安人信奉的「过去、现在和未来」，但泰伦斯不知道如何用这三颗石头通过黑雾，他只能回去再次询问那株奇怪的植物。",
		ShowQuestId = "55023;55021",
		DLCQuest = 0,
		CompleteQuestId = "55024",
		QuestId = 10504,
		Name = "询问向日葵",
		QuestSort = 42,
		QuestType = 2,
		NextQuestId = "10505"
	},
	{
		Description = "经过奇怪的仪式，三颗时间之石聚合到一起，组成了马吉安机关球。凭借它，泰伦斯终于能穿过这道剧毒的黑雾。",
		ShowQuestId = "55024",
		DLCQuest = 0,
		CompleteQuestId = "55011",
		QuestId = 10505,
		Name = "深入基塔布",
		QuestSort = 43,
		QuestType = 2,
		NextQuestId = "10506"
	},
	{
		Description = "黑雾后的巫女小屋中，泰伦斯瞥见了特蕾莎残留的幻影，他依稀听见特蕾莎呢喃着基塔布中心圣塔的顶部。\n屋内的角落，泰伦斯找到了特蕾莎留下的羊皮卷，上面记录着她痛苦、仇恨还有疑惑……泰伦斯此时的内心也随着文字起伏。如果有什么事能够挽回特蕾莎、偿还她所遭受的痛苦，泰伦斯都愿意不惜一切代价去完成。为此，他一定要去圣塔，他必须要知道特蕾莎来这里做了什么，她的真正目的又是什么。",
		ShowQuestId = "55011",
		DLCQuest = 0,
		CompleteQuestId = "53713",
		QuestId = 10506,
		Name = "前往圣塔顶部",
		QuestSort = 44,
		QuestType = 2,
		NextQuestId = "10507"
	},
	{
		Description = "基塔布的巨像与圣塔融合了，这里的一切都超出了想象。整座圣塔内部到处是破裂的墙壁和坍塌的楼梯，塔内的活物都已成了怪物，费尽周折在废墟中找到通往塔顶的路，但如同往常一样一无所获，没有教会，没有马吉安人，更没有特蕾莎的踪影。多亏有格伦的猫头鹰提醒，他发现塔顶的祭坛有熟悉的气息。泰伦斯握着从伊瑟流姆得到的碎裂耶库伯之印，走上祭坛……",
		ShowQuestId = "53713",
		DLCQuest = 0,
		CompleteQuestId = "52087",
		QuestId = 10507,
		Name = "调查祭坛",
		QuestSort = 45,
		QuestType = 2,
		NextQuestId = "10508"
	},
	{
		Description = "碎裂的耶库伯之印与祭坛发生了共鸣，泰伦斯得以窥见过往。特蕾莎曾经来过这里，并且拿走了耶库伯之印。然而回溯戛然而止，泰伦斯没能看到接下来发生的事情，也无法确认基塔布的种种异常是否与此有关。\n在祭坛中，泰伦斯发现了一枚钥匙，可以打开圣塔中央升降室的门。圣塔之顶已经没有更多线索，但隐隐透出哀嚎的圣塔底部或许还埋藏着一些秘密。",
		ShowQuestId = "52087",
		DLCQuest = 0,
		CompleteQuestId = "53010",
		QuestId = 10508,
		Name = "去往圣塔之底",
		QuestSort = 46,
		QuestType = 2,
		NextQuestId = "10509"
	},
	{
		Description = "圣塔之底原本已被封锁，但巨像与圣塔融合后，在这里却制造了一道裂缝，得以让人进入底部的巨大空间。但泰伦斯他们并不孤单，那熟悉的身影分明就是德克，那个一直在寻找沙漏的先驱者。此时，哀嚎渐渐变成了模糊不清的话语，很多人的话语……",
		ShowQuestId = "53010",
		DLCQuest = 0,
		CompleteQuestId = "55041",
		QuestId = 10509,
		Name = "圣塔之底的怪物",
		QuestSort = 47,
		QuestType = 2,
		NextQuestId = "10510"
	},
	{
		Description = "击败了圣塔之底的怪物后，泰伦斯意识到特蕾莎夺走耶库伯之印，并非为了打开巨像墓地，摧毁教会所在的赐福之地，让它变成下一个基塔布才是她真正的目的。\n这场复仇究竟因何而起？似乎泰伦斯心中早已有了隐约的答案。现在，他已无法逃避，只有直面过去，并且前往赐福之地，阻止特蕾莎将一切导向毁灭。",
		ShowQuestId = "55041",
		DLCQuest = 0,
		CompleteQuestId = "45065",
		QuestId = 10510,
		Name = "再次启程",
		QuestSort = 48,
		QuestType = 2,
		NextQuestId = "10511"
	},
	{
		Description = "作为先驱者，泰伦斯早就失去了回到赐福之地的资格。正当他一筹莫展时，诺伍德提出建议，前往伊迪斯，借此进入赐福之地。在泰伦斯的记忆中，伊迪斯是被教会遗弃的无光死城，而诺伍德透露，那里并非毫无人烟。十几年前，教会把圣修院的德慕格派流放到了伊迪斯。可以想象，德慕格派在那座绝望之城中到底遭受了多少痛苦，所以他们对教会必然怀有仇怨，或许会愿意帮助泰伦斯进入赐福之地。",
		ShowQuestId = "45065",
		DLCQuest = 0,
		CompleteQuestId = "45001",
		QuestId = 10511,
		Name = "前往伊迪斯",
		QuestSort = 49,
		QuestType = 2,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "55001",
		DLCQuest = 0,
		CompleteQuestId = "55007",
		QuestId = 20501,
		Name = "游荡的先驱者",
		QuestSort = 106,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "在基塔布森林外的桥边，泰伦斯见到一名自称德克的先驱者。他原本同其他先驱者一起被派去圣塔底部寻找耶库伯之印。但却弄丢了教会配发的沙漏，没有沙漏计时，他不敢再踏入充满诅咒的圣塔底部。",
		ShowQuestId = "55001",
		DLCQuest = 0,
		CompleteQuestId = "52201",
		QuestId = 20502,
		Name = "先驱者的沙漏",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20503"
	},
	{
		Description = "泰伦斯在基塔布森林中的地下甬道发现了德克遗失的沙漏，一路上他遭遇几名教会骑士，但所谓的骑士，也都是已经被污秽腐化的污染者罢了。而德克提及的其他先驱者，泰伦斯一个也没有见到。这一切透着古怪，泰伦斯打算先把沙漏归还给德克，然后继续向基塔布的核心进发。",
		ShowQuestId = "55001;52201",
		DLCQuest = 0,
		CompleteQuestId = "55007",
		QuestId = 20503,
		Name = "交还沙漏",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "45001",
		DLCQuest = 0,
		CompleteQuestId = "65001",
		QuestId = 10401,
		Name = "伊迪斯",
		QuestSort = 5,
		QuestType = 1,
		NextQuestId = ""
	},
	{
		Description = "伊迪斯的景象和预想的不尽相同。众所周知，这里的巨像已经陨落，应该完全被黑暗笼罩。但现在，伊迪斯的的天幕却映出一片赤霞。这光源究竟来自哪里？怀着满腹的疑问，泰伦斯推来了伊迪斯的大门。",
		ShowQuestId = "45001",
		DLCQuest = 0,
		CompleteQuestId = "45004",
		QuestId = 10402,
		Name = "调查伊迪斯",
		QuestSort = 50,
		QuestType = 2,
		NextQuestId = "10403"
	},
	{
		Description = "轰鸣的钟声似乎让眼前的这名德慕格极其痛苦。这个充满戾气的女人，是一名德慕格，她宣称德慕格们已经获得了向教会发起复仇的力量。\n为了抓捕敲钟的叛徒，通往赐福之地的大门已经被完全封锁。虽然女人警告泰伦斯不要插手，但为了尽快前往赐福之地，泰伦斯不顾警告，进入村内寻找敲钟人。",
		ShowQuestId = "45004",
		DLCQuest = 0,
		CompleteQuestId = "45046",
		QuestId = 10403,
		Name = "寻找敲钟人",
		QuestSort = 51,
		QuestType = 2,
		NextQuestId = "10404"
	},
	{
		Description = "刚进入村内泰伦斯一行就遭到了攻击，这里的人们似乎已经彻底疯狂，说着莫名其妙的话，当远处钟塔传来钟声，他们变得更加狂暴。\n钟声才停下不久，敲钟人还未走远，泰伦斯立即赶往那座钟塔。",
		ShowQuestId = "45046",
		DLCQuest = 0,
		CompleteQuestId = "45008",
		QuestId = 10404,
		Name = "前往钟塔",
		QuestSort = 52,
		QuestType = 2,
		NextQuestId = "10405"
	},
	{
		Description = "敲钟人自称弗罗洛，他辩解自己并非叛徒，而是为了阻止德慕格再次走上歧途。弗罗洛的话让人疑窦丛生，在钟塔之下，再次遇见了伊琳娜。在无法辨清情况的局面下，泰伦斯一行也不敢轻举妄动。不管如何，只有阻止钟声才能离开伊迪斯。",
		ShowQuestId = "45008",
		DLCQuest = 0,
		CompleteQuestId = "45013",
		QuestId = 10405,
		Name = "调查德慕格村庄",
		QuestSort = 53,
		QuestType = 2,
		NextQuestId = "10406"
	},
	{
		Description = "德慕格派的确在走向毁灭，但泰伦斯始终无法判断伊琳娜和弗罗洛两人中，是谁造成了这种局面。\n在村庄深处的钟塔外，伊琳娜拼死要阻止弗罗洛敲响第三座钟塔，而弗罗洛却告知泰伦斯，只要敲响第三座钟塔，就会看到真相。\n泰伦斯从弗罗洛手中获得一枚钥匙，可以打开村庄后门，去往第三座钟塔。",
		ShowQuestId = "45013",
		DLCQuest = 0,
		CompleteQuestId = "45018",
		QuestId = 10406,
		Name = "打开村庄后门",
		QuestSort = 54,
		QuestType = 2,
		NextQuestId = "10407"
	},
	{
		Description = "在去往第三座钟塔的路上，伊琳娜拦住了泰伦斯。她感叹马吉安女人的话最终成谶，原本用于警示污秽入侵的钟声竟然会伤害巨像。\n而泰伦斯只关心马吉安女人的事情，那很可能是特蕾莎。泰伦斯的焦躁让伊琳娜抓住了谈判的筹码，马吉安女人已经去了赐福之地，只要泰伦斯杀了弗罗洛，伊琳娜就为泰伦斯打开去往赐福之地的大门。",
		ShowQuestId = "45018",
		DLCQuest = 0,
		CompleteQuestId = "45047",
		QuestId = 10407,
		Name = "伊琳娜的条件",
		QuestSort = 55,
		QuestType = 2,
		NextQuestId = "10408;10411"
	},
	{
		Description = "在第三座钟塔前，泰伦斯找到了弗罗洛，他宣称伊琳娜和其他德慕格们都被谎言蒙蔽了，德慕格的悲惨遭遇其实是原领袖维伦特造成的。混乱的信息让泰伦斯感到不耐，特蕾莎或许已经去往赐福之地，他不能再被伊迪斯的事情拖住脚步。他决定完成和伊琳娜进行交易。",
		ShowQuestId = "45021",
		DLCQuest = 0,
		CompleteQuestId = "41003",
		QuestId = 10408,
		Name = "敲响弗罗洛的丧钟",
		QuestSort = 56,
		QuestType = 2,
		NextQuestId = "10409"
	},
	{
		Description = "不管真相如何，这个装神弄鬼的敲钟人已经倒下。一切都已经结束，泰伦斯捡起弗罗洛那张染血的覆面作为信物，回身前往伊琳娜所在的审判庭。\n伊迪斯的事情就告一段落了，泰伦斯想着那座通往赐福之地的大桥，加快了脚步。",
		ShowQuestId = "41003",
		DLCQuest = 0,
		CompleteQuestId = "45023",
		QuestId = 10409,
		Name = "完成与伊琳娜的交易",
		QuestSort = 57,
		QuestType = 2,
		NextQuestId = "10410"
	},
	{
		Description = "德慕格的疯狂似乎愈演愈烈，泰伦斯打算尽快通过第三座塔抵达赐福之地的大门。伊琳娜将会按照约定，为泰伦斯打开通往赐福之地的大门。在这帮疯子冲进赐福之地前，他必须尽快找到特蕾莎。",
		ShowQuestId = "45023",
		DLCQuest = 0,
		CompleteQuestId = "45037",
		QuestId = 10410,
		Name = "前往大门",
		QuestSort = 58,
		QuestType = 2,
		NextQuestId = "10411"
	},
	{
		Description = "在第三座钟塔前，泰伦斯找到了弗罗洛，在泰伦斯看来，无心复仇的弗罗洛似乎是唯一还保有理智的人。在狂热的信仰与复仇的意志下，人类会做出多么可怕的事情？泰伦斯心知肚明。根据弗罗洛的提示，泰伦斯返回审判庭，通往赐福之地的大门的钥匙被伊琳娜藏在那里，无论是进入赐福之地还是了解真相，都需要这枚钥匙。",
		ShowQuestId = "45022",
		DLCQuest = 0,
		CompleteQuestId = "42302",
		QuestId = 10411,
		Name = "夺取大门钥匙",
		QuestSort = 59,
		QuestType = 2,
		NextQuestId = "10412"
	},
	{
		Description = "高傲的伊琳娜，俯视着泰伦斯，她眼中充斥着难以抑制的怒火。对于伊琳娜来说，任何忤逆德慕格意志的人都将成为她的敌人。\n解决了这些疯狂的信徒之后，伊琳娜却不知去向，接下来只要前往第三座钟塔找到弗罗洛，也许就能知道这里究竟隐藏着什么……一切即将告一段落的感觉让泰伦斯暗暗松了一口气。",
		ShowQuestId = "42302",
		DLCQuest = 0,
		CompleteQuestId = "45024",
		QuestId = 10412,
		Name = "把钥匙交给弗罗洛",
		QuestSort = 60,
		QuestType = 2,
		NextQuestId = "10413"
	},
	{
		Description = "当第三座钟塔的钟声响起时，弗罗洛终于对泰伦斯道出真相，白尘是伊迪斯巨像的产物，德慕格们通过女巫授予的马吉安仪式让白尘与自身结合从而获取力量，代价则是失去自己的心智。泰伦斯打算尽快通过第三座塔下抵达赐福之地的大门。现在白尘已经散去，按照约定，弗罗洛将为泰伦斯打开通往赐福之地的大门。泰伦斯沿路前往，距离赐福之地似乎越来越近，但他心底隐隐觉得弗罗洛似乎还隐藏着什么……",
		ShowQuestId = "45024",
		DLCQuest = 0,
		CompleteQuestId = "45037",
		QuestId = 10413,
		Name = "前往大门",
		QuestSort = 61,
		QuestType = 2,
		NextQuestId = "10414"
	},
	{
		Description = "白尘虽然散去，但德慕格的复仇意志并没有消失。面对眼前初生的伊迪斯巨像，泰伦斯惟有奋力一搏。",
		ShowQuestId = "45037",
		DLCQuest = 0,
		CompleteQuestId = "45038",
		QuestId = 10414,
		Name = "击败初生的伊迪斯",
		QuestSort = 62,
		QuestType = 2,
		NextQuestId = "10415"
	},
	{
		Description = "伊迪斯的巨像轰然陨落，被吞噬的复仇意志从中得到解放。德慕格复仇的脚步仍未停止，而此时的特蕾莎是否已经同他们一起准备掀起一场腥风血雨？",
		ShowQuestId = "45038",
		DLCQuest = 0,
		CompleteQuestId = "65001",
		QuestId = 10415,
		Name = "前往赐福之地",
		QuestSort = 63,
		QuestType = 2,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "45010",
		DLCQuest = 0,
		CompleteQuestId = "45044",
		QuestId = 20701,
		Name = "寻找安德烈",
		QuestSort = 107,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "老妇人的两个儿子都加入德慕格反抗军奔赴前线，小孩子安德烈自从两位哥哥离开后就离家出走，至今未归。老妇人有些担心，拜托泰伦斯帮忙寻找安德烈。拒绝一位等待儿子回家的母亲，未免显得过于残酷。",
		ShowQuestId = "45010",
		DLCQuest = 0,
		CompleteQuestId = "45043",
		QuestId = 20702,
		Name = "寻找安德烈",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20703"
	},
	{
		Description = "泰伦斯是偶然间找到安德烈的，在伊迪斯村庄后的纪念碑上，刻着安德烈的名字。石碑上还有许多陌生的名字，但他们似乎都不会再回来了。",
		ShowQuestId = "45043;45010",
		DLCQuest = 0,
		CompleteQuestId = "45044",
		QuestId = 20703,
		Name = "刻在碑上的名字",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "45048",
		DLCQuest = 0,
		CompleteQuestId = "45045",
		QuestId = 20801,
		Name = "老人与蜡烛",
		QuestSort = 108,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "这个苍老的声音，瑟瑟发抖地躲在屋子里。他只想要一根蜡烛，伊迪斯天空中的光源太微弱了，他觉得冷。",
		ShowQuestId = "45048",
		DLCQuest = 0,
		CompleteQuestId = "42301",
		QuestId = 20802,
		Name = "为老人找一根蜡烛",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20803"
	},
	{
		Description = "泰伦斯带着蜡烛回去找那个老人，希望他还没有冻死……",
		ShowQuestId = "42301;45048",
		DLCQuest = 0,
		CompleteQuestId = "45045",
		QuestId = 20803,
		Name = "给老人一点温暖",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "65001",
		DLCQuest = 0,
		CompleteQuestId = "75007",
		QuestId = 10601,
		Name = "赐福之地",
		QuestSort = 6,
		QuestType = 1,
		NextQuestId = ""
	},
	{
		Description = "如今的赐福之地与泰伦斯记忆中那座光明之城完全不一样，号称不灭的光芒也有黯淡的一天，城中四处弥漫着污秽的气味……\n这里的情况很糟糕，想到特蕾莎可能遭遇危险，泰伦斯向赐福之地深处冲去。",
		ShowQuestId = "65001",
		DLCQuest = 0,
		CompleteQuestId = "63017",
		QuestId = 10602,
		Name = "进入赐福之地",
		QuestSort = 64,
		QuestType = 2,
		NextQuestId = "10603"
	},
	{
		Description = "在污秽与德慕格的侵袭下，杀戮与破坏充斥四周。当泰伦斯终于找到特蕾莎的身影时，却被半路杀出的伊琳娜拦住了去路，当然无论是谁都无法阻挡泰伦斯想要追上特蕾莎的脚步。",
		ShowQuestId = "63017",
		DLCQuest = 0,
		CompleteQuestId = "63703",
		QuestId = 10603,
		Name = "追上特蕾莎",
		QuestSort = 65,
		QuestType = 2,
		NextQuestId = "10604"
	},
	{
		Description = "赐福之地的情况极度混乱，伊琳娜的阻挠，让泰伦斯始终无法追上近在咫尺的特蕾莎。\n三圣所是教会中枢所在，特蕾莎距离完成她的复仇只有一步之遥，到那时一切将无可挽回。泰伦斯不敢多做逗留，紧追在特蕾莎之后，进入三圣所。",
		ShowQuestId = "63703",
		DLCQuest = 0,
		CompleteQuestId = "65071",
		QuestId = 10604,
		Name = "前往三圣所",
		QuestSort = 66,
		QuestType = 2,
		NextQuestId = "10605"
	},
	{
		Description = "艾克哈特告诉泰伦斯，教宗早在多年之前回到赐福之地后，就躲进寝宫不再见人。至此之后，三圣所的深处就时有传出痛苦的呻吟和疯狂的低语……但难办的是，并没多少人知道教宗隐匿的寝宫究竟在哪里。那声音似乎永远在三圣所坚硬的石墙中不断徘徊。",
		ShowQuestId = "65071",
		DLCQuest = 0,
		CompleteQuestId = "65070",
		QuestId = 10605,
		Name = "寻找教宗",
		QuestSort = 67,
		QuestType = 2,
		NextQuestId = "10607"
	},
	{
		Description = "隐秘的墙壁已经打开，教宗歇斯底里的低语愈发清晰，他究竟在和谁说话，会是特蕾莎吗？",
		ShowQuestId = "65070",
		DLCQuest = 0,
		CompleteQuestId = "63015",
		QuestId = 10606,
		Name = "前往教宗寝宫",
		QuestSort = 68,
		QuestType = 2,
		NextQuestId = "10608"
	},
	{
		Description = "很难辨认那个干枯的人形正是曾经威严的教宗，他究竟经历什么？寝宫内有一种浓烈的气味，类似污秽但又掺杂了别的什么，泰伦斯突然感觉到背脊上强烈的寒意……",
		ShowQuestId = "63015",
		DLCQuest = 0,
		CompleteQuestId = "65013",
		QuestId = 10607,
		Name = "打败教宗的仆人",
		QuestSort = 69,
		QuestType = 2,
		NextQuestId = "10609"
	},
	{
		Description = "突如其来的背叛让泰伦斯彻底陷入了混乱，失去了方向。好在贝妮塔找到了一把钥匙，让绝境重现生机……现在唯一能做的就是前往基塔布圣塔底部，用它打开那扇封闭已久的大门。",
		ShowQuestId = "65013",
		DLCQuest = 0,
		CompleteQuestId = "75007",
		QuestId = 10608,
		Name = "前往基塔布圣塔底部",
		QuestSort = 70,
		QuestType = 2,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "65007",
		DLCQuest = 0,
		CompleteQuestId = "65068",
		QuestId = 20901,
		Name = "死亡，或者成为污秽",
		QuestSort = 109,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "泰伦斯遇到了一名倒在路边的德慕格，她已经被污秽彻底感染。而她她乞求着泰伦斯为她找来教会的圣剑，据说那是一柄可以净化污秽的圣器，德慕格希望最后以人类的身份死去。",
		ShowQuestId = "65007",
		DLCQuest = 0,
		CompleteQuestId = "62301",
		QuestId = 20902,
		Name = "寻找圣剑",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "20903"
	},
	{
		Description = "在三圣所外，泰伦斯找到了教会的圣剑。当他取下圣剑，周围突然出现了数名堕落的污染者，看来需要这柄圣剑的人可不只他一个……",
		ShowQuestId = "65007;62301",
		DLCQuest = 0,
		CompleteQuestId = "65068",
		QuestId = 20903,
		Name = "教会的圣剑",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "65008",
		DLCQuest = 0,
		CompleteQuestId = "65037",
		QuestId = 21001,
		Name = "四神柱的秘密",
		QuestSort = 110,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "赐福之地的一名双目失明老者告诉泰伦斯，四神柱的光芒早已在十多年前开始衰弱。\n他拜托泰伦斯去调查四神柱，探寻教会掌握的秘密",
		ShowQuestId = "65008",
		DLCQuest = 0,
		CompleteQuestId = "62302",
		QuestId = 21002,
		Name = "调查四神柱",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "21003"
	},
	{
		Description = "让泰伦斯惊讶的是，从四神柱取走断剑后，他隐约感觉到四神柱的光芒变强了一些。当然这可能是错觉，这把破损的断剑到底是何物？或许那个老者会在三圣所告诉他答案。",
		ShowQuestId = "62302;65008",
		DLCQuest = 0,
		CompleteQuestId = "65037",
		QuestId = 21003,
		Name = "与艾克哈特交流情报",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "地下溶洞",
		ShowQuestId = "75007",
		DLCQuest = 0,
		CompleteQuestId = "85001",
		QuestId = 10701,
		Name = "地下溶洞",
		QuestSort = 7,
		QuestType = 1,
		NextQuestId = ""
	},
	{
		Description = "尘封多年的大门再次开启，掩盖许久的真相正在慢慢揭开。",
		ShowQuestId = "75007",
		DLCQuest = 0,
		CompleteQuestId = "75005",
		QuestId = 10702,
		Name = "调查溶洞",
		QuestSort = 71,
		QuestType = 2,
		NextQuestId = "10703"
	},
	{
		Description = "庞大的地下遗迹，连通着赐福之地与基塔布，它究竟存在了多久无人知晓。一阵喧闹的争吵声回荡在空旷的溶洞之中，泰伦斯循声追去发现维奥拉被关押了起来并且陷入了昏迷，诡异的红光充斥着监牢，似乎多看一眼就会失去理智。",
		ShowQuestId = "75005",
		DLCQuest = 0,
		CompleteQuestId = "75011",
		QuestId = 10703,
		Name = "解救维奥拉",
		QuestSort = 72,
		QuestType = 2,
		NextQuestId = "10704"
	},
	{
		Description = "在泰伦斯的帮助下，维奥拉逐渐解开了心结。而与此同时，诺伍德已经带着特蕾莎前往溶洞深处的遗迹。",
		ShowQuestId = "75011",
		DLCQuest = 0,
		CompleteQuestId = "75015",
		QuestId = 10704,
		Name = "前往溶洞深处的祭坛",
		QuestSort = 73,
		QuestType = 2,
		NextQuestId = "10705"
	},
	{
		Description = "通往溶洞深处的路被一扇大门挡住。在监狱一角，泰伦斯遇到一位衣衫褴褛的老者，他被关在半空的牢笼中，语无伦次，神志不清，但他似乎又隐藏着某些与此地相关的秘密。为了尽快到达溶洞深处的遗迹，泰伦斯只有接受老人的请求，帮他脱离牢笼。",
		ShowQuestId = "75015",
		DLCQuest = 0,
		CompleteQuestId = "72201",
		QuestId = 10705,
		Name = "降下疯子的牢笼",
		QuestSort = 74,
		QuestType = 2,
		NextQuestId = "10706"
	},
	{
		Description = "泰伦斯在监狱上层天桥处找到了机关，并把老者所在的牢笼降下。同时也顺利扫清了前进的障碍。",
		ShowQuestId = "72201",
		DLCQuest = 0,
		CompleteQuestId = "73006",
		QuestId = 10706,
		Name = "帮疯子打开牢笼",
		QuestSort = 75,
		QuestType = 2,
		NextQuestId = "10707"
	},
	{
		Description = "祭坛处发生的仪式让人不寒而栗，但更令人吃惊的是诺伍德的举动，事情发生的太突然，难道这一切都是他的计划？",
		ShowQuestId = "73006",
		DLCQuest = 0,
		CompleteQuestId = "75018",
		QuestId = 10707,
		Name = "找诺伍德问明真相",
		QuestSort = 76,
		QuestType = 2,
		NextQuestId = "10708"
	},
	{
		Description = "谁能想到诺伍德竟也是马吉安人，冥冥之中似乎所有的人和事都联系在了一起。虽然泰伦斯一时难以接受，然而现在特蕾莎正身陷危险之中，每一秒的犹豫都可能导致难以挽回的结果。",
		ShowQuestId = "75018",
		DLCQuest = 0,
		CompleteQuestId = "75036",
		QuestId = 10708,
		Name = "拯救特蕾莎",
		QuestSort = 77,
		QuestType = 2,
		NextQuestId = "10709"
	},
	{
		Description = "巨像墓地已经被打开了，失去了马吉安人和耶库伯之印，凡人之躯理应无法进入。但万幸泰伦斯身上还留有着红星碎片，让他博得最后一丝机会。",
		ShowQuestId = "75036",
		DLCQuest = 0,
		CompleteQuestId = "85001",
		QuestId = 10709,
		Name = "进入巨像墓地",
		QuestSort = 78,
		QuestType = 2,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "75022",
		DLCQuest = 0,
		CompleteQuestId = "75035",
		QuestId = 21101,
		Name = "饥饿感",
		QuestSort = 111,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "那人被倒吊在空中，叫嚷着想要一种泛着微光的美味。身体诡异地扭动着，束缚着，犹如蛹茧一般，但破茧之后，里面又会出来什么样骇人的东西呢？",
		ShowQuestId = "75022",
		DLCQuest = 0,
		CompleteQuestId = "72305",
		QuestId = 21102,
		Name = "寻找发光的美味",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = "21103"
	},
	{
		Description = "这或许就是那个被倒掉着的家伙可求的美味，但这种奇怪的东西怎么可能用来作为食物？",
		ShowQuestId = "75022;72305",
		DLCQuest = 0,
		CompleteQuestId = "75035",
		QuestId = 21103,
		Name = "满足倒吊者",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "55091",
		DLCQuest = 1,
		CompleteQuestId = "99103",
		QuestId = 10901,
		Name = "伊西索亚",
		QuestSort = 9,
		QuestType = 1,
		NextQuestId = ""
	},
	{
		Description = "异乡人杰洛尔德为泰伦斯提供了新的选择：用红星去唤醒杰洛尔德的故乡伊西索亚，或许能给几乎难以挽回的现状带来转机。而这趟旅途的起点，是伊迪斯海边的一座废弃的码头。",
		ShowQuestId = "55091",
		DLCQuest = 1,
		CompleteQuestId = "95179",
		QuestId = 10902,
		Name = "前往伊迪斯废弃的码头",
		QuestSort = 91,
		QuestType = 2,
		NextQuestId = "10903"
	},
	{
		Description = "一场可怕的风暴无情地袭击了泰伦斯他们的船只。在昏迷之前，泰伦斯最后看到的画面却是杰洛尔德那古怪诡异的表情。\n当泰伦斯再次清醒过来时，他发现自己已经被海浪冲上岸。这里是哪儿？其他人还活着吗？得尽快找到他们……泰伦斯艰难地撑起身，开始寻找自己的同伴。",
		ShowQuestId = "95179",
		DLCQuest = 1,
		CompleteQuestId = "95181",
		QuestId = 10903,
		Name = "寻找格伦与杰洛尔德",
		QuestSort = 92,
		QuestType = 2,
		NextQuestId = "10904"
	},
	{
		Description = "原来杰洛尔德的故乡竟是在巨兽伊西索亚的腹内，这里的人们和它似乎保持着一种奇妙的共生关系。\n在杰洛尔德离开伊西索亚的这段时间里，一切都好像变得更糟了，神圣的浸灵河水已近已经完全干涸，充满了腐朽的气息。\n目睹这一切，杰洛尔德似乎承受着巨大痛苦，但他还执意继续前进：沿着浸灵河一直向上游走，艾宾浩斯大人就在河的源头。",
		ShowQuestId = "95181",
		DLCQuest = 1,
		CompleteQuestId = "93005",
		QuestId = 10904,
		Name = "寻找浸灵河的源头",
		QuestSort = 93,
		QuestType = 2,
		NextQuestId = "10905"
	},
	{
		Description = "泰伦斯一行遭遇了几名神秘人的攻击。危急时刻，一名男孩救了他们，并示意泰伦斯一行人跟上他。\n这是他们在伊西索亚遇到第一个友善的人，泰伦斯决定追上男孩，希望他能告诉自己这里究竟发生了什么。",
		ShowQuestId = "93005",
		DLCQuest = 1,
		CompleteQuestId = "95182",
		QuestId = 10905,
		Name = "追上男孩",
		QuestSort = 94,
		QuestType = 2,
		NextQuestId = "10906"
	},
	{
		Description = "泰伦斯他们在一间堆满石棺的屋子里找到了布沃尔，那个救了他们的男孩。布沃尔告诉他们，如果想去浸灵河的源头必须通过静默之墙，而浸灵河之所以会干涸，正是因为静默之墙拦住了河水。\n对于泰伦斯和杰洛尔德来说，他们别无选择，为了去浸灵河的上游找艾宾浩斯，他们必须突破静默之墙。",
		ShowQuestId = "95182",
		DLCQuest = 1,
		CompleteQuestId = "93019",
		QuestId = 10906,
		Name = "突破静默之墙",
		QuestSort = 95,
		QuestType = 2,
		NextQuestId = "10907"
	},
	{
		Description = "越过静默之墙，泰伦斯终于看到了腹腔尽头的那座高塔，浸灵河水正从那里缓缓流下。那里应该就是浸灵河的源头，杰洛尔德一直追随的艾宾浩斯大人就在那里。",
		ShowQuestId = "93019",
		DLCQuest = 1,
		CompleteQuestId = "99103",
		QuestId = 10907,
		Name = "登上源流之塔",
		QuestSort = 96,
		QuestType = 2,
		NextQuestId = ""
	},
	{
		Description = "",
		ShowQuestId = "95183",
		DLCQuest = 0,
		CompleteQuestId = "93008",
		QuestId = 21201,
		Name = "记忆之河",
		QuestSort = 0,
		QuestType = 3,
		NextQuestId = ""
	},
	{
		Description = "布沃尔认为只要重新打开静默之墙，让浸灵河水重新流下，被污染的伊西索亚将会慢慢恢复。\n打开静默之墙的关键是要找到它的操纵杆和齿轮，布沃尔猜测它们被藏在了伊西索亚的某处。作为「朋友」，泰伦斯他们决定帮男孩一把。",
		ShowQuestId = "95183",
		DLCQuest = 0,
		CompleteQuestId = "93008",
		QuestId = 21202,
		Name = "寻找操纵杆和齿轮",
		QuestSort = 0,
		QuestType = 4,
		NextQuestId = ""
	},
	{
		Description = "言语无法描绘的巨像，目光无从传递的仰望，蝼蚁般的人类依附在神秘的光环之下，夜以继日地追赶，日月同辉的光芒，无名的遗迹终于让海格姆停下了沉重的脚步，追随者们享受着片刻的静息，为继续无尽的旅途稍作停留。",
		ShowQuestId = "12900",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30101,
		Name = "海格姆",
		QuestSort = 1,
		QuestType = 5,
		NextQuestId = ""
	},
	{
		Description = "雷蒙斯大人是何等的圣人啊，为了我们……素不相识的我们……他当然明白这一切的后果，可最后还是选择了与我们共同进退。",
		ShowQuestId = "12901",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30102,
		Name = "丢弃的手卷",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "没人能劝阻他，没人能理解他为什么要这样做？不断地鞭挞……一次比一次更用力。\n雷蒙斯大人声称这是通过肉体的伤痛，惩戒灵魂的罪孽。这种难以想象的可怕习俗来自于雷蒙斯大人的家乡。可雷蒙斯大人又有什么罪呢？如果不是他……海格姆可能早就没有活人了！",
		ShowQuestId = "12902",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30103,
		Name = "泛黄的日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "从这洞底向上看，不见一丝光亮，黑雾笼罩之下何处是家的方向？我求索半生可依然一无所获，那地方到底在哪？……我还有时间继续找下去吗？",
		ShowQuestId = "12903",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30104,
		Name = "雷蒙斯的笔记之一",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "矿洞里渐渐有了欢声笑语，也许神真的听到了我的祈祷，篝火的柴堆冷却了，到了该受鞭笞的时候了。",
		ShowQuestId = "12904",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30105,
		Name = "雷蒙斯的笔记之二",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "又有许多人被污染了，看来那些纠缠不休的可憎之物已经侵袭进来了……是谁夺走了庇护这里的晶石？神啊，为何要扼住海格姆的喉咙！",
		ShowQuestId = "12905",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30106,
		Name = "雷蒙斯的笔记之三",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "海格姆黄水晶、海蓝宝、碧玺、托帕……商人们视若珍宝的矿石我们这儿应有尽有。可自从巨像瘟疫降临，就再也没有商队出现过……这些稀释的珍宝，反倒变成了一堆破烂……海格姆每况愈下，这该死的瘟疫什么时候才能结束？",
		ShowQuestId = "12906",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30107,
		Name = "散落的日记残页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "这应该是我最后一次来这儿了！说实话，我从没喜欢过这些粗人。过去为了生意嘛……不过还是命重要。这儿的巨像快完了？没错，一定是这样的。这次我发现有些矿工獠牙外露，背上的矿石牢牢地嵌进了身体里……",
		ShowQuestId = "12907",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30108,
		Name = "商队的备忘录",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "一向健壮的弗兰克也染上了瘟疫，而且病得越来越沉重……不停地发出没人能懂的噪音，像在抱怨命运的不公平。眼下我只能一个人下到矿井去，人越来越少……我想早晚会轮到我的吧？ 我们这群被海格姆抛弃的渣滓，还有谁会来拯救？",
		ShowQuestId = "12908",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30109,
		Name = "残破的手记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "神早已抛弃了他们，似乎唯有对着阿达米亚不断地虔诚祈祷，才可以延续游丝般微弱的血脉。不计代价地抓住这不知何时就会熄灭的微光。",
		ShowQuestId = "22900",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30201,
		Name = "阿达米亚",
		QuestSort = 2,
		QuestType = 5,
		NextQuestId = ""
	},
	{
		Description = "过去我们随着头顶的微光颠沛流离，酷暑难耐或寒风凛冽……每天都有人死去，从没有婴孩降生。\n是圣父的到来使我们告别了愚昧与贫瘠——受圣父眷顾的病人能忘记疼痛，干枯的女人们竟开始孕育生命，圣父还赐予了我们狩戒的勇气。",
		ShowQuestId = "22901",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30202,
		Name = "神秘的笔记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "圣父来了，阿达米亚就又重新亮起了旺盛的光芒。它活过来了！万福！不朽的圣父！",
		ShowQuestId = "22902",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30203,
		Name = "细心记录的祈祷词",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "为了新的生命……狩戒！清除所有威胁圣父的存在……为圣父奉献一切！",
		ShowQuestId = "22903",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30204,
		Name = "发狂女人的日志",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "艾伦终于没能挺住，在安德鲁之后他也离开了我们。\n浑身紫青色，直挺挺地躺在那儿，这可怕的诅咒已经夺取了多少男人的性命？到底什么时候才能停止？愿圣父保佑阿达米亚，并且也保佑你，我亲爱的母亲。希望在神谕之地，圣父的福泽正照耀着你。一切安好，您的女儿塞西莉。",
		ShowQuestId = "22904",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30205,
		Name = "给母亲的信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "最近发生的一些事情始终令我耿耿于怀。\n我不敢说，因为一定没人会相信我。\n阿达米亚一直是个资源短缺的地方，却忽然间有那么多沉甸甸的包裹，圣父派了我们一队兄弟运送粮食，干了整整一宿才运进那漆黑的山洞口…… ……那里伸手不见五指，但我一直难以忘记那里面的味道，夹杂着血腥和腐臭，在那黑暗的深处似乎有人在窃窃私语……我不敢多想那究竟是什么。\n在离开了那山洞之后，和我一起干活的兄弟们仿佛得罪了神灵似的，不是病倒就是不知所踪，这样下去，难道要女人们干活？！那山洞里一定有什么受到诅咒的东西，或许我得去向圣父请示。",
		ShowQuestId = "22905",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30206,
		Name = "失踪男人的日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "这真是一个游戏吗……艾尔玛教我带着凯文去找她玩，她给我们热腾腾肉饼吃，我们睡着了，跟着醒来凯文就不见了，和之前的詹米一样……奇怪，我应该去哪把他们找回来呢？",
		ShowQuestId = "22906",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30207,
		Name = "女孩的日记片段",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "在基塔布——被教会追杀的火红色女人——发光的圣盒\n敬畏，但又好奇，我不能食言，可它仿佛长着蛇的眼睛，要引我犯禁……\n那是难以形容的快乐，感到自己仿佛可以，也应该拥有一切。\n……还是无法满足，那一刻的感觉再也找不到了吗？\n还是，我被毁掉了？停下吧，请放过我吧……不！我不能，我是救世主，是阿达米亚唯一的圣人，我不能停！",
		ShowQuestId = "22907",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30208,
		Name = "达拉姆的账本",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "圣父嘱咐我采集食物，为此我不得不特别「关照」那些路经阿达米亚的异乡人。\n我的刀锋已经问候过数百名陌生男人的咽喉……而对于女客则另有安排。",
		ShowQuestId = "22908",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30209,
		Name = "屠夫的日志",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "天火坠落，击碎了伊瑟流姆锈迹斑斑的誓言，昔日的战神驻地如今爬满荒草。孤魂野鬼在悲泣，而意志消沉的无名者对残生已无所求。",
		ShowQuestId = "32900",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30301,
		Name = "伊瑟流姆",
		QuestSort = 3,
		QuestType = 5,
		NextQuestId = ""
	},
	{
		Description = "迪迪埃，与妓女通奸败露，愤怒中杀害妻子而获罪，行刑前痛哭悔过，自愿成为先驱者，得以苟全性命。\n克里斯蒂亚诺，触犯教会法令而遭杀身之祸。其父奔走哀求，以加入先驱者抵罪，逃过一劫。\n费尔南多，受命修复教会古建筑。具体获罪原因不详，来到伊瑟流姆时他已被割去了舌头。\n菲利普，因走私罪，散尽家财，更名换姓加入先驱者避难。来到伊瑟流姆后，继续做着过去的生意。",
		ShowQuestId = "32901",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30302,
		Name = "流放记录的残页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "仁慈的修女啊，阿尔贝图斯要忏悔！我其实是认识外面那些人的……他们曾经都是我最亲的朋友。我们一同迷失在污秽中，我为了自保就抛弃了他们，也欺骗了你。可他们那无休止的、不人不鬼的哀鸣，不断地透过那扇大门来折磨着我。我想出去可又害怕，既怕死，又怕外面那个熟悉的世界里早已没有我的一席之地了。",
		ShowQuestId = "32902",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30303,
		Name = "忏悔者的笔记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "总被山顶传来的歌声惊醒。距离分明很遥远，却又像在耳边唱一样……寂寞、哀怨， 眼前也影影绰绰出现了幻觉，我忍不住堵起耳朵、紧闭双眼，让那可怕的景象别追着我。",
		ShowQuestId = "32903",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30304,
		Name = "狂乱的笔记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "伊瑟流姆的巨像完蛋了，黑暗已将我们吞噬……奇怪的是只有那山顶上偏偏光照不衰，可又没有人敢去探个究竟。",
		ShowQuestId = "32904",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30305,
		Name = "最后的日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "……终于找到了驱散污秽的办法！帕特里克！等着珍妮，她很快就会穿过黑雾回到你身边了。",
		ShowQuestId = "32905",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30306,
		Name = "没有寄出的信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "在红星划破天空，击倒巨像的那天，我那在军港里守卫的丈夫和儿子也一并失踪了，至今音讯全无。我当时就劝他们不要参与对那红发女巫行刑……\n可他们就是没人听我的啊！",
		ShowQuestId = "32906",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30307,
		Name = "陈旧的军属日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "那红色的灾星把黑雾带进了伊瑟流姆，士兵们渐渐变得疯狂，在守夜时会冲进民舍向我们发动攻击……\n军港里已无处可躲，唯有圣所中的修女，可那扇门却死死地关住了，任我们如何哀求都无人理会……",
		ShowQuestId = "32907",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30308,
		Name = "乞援人的日志",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "一边同异化的兵士奋战，一边呼喊那个懦夫的名字。可他无动于衷……我恐惧的是，我感到自己正与曾见过的那些怪物同化……如果我真的变成那种丑陋的东西，还不如就此死掉。\n文森特大人啊……最终还是辜负了您……",
		ShowQuestId = "32908",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30309,
		Name = "卡桑德拉的遗言",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "罪孽深重的流亡者，用仇恨将这无光的空城从沉睡中唤醒。猩红的伊迪斯啊，你在为谁的命运哭泣？",
		ShowQuestId = "42900",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30401,
		Name = "伊迪斯",
		QuestSort = 5,
		QuestType = 5,
		NextQuestId = ""
	},
	{
		Description = "伊迪斯比传说里形容得更糟。在黑雾中流亡，直到堕入疯狂……这就是教会对德慕格无情的惩罚啊。我要离开这儿，这种没有光的地方我一天也待不下去。",
		ShowQuestId = "42901",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30402,
		Name = "被丢下的日记本",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "据说在久远之前伊迪斯也曾有过居民，后来一夜之间消亡殆尽……会不会就是这伊迪斯之苔把它瞬间变成了一座死城？呵！\n早知道这样的结局，还不如当初就死在赐福之地！",
		ShowQuestId = "42902",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30403,
		Name = "日记残章",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "大祭司曾带给我们的安宁、喜悦和灵感已经完全消失了。但伊琳娜仍然告诉我们终有一天大祭司会回来，带领我们重新走出这片黑雾。\n我们必须想尽办法在这座死城的污秽侵袭中苟延残喘，蜷缩或拥抱在一起，即便耳边尽是污秽的游走和呼啸声，我们也必须等到那一天的到来。",
		ShowQuestId = "42903",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30404,
		Name = "关于伊迪斯的信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "自从那个神秘的女巫到来之后，伊琳娜便开始同她一起积极谋划着什么。伊琳娜可不是一个轻易相信别人的人，那个女巫到底给予了她什么？",
		ShowQuestId = "42904",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30405,
		Name = "私下的谣言",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "神啊，请求你发发慈悲，让伊迪斯之苔快些从这孩子身上散去吧，愿这些白色的粉尘真的能产生效力，我情愿用自己的生命换我孩子的平安……",
		ShowQuestId = "42905",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30406,
		Name = "母亲的祷告",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "这都是什么鬼话……我们可是被驱逐到这儿来的啊……回去，那不是找死？就因为那么一个不知道从哪儿冒出来的女巫的几句呓语就要打回赐福之地？\n疯了……疯了，大家都疯了！德慕格一贯的理智哪里去了？",
		ShowQuestId = "42906",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30407,
		Name = "癫狂的日志",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "我们为什么要忍受这种不公的判决？我们怎么能够忘记维伦特所受的污蔑？\n智者们、战士们、祭司们，你们真的甘于放弃，永远地活在黑暗中？\n不，我们要回去，我们要揭开赐福之地虚伪的假面，拆穿教宗用欲望编织的谎言，我们要用战火焚烧教会施加给德慕格的屈辱。\n这是我们最好的，也可能是唯一的机会。",
		ShowQuestId = "42907",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30408,
		Name = "伊琳娜的征讨檄文",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "我难以相信会有这样的事情……彼得、阿尔文和纽伦先后从虚弱中康复起来……这白尘当中究竟含有怎样神奇的成分？我无法用医药学理来解释。",
		ShowQuestId = "42908",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30409,
		Name = "药师的日志",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "是真的吗？！……如果伊琳娜大人和那女巫没有说谎，那我们是一定要回去的，对！\n回去拯救我们的大祭司！夺回德慕格失去的一切！",
		ShowQuestId = "42909",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30410,
		Name = "士兵的日志",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "那是多么奇特绚丽的光！我们紧张的不敢发出一丝声音。那位神奇的女巫独自站在飞舞的白尘中央，从手中那枚闪亮的东西里释放出了令伊迪斯新生的光芒！在一片艳丽的红色里漂浮着神之子，伊迪斯有了属于自己的光。",
		ShowQuestId = "42910",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30411,
		Name = "我的宣言",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "女巫引导空中漂浮的白尘落在我们身上，吞食之后仿佛有火焰在灼烧着五脏六腑，感到自己拥有一种源源不绝的力量,和所有人一起发出热情的呼号声，感觉自己仿佛已经不再是人，而是伊迪斯复仇的使者。",
		ShowQuestId = "42911",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30412,
		Name = "《复仇使者》",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "在如何处理教会派来的杂碎上还是司祭们有一套……既让敌人吃尽了苦头，又验证白尘的力量。这些混乱的「小丑」将和教会的走狗自相残杀……",
		ShowQuestId = "42912",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30413,
		Name = "审判日志",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "自愿吞食白尘后，身体果然在慢慢变化……很难形容那种感觉，我想自己已经成为了伊迪斯伟大神力的一部分——它的声音在我的头脑里回荡，它的意图指引我前行。\n眼睛已经看到千里之外，红色的光芒终将取代一切！",
		ShowQuestId = "42913",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30414,
		Name = "德慕格战士的手札",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "参天古树覆盖的幽暗密林，基塔布模糊的记忆里或许依然回响着古老文明的呐喊声。世代传承的仪式无力挽救，毁灭的种子早已生根。",
		ShowQuestId = "52900",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30501,
		Name = "基塔布",
		QuestSort = 4,
		QuestType = 5,
		NextQuestId = ""
	},
	{
		Description = "那些马吉安人似乎对我们的到来并不意外，这些异族，早就对赐福之地有所了解。这让我们颇为惊讶。虽然对我们也算恭敬有礼，但我依然能感觉到他们的高傲……只有德慕格能够与他们进行交流，站在一边的我多少感觉有点不自在。",
		ShowQuestId = "52901",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30502,
		Name = "士兵日志",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "一连几天那些异族的族长们都在和我们的首领进行着密谈。似乎是有关马吉安人祖先失落遗址的消息。被选中的马吉安少女们聚集起来……不知要准备做什么？",
		ShowQuestId = "52902",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30503,
		Name = "记录的文书",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "（混合着马吉安与赐福之地文字）族长离开后至今音讯全无。那支留在村子里的军队还是一如既往的规矩。但与往常不同的是，今天他们把族人送去的酒和餐食都退了回来。",
		ShowQuestId = "52903",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30504,
		Name = "几张废纸",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "（马吉安的文字）卓越先民的后裔、马吉安人尊贵的族长：近日将有西方兵团抵达基塔布，为达某种目的他们会请求协助，接受与否是你们的自由。而我只想提醒，他们所寻觅的事物上面所蕴藏的力量，记载着基塔布祖先昌荣的秘诀。\n如果事实证明这番话只是虚无的幻影，那么就当我不曾预言，世人也从未诚实。",
		ShowQuestId = "52904",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30505,
		Name = "村落里隐藏的匿名信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "驻扎在基塔布的日子真是枯燥，对村落里的符文和装饰我们一窍不通，（不过即便能够看懂，那些文字也已经磨损得无法辨认了。）马吉安人自己似乎也弄不明白。这些披着破衣烂衫的男女常聚在一块搞些灵魂出窍似的古怪仪式。说实话，那过程也让我动容，因为从那些古怪的、丑陋的动作下面，我瞧见他们始终弯曲的膝盖……在用一种谦卑的姿态传递远古的奥秘。总之这里的一切都完全是另一种……形式。对他们自己来说或许是神圣，对我们却莫名的恐惧。",
		ShowQuestId = "52905",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30506,
		Name = "给妮塔的一封信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "这真是一个难缠的族群，用他们的法术向我们还击，但感觉只有少部分人会使用咒语。那玩意施展起来确实力量强大，但弱点明显：在一定距离之外我们束手无策。不过一旦给逼近包围，马吉安人就该倒霉了！那些手舞足蹈的把戏就失去用武之地，当他们倒下的时候，我的血液在沸腾。",
		ShowQuestId = "52906",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30507,
		Name = "最后的一封信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "头好疼……这里是我的故乡？为何没有丝毫亲切的感觉……只有恐惧，痛苦，只有憎恨！烧焦的土地上依旧闻到血腥味道。\n……看来塔里依然残余着一些借着神的幌子而四处行凶的暴徒们。不过假如里面真的藏着我需要的东西……必须取得他们的信任。以不义开始的事情，必然会以灭亡来终结。\n……离圣塔越近，呼唤就越强烈。在冥冥之中，总有一个声音在窃窃私语——「来啊。过来吧，这是我们盼望已久的重逢。」……我不懂，可它不断地钻进我的脑子里，拖着我走过去。",
		ShowQuestId = "52907",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30508,
		Name = "特蕾莎的羊皮卷",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "遵循神圣的赐福之光的旨意，信仰异端的女巫盗取了教会的圣物，现急令抓捕，夺回圣物。\n此女巫红发，巫术多端，慎重处置。一经发现切勿单独接触，需立即上报进行围捕。",
		ShowQuestId = "52908",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30509,
		Name = "通缉令",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "回到基塔布，这里似乎余烬未消。那座圣塔之中，有什么东西……\n种种迹象表明教会的实验依然持续着，这群不死心的家伙，仍然奢望着进入巨像墓地。\n时间不多了，教会的人似乎已经注意到了我……我不能让他们拿走库耶伯盒",
		ShowQuestId = "52909",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30510,
		Name = "关于基塔布的信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "基塔布已经被彻底毁了，在那场屠杀之后，为什么还要回到这里？圣塔的底下真的有耶库伯之印吗？说实话，我觉得司布伦格主教这次过于冒险了。\n还有那些臭气熏天、举止粗鲁的先驱者，我无法相信他们能够胜任如此重要的任务……不过我也为此庆幸，因为我们不用下去送死了。",
		ShowQuestId = "52910",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30511,
		Name = "门徒秘录，第一部",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "他们回来了……虽然损失惨重，但耶库伯之印奇迹般地被找到了。然而这些活下来的先驱者，他们的眼神变得令人毛骨悚然，似乎是因为在圣塔的下面见到了什么。\n这些都已经不重要了，研究耶库伯之印、重新打开巨像墓地才是现在的第一要务。",
		ShowQuestId = "52911",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30512,
		Name = "门徒秘录，第二部",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "第5次实验，那圣物依然毫无反应，到底缺少了什么？没人知道，虽然大家想要集中精力投入后续的研究，但奇怪的谣言开始散布。那些侥幸活下来的先驱者不知为何染上了一种怪病，变得疯疯癫癫，他们宣称自己总是能够听见来自地底的奇怪声音……",
		ShowQuestId = "52912",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30513,
		Name = "破损的实验日志,第6页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "第18次实验，仪式还是无法成功，更令人困扰的是，我们也都开始听见从地底传来的声音。准确地说，那声音更像是低语，但没人能听清具体是什么……更令人惊恐的是，那些活下来的先驱者，他们的皮肤开始呈现出明显的液化趋势，有人说这是因为我们触怒了马吉安人的冤魂，遭到了诅咒……",
		ShowQuestId = "52913",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30514,
		Name = "破损的实验日志,第19页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "第35次实验，根据此前残余的研究资料，我们终于确认：启动耶库伯之印需要马吉安人的血脉。然而在那场战争之后，马吉安人应该已经都不复存在了，研究陷入死局，主教变得愈发急躁。耳边还不停传来地底的声音，所有人快被逼疯了。\n因为害怕异变具有传染性，那些剩下的先驱者被活活地烧死，再也无法回到赐福之地了……主教下令封锁一切通往地下路径，以免情况变得不可控制。终于，那恶魔的低语消失了，今天总算能安稳地睡一觉了。",
		ShowQuestId = "52914",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30515,
		Name = "破损的实验日志,第48页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "实验暂停的第三天，圣塔里的教会成员陆续出现身体异常状况，他们的肌肉开始软化，皮肤也变得透明，和那些先驱者一样……然而主教似乎并不打算处理这件事，而是决定明天重新开始实验。",
		ShowQuestId = "52915",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30516,
		Name = "破损的实验日志,第61页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "这一定是神的眷顾，一个女巫自称是最后的马吉安人，她愿意为主教启动耶库伯之印。我们终于要得到解脱了，现在我只想早点完成实验，然后离开这个鬼地方。",
		ShowQuestId = "52916",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30517,
		Name = "破损的实验日志,第78页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "我们被骗了！那个女巫把耶库伯之印带走了！真是一场灾难，基塔布的巨像被巨大的能量吸引而来，与圣塔融合在了一起，即使亲眼所见，还是很难相信这一切竟然真实存在。\n所有东西都开始融合……我指的是所有，已经无法用言语描述我看的东西，就像地狱出现在你的面前。那犹如恶魔般的低语声再次回荡在整个圣塔中！得把这个消息告诉赐福之地……必须把女巫抓回来……必须……",
		ShowQuestId = "52917",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30518,
		Name = "破损的实验日志,第93页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "站在圣塔顶上俯瞰整个基塔布，我不寒而栗，空气弥漫着浓郁的烧焦味，村落里没有留下一个活物。真为骑士们感到羞耻！而这枚耶库伯盒又将为教会带来什么呢？\n相信这个问题解开的时刻，又将有一场劫难随之而来。",
		ShowQuestId = "52918",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30519,
		Name = "先驱者的羊皮卷",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "受神眷顾的赐福之地，昔日的光荣和鼎盛正日复一日地衰落。在贤者汇聚的圣殿里，阴影踏着细碎的脚步，逼近那至高的信仰。",
		ShowQuestId = "62900",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30601,
		Name = "赐福之地",
		QuestSort = 6,
		QuestType = 5,
		NextQuestId = ""
	},
	{
		Description = "当夜枭开始低鸣的时候，我结束了在圣所外的巡逻，那个叫德里摩尔的小子来换班了，二十出头，应该是干劲十足的年纪，却总是一副无精打采的模样。像他一样的孩子，如果生在过去是否会好过一些呢？",
		ShowQuestId = "62901",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30602,
		Name = "轮岗日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "已经记不清这是第几年在圣院做守卫，老兵们都说过去经常能在那儿看见教宗的身影。\n可这「过去」究竟是什么时候呢？从我出生至今，从没见过教宗露面。",
		ShowQuestId = "62902",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30603,
		Name = "哨兵的笔记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "逼迫这些荒淫的教会信众们吞下白尘后，他们不人不鬼的模样比任何报复的手段都痛快……他们将领悟我们的痛苦，理解我们的愤怒，最后同样化作伊迪斯复仇的意志……夺取教宗可悲的性命！",
		ShowQuestId = "62903",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30604,
		Name = "人体试验报告",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "哨兵居伊与拉格洛在岗位上喝酒闲聊，无端揣测教宗病况，其言论造成了很大危害。依令判处绞刑。",
		ShowQuestId = "62904",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30605,
		Name = "惩处记录",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "教会人自小受教，四支神柱亘古存在，赐福之地的整体布局都是围绕着神柱规建的。可怪事偏偏就发生了！\n我发誓这以下记录都是我和教友拉斐尔亲眼所见——就在教宗主持的祈祷仪式结束之后，我们这些下级学者照例要清理中庭。就在这时，我和拉斐尔同时发现，其中一支神柱竟然在说话……不，准确说是在呻吟，它像人一样发出痛苦的呻吟，虽然十分短暂……我害怕被当成疯子，触犯了教会的律法招来杀身之祸……",
		ShowQuestId = "62905",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30606,
		Name = "神秘的通讯书",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "我们都被骗了……我不是疯子，我发誓那是真的……四神柱是用来迷惑我们让我们陪葬的谎言。都等着完蛋吧，你们这群蠢货，你们这些帮凶……这里没有一个人是干净的！",
		ShowQuestId = "62906",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30607,
		Name = "狂人日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "保罗的死亡分明就是污秽侵袭造成的，可那些教徒们偏偏不承认。也许他们心里以为靠着祈祷和幻想能逃避问题，把一切福、祸都维系在虚无缥缈的……事物上。\n可是我们德慕格人，活着就要求索真相。",
		ShowQuestId = "62907",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30608,
		Name = "短信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "雅格——时空、撒布——生命、萨达——混沌、奈耶——神言，是神的意志在地上四相化身。\n初代教宗在索拉斯先民拥戴中围绕这四根神柱建立赐福之地，守护人世安宁。",
		ShowQuestId = "62908",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30609,
		Name = "图书馆中的文献",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "在这柄剑铸成之后，我愈发担心我的老友。没错，他也许是高高在上，可每天都是活在苦恼中……作为朋友，我所能做的也就是这些了……我守住了这个秘密，可失去自己的良知……",
		ShowQuestId = "62909",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30610,
		Name = "铸剑师的手札",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "不错，这是一把好剑。可它只是一个信念……真正的希望在那虔诚信奉的那四盏明光当中。唉，可它们又能维持多久呢？是时候离开了。\n这地方的未来与我再无瓜葛。",
		ShowQuestId = "62910",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30611,
		Name = "铸剑师的道别",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "巨像衰落已经够令人焦头烂额了，又发生了红星陨落这样的天灾。 这件事引起教会上层的关注。经过讨论，决定加派先驱者进一步勘察伊瑟流姆，最好能收集到有关红星碎片的更多讯息，暂时还无法确定跟最近的那一批流放者有关……而每天来自各方的遗民涌向赐福之地。\n至于是放他们进城还是驱赶回去，议会始终争执不休。",
		ShowQuestId = "62911",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30612,
		Name = "会议记录，一",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "「此处文字被涂抹」\n在匆忙接见德慕格的大祭司之后，教宗即刻命令骑士团赶往基塔布。这是教会成立以来，骑士团首次离开赐福之地远征。希望能带回好的结果。因为已经许久未见过教宗怀有如此热切的期望。\n骑士们发回的传书详细陈述了基塔布让人既敬畏又恐慌古老传说和献祭仪式。长久以来始终是一个解不开的谜团。希望德慕格的祭司和学者们能充分发挥作用，稍加收敛目中无人的脾性。",
		ShowQuestId = "62912",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30613,
		Name = "会议记录，二",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "大祭司提出了反对意见，争执下，教宗震怒，大祭司愤然离去。\n教宗最终决定亲赴基塔布与骑士团汇合。尽管已经数次缺席会议，同行者名单里依然有大祭司的名字。\n从基塔布归来以后，教宗闭门不出，对这趟旅程只字不提。\n五日后，执事会突然宣布对大祭司维伦特处以极刑，并责令议会封存所有关于基塔布的讨论。",
		ShowQuestId = "62913",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30614,
		Name = "会议记录，三",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "「此处记载明显与其他会议记录的字体不同」：十名研究员带着教宗的密令离开赐福之地，去向不明。\n对伊迪斯暴动的镇压接连全军覆没……这绝不是偶然！德慕格的背后一定有某种力量在支持……\n需要增派更多人手，直到查明真相，以绝后患。",
		ShowQuestId = "62914",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30615,
		Name = "会议记录，四",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "犯人西奥多。年轻的德慕格话语之间对他的领袖极为忠诚。当这个朝气蓬勃的年轻人被折磨得掉光了头发，脱落了牙齿，脆弱到一个孩子都可以轻易折断他的脖子的时候，我们终于得到了理想的结果——维伦特刺杀教宗的计划确实早有预谋。\n犯人温斯顿。居内宫要职，与教会过从甚密，实为德慕格派秘密领袖之一。被情人出卖而暴露身份。审讯过程犯人极不配合。 精神崩溃，在问及叛徒维伦特妻小去向时，犯人咬舌自尽。\n 犯人罗施坦，维伦特的好友。对于老年人我们向来很有办法的。总之，这位维伦特信赖非凡的老友乖乖录下了维伦特女儿的去向，先驱者已开启追击。",
		ShowQuestId = "62915",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30616,
		Name = "审问记录",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "2次治疗，希金斯大人状态好转，恢复站立行走的体力。可他还是喝不下任何东西，很早就入睡了；清晨用药后，希金斯大人抱怨周身疼痛，午后开始难以进食，长时间昏睡；\n……希金斯大人醒了，说想出去散步，眉头紧锁，面色苍白；\n第5次治疗，希金斯大人不停地喊着「维伦特」的名字，可这位德慕格的大祭司不是早已经死了么？",
		ShowQuestId = "62916",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30617,
		Name = "隐秘的记录一",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "第7次治疗，希金斯大人的皮肤沿手臂至前胸开始大面积溃烂，嗓子里不停地发出痛苦的呻吟，似乎有许多话想说，但因为长期的缺水嗓子早已失声；\n希金斯大人陷入了昏迷，烂掉的身体遮盖在亚麻布下，散发着难闻的气味，另外像极了污秽的黑烟从他的身体上升腾，众內侍皆畏惧躲避，仅我一人侍候身前； \n上午时候希金斯大人醒了，到中午又开始胡言乱语，像祷告也像忏悔，我感到皮肤干燥瘙痒。可我绝不会背弃希金斯大人。为教会的尽忠，至死方休！",
		ShowQuestId = "62917",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30618,
		Name = "隐秘的记录二",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "第8次治疗……寝宫里笼罩着坟墓一样阴森荒凉的气氛，希金斯大人发出可怕的哀嚎声。而我的体貌和声音也在发生变化……神啊……请让伟大的教宗恢复他的力量吧……只有他能驱散污秽……驱散污秽……保佑我们这些卑微的教徒。",
		ShowQuestId = "62918",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30619,
		Name = "隐秘的记录三",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "那帮异族毕竟是野心勃勃而且难以驯化的，您这一路上的遭遇就是最好的证明，所以剩在基塔布的残余恐怕早晚也会成为祸患……\n……请允许我再向您透露一些内心最真实的想法……尽管我对那里面发生的事情一无所知，但那个男人口中的每一句话都掩饰不住一颗叛逆的心。三番四次对您的意志违抗不尊，无异于是对神地亵渎啊……",
		ShowQuestId = "62919",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30620,
		Name = "寝宫的信件",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "驱除污秽，防止赐福之地的衰落是历任教宗的宿命，可是站在这圣院的中心，我却感觉到那难以名状的恐怖已穿过大陆，来到了我的身边，它正一寸、一寸地爬满我的躯体……\n ……一旦信念崩塌，索拉斯大陆上的遗民该何去何从？我希金斯生无法带他们脱离苦难，至少死不能让他们信仰沦丧。这个真相无论如何是不能揭开的。\n 我的身体……该死！维伦特，是你吗？是你在诅咒我吗？不要纠缠我！……你想颠覆人的信仰……做梦！我要活下去，污秽伤害不了我，马吉安人伤害不了我，维伦特伤害不了我。我还活着，赐福之地还活着……",
		ShowQuestId = "62920",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30621,
		Name = "精美的笔记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "先民鬼斧神工造就的地下世界，被放逐的灵魂低诉着哀伤的秘密，洞悉的人沉入回忆的荒坟，与厄运拥眠。",
		ShowQuestId = "72900",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30701,
		Name = "地下溶洞",
		QuestSort = 7,
		QuestType = 5,
		NextQuestId = ""
	},
	{
		Description = "为什么我们非得在这种鬼地方看守？又脏又臭，稍一坐下就冻得浑身发抖……还被那些叫声吵得夜不能寐……\n被囚禁的家伙本来都被教宗判处了死刑……不知道那位大人私下留着他们想要做什么。",
		ShowQuestId = "72901",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30702,
		Name = "守卫的日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "终于看清了那个被单独关押的老头，从他身上披挂的破烂下面……天呐，他的手臂和小腿简直不能算是人类了。\n 那不过是白森森的骨头上还黏连着几丝肉筋罢了……",
		ShowQuestId = "72902",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30703,
		Name = "泛黄纸页",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "……那些浆果散发着一股生肉的腥味，隔着盔甲也能闻见。犯人吞食后，痛苦不堪，变得暴躁起来了。",
		ShowQuestId = "72903",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30704,
		Name = "潦草的记录",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "太令人兴奋了，这些嫩芽果然在这些犯人身上发生了作用……假如能找到方法来控制他们，我无疑就掌握了一种可在黑雾中自由穿行的利器……它们将帮助我带领可悲的人类脱离深渊，实现最终的目标……",
		ShowQuestId = "72904",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30705,
		Name = "一张破损的纸条",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "见了鬼了！这群犯人的四肢正在变长，肢体也在增大，脖子上面的光亮加速膨胀着，它们疯狂地砸着牢门，地牢眼看就要被它们冲破了……",
		ShowQuestId = "72905",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30706,
		Name = "监狱守卫的日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "维伦特一直在叫嚷着口渴……他似乎在找求一种特殊的东西，并对之产生了强烈的依赖，也许他身体的急速变化也跟这有关系，我一定要弄清楚到底是怎么回事……",
		ShowQuestId = "72906",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30707,
		Name = "潦草的速写",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "从维伦特的血液取样中会有好似污秽的成分，但与此同时他并未堕落……或许这就是他进入过巨像墓地后的变化。（以下字体无法辨认。）",
		ShowQuestId = "72907",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30708,
		Name = "字迹模糊的研究报告",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "希金斯已如同行尸走肉。果真！唯有我才是带领教会回归光荣的命定之人吶。神啊，谢谢你，我将歌颂你，赞美你，用我的灵魂侍奉你。\n只有我了，只有我能去打开那里……去接受赐福，去散播，信仰的种子！",
		ShowQuestId = "72908",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30709,
		Name = "艾克哈特的日记二",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "「那高耸入云的奇异山岩建筑，在暗夜上方狂风肆虐，几盏光柱交错，乘着风一半清新一半腐烂的空气扑鼻而来。嵌在岩石中的巨大柱体上刻着一些文字，只有马吉安人的族长能够读懂。 他用一种外人完全不能理解的语言念那些字，节奏可笑，可他的声音里有着掩饰不住的喜悦。」                                                                                                                                            \n……之后的几页都被维伦特那家伙撕掉了……该死，他到底藏着什么？！",
		ShowQuestId = "72909",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30710,
		Name = "艾克哈特的日记三",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "……这里只剩下他噩梦中的景象描述了——「厮杀声和悲号声至今仍在梦中回响。闭上眼睛，仿佛又置身在恐怖的地底世界，被那些长眠地下的幽魂追赶……硕大的扭曲的面孔，流泪的眼睛，血手……红发女孩一个个地倒下。穿铠甲的骑士和不穿鞋的马吉安战士如同野兽混作一团……」 \n可是究竟该如何打开巨像墓地……那下面到底有什么呢？维伦特和希金斯这两个蠢东西谁也没说出我想的答案！",
		ShowQuestId = "72910",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30711,
		Name = "艾克哈特的日记五",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "多么了不起的行为！真是令我大开眼界！我所受的煎熬和付出的一切努力，最终都成全了你的功劳……\n你和希金斯活在谎言背后，竟宣称自己代表了神？荒唐！可笑！",
		ShowQuestId = "72911",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30712,
		Name = "一封匿名信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "沉睡于深海的上古巨兽，无人勘破的千年记忆在此彷徨。灵魂的长河带来永恒的安宁，诅咒的宿命早已被人们遗忘。",
		ShowQuestId = "92900",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30901,
		Name = "伊西索亚",
		QuestSort = 9,
		QuestType = 5,
		NextQuestId = ""
	},
	{
		Description = "「……逃……」\n扭曲的红色字迹，留在帆布的一角。",
		ShowQuestId = "92901",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30902,
		Name = "破帆布",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "神或许是无私的，但人注定是自私的。\n弗拉梅尔不明白，我们发现的赐福之地不过是暂时的避难所，人们无法在那里真正地长久安居。\n即使穿越最深的黑雾，即使踏足最远的边界，先民古文中的传说之地，我一定会找到！",
		ShowQuestId = "92902",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30903,
		Name = "鳞纹日记一",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "我看到海了！这一定是受到了神的眷顾，如果不是加入公爵大人的队伍，我可能早已经被处死了。\n公爵真看得起我们，他居然想要教我们认字。\n博克那个笨蛋，我敢说他到现在认识的字超不过10个。\n不过那个克鲁格（Kluge），公爵大人真不该救他，他比我们所有人心眼都坏，毫无信仰可言，就该让他烂在赐福之地的下水道里。",
		ShowQuestId = "92903",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30904,
		Name = "李布的行军日记一",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "敬爱的主啊，我已无力拯救您的信徒，只能将他们安葬在这陌生的异乡。\n但请您放心，尽管邪恶的黑暗腐蚀了他们的肉体，但直到最后他们的内心依然忠于您，未曾喝下那异端的毒药。\n我祈求能够得到您的宽恕，赦免他们原来的罪。\n我会继续用那神圣的银钉传播您的福音，直到这场噩梦终结之时。",
		ShowQuestId = "92904",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30905,
		Name = "牧师的日记",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "公爵大人应该已经被那场风暴夺走了性命，那个满嘴信仰的牧师竟然也自杀了，污秽依然在船员间蔓延，他们的士气已经降到了谷底。\n我已经不愿再去思考这里究竟是什么地方，还有那些奇怪的住民到底想要干什么。\n光是处理队伍里发狂的家伙就已经够让人疲倦了，我不知道还能撑多久。\n但是我绝对不会放弃，那是懦夫的行为！",
		ShowQuestId = "92905",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30906,
		Name = "潦草的记录，一",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "那些废物们都在哀叹自己的时运不济，弱小的家伙们就是这样，只会人云亦云，没了那个自命清高的公爵，他们就是一群散沙，根本不会自寻出路。\n如果那些伊西索亚人带来的河水能够净化污秽，那还有什么好犹豫的呢？只要能够活下去，那狗屁的信仰和我有什么关系。",
		ShowQuestId = "92906",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30907,
		Name = "湿透的莎草纸",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "我感到时间正在眼前混乱地流动，灵魂与肉体被不断地撕扯着，抛向无尽的虚空。\n我看见那些犹如神明一般的庞然大物纷纷倒下，熄灭了原本永恒不灭的光芒。\n我看见原初无垢的生命静静地萌芽，迸发在孤独而又炙热的世界。\n在那巨响之后一切都走到了终点，一切又重新开始，而我却已经无处可去，只能飘流在这循环往复的轮回之中……",
		ShowQuestId = "92907",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30908,
		Name = "遗书",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "当罗切特找到公爵大人的时候，哦，现在想起那个画面我还是会忍不住激动颤抖，我简直不敢相信自己的眼睛！那一定是神迹！那些不曾相信神明存在的异端，是时候闭嘴了。\n不过，公爵大人现在还非常虚弱，持续高烧，身上布满着骇人的伤痕。\n更让人不忍的是，那些伤口里嵌满了坚硬的鳞片，很难清理干净。\n他一定是在那黑暗的深海中遭遇了某种生物可怕的袭击。\n得尽全力让他好起来。大家都沉默着做着自己的事情，但我知道他们现在都抱有和我一样的想法。",
		ShowQuestId = "92908",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30909,
		Name = "潦草的记录，二",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "那个叫亨德尔的家伙，我还记得他从海里被救回来的样子，挂满海草，面目难辨，满身的伤口惨不忍睹。\n不过，他的恢复能力着实让人感到惊讶。自从他醒来之后，才短短数日他就已经可以走动了，而那些致命的伤口也变成了坚硬的疤痕。\n但今天发生了一件奇怪的事情，同往常一样，当我遵从上面的旨意，给他送去艾宾浩斯圣露的时候，他那原本虚弱的眼神突然变得让人不寒而栗，就好像是饥渴的野兽。\n虽然只是一瞬间，但那眼神让人难以心安，我有一种不祥的预感……",
		ShowQuestId = "92909",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30910,
		Name = "风化的海砂板",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "死而复生究竟是什么样的感觉？说实话，直到现在我也无法说清。\n似乎是做了一场漫长而又痛苦的噩梦，在梦里我见到了沉入水底的太阳，它耀眼却又冰冷，周边围绕着可怕的巨兽。\n每当我回想起这场噩梦，一个声音就开始不停地呼唤着我的名字。\n现在它又开始了，而这一次我敢肯定，那个声音就在艾宾浩斯高高在上的城堡里。",
		ShowQuestId = "92910",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30911,
		Name = "鳞纹日记二",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "一个古怪的老者带着一群人粗暴地踹开了我的房门，他自称古德里安，是这里的司祭。\n他似乎对我的一切都抱有怀疑，我耐心地向他说明了一切。奇怪的是当我说出“赐福之地”这几个字的时候，他一直木然的表情突然变得扭曲起来，接着他同随行的几人耳语了几句，便拂袖而去。\n……艾宾浩斯……我似乎在哪里听说过他的名字，这里的人们都对他抱有狂热的崇敬，但不同于赐福之地，那并不是基于神的威严。\n这个地方太不寻常，所有人似乎都在隐瞒着什么，而且我感觉到有人一直在监视我的一举一动。",
		ShowQuestId = "92911",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30912,
		Name = "鳞纹日记三",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "我的脑子里充斥着奇怪的恶念，那些巨像在我眼前不断浮现，它们静止不动地仰望着幽蓝色的天际，那似乎就是我一直追寻的传说之地。\n它不会放过我，不会放过我们！我已经听不到任何声音，除了那始终回荡在耳边的低语。\n杀了艾宾浩斯……把它夺回来！杀了艾宾浩斯……把它夺回来！\n我现在就应该把笔放下，遵从它的意志，把我的一切奉献给赐予我生命的主人！",
		ShowQuestId = "92912",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30913,
		Name = "鳞纹日记四",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "我已经喝下了足够多的浸灵河水，为什么那个可怕的影子总是挥之不去，它让我回想起那些曾经追逐着伊西索亚的巨兽，难道它们又回来了？我不想被当成一个疯子，但我有责任把这件事告诉古德里安大人。",
		ShowQuestId = "92913",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30914,
		Name = "碎裂的莎草纸",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "幸好公爵大人让我们提前有所准备，才让大家免遭那些清道夫的毒手。\n虽然他们都是狠角色，但我们也不是吃素的。\n接下来，他们一定会派更多的力量来围剿我们，公爵大人一定是意识到了什么，我从未见过他如此慌张，必须尽快找到他，然后离开这里。",
		ShowQuestId = "92914",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30915,
		Name = "李布的行军日记二",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "静默之墙外死一般的寂静，偶尔传来声凄厉恐怖的尖叫，大家脆弱的神经几乎难以承受。\n那些疯人船上的家伙为什么还没有被消灭干净？离开了浸灵河水，他们早就应该抵挡不住污秽的侵蚀。\n我们已经牺牲了太多，那些没有来得及逃回来的和自愿成为清道夫的同胞们，我会为你们祈祷，希望这场苦难能够早点过去吧。",
		ShowQuestId = "92915",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30916,
		Name = "古旧的鱼皮纸",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "艾宾浩斯大人为卑微的我们打开了一条道路，让我们在这世间痛苦的夹缝中寻得安乐。\n他清除了一切欲望的烦忧，引领我们走向智慧，走向平和，走向仁爱，不再忧虑，远离战火，请让他永远领导伊西索亚吧，我愿为此奉献一切。",
		ShowQuestId = "92916",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30917,
		Name = "伊西索亚祷文",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "永无止尽的逃亡，最终还是来到了终点。它终于还是找到了这里。\n我内心唯一的不安却被这个孩子触动了，他倒在血泊之中不断地质问我，这一切究竟有什么意义？\n可我无法给他一个答案。\n我们从那里盗走的三颗耶库伯之印孕育了萨马罗萨的文明与历史。\n然而痛苦与杀戮也随之诞生，无垢的纯洁从此附上了原罪的烙印。\n堕落早已无可避免，但只要能够守住这一颗破碎的耶库伯之印，黑暗就不会褪去，轮回依旧存续。\n这一次，我所能做的只有让他遗忘一切，离开这里。",
		ShowQuestId = "92917",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30918,
		Name = "蚀刻长卷",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "马特已经疯了，他说在自己家里看见了一个和他长得一模一样的家伙，可等我们到了那，却只看见一具面目模糊的躯体，已经失去了气息。从他的身体里不断地冒出黑色的恶臭的液体，没人知道那家伙到底是谁，而在那件事发生以后，伊西索亚的每个人依然都按部就班地过着自己的日子。没过多久之后，马特就被人带走了，据说是去接受艾宾浩斯大人的治疗。也许是因为见到这样令人害怕的景象，最近我也开始做梦，梦见一个和我一样的人，只是从他的眼里不停地流出黑色的泪水……",
		ShowQuestId = "92918",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30919,
		Name = "发黑的纸卷",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "……那只怪物从高处跳进了成群的清道夫中，肆意挥舞着那把血红的巨剑，我从未见过那样巨大的武器，清道夫们坚硬的盔甲，在它面前就好像陶片般一击即碎。一切都太疯狂了，任何阻挡在它面前的东西都被砸得稀巴烂，即使不断地增派援兵也无济于事，我们只能眼睁睁地看着它冲破封锁，走向艾宾浩斯大人的居所。在那震耳欲聋的嘶吼中，我分明听见了嗜杀的笑声，它正陷入一场只属于自己的狂欢……",
		ShowQuestId = "92919",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30920,
		Name = "沾泥的书柬",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "只能把剩下的孩子们送进这些活棺材里了，从没想到会走到这一步，这疯狂的罪名就由我来背负吧。\n那些疯人船上的家伙本来不足为惧，可有些事情超出了计划。\n无论如何，不能再让任何人通过静默之墙了，只要能阻挡剩下的鼠辈，艾宾浩斯大人就还有余力应付这场危机。\n当然，我也不会置身世外，永别了，卡罗琳，希望我们还能相见，希望你能理解我的苦衷。",
		ShowQuestId = "92922",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30923,
		Name = "古德里安的鱼皮书",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "自从那声巨响之后，我已经记不清有多久没喝到浸灵河水。头越来越沉，嘴唇也已经干裂的不像话，连呼吸都会撕裂出新的伤口。\n外面已经听不见武器碰撞的声音，艾宾浩斯大人应该已经把那些家伙解决了吧，我快忍不住了，今天我一定要喝上一口，谁都别想拦住我。",
		ShowQuestId = "92923",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30924,
		Name = "螺纹壳板",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "即刻起，禁止伊西索亚住民接近并饮用被污染的浸灵河水，每日定量分发库存河水。\n如有违者，格杀勿论。",
		ShowQuestId = "92924",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30925,
		Name = "密令",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "当第一面旗帜插上赐福之地的土地，于黑雾中流浪的人们终于找到了自己永居的圣城。\n接着，空无一物的旗面被绘上代表信仰的徽记，神便诞生了。\n至于赐福之地的过去，只需存于那令人不安的异端邪说中便足够了。",
		ShowQuestId = "92925",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30926,
		Name = "烫金的宝物记录",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "亲爱卡罗琳女士：冒昧给您写下这封唐突的信件。我们即将成为清道夫，成为守护伊西索亚的最坚实的盾。\n但在此之前，我们依然是一名父亲或者一名母亲，我们自愿牺牲一切，为的就是让这些孩子们拥有一个未来，就像艾宾浩斯大人曾经给予绝望的我们一个安身之所。\n世界从未公平过，尤其是对我们而言。每当想起这些孩子们可能没有机会经历他们自己的人生，我们内心便无法安宁。\n如果连他们的未来都无法守护，那将是整个伊西索亚最大的失败。\n虽然我们未曾谋面，但在即将舍弃肉身遗忘一切之前，希望您能答应我们，无论如何守护好他们，守护好伊西索亚的未来。\n一个父亲、母亲",
		ShowQuestId = "92926",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30927,
		Name = "无名的短信",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "在那场爆炸之后，我的记忆就开始慢慢模糊，翻看曾经的记录，那些事情对我来说都是如此陌生。\n我必须在彻底忘记一切之前，把能想到的一切都记录下来。\n我们都太过大意了，直到最后才发现这令人恐惧的事实。\n这里的人们，包括我们都被这该死的浸灵河水控制了……没法离开这里。\n还有那个与艾宾浩斯不停战斗的怪物究竟是什么？我们已经溃不成军，无力再做反抗，静默之墙彻底关上了，我们将被永远地困在了这里。\n伊西索亚再一次发出了哀鸣，公爵大人你到底在哪？",
		ShowQuestId = "92927",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30928,
		Name = "李布的行军日记三",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "萨马罗萨每年一度的灼火节，我们再次集结于源流之塔下聆听艾宾浩斯大人的教诲。\n为了纪念那些曾经与黑暗抗争，抵御来自深海诅咒的亡者们。\n虽然我们已经许久未曾见过他，但他的声音依然犹如温暖的火苗，照亮我们每一个人的内心。\n仿佛是受到了某种召唤，我们不由自主地列成长队，行走在无尽的台阶之上，享受着秩序给我们带来的安宁，一切的伤痛正在慢慢地退却。",
		ShowQuestId = "92928",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30929,
		Name = "碎裂的泥板",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "贪婪的<color=#DBBA7FFF>人类</color>冲锋在前，为我最信任的<color=#DBBA7FFF>子民</color>开辟通往宝库大门的道路。\n即使<color=#DBBA7FFF>巨像</color>的微光早已在身后不见踪影，只要击败阻挡在<color=#DBBA7FFF>大门</color>之前的<color=#DBBA7FFF>赫吉</color>，金色的大门就将重新敞开。",
		ShowQuestId = "92929",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30930,
		Name = "宝库之主的试炼",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	},
	{
		Description = "古籍的文字与赐福之地的文字颇为相似，但又有些不同，只能勉强读懂只言片语。\n「……从四方汇聚而来，但却早已不分彼此。不再因为理念互相仇恨，不再因为不公忍气吞声……在这里我们找到了自己真正的价值……从未低人一等。\n伊西索亚是一个理想国，它包容一切，信仰不再是束缚自由灵魂的枷锁……抛却世俗……终于都成为了真正的 ‘人’ ，也将是最后的‘人’。只要我们谨记肩负的使命……追随艾宾浩斯大人……忍耐，直到黑夜彻底过去。」",
		ShowQuestId = "92930",
		DLCQuest = 0,
		CompleteQuestId = "",
		QuestId = 30931,
		Name = "残缺的古籍",
		QuestSort = 0,
		QuestType = 6,
		NextQuestId = ""
	}
}
