-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Protocol/Protobuf/BattleStage_pb.lua

local protobuf = require("protobuf/protobuf")

module("LuaScript/Protocol/Protobuf/BattleStage_pb")

STAGETASK = protobuf.Descriptor()

local STAGETASK_STAGENO_FIELD = protobuf.FieldDescriptor()
local STAGETASK_STAGETASKNO_FIELD = protobuf.FieldDescriptor()

STAGESAVEDATA = protobuf.Descriptor()

local STAGESAVEDATA_STAGENO_FIELD = protobuf.FieldDescriptor()
local STAGESAVEDATA_SAVEPOINT_FIELD = protobuf.FieldDescriptor()
local STAGESAVEDATA_SAVETIME_FIELD = protobuf.FieldDescriptor()
local STAGESAVEDATA_STAGETASKS_FIELD = protobuf.FieldDescriptor()

REQSAVESTAGE = protobuf.Descriptor()

local REQSAVESTAGE_STAGENO_FIELD = protobuf.FieldDescriptor()
local REQSAVESTAGE_SAVEPOINT_FIELD = protobuf.FieldDescriptor()
local REQSAVESTAGE_SAVETIME_FIELD = protobuf.FieldDescriptor()
local REQSAVESTAGE_SIGN_FIELD = protobuf.FieldDescriptor()
local REQSAVESTAGE_STAGETASKNO_FIELD = protobuf.FieldDescriptor()

RESPSAVESTAGEDONE = protobuf.Descriptor()
STAGETASK_STAGENO_FIELD.name = "stageNo"
STAGETASK_STAGENO_FIELD.full_name = ".StageTask.stageNo"
STAGETASK_STAGENO_FIELD.number = 1
STAGETASK_STAGENO_FIELD.index = 0
STAGETASK_STAGENO_FIELD.label = 2
STAGETASK_STAGENO_FIELD.has_default_value = false
STAGETASK_STAGENO_FIELD.default_value = 0
STAGETASK_STAGENO_FIELD.type = 13
STAGETASK_STAGENO_FIELD.cpp_type = 3
STAGETASK_STAGETASKNO_FIELD.name = "stageTaskNo"
STAGETASK_STAGETASKNO_FIELD.full_name = ".StageTask.stageTaskNo"
STAGETASK_STAGETASKNO_FIELD.number = 2
STAGETASK_STAGETASKNO_FIELD.index = 1
STAGETASK_STAGETASKNO_FIELD.label = 3
STAGETASK_STAGETASKNO_FIELD.has_default_value = false
STAGETASK_STAGETASKNO_FIELD.default_value = {}
STAGETASK_STAGETASKNO_FIELD.type = 13
STAGETASK_STAGETASKNO_FIELD.cpp_type = 3
STAGETASK.name = "StageTask"
STAGETASK.full_name = ".StageTask"
STAGETASK.nested_types = {}
STAGETASK.enum_types = {}
STAGETASK.fields = {
	STAGETASK_STAGENO_FIELD,
	STAGETASK_STAGETASKNO_FIELD
}
STAGETASK.is_extendable = false
STAGETASK.extensions = {}
STAGESAVEDATA_STAGENO_FIELD.name = "stageNo"
STAGESAVEDATA_STAGENO_FIELD.full_name = ".StageSaveData.stageNo"
STAGESAVEDATA_STAGENO_FIELD.number = 1
STAGESAVEDATA_STAGENO_FIELD.index = 0
STAGESAVEDATA_STAGENO_FIELD.label = 2
STAGESAVEDATA_STAGENO_FIELD.has_default_value = false
STAGESAVEDATA_STAGENO_FIELD.default_value = 0
STAGESAVEDATA_STAGENO_FIELD.type = 13
STAGESAVEDATA_STAGENO_FIELD.cpp_type = 3
STAGESAVEDATA_SAVEPOINT_FIELD.name = "savePoint"
STAGESAVEDATA_SAVEPOINT_FIELD.full_name = ".StageSaveData.savePoint"
STAGESAVEDATA_SAVEPOINT_FIELD.number = 2
STAGESAVEDATA_SAVEPOINT_FIELD.index = 1
STAGESAVEDATA_SAVEPOINT_FIELD.label = 2
STAGESAVEDATA_SAVEPOINT_FIELD.has_default_value = false
STAGESAVEDATA_SAVEPOINT_FIELD.default_value = 0
STAGESAVEDATA_SAVEPOINT_FIELD.type = 13
STAGESAVEDATA_SAVEPOINT_FIELD.cpp_type = 3
STAGESAVEDATA_SAVETIME_FIELD.name = "saveTime"
STAGESAVEDATA_SAVETIME_FIELD.full_name = ".StageSaveData.saveTime"
STAGESAVEDATA_SAVETIME_FIELD.number = 3
STAGESAVEDATA_SAVETIME_FIELD.index = 2
STAGESAVEDATA_SAVETIME_FIELD.label = 2
STAGESAVEDATA_SAVETIME_FIELD.has_default_value = false
STAGESAVEDATA_SAVETIME_FIELD.default_value = 0
STAGESAVEDATA_SAVETIME_FIELD.type = 13
STAGESAVEDATA_SAVETIME_FIELD.cpp_type = 3
STAGESAVEDATA_STAGETASKS_FIELD.name = "stageTasks"
STAGESAVEDATA_STAGETASKS_FIELD.full_name = ".StageSaveData.stageTasks"
STAGESAVEDATA_STAGETASKS_FIELD.number = 4
STAGESAVEDATA_STAGETASKS_FIELD.index = 3
STAGESAVEDATA_STAGETASKS_FIELD.label = 3
STAGESAVEDATA_STAGETASKS_FIELD.has_default_value = false
STAGESAVEDATA_STAGETASKS_FIELD.default_value = {}
STAGESAVEDATA_STAGETASKS_FIELD.message_type = STAGETASK
STAGESAVEDATA_STAGETASKS_FIELD.type = 11
STAGESAVEDATA_STAGETASKS_FIELD.cpp_type = 10
STAGESAVEDATA.name = "StageSaveData"
STAGESAVEDATA.full_name = ".StageSaveData"
STAGESAVEDATA.nested_types = {}
STAGESAVEDATA.enum_types = {}
STAGESAVEDATA.fields = {
	STAGESAVEDATA_STAGENO_FIELD,
	STAGESAVEDATA_SAVEPOINT_FIELD,
	STAGESAVEDATA_SAVETIME_FIELD,
	STAGESAVEDATA_STAGETASKS_FIELD
}
STAGESAVEDATA.is_extendable = false
STAGESAVEDATA.extensions = {}
REQSAVESTAGE_STAGENO_FIELD.name = "stageNo"
REQSAVESTAGE_STAGENO_FIELD.full_name = ".ReqSaveStage.stageNo"
REQSAVESTAGE_STAGENO_FIELD.number = 1
REQSAVESTAGE_STAGENO_FIELD.index = 0
REQSAVESTAGE_STAGENO_FIELD.label = 2
REQSAVESTAGE_STAGENO_FIELD.has_default_value = false
REQSAVESTAGE_STAGENO_FIELD.default_value = 0
REQSAVESTAGE_STAGENO_FIELD.type = 13
REQSAVESTAGE_STAGENO_FIELD.cpp_type = 3
REQSAVESTAGE_SAVEPOINT_FIELD.name = "savePoint"
REQSAVESTAGE_SAVEPOINT_FIELD.full_name = ".ReqSaveStage.savePoint"
REQSAVESTAGE_SAVEPOINT_FIELD.number = 2
REQSAVESTAGE_SAVEPOINT_FIELD.index = 1
REQSAVESTAGE_SAVEPOINT_FIELD.label = 2
REQSAVESTAGE_SAVEPOINT_FIELD.has_default_value = false
REQSAVESTAGE_SAVEPOINT_FIELD.default_value = 0
REQSAVESTAGE_SAVEPOINT_FIELD.type = 13
REQSAVESTAGE_SAVEPOINT_FIELD.cpp_type = 3
REQSAVESTAGE_SAVETIME_FIELD.name = "saveTime"
REQSAVESTAGE_SAVETIME_FIELD.full_name = ".ReqSaveStage.saveTime"
REQSAVESTAGE_SAVETIME_FIELD.number = 3
REQSAVESTAGE_SAVETIME_FIELD.index = 2
REQSAVESTAGE_SAVETIME_FIELD.label = 2
REQSAVESTAGE_SAVETIME_FIELD.has_default_value = false
REQSAVESTAGE_SAVETIME_FIELD.default_value = 0
REQSAVESTAGE_SAVETIME_FIELD.type = 13
REQSAVESTAGE_SAVETIME_FIELD.cpp_type = 3
REQSAVESTAGE_SIGN_FIELD.name = "sign"
REQSAVESTAGE_SIGN_FIELD.full_name = ".ReqSaveStage.sign"
REQSAVESTAGE_SIGN_FIELD.number = 4
REQSAVESTAGE_SIGN_FIELD.index = 3
REQSAVESTAGE_SIGN_FIELD.label = 2
REQSAVESTAGE_SIGN_FIELD.has_default_value = false
REQSAVESTAGE_SIGN_FIELD.default_value = ""
REQSAVESTAGE_SIGN_FIELD.type = 9
REQSAVESTAGE_SIGN_FIELD.cpp_type = 9
REQSAVESTAGE_STAGETASKNO_FIELD.name = "stageTaskNo"
REQSAVESTAGE_STAGETASKNO_FIELD.full_name = ".ReqSaveStage.stageTaskNo"
REQSAVESTAGE_STAGETASKNO_FIELD.number = 5
REQSAVESTAGE_STAGETASKNO_FIELD.index = 4
REQSAVESTAGE_STAGETASKNO_FIELD.label = 3
REQSAVESTAGE_STAGETASKNO_FIELD.has_default_value = false
REQSAVESTAGE_STAGETASKNO_FIELD.default_value = {}
REQSAVESTAGE_STAGETASKNO_FIELD.type = 13
REQSAVESTAGE_STAGETASKNO_FIELD.cpp_type = 3
REQSAVESTAGE.name = "ReqSaveStage"
REQSAVESTAGE.full_name = ".ReqSaveStage"
REQSAVESTAGE.nested_types = {}
REQSAVESTAGE.enum_types = {}
REQSAVESTAGE.fields = {
	REQSAVESTAGE_STAGENO_FIELD,
	REQSAVESTAGE_SAVEPOINT_FIELD,
	REQSAVESTAGE_SAVETIME_FIELD,
	REQSAVESTAGE_SIGN_FIELD,
	REQSAVESTAGE_STAGETASKNO_FIELD
}
REQSAVESTAGE.is_extendable = false
REQSAVESTAGE.extensions = {}
RESPSAVESTAGEDONE.name = "RespSaveStageDone"
RESPSAVESTAGEDONE.full_name = ".RespSaveStageDone"
RESPSAVESTAGEDONE.nested_types = {}
RESPSAVESTAGEDONE.enum_types = {}
RESPSAVESTAGEDONE.fields = {}
RESPSAVESTAGEDONE.is_extendable = false
RESPSAVESTAGEDONE.extensions = {}
ReqSaveStage = protobuf.Message(REQSAVESTAGE)
RespSaveStageDone = protobuf.Message(RESPSAVESTAGEDONE)
StageSaveData = protobuf.Message(STAGESAVEDATA)
StageTask = protobuf.Message(STAGETASK)
