-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Protocol/Protobuf/BattleBattle_pb.lua

local protobuf = require("protobuf/protobuf")

module("LuaScript/Protocol/Protobuf/BattleBattle_pb")

FRAMEDATA = protobuf.Descriptor()

local FRAMEDATA_USERID_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_ISPREDICTED_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_MOVEX_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_MOVEY_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_MOVEZ_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_ACTION_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_ACTIONX_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_ACTIONY_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_TARGETX_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_TARGETY_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_TARGETZ_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_LOCKID_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_ACTIONASSIST_FIELD = protobuf.FieldDescriptor()
local FRAMEDATA_ACTIONITEM_FIELD = protobuf.FieldDescriptor()

FRAMEPACKET = protobuf.Descriptor()

local FRAMEPACKET_INDEX_FIELD = protobuf.FieldDescriptor()
local FRAMEPACKET_FRAMES_FIELD = protobuf.FieldDescriptor()

REQFRAME = protobuf.Descriptor()

local REQFRAME_FRAMEPACKET_FIELD = protobuf.FieldDescriptor()

RESPFRAME = protobuf.Descriptor()

local RESPFRAME_FRAMEPACKET_FIELD = protobuf.FieldDescriptor()

FRAMEDATA_USERID_FIELD.name = "userId"
FRAMEDATA_USERID_FIELD.full_name = ".FrameData.userId"
FRAMEDATA_USERID_FIELD.number = 1
FRAMEDATA_USERID_FIELD.index = 0
FRAMEDATA_USERID_FIELD.label = 2
FRAMEDATA_USERID_FIELD.has_default_value = false
FRAMEDATA_USERID_FIELD.default_value = 0
FRAMEDATA_USERID_FIELD.type = 13
FRAMEDATA_USERID_FIELD.cpp_type = 3
FRAMEDATA_ISPREDICTED_FIELD.name = "isPredicted"
FRAMEDATA_ISPREDICTED_FIELD.full_name = ".FrameData.isPredicted"
FRAMEDATA_ISPREDICTED_FIELD.number = 2
FRAMEDATA_ISPREDICTED_FIELD.index = 1
FRAMEDATA_ISPREDICTED_FIELD.label = 1
FRAMEDATA_ISPREDICTED_FIELD.has_default_value = false
FRAMEDATA_ISPREDICTED_FIELD.default_value = false
FRAMEDATA_ISPREDICTED_FIELD.type = 8
FRAMEDATA_ISPREDICTED_FIELD.cpp_type = 7
FRAMEDATA_MOVEX_FIELD.name = "moveX"
FRAMEDATA_MOVEX_FIELD.full_name = ".FrameData.moveX"
FRAMEDATA_MOVEX_FIELD.number = 3
FRAMEDATA_MOVEX_FIELD.index = 2
FRAMEDATA_MOVEX_FIELD.label = 1
FRAMEDATA_MOVEX_FIELD.has_default_value = false
FRAMEDATA_MOVEX_FIELD.default_value = 0
FRAMEDATA_MOVEX_FIELD.type = 5
FRAMEDATA_MOVEX_FIELD.cpp_type = 1
FRAMEDATA_MOVEY_FIELD.name = "moveY"
FRAMEDATA_MOVEY_FIELD.full_name = ".FrameData.moveY"
FRAMEDATA_MOVEY_FIELD.number = 4
FRAMEDATA_MOVEY_FIELD.index = 3
FRAMEDATA_MOVEY_FIELD.label = 1
FRAMEDATA_MOVEY_FIELD.has_default_value = false
FRAMEDATA_MOVEY_FIELD.default_value = 0
FRAMEDATA_MOVEY_FIELD.type = 5
FRAMEDATA_MOVEY_FIELD.cpp_type = 1
FRAMEDATA_MOVEZ_FIELD.name = "moveZ"
FRAMEDATA_MOVEZ_FIELD.full_name = ".FrameData.moveZ"
FRAMEDATA_MOVEZ_FIELD.number = 5
FRAMEDATA_MOVEZ_FIELD.index = 4
FRAMEDATA_MOVEZ_FIELD.label = 1
FRAMEDATA_MOVEZ_FIELD.has_default_value = false
FRAMEDATA_MOVEZ_FIELD.default_value = 0
FRAMEDATA_MOVEZ_FIELD.type = 5
FRAMEDATA_MOVEZ_FIELD.cpp_type = 1
FRAMEDATA_ACTION_FIELD.name = "action"
FRAMEDATA_ACTION_FIELD.full_name = ".FrameData.action"
FRAMEDATA_ACTION_FIELD.number = 6
FRAMEDATA_ACTION_FIELD.index = 5
FRAMEDATA_ACTION_FIELD.label = 1
FRAMEDATA_ACTION_FIELD.has_default_value = false
FRAMEDATA_ACTION_FIELD.default_value = 0
FRAMEDATA_ACTION_FIELD.type = 5
FRAMEDATA_ACTION_FIELD.cpp_type = 1
FRAMEDATA_ACTIONX_FIELD.name = "actionX"
FRAMEDATA_ACTIONX_FIELD.full_name = ".FrameData.actionX"
FRAMEDATA_ACTIONX_FIELD.number = 7
FRAMEDATA_ACTIONX_FIELD.index = 6
FRAMEDATA_ACTIONX_FIELD.label = 1
FRAMEDATA_ACTIONX_FIELD.has_default_value = false
FRAMEDATA_ACTIONX_FIELD.default_value = 0
FRAMEDATA_ACTIONX_FIELD.type = 5
FRAMEDATA_ACTIONX_FIELD.cpp_type = 1
FRAMEDATA_ACTIONY_FIELD.name = "actionY"
FRAMEDATA_ACTIONY_FIELD.full_name = ".FrameData.actionY"
FRAMEDATA_ACTIONY_FIELD.number = 8
FRAMEDATA_ACTIONY_FIELD.index = 7
FRAMEDATA_ACTIONY_FIELD.label = 1
FRAMEDATA_ACTIONY_FIELD.has_default_value = false
FRAMEDATA_ACTIONY_FIELD.default_value = 0
FRAMEDATA_ACTIONY_FIELD.type = 5
FRAMEDATA_ACTIONY_FIELD.cpp_type = 1
FRAMEDATA_TARGETX_FIELD.name = "targetX"
FRAMEDATA_TARGETX_FIELD.full_name = ".FrameData.targetX"
FRAMEDATA_TARGETX_FIELD.number = 9
FRAMEDATA_TARGETX_FIELD.index = 8
FRAMEDATA_TARGETX_FIELD.label = 1
FRAMEDATA_TARGETX_FIELD.has_default_value = false
FRAMEDATA_TARGETX_FIELD.default_value = 0
FRAMEDATA_TARGETX_FIELD.type = 5
FRAMEDATA_TARGETX_FIELD.cpp_type = 1
FRAMEDATA_TARGETY_FIELD.name = "targetY"
FRAMEDATA_TARGETY_FIELD.full_name = ".FrameData.targetY"
FRAMEDATA_TARGETY_FIELD.number = 10
FRAMEDATA_TARGETY_FIELD.index = 9
FRAMEDATA_TARGETY_FIELD.label = 1
FRAMEDATA_TARGETY_FIELD.has_default_value = false
FRAMEDATA_TARGETY_FIELD.default_value = 0
FRAMEDATA_TARGETY_FIELD.type = 5
FRAMEDATA_TARGETY_FIELD.cpp_type = 1
FRAMEDATA_TARGETZ_FIELD.name = "targetZ"
FRAMEDATA_TARGETZ_FIELD.full_name = ".FrameData.targetZ"
FRAMEDATA_TARGETZ_FIELD.number = 11
FRAMEDATA_TARGETZ_FIELD.index = 10
FRAMEDATA_TARGETZ_FIELD.label = 1
FRAMEDATA_TARGETZ_FIELD.has_default_value = false
FRAMEDATA_TARGETZ_FIELD.default_value = 0
FRAMEDATA_TARGETZ_FIELD.type = 5
FRAMEDATA_TARGETZ_FIELD.cpp_type = 1
FRAMEDATA_LOCKID_FIELD.name = "lockId"
FRAMEDATA_LOCKID_FIELD.full_name = ".FrameData.lockId"
FRAMEDATA_LOCKID_FIELD.number = 12
FRAMEDATA_LOCKID_FIELD.index = 11
FRAMEDATA_LOCKID_FIELD.label = 1
FRAMEDATA_LOCKID_FIELD.has_default_value = false
FRAMEDATA_LOCKID_FIELD.default_value = 0
FRAMEDATA_LOCKID_FIELD.type = 5
FRAMEDATA_LOCKID_FIELD.cpp_type = 1
FRAMEDATA_ACTIONASSIST_FIELD.name = "actionAssist"
FRAMEDATA_ACTIONASSIST_FIELD.full_name = ".FrameData.actionAssist"
FRAMEDATA_ACTIONASSIST_FIELD.number = 13
FRAMEDATA_ACTIONASSIST_FIELD.index = 12
FRAMEDATA_ACTIONASSIST_FIELD.label = 1
FRAMEDATA_ACTIONASSIST_FIELD.has_default_value = false
FRAMEDATA_ACTIONASSIST_FIELD.default_value = 0
FRAMEDATA_ACTIONASSIST_FIELD.type = 5
FRAMEDATA_ACTIONASSIST_FIELD.cpp_type = 1
FRAMEDATA_ACTIONITEM_FIELD.name = "actionItem"
FRAMEDATA_ACTIONITEM_FIELD.full_name = ".FrameData.actionItem"
FRAMEDATA_ACTIONITEM_FIELD.number = 14
FRAMEDATA_ACTIONITEM_FIELD.index = 13
FRAMEDATA_ACTIONITEM_FIELD.label = 1
FRAMEDATA_ACTIONITEM_FIELD.has_default_value = false
FRAMEDATA_ACTIONITEM_FIELD.default_value = 0
FRAMEDATA_ACTIONITEM_FIELD.type = 5
FRAMEDATA_ACTIONITEM_FIELD.cpp_type = 1
FRAMEDATA.name = "FrameData"
FRAMEDATA.full_name = ".FrameData"
FRAMEDATA.nested_types = {}
FRAMEDATA.enum_types = {}
FRAMEDATA.fields = {
	FRAMEDATA_USERID_FIELD,
	FRAMEDATA_ISPREDICTED_FIELD,
	FRAMEDATA_MOVEX_FIELD,
	FRAMEDATA_MOVEY_FIELD,
	FRAMEDATA_MOVEZ_FIELD,
	FRAMEDATA_ACTION_FIELD,
	FRAMEDATA_ACTIONX_FIELD,
	FRAMEDATA_ACTIONY_FIELD,
	FRAMEDATA_TARGETX_FIELD,
	FRAMEDATA_TARGETY_FIELD,
	FRAMEDATA_TARGETZ_FIELD,
	FRAMEDATA_LOCKID_FIELD,
	FRAMEDATA_ACTIONASSIST_FIELD,
	FRAMEDATA_ACTIONITEM_FIELD
}
FRAMEDATA.is_extendable = false
FRAMEDATA.extensions = {}
FRAMEPACKET_INDEX_FIELD.name = "index"
FRAMEPACKET_INDEX_FIELD.full_name = ".FramePacket.index"
FRAMEPACKET_INDEX_FIELD.number = 1
FRAMEPACKET_INDEX_FIELD.index = 0
FRAMEPACKET_INDEX_FIELD.label = 2
FRAMEPACKET_INDEX_FIELD.has_default_value = false
FRAMEPACKET_INDEX_FIELD.default_value = 0
FRAMEPACKET_INDEX_FIELD.type = 13
FRAMEPACKET_INDEX_FIELD.cpp_type = 3
FRAMEPACKET_FRAMES_FIELD.name = "frames"
FRAMEPACKET_FRAMES_FIELD.full_name = ".FramePacket.frames"
FRAMEPACKET_FRAMES_FIELD.number = 2
FRAMEPACKET_FRAMES_FIELD.index = 1
FRAMEPACKET_FRAMES_FIELD.label = 3
FRAMEPACKET_FRAMES_FIELD.has_default_value = false
FRAMEPACKET_FRAMES_FIELD.default_value = {}
FRAMEPACKET_FRAMES_FIELD.message_type = FRAMEDATA
FRAMEPACKET_FRAMES_FIELD.type = 11
FRAMEPACKET_FRAMES_FIELD.cpp_type = 10
FRAMEPACKET.name = "FramePacket"
FRAMEPACKET.full_name = ".FramePacket"
FRAMEPACKET.nested_types = {}
FRAMEPACKET.enum_types = {}
FRAMEPACKET.fields = {
	FRAMEPACKET_INDEX_FIELD,
	FRAMEPACKET_FRAMES_FIELD
}
FRAMEPACKET.is_extendable = false
FRAMEPACKET.extensions = {}
REQFRAME_FRAMEPACKET_FIELD.name = "framePacket"
REQFRAME_FRAMEPACKET_FIELD.full_name = ".ReqFrame.framePacket"
REQFRAME_FRAMEPACKET_FIELD.number = 1
REQFRAME_FRAMEPACKET_FIELD.index = 0
REQFRAME_FRAMEPACKET_FIELD.label = 2
REQFRAME_FRAMEPACKET_FIELD.has_default_value = false
REQFRAME_FRAMEPACKET_FIELD.default_value = nil
REQFRAME_FRAMEPACKET_FIELD.message_type = FRAMEPACKET
REQFRAME_FRAMEPACKET_FIELD.type = 11
REQFRAME_FRAMEPACKET_FIELD.cpp_type = 10
REQFRAME.name = "ReqFrame"
REQFRAME.full_name = ".ReqFrame"
REQFRAME.nested_types = {}
REQFRAME.enum_types = {}
REQFRAME.fields = {
	REQFRAME_FRAMEPACKET_FIELD
}
REQFRAME.is_extendable = false
REQFRAME.extensions = {}
RESPFRAME_FRAMEPACKET_FIELD.name = "framePacket"
RESPFRAME_FRAMEPACKET_FIELD.full_name = ".RespFrame.framePacket"
RESPFRAME_FRAMEPACKET_FIELD.number = 1
RESPFRAME_FRAMEPACKET_FIELD.index = 0
RESPFRAME_FRAMEPACKET_FIELD.label = 3
RESPFRAME_FRAMEPACKET_FIELD.has_default_value = false
RESPFRAME_FRAMEPACKET_FIELD.default_value = {}
RESPFRAME_FRAMEPACKET_FIELD.message_type = FRAMEPACKET
RESPFRAME_FRAMEPACKET_FIELD.type = 11
RESPFRAME_FRAMEPACKET_FIELD.cpp_type = 10
RESPFRAME.name = "RespFrame"
RESPFRAME.full_name = ".RespFrame"
RESPFRAME.nested_types = {}
RESPFRAME.enum_types = {}
RESPFRAME.fields = {
	RESPFRAME_FRAMEPACKET_FIELD
}
RESPFRAME.is_extendable = false
RESPFRAME.extensions = {}
FrameData = protobuf.Message(FRAMEDATA)
FramePacket = protobuf.Message(FRAMEPACKET)
ReqFrame = protobuf.Message(REQFRAME)
RespFrame = protobuf.Message(RESPFRAME)
