-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Protocol/Protobuf/BattleBuddy_pb.lua

local protobuf = require("protobuf/protobuf")

module("LuaScript/Protocol/Protobuf/BattleBuddy_pb")

BUDDYINFO = protobuf.Descriptor()

local BUDDYINFO_SERVERID_FIELD = protobuf.FieldDescriptor()
local BUDDYINFO_PLAYERID_FIELD = protobuf.FieldDescriptor()
local BUDDYINFO_ICON_FIELD = protobuf.FieldDescriptor()
local BUDDYINFO_ICONURL_FIELD = protobuf.FieldDescriptor()
local BUDDYINFO_NAME_FIELD = protobuf.FieldDescriptor()
local BUDDYINFO_LEVEL_FIELD = protobuf.FieldDescriptor()
local BUDDYINFO_SRCTYPE_FIELD = protobuf.FieldDescriptor()
local BUDDYINFO_SRCID_FIELD = protobuf.FieldDescriptor()
local BUDDYINFO_ISONLINE_FIELD = protobuf.FieldDescriptor()

BUDDYIDINFO = protobuf.Descriptor()

local BUDDYIDINFO_SERVERID_FIELD = protobuf.FieldDescriptor()
local BUDDYIDINFO_PLAYERID_FIELD = protobuf.FieldDescriptor()

BUDDYREQUESTLIST = protobuf.Descriptor()

local BUDDYREQUESTLIST_LIST_FIELD = protobuf.FieldDescriptor()

BUDDYLIST = protobuf.Descriptor()

local BUDDYLIST_LIST_FIELD = protobuf.FieldDescriptor()

BUDDYREQUESTINFO = protobuf.Descriptor()

local BUDDYREQUESTINFO_FROMSERVERID_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_FROMID_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_FROMICON_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_FROMICONURL_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_FROMNAME_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_FROMLEVEL_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_TOSERVERID_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_TOID_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_SRCTYPE_FIELD = protobuf.FieldDescriptor()
local BUDDYREQUESTINFO_SRCID_FIELD = protobuf.FieldDescriptor()

BUDDYUPDATED = protobuf.Descriptor()

local BUDDYUPDATED_BUDDYSERVERID_FIELD = protobuf.FieldDescriptor()
local BUDDYUPDATED_BUDDYID_FIELD = protobuf.FieldDescriptor()
local BUDDYUPDATED_BUDDYICON_FIELD = protobuf.FieldDescriptor()
local BUDDYUPDATED_BUDDYICONURL_FIELD = protobuf.FieldDescriptor()
local BUDDYUPDATED_BUDDYNAME_FIELD = protobuf.FieldDescriptor()
local BUDDYUPDATED_BUDDYLEVEL_FIELD = protobuf.FieldDescriptor()

INITBUDDYREQUEST = protobuf.Descriptor()
UPDATEONLINESTATUS = protobuf.Descriptor()

local UPDATEONLINESTATUS_SERVERID_FIELD = protobuf.FieldDescriptor()
local UPDATEONLINESTATUS_PLAYERID_FIELD = protobuf.FieldDescriptor()
local UPDATEONLINESTATUS_ISONLINE_FIELD = protobuf.FieldDescriptor()

BUDDYINFO_SERVERID_FIELD.name = "serverId"
BUDDYINFO_SERVERID_FIELD.full_name = ".BuddyInfo.serverId"
BUDDYINFO_SERVERID_FIELD.number = 1
BUDDYINFO_SERVERID_FIELD.index = 0
BUDDYINFO_SERVERID_FIELD.label = 2
BUDDYINFO_SERVERID_FIELD.has_default_value = false
BUDDYINFO_SERVERID_FIELD.default_value = 0
BUDDYINFO_SERVERID_FIELD.type = 13
BUDDYINFO_SERVERID_FIELD.cpp_type = 3
BUDDYINFO_PLAYERID_FIELD.name = "playerId"
BUDDYINFO_PLAYERID_FIELD.full_name = ".BuddyInfo.playerId"
BUDDYINFO_PLAYERID_FIELD.number = 2
BUDDYINFO_PLAYERID_FIELD.index = 1
BUDDYINFO_PLAYERID_FIELD.label = 2
BUDDYINFO_PLAYERID_FIELD.has_default_value = false
BUDDYINFO_PLAYERID_FIELD.default_value = 0
BUDDYINFO_PLAYERID_FIELD.type = 13
BUDDYINFO_PLAYERID_FIELD.cpp_type = 3
BUDDYINFO_ICON_FIELD.name = "icon"
BUDDYINFO_ICON_FIELD.full_name = ".BuddyInfo.icon"
BUDDYINFO_ICON_FIELD.number = 3
BUDDYINFO_ICON_FIELD.index = 2
BUDDYINFO_ICON_FIELD.label = 1
BUDDYINFO_ICON_FIELD.has_default_value = false
BUDDYINFO_ICON_FIELD.default_value = 0
BUDDYINFO_ICON_FIELD.type = 13
BUDDYINFO_ICON_FIELD.cpp_type = 3
BUDDYINFO_ICONURL_FIELD.name = "iconUrl"
BUDDYINFO_ICONURL_FIELD.full_name = ".BuddyInfo.iconUrl"
BUDDYINFO_ICONURL_FIELD.number = 4
BUDDYINFO_ICONURL_FIELD.index = 3
BUDDYINFO_ICONURL_FIELD.label = 1
BUDDYINFO_ICONURL_FIELD.has_default_value = false
BUDDYINFO_ICONURL_FIELD.default_value = ""
BUDDYINFO_ICONURL_FIELD.type = 9
BUDDYINFO_ICONURL_FIELD.cpp_type = 9
BUDDYINFO_NAME_FIELD.name = "name"
BUDDYINFO_NAME_FIELD.full_name = ".BuddyInfo.name"
BUDDYINFO_NAME_FIELD.number = 5
BUDDYINFO_NAME_FIELD.index = 4
BUDDYINFO_NAME_FIELD.label = 1
BUDDYINFO_NAME_FIELD.has_default_value = false
BUDDYINFO_NAME_FIELD.default_value = ""
BUDDYINFO_NAME_FIELD.type = 9
BUDDYINFO_NAME_FIELD.cpp_type = 9
BUDDYINFO_LEVEL_FIELD.name = "level"
BUDDYINFO_LEVEL_FIELD.full_name = ".BuddyInfo.level"
BUDDYINFO_LEVEL_FIELD.number = 6
BUDDYINFO_LEVEL_FIELD.index = 5
BUDDYINFO_LEVEL_FIELD.label = 1
BUDDYINFO_LEVEL_FIELD.has_default_value = false
BUDDYINFO_LEVEL_FIELD.default_value = 0
BUDDYINFO_LEVEL_FIELD.type = 13
BUDDYINFO_LEVEL_FIELD.cpp_type = 3
BUDDYINFO_SRCTYPE_FIELD.name = "srcType"
BUDDYINFO_SRCTYPE_FIELD.full_name = ".BuddyInfo.srcType"
BUDDYINFO_SRCTYPE_FIELD.number = 7
BUDDYINFO_SRCTYPE_FIELD.index = 6
BUDDYINFO_SRCTYPE_FIELD.label = 1
BUDDYINFO_SRCTYPE_FIELD.has_default_value = false
BUDDYINFO_SRCTYPE_FIELD.default_value = 0
BUDDYINFO_SRCTYPE_FIELD.type = 13
BUDDYINFO_SRCTYPE_FIELD.cpp_type = 3
BUDDYINFO_SRCID_FIELD.name = "srcId"
BUDDYINFO_SRCID_FIELD.full_name = ".BuddyInfo.srcId"
BUDDYINFO_SRCID_FIELD.number = 8
BUDDYINFO_SRCID_FIELD.index = 7
BUDDYINFO_SRCID_FIELD.label = 1
BUDDYINFO_SRCID_FIELD.has_default_value = false
BUDDYINFO_SRCID_FIELD.default_value = ""
BUDDYINFO_SRCID_FIELD.type = 9
BUDDYINFO_SRCID_FIELD.cpp_type = 9
BUDDYINFO_ISONLINE_FIELD.name = "isOnline"
BUDDYINFO_ISONLINE_FIELD.full_name = ".BuddyInfo.isOnline"
BUDDYINFO_ISONLINE_FIELD.number = 9
BUDDYINFO_ISONLINE_FIELD.index = 8
BUDDYINFO_ISONLINE_FIELD.label = 1
BUDDYINFO_ISONLINE_FIELD.has_default_value = false
BUDDYINFO_ISONLINE_FIELD.default_value = false
BUDDYINFO_ISONLINE_FIELD.type = 8
BUDDYINFO_ISONLINE_FIELD.cpp_type = 7
BUDDYINFO.name = "BuddyInfo"
BUDDYINFO.full_name = ".BuddyInfo"
BUDDYINFO.nested_types = {}
BUDDYINFO.enum_types = {}
BUDDYINFO.fields = {
	BUDDYINFO_SERVERID_FIELD,
	BUDDYINFO_PLAYERID_FIELD,
	BUDDYINFO_ICON_FIELD,
	BUDDYINFO_ICONURL_FIELD,
	BUDDYINFO_NAME_FIELD,
	BUDDYINFO_LEVEL_FIELD,
	BUDDYINFO_SRCTYPE_FIELD,
	BUDDYINFO_SRCID_FIELD,
	BUDDYINFO_ISONLINE_FIELD
}
BUDDYINFO.is_extendable = false
BUDDYINFO.extensions = {}
BUDDYIDINFO_SERVERID_FIELD.name = "serverId"
BUDDYIDINFO_SERVERID_FIELD.full_name = ".BuddyIdInfo.serverId"
BUDDYIDINFO_SERVERID_FIELD.number = 1
BUDDYIDINFO_SERVERID_FIELD.index = 0
BUDDYIDINFO_SERVERID_FIELD.label = 2
BUDDYIDINFO_SERVERID_FIELD.has_default_value = false
BUDDYIDINFO_SERVERID_FIELD.default_value = 0
BUDDYIDINFO_SERVERID_FIELD.type = 13
BUDDYIDINFO_SERVERID_FIELD.cpp_type = 3
BUDDYIDINFO_PLAYERID_FIELD.name = "playerId"
BUDDYIDINFO_PLAYERID_FIELD.full_name = ".BuddyIdInfo.playerId"
BUDDYIDINFO_PLAYERID_FIELD.number = 2
BUDDYIDINFO_PLAYERID_FIELD.index = 1
BUDDYIDINFO_PLAYERID_FIELD.label = 2
BUDDYIDINFO_PLAYERID_FIELD.has_default_value = false
BUDDYIDINFO_PLAYERID_FIELD.default_value = 0
BUDDYIDINFO_PLAYERID_FIELD.type = 13
BUDDYIDINFO_PLAYERID_FIELD.cpp_type = 3
BUDDYIDINFO.name = "BuddyIdInfo"
BUDDYIDINFO.full_name = ".BuddyIdInfo"
BUDDYIDINFO.nested_types = {}
BUDDYIDINFO.enum_types = {}
BUDDYIDINFO.fields = {
	BUDDYIDINFO_SERVERID_FIELD,
	BUDDYIDINFO_PLAYERID_FIELD
}
BUDDYIDINFO.is_extendable = false
BUDDYIDINFO.extensions = {}
BUDDYREQUESTLIST_LIST_FIELD.name = "list"
BUDDYREQUESTLIST_LIST_FIELD.full_name = ".BuddyRequestList.list"
BUDDYREQUESTLIST_LIST_FIELD.number = 1
BUDDYREQUESTLIST_LIST_FIELD.index = 0
BUDDYREQUESTLIST_LIST_FIELD.label = 3
BUDDYREQUESTLIST_LIST_FIELD.has_default_value = false
BUDDYREQUESTLIST_LIST_FIELD.default_value = {}
BUDDYREQUESTLIST_LIST_FIELD.message_type = BUDDYINFO
BUDDYREQUESTLIST_LIST_FIELD.type = 11
BUDDYREQUESTLIST_LIST_FIELD.cpp_type = 10
BUDDYREQUESTLIST.name = "BuddyRequestList"
BUDDYREQUESTLIST.full_name = ".BuddyRequestList"
BUDDYREQUESTLIST.nested_types = {}
BUDDYREQUESTLIST.enum_types = {}
BUDDYREQUESTLIST.fields = {
	BUDDYREQUESTLIST_LIST_FIELD
}
BUDDYREQUESTLIST.is_extendable = false
BUDDYREQUESTLIST.extensions = {}
BUDDYLIST_LIST_FIELD.name = "list"
BUDDYLIST_LIST_FIELD.full_name = ".BuddyList.list"
BUDDYLIST_LIST_FIELD.number = 1
BUDDYLIST_LIST_FIELD.index = 0
BUDDYLIST_LIST_FIELD.label = 3
BUDDYLIST_LIST_FIELD.has_default_value = false
BUDDYLIST_LIST_FIELD.default_value = {}
BUDDYLIST_LIST_FIELD.message_type = BUDDYINFO
BUDDYLIST_LIST_FIELD.type = 11
BUDDYLIST_LIST_FIELD.cpp_type = 10
BUDDYLIST.name = "BuddyList"
BUDDYLIST.full_name = ".BuddyList"
BUDDYLIST.nested_types = {}
BUDDYLIST.enum_types = {}
BUDDYLIST.fields = {
	BUDDYLIST_LIST_FIELD
}
BUDDYLIST.is_extendable = false
BUDDYLIST.extensions = {}
BUDDYREQUESTINFO_FROMSERVERID_FIELD.name = "fromServerId"
BUDDYREQUESTINFO_FROMSERVERID_FIELD.full_name = ".BuddyRequestInfo.fromServerId"
BUDDYREQUESTINFO_FROMSERVERID_FIELD.number = 1
BUDDYREQUESTINFO_FROMSERVERID_FIELD.index = 0
BUDDYREQUESTINFO_FROMSERVERID_FIELD.label = 1
BUDDYREQUESTINFO_FROMSERVERID_FIELD.has_default_value = false
BUDDYREQUESTINFO_FROMSERVERID_FIELD.default_value = 0
BUDDYREQUESTINFO_FROMSERVERID_FIELD.type = 13
BUDDYREQUESTINFO_FROMSERVERID_FIELD.cpp_type = 3
BUDDYREQUESTINFO_FROMID_FIELD.name = "fromId"
BUDDYREQUESTINFO_FROMID_FIELD.full_name = ".BuddyRequestInfo.fromId"
BUDDYREQUESTINFO_FROMID_FIELD.number = 2
BUDDYREQUESTINFO_FROMID_FIELD.index = 1
BUDDYREQUESTINFO_FROMID_FIELD.label = 1
BUDDYREQUESTINFO_FROMID_FIELD.has_default_value = false
BUDDYREQUESTINFO_FROMID_FIELD.default_value = 0
BUDDYREQUESTINFO_FROMID_FIELD.type = 13
BUDDYREQUESTINFO_FROMID_FIELD.cpp_type = 3
BUDDYREQUESTINFO_FROMICON_FIELD.name = "fromIcon"
BUDDYREQUESTINFO_FROMICON_FIELD.full_name = ".BuddyRequestInfo.fromIcon"
BUDDYREQUESTINFO_FROMICON_FIELD.number = 3
BUDDYREQUESTINFO_FROMICON_FIELD.index = 2
BUDDYREQUESTINFO_FROMICON_FIELD.label = 1
BUDDYREQUESTINFO_FROMICON_FIELD.has_default_value = false
BUDDYREQUESTINFO_FROMICON_FIELD.default_value = 0
BUDDYREQUESTINFO_FROMICON_FIELD.type = 13
BUDDYREQUESTINFO_FROMICON_FIELD.cpp_type = 3
BUDDYREQUESTINFO_FROMICONURL_FIELD.name = "fromIconUrl"
BUDDYREQUESTINFO_FROMICONURL_FIELD.full_name = ".BuddyRequestInfo.fromIconUrl"
BUDDYREQUESTINFO_FROMICONURL_FIELD.number = 4
BUDDYREQUESTINFO_FROMICONURL_FIELD.index = 3
BUDDYREQUESTINFO_FROMICONURL_FIELD.label = 1
BUDDYREQUESTINFO_FROMICONURL_FIELD.has_default_value = false
BUDDYREQUESTINFO_FROMICONURL_FIELD.default_value = ""
BUDDYREQUESTINFO_FROMICONURL_FIELD.type = 9
BUDDYREQUESTINFO_FROMICONURL_FIELD.cpp_type = 9
BUDDYREQUESTINFO_FROMNAME_FIELD.name = "fromName"
BUDDYREQUESTINFO_FROMNAME_FIELD.full_name = ".BuddyRequestInfo.fromName"
BUDDYREQUESTINFO_FROMNAME_FIELD.number = 5
BUDDYREQUESTINFO_FROMNAME_FIELD.index = 4
BUDDYREQUESTINFO_FROMNAME_FIELD.label = 1
BUDDYREQUESTINFO_FROMNAME_FIELD.has_default_value = false
BUDDYREQUESTINFO_FROMNAME_FIELD.default_value = ""
BUDDYREQUESTINFO_FROMNAME_FIELD.type = 9
BUDDYREQUESTINFO_FROMNAME_FIELD.cpp_type = 9
BUDDYREQUESTINFO_FROMLEVEL_FIELD.name = "fromLevel"
BUDDYREQUESTINFO_FROMLEVEL_FIELD.full_name = ".BuddyRequestInfo.fromLevel"
BUDDYREQUESTINFO_FROMLEVEL_FIELD.number = 6
BUDDYREQUESTINFO_FROMLEVEL_FIELD.index = 5
BUDDYREQUESTINFO_FROMLEVEL_FIELD.label = 1
BUDDYREQUESTINFO_FROMLEVEL_FIELD.has_default_value = false
BUDDYREQUESTINFO_FROMLEVEL_FIELD.default_value = 0
BUDDYREQUESTINFO_FROMLEVEL_FIELD.type = 13
BUDDYREQUESTINFO_FROMLEVEL_FIELD.cpp_type = 3
BUDDYREQUESTINFO_TOSERVERID_FIELD.name = "toServerId"
BUDDYREQUESTINFO_TOSERVERID_FIELD.full_name = ".BuddyRequestInfo.toServerId"
BUDDYREQUESTINFO_TOSERVERID_FIELD.number = 7
BUDDYREQUESTINFO_TOSERVERID_FIELD.index = 6
BUDDYREQUESTINFO_TOSERVERID_FIELD.label = 2
BUDDYREQUESTINFO_TOSERVERID_FIELD.has_default_value = false
BUDDYREQUESTINFO_TOSERVERID_FIELD.default_value = 0
BUDDYREQUESTINFO_TOSERVERID_FIELD.type = 13
BUDDYREQUESTINFO_TOSERVERID_FIELD.cpp_type = 3
BUDDYREQUESTINFO_TOID_FIELD.name = "toId"
BUDDYREQUESTINFO_TOID_FIELD.full_name = ".BuddyRequestInfo.toId"
BUDDYREQUESTINFO_TOID_FIELD.number = 8
BUDDYREQUESTINFO_TOID_FIELD.index = 7
BUDDYREQUESTINFO_TOID_FIELD.label = 2
BUDDYREQUESTINFO_TOID_FIELD.has_default_value = false
BUDDYREQUESTINFO_TOID_FIELD.default_value = 0
BUDDYREQUESTINFO_TOID_FIELD.type = 13
BUDDYREQUESTINFO_TOID_FIELD.cpp_type = 3
BUDDYREQUESTINFO_SRCTYPE_FIELD.name = "srcType"
BUDDYREQUESTINFO_SRCTYPE_FIELD.full_name = ".BuddyRequestInfo.srcType"
BUDDYREQUESTINFO_SRCTYPE_FIELD.number = 9
BUDDYREQUESTINFO_SRCTYPE_FIELD.index = 8
BUDDYREQUESTINFO_SRCTYPE_FIELD.label = 1
BUDDYREQUESTINFO_SRCTYPE_FIELD.has_default_value = false
BUDDYREQUESTINFO_SRCTYPE_FIELD.default_value = 0
BUDDYREQUESTINFO_SRCTYPE_FIELD.type = 13
BUDDYREQUESTINFO_SRCTYPE_FIELD.cpp_type = 3
BUDDYREQUESTINFO_SRCID_FIELD.name = "srcId"
BUDDYREQUESTINFO_SRCID_FIELD.full_name = ".BuddyRequestInfo.srcId"
BUDDYREQUESTINFO_SRCID_FIELD.number = 10
BUDDYREQUESTINFO_SRCID_FIELD.index = 9
BUDDYREQUESTINFO_SRCID_FIELD.label = 1
BUDDYREQUESTINFO_SRCID_FIELD.has_default_value = false
BUDDYREQUESTINFO_SRCID_FIELD.default_value = ""
BUDDYREQUESTINFO_SRCID_FIELD.type = 9
BUDDYREQUESTINFO_SRCID_FIELD.cpp_type = 9
BUDDYREQUESTINFO.name = "BuddyRequestInfo"
BUDDYREQUESTINFO.full_name = ".BuddyRequestInfo"
BUDDYREQUESTINFO.nested_types = {}
BUDDYREQUESTINFO.enum_types = {}
BUDDYREQUESTINFO.fields = {
	BUDDYREQUESTINFO_FROMSERVERID_FIELD,
	BUDDYREQUESTINFO_FROMID_FIELD,
	BUDDYREQUESTINFO_FROMICON_FIELD,
	BUDDYREQUESTINFO_FROMICONURL_FIELD,
	BUDDYREQUESTINFO_FROMNAME_FIELD,
	BUDDYREQUESTINFO_FROMLEVEL_FIELD,
	BUDDYREQUESTINFO_TOSERVERID_FIELD,
	BUDDYREQUESTINFO_TOID_FIELD,
	BUDDYREQUESTINFO_SRCTYPE_FIELD,
	BUDDYREQUESTINFO_SRCID_FIELD
}
BUDDYREQUESTINFO.is_extendable = false
BUDDYREQUESTINFO.extensions = {}
BUDDYUPDATED_BUDDYSERVERID_FIELD.name = "buddyServerId"
BUDDYUPDATED_BUDDYSERVERID_FIELD.full_name = ".BuddyUpdated.buddyServerId"
BUDDYUPDATED_BUDDYSERVERID_FIELD.number = 1
BUDDYUPDATED_BUDDYSERVERID_FIELD.index = 0
BUDDYUPDATED_BUDDYSERVERID_FIELD.label = 2
BUDDYUPDATED_BUDDYSERVERID_FIELD.has_default_value = false
BUDDYUPDATED_BUDDYSERVERID_FIELD.default_value = 0
BUDDYUPDATED_BUDDYSERVERID_FIELD.type = 13
BUDDYUPDATED_BUDDYSERVERID_FIELD.cpp_type = 3
BUDDYUPDATED_BUDDYID_FIELD.name = "buddyId"
BUDDYUPDATED_BUDDYID_FIELD.full_name = ".BuddyUpdated.buddyId"
BUDDYUPDATED_BUDDYID_FIELD.number = 2
BUDDYUPDATED_BUDDYID_FIELD.index = 1
BUDDYUPDATED_BUDDYID_FIELD.label = 2
BUDDYUPDATED_BUDDYID_FIELD.has_default_value = false
BUDDYUPDATED_BUDDYID_FIELD.default_value = 0
BUDDYUPDATED_BUDDYID_FIELD.type = 13
BUDDYUPDATED_BUDDYID_FIELD.cpp_type = 3
BUDDYUPDATED_BUDDYICON_FIELD.name = "buddyIcon"
BUDDYUPDATED_BUDDYICON_FIELD.full_name = ".BuddyUpdated.buddyIcon"
BUDDYUPDATED_BUDDYICON_FIELD.number = 3
BUDDYUPDATED_BUDDYICON_FIELD.index = 2
BUDDYUPDATED_BUDDYICON_FIELD.label = 1
BUDDYUPDATED_BUDDYICON_FIELD.has_default_value = false
BUDDYUPDATED_BUDDYICON_FIELD.default_value = 0
BUDDYUPDATED_BUDDYICON_FIELD.type = 13
BUDDYUPDATED_BUDDYICON_FIELD.cpp_type = 3
BUDDYUPDATED_BUDDYICONURL_FIELD.name = "buddyIconUrl"
BUDDYUPDATED_BUDDYICONURL_FIELD.full_name = ".BuddyUpdated.buddyIconUrl"
BUDDYUPDATED_BUDDYICONURL_FIELD.number = 4
BUDDYUPDATED_BUDDYICONURL_FIELD.index = 3
BUDDYUPDATED_BUDDYICONURL_FIELD.label = 1
BUDDYUPDATED_BUDDYICONURL_FIELD.has_default_value = false
BUDDYUPDATED_BUDDYICONURL_FIELD.default_value = ""
BUDDYUPDATED_BUDDYICONURL_FIELD.type = 9
BUDDYUPDATED_BUDDYICONURL_FIELD.cpp_type = 9
BUDDYUPDATED_BUDDYNAME_FIELD.name = "buddyName"
BUDDYUPDATED_BUDDYNAME_FIELD.full_name = ".BuddyUpdated.buddyName"
BUDDYUPDATED_BUDDYNAME_FIELD.number = 5
BUDDYUPDATED_BUDDYNAME_FIELD.index = 4
BUDDYUPDATED_BUDDYNAME_FIELD.label = 1
BUDDYUPDATED_BUDDYNAME_FIELD.has_default_value = false
BUDDYUPDATED_BUDDYNAME_FIELD.default_value = ""
BUDDYUPDATED_BUDDYNAME_FIELD.type = 9
BUDDYUPDATED_BUDDYNAME_FIELD.cpp_type = 9
BUDDYUPDATED_BUDDYLEVEL_FIELD.name = "buddyLevel"
BUDDYUPDATED_BUDDYLEVEL_FIELD.full_name = ".BuddyUpdated.buddyLevel"
BUDDYUPDATED_BUDDYLEVEL_FIELD.number = 6
BUDDYUPDATED_BUDDYLEVEL_FIELD.index = 5
BUDDYUPDATED_BUDDYLEVEL_FIELD.label = 1
BUDDYUPDATED_BUDDYLEVEL_FIELD.has_default_value = false
BUDDYUPDATED_BUDDYLEVEL_FIELD.default_value = 0
BUDDYUPDATED_BUDDYLEVEL_FIELD.type = 13
BUDDYUPDATED_BUDDYLEVEL_FIELD.cpp_type = 3
BUDDYUPDATED.name = "BuddyUpdated"
BUDDYUPDATED.full_name = ".BuddyUpdated"
BUDDYUPDATED.nested_types = {}
BUDDYUPDATED.enum_types = {}
BUDDYUPDATED.fields = {
	BUDDYUPDATED_BUDDYSERVERID_FIELD,
	BUDDYUPDATED_BUDDYID_FIELD,
	BUDDYUPDATED_BUDDYICON_FIELD,
	BUDDYUPDATED_BUDDYICONURL_FIELD,
	BUDDYUPDATED_BUDDYNAME_FIELD,
	BUDDYUPDATED_BUDDYLEVEL_FIELD
}
BUDDYUPDATED.is_extendable = false
BUDDYUPDATED.extensions = {}
INITBUDDYREQUEST.name = "InitBuddyRequest"
INITBUDDYREQUEST.full_name = ".InitBuddyRequest"
INITBUDDYREQUEST.nested_types = {}
INITBUDDYREQUEST.enum_types = {}
INITBUDDYREQUEST.fields = {}
INITBUDDYREQUEST.is_extendable = false
INITBUDDYREQUEST.extensions = {}
UPDATEONLINESTATUS_SERVERID_FIELD.name = "serverId"
UPDATEONLINESTATUS_SERVERID_FIELD.full_name = ".UpdateOnlineStatus.serverId"
UPDATEONLINESTATUS_SERVERID_FIELD.number = 1
UPDATEONLINESTATUS_SERVERID_FIELD.index = 0
UPDATEONLINESTATUS_SERVERID_FIELD.label = 2
UPDATEONLINESTATUS_SERVERID_FIELD.has_default_value = false
UPDATEONLINESTATUS_SERVERID_FIELD.default_value = 0
UPDATEONLINESTATUS_SERVERID_FIELD.type = 13
UPDATEONLINESTATUS_SERVERID_FIELD.cpp_type = 3
UPDATEONLINESTATUS_PLAYERID_FIELD.name = "playerId"
UPDATEONLINESTATUS_PLAYERID_FIELD.full_name = ".UpdateOnlineStatus.playerId"
UPDATEONLINESTATUS_PLAYERID_FIELD.number = 2
UPDATEONLINESTATUS_PLAYERID_FIELD.index = 1
UPDATEONLINESTATUS_PLAYERID_FIELD.label = 2
UPDATEONLINESTATUS_PLAYERID_FIELD.has_default_value = false
UPDATEONLINESTATUS_PLAYERID_FIELD.default_value = 0
UPDATEONLINESTATUS_PLAYERID_FIELD.type = 13
UPDATEONLINESTATUS_PLAYERID_FIELD.cpp_type = 3
UPDATEONLINESTATUS_ISONLINE_FIELD.name = "isOnline"
UPDATEONLINESTATUS_ISONLINE_FIELD.full_name = ".UpdateOnlineStatus.isOnline"
UPDATEONLINESTATUS_ISONLINE_FIELD.number = 3
UPDATEONLINESTATUS_ISONLINE_FIELD.index = 2
UPDATEONLINESTATUS_ISONLINE_FIELD.label = 2
UPDATEONLINESTATUS_ISONLINE_FIELD.has_default_value = false
UPDATEONLINESTATUS_ISONLINE_FIELD.default_value = false
UPDATEONLINESTATUS_ISONLINE_FIELD.type = 8
UPDATEONLINESTATUS_ISONLINE_FIELD.cpp_type = 7
UPDATEONLINESTATUS.name = "UpdateOnlineStatus"
UPDATEONLINESTATUS.full_name = ".UpdateOnlineStatus"
UPDATEONLINESTATUS.nested_types = {}
UPDATEONLINESTATUS.enum_types = {}
UPDATEONLINESTATUS.fields = {
	UPDATEONLINESTATUS_SERVERID_FIELD,
	UPDATEONLINESTATUS_PLAYERID_FIELD,
	UPDATEONLINESTATUS_ISONLINE_FIELD
}
UPDATEONLINESTATUS.is_extendable = false
UPDATEONLINESTATUS.extensions = {}
BuddyIdInfo = protobuf.Message(BUDDYIDINFO)
BuddyInfo = protobuf.Message(BUDDYINFO)
BuddyList = protobuf.Message(BUDDYLIST)
BuddyRequestInfo = protobuf.Message(BUDDYREQUESTINFO)
BuddyRequestList = protobuf.Message(BUDDYREQUESTLIST)
BuddyUpdated = protobuf.Message(BUDDYUPDATED)
InitBuddyRequest = protobuf.Message(INITBUDDYREQUEST)
UpdateOnlineStatus = protobuf.Message(UPDATEONLINESTATUS)
