-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Protocol/Protobuf/BattleGameRoom_pb.lua

local protobuf = require("protobuf/protobuf")

module("LuaScript/Protocol/Protobuf/BattleGameRoom_pb")

REQMATCHGAME = protobuf.Descriptor()

local REQMATCHGAME_GAMETYPE_FIELD = protobuf.FieldDescriptor()

REQREJOINGAME = protobuf.Descriptor()
REQCANCELMATCHGAME = protobuf.Descriptor()
RESPREMATCHGAME = protobuf.Descriptor()
RESPMATCHGAMEINPROGRESS = protobuf.Descriptor()
MATCHEDPLAYERINFO = protobuf.Descriptor()

local MATCHEDPLAYERINFO_USERID_FIELD = protobuf.FieldDescriptor()
local MATCHEDPLAYERINFO_NAME_FIELD = protobuf.FieldDescriptor()
local MATCHEDPLAYERINFO_PLAYERID_FIELD = protobuf.FieldDescriptor()
local MATCHEDPLAYERINFO_ICON_FIELD = protobuf.FieldDescriptor()
local MATCHEDPLAYERINFO_ICONURL_FIELD = protobuf.FieldDescriptor()

RESPMATCHEDPLAYERLIST = protobuf.Descriptor()

local RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD = protobuf.FieldDescriptor()
local RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD = protobuf.FieldDescriptor()

REQCONFIRMENTERGAME = protobuf.Descriptor()
RESPCONFIRMENTERGAME = protobuf.Descriptor()

local RESPCONFIRMENTERGAME_USERID_FIELD = protobuf.FieldDescriptor()

RESPKICKOUTUNCONFIRMEDUSER = protobuf.Descriptor()
TEAMMEMBERINFO = protobuf.Descriptor()

local TEAMMEMBERINFO_USERID_FIELD = protobuf.FieldDescriptor()
local TEAMMEMBERINFO_NAME_FIELD = protobuf.FieldDescriptor()
local TEAMMEMBERINFO_ICON_FIELD = protobuf.FieldDescriptor()
local TEAMMEMBERINFO_ICONURL_FIELD = protobuf.FieldDescriptor()
local TEAMMEMBERINFO_TEAMID_FIELD = protobuf.FieldDescriptor()
local TEAMMEMBERINFO_HEROID_FIELD = protobuf.FieldDescriptor()
local TEAMMEMBERINFO_PLAYERID_FIELD = protobuf.FieldDescriptor()
local TEAMMEMBERINFO_PERCENT_FIELD = protobuf.FieldDescriptor()

TEAMINFO = protobuf.Descriptor()

local TEAMINFO_TEAMID_FIELD = protobuf.FieldDescriptor()
local TEAMINFO_TEAMMEMBERINFO_FIELD = protobuf.FieldDescriptor()

RESPBEGINCHOOSINGHERO = protobuf.Descriptor()

local RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD = protobuf.FieldDescriptor()
local RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD = protobuf.FieldDescriptor()

REQCHOOSEHERO = protobuf.Descriptor()

local REQCHOOSEHERO_HEROID_FIELD = protobuf.FieldDescriptor()

RESPCHOOSEHERO = protobuf.Descriptor()

local RESPCHOOSEHERO_USERID_FIELD = protobuf.FieldDescriptor()
local RESPCHOOSEHERO_HEROID_FIELD = protobuf.FieldDescriptor()

REQCONFIRMHERO = protobuf.Descriptor()
RESPCONFIRMHERO = protobuf.Descriptor()

local RESPCONFIRMHERO_USERID_FIELD = protobuf.FieldDescriptor()
local RESPCONFIRMHERO_HEROID_FIELD = protobuf.FieldDescriptor()

RESPBEGINGAMELOADING = protobuf.Descriptor()

local RESPBEGINGAMELOADING_GONEXTTIME_FIELD = protobuf.FieldDescriptor()
local RESPBEGINGAMELOADING_RANDOMSEED_FIELD = protobuf.FieldDescriptor()
local RESPBEGINGAMELOADING_PLAYERINFO_FIELD = protobuf.FieldDescriptor()
local RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD = protobuf.FieldDescriptor()

REQCLIENTLOADINGUPDATE = protobuf.Descriptor()

local REQCLIENTLOADINGUPDATE_PERCENT_FIELD = protobuf.FieldDescriptor()

RESPCLIENTLOADINGUPDATE = protobuf.Descriptor()

local RESPCLIENTLOADINGUPDATE_USERID_FIELD = protobuf.FieldDescriptor()
local RESPCLIENTLOADINGUPDATE_PERCENT_FIELD = protobuf.FieldDescriptor()

RESPSTARTGAME = protobuf.Descriptor()
BATTLEROOMUSERINFO = protobuf.Descriptor()

local BATTLEROOMUSERINFO_USERID_FIELD = protobuf.FieldDescriptor()
local BATTLEROOMUSERINFO_SERVERID_FIELD = protobuf.FieldDescriptor()
local BATTLEROOMUSERINFO_PLAYERID_FIELD = protobuf.FieldDescriptor()

BATTLEROOMINFO = protobuf.Descriptor()

local BATTLEROOMINFO_ROOMID_FIELD = protobuf.FieldDescriptor()
local BATTLEROOMINFO_GAMETYPE_FIELD = protobuf.FieldDescriptor()
local BATTLEROOMINFO_STATE_FIELD = protobuf.FieldDescriptor()
local BATTLEROOMINFO_NEEDPLAYERS_FIELD = protobuf.FieldDescriptor()
local BATTLEROOMINFO_GAMEID_FIELD = protobuf.FieldDescriptor()
local BATTLEROOMINFO_USERS_FIELD = protobuf.FieldDescriptor()

REQUPLOADROOMINFOSTOSEARCH = protobuf.Descriptor()

local REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD = protobuf.FieldDescriptor()

REQUPDATEROOMINFOTOSEARCH = protobuf.Descriptor()

local REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD = protobuf.FieldDescriptor()

REQUSERLEAVEGAMEINZONE = protobuf.Descriptor()

local REQUSERLEAVEGAMEINZONE_USERID_FIELD = protobuf.FieldDescriptor()
local REQUSERLEAVEGAMEINZONE_ROOMID_FIELD = protobuf.FieldDescriptor()
local REQUSERLEAVEGAMEINZONE_REMATCH_FIELD = protobuf.FieldDescriptor()

REQMATCHGAMEINZONE = protobuf.Descriptor()

local REQMATCHGAMEINZONE_GAMETYPE_FIELD = protobuf.FieldDescriptor()
local REQMATCHGAMEINZONE_NAME_FIELD = protobuf.FieldDescriptor()
local REQMATCHGAMEINZONE_ICON_FIELD = protobuf.FieldDescriptor()
local REQMATCHGAMEINZONE_ICONURL_FIELD = protobuf.FieldDescriptor()
local REQMATCHGAMEINZONE_PLAYERID_FIELD = protobuf.FieldDescriptor()

RESPMATCHGAMEINZONE = protobuf.Descriptor()

local RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD = protobuf.FieldDescriptor()
local RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD = protobuf.FieldDescriptor()
local RESPMATCHGAMEINZONE_SIGN_FIELD = protobuf.FieldDescriptor()

REQJOINGAMEINZONE = protobuf.Descriptor()

local REQJOINGAMEINZONE_ROOMID_FIELD = protobuf.FieldDescriptor()
local REQJOINGAMEINZONE_GAMETYPE_FIELD = protobuf.FieldDescriptor()
local REQJOINGAMEINZONE_USERID_FIELD = protobuf.FieldDescriptor()
local REQJOINGAMEINZONE_NAME_FIELD = protobuf.FieldDescriptor()
local REQJOINGAMEINZONE_ICON_FIELD = protobuf.FieldDescriptor()
local REQJOINGAMEINZONE_ICONURL_FIELD = protobuf.FieldDescriptor()
local REQJOINGAMEINZONE_PLAYERID_FIELD = protobuf.FieldDescriptor()

RESPJOINGAMEINZONE = protobuf.Descriptor()

local RESPJOINGAMEINZONE_ROOMID_FIELD = protobuf.FieldDescriptor()
local RESPJOINGAMEINZONE_GAMETYPE_FIELD = protobuf.FieldDescriptor()
local RESPJOINGAMEINZONE_USERID_FIELD = protobuf.FieldDescriptor()
local RESPJOINGAMEINZONE_SIGN_FIELD = protobuf.FieldDescriptor()
local RESPJOINGAMEINZONE_SUCCESS_FIELD = protobuf.FieldDescriptor()
local RESPJOINGAMEINZONE_PLAYERID_FIELD = protobuf.FieldDescriptor()
local RESPJOINGAMEINZONE_ERRORCODE_FIELD = protobuf.FieldDescriptor()

REQCHECKISINZONE = protobuf.Descriptor()
RESPCHECKISINZONE = protobuf.Descriptor()

local RESPCHECKISINZONE_ISINZONE_FIELD = protobuf.FieldDescriptor()
local RESPCHECKISINZONE_GAMETYPE_FIELD = protobuf.FieldDescriptor()

REQBATTLERESULT = protobuf.Descriptor()

local REQBATTLERESULT_RESULT_FIELD = protobuf.FieldDescriptor()

RESPBATTLERESULT = protobuf.Descriptor()

local RESPBATTLERESULT_RESULT_FIELD = protobuf.FieldDescriptor()

REQMATCHGAME_GAMETYPE_FIELD.name = "gameType"
REQMATCHGAME_GAMETYPE_FIELD.full_name = ".ReqMatchGame.gameType"
REQMATCHGAME_GAMETYPE_FIELD.number = 1
REQMATCHGAME_GAMETYPE_FIELD.index = 0
REQMATCHGAME_GAMETYPE_FIELD.label = 2
REQMATCHGAME_GAMETYPE_FIELD.has_default_value = false
REQMATCHGAME_GAMETYPE_FIELD.default_value = 0
REQMATCHGAME_GAMETYPE_FIELD.type = 13
REQMATCHGAME_GAMETYPE_FIELD.cpp_type = 3
REQMATCHGAME.name = "ReqMatchGame"
REQMATCHGAME.full_name = ".ReqMatchGame"
REQMATCHGAME.nested_types = {}
REQMATCHGAME.enum_types = {}
REQMATCHGAME.fields = {
	REQMATCHGAME_GAMETYPE_FIELD
}
REQMATCHGAME.is_extendable = false
REQMATCHGAME.extensions = {}
REQREJOINGAME.name = "ReqRejoinGame"
REQREJOINGAME.full_name = ".ReqRejoinGame"
REQREJOINGAME.nested_types = {}
REQREJOINGAME.enum_types = {}
REQREJOINGAME.fields = {}
REQREJOINGAME.is_extendable = false
REQREJOINGAME.extensions = {}
REQCANCELMATCHGAME.name = "ReqCancelMatchGame"
REQCANCELMATCHGAME.full_name = ".ReqCancelMatchGame"
REQCANCELMATCHGAME.nested_types = {}
REQCANCELMATCHGAME.enum_types = {}
REQCANCELMATCHGAME.fields = {}
REQCANCELMATCHGAME.is_extendable = false
REQCANCELMATCHGAME.extensions = {}
RESPREMATCHGAME.name = "RespRematchGame"
RESPREMATCHGAME.full_name = ".RespRematchGame"
RESPREMATCHGAME.nested_types = {}
RESPREMATCHGAME.enum_types = {}
RESPREMATCHGAME.fields = {}
RESPREMATCHGAME.is_extendable = false
RESPREMATCHGAME.extensions = {}
RESPMATCHGAMEINPROGRESS.name = "RespMatchGameInProgress"
RESPMATCHGAMEINPROGRESS.full_name = ".RespMatchGameInProgress"
RESPMATCHGAMEINPROGRESS.nested_types = {}
RESPMATCHGAMEINPROGRESS.enum_types = {}
RESPMATCHGAMEINPROGRESS.fields = {}
RESPMATCHGAMEINPROGRESS.is_extendable = false
RESPMATCHGAMEINPROGRESS.extensions = {}
MATCHEDPLAYERINFO_USERID_FIELD.name = "userId"
MATCHEDPLAYERINFO_USERID_FIELD.full_name = ".MatchedPlayerInfo.userId"
MATCHEDPLAYERINFO_USERID_FIELD.number = 1
MATCHEDPLAYERINFO_USERID_FIELD.index = 0
MATCHEDPLAYERINFO_USERID_FIELD.label = 2
MATCHEDPLAYERINFO_USERID_FIELD.has_default_value = false
MATCHEDPLAYERINFO_USERID_FIELD.default_value = 0
MATCHEDPLAYERINFO_USERID_FIELD.type = 13
MATCHEDPLAYERINFO_USERID_FIELD.cpp_type = 3
MATCHEDPLAYERINFO_NAME_FIELD.name = "name"
MATCHEDPLAYERINFO_NAME_FIELD.full_name = ".MatchedPlayerInfo.name"
MATCHEDPLAYERINFO_NAME_FIELD.number = 2
MATCHEDPLAYERINFO_NAME_FIELD.index = 1
MATCHEDPLAYERINFO_NAME_FIELD.label = 2
MATCHEDPLAYERINFO_NAME_FIELD.has_default_value = false
MATCHEDPLAYERINFO_NAME_FIELD.default_value = ""
MATCHEDPLAYERINFO_NAME_FIELD.type = 9
MATCHEDPLAYERINFO_NAME_FIELD.cpp_type = 9
MATCHEDPLAYERINFO_PLAYERID_FIELD.name = "playerId"
MATCHEDPLAYERINFO_PLAYERID_FIELD.full_name = ".MatchedPlayerInfo.playerId"
MATCHEDPLAYERINFO_PLAYERID_FIELD.number = 3
MATCHEDPLAYERINFO_PLAYERID_FIELD.index = 2
MATCHEDPLAYERINFO_PLAYERID_FIELD.label = 2
MATCHEDPLAYERINFO_PLAYERID_FIELD.has_default_value = false
MATCHEDPLAYERINFO_PLAYERID_FIELD.default_value = 0
MATCHEDPLAYERINFO_PLAYERID_FIELD.type = 13
MATCHEDPLAYERINFO_PLAYERID_FIELD.cpp_type = 3
MATCHEDPLAYERINFO_ICON_FIELD.name = "icon"
MATCHEDPLAYERINFO_ICON_FIELD.full_name = ".MatchedPlayerInfo.icon"
MATCHEDPLAYERINFO_ICON_FIELD.number = 4
MATCHEDPLAYERINFO_ICON_FIELD.index = 3
MATCHEDPLAYERINFO_ICON_FIELD.label = 1
MATCHEDPLAYERINFO_ICON_FIELD.has_default_value = false
MATCHEDPLAYERINFO_ICON_FIELD.default_value = 0
MATCHEDPLAYERINFO_ICON_FIELD.type = 13
MATCHEDPLAYERINFO_ICON_FIELD.cpp_type = 3
MATCHEDPLAYERINFO_ICONURL_FIELD.name = "iconUrl"
MATCHEDPLAYERINFO_ICONURL_FIELD.full_name = ".MatchedPlayerInfo.iconUrl"
MATCHEDPLAYERINFO_ICONURL_FIELD.number = 5
MATCHEDPLAYERINFO_ICONURL_FIELD.index = 4
MATCHEDPLAYERINFO_ICONURL_FIELD.label = 1
MATCHEDPLAYERINFO_ICONURL_FIELD.has_default_value = false
MATCHEDPLAYERINFO_ICONURL_FIELD.default_value = ""
MATCHEDPLAYERINFO_ICONURL_FIELD.type = 9
MATCHEDPLAYERINFO_ICONURL_FIELD.cpp_type = 9
MATCHEDPLAYERINFO.name = "MatchedPlayerInfo"
MATCHEDPLAYERINFO.full_name = ".MatchedPlayerInfo"
MATCHEDPLAYERINFO.nested_types = {}
MATCHEDPLAYERINFO.enum_types = {}
MATCHEDPLAYERINFO.fields = {
	MATCHEDPLAYERINFO_USERID_FIELD,
	MATCHEDPLAYERINFO_NAME_FIELD,
	MATCHEDPLAYERINFO_PLAYERID_FIELD,
	MATCHEDPLAYERINFO_ICON_FIELD,
	MATCHEDPLAYERINFO_ICONURL_FIELD
}
MATCHEDPLAYERINFO.is_extendable = false
MATCHEDPLAYERINFO.extensions = {}
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.name = "goNextTime"
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.full_name = ".RespMatchedPlayerList.goNextTime"
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.number = 1
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.index = 0
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.label = 2
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.has_default_value = false
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.default_value = 0
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.type = 13
RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD.cpp_type = 3
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.name = "playerInfo"
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.full_name = ".RespMatchedPlayerList.playerInfo"
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.number = 2
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.index = 1
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.label = 3
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.has_default_value = false
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.default_value = {}
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.message_type = MATCHEDPLAYERINFO
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.type = 11
RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD.cpp_type = 10
RESPMATCHEDPLAYERLIST.name = "RespMatchedPlayerList"
RESPMATCHEDPLAYERLIST.full_name = ".RespMatchedPlayerList"
RESPMATCHEDPLAYERLIST.nested_types = {}
RESPMATCHEDPLAYERLIST.enum_types = {}
RESPMATCHEDPLAYERLIST.fields = {
	RESPMATCHEDPLAYERLIST_GONEXTTIME_FIELD,
	RESPMATCHEDPLAYERLIST_PLAYERINFO_FIELD
}
RESPMATCHEDPLAYERLIST.is_extendable = false
RESPMATCHEDPLAYERLIST.extensions = {}
REQCONFIRMENTERGAME.name = "ReqConfirmEnterGame"
REQCONFIRMENTERGAME.full_name = ".ReqConfirmEnterGame"
REQCONFIRMENTERGAME.nested_types = {}
REQCONFIRMENTERGAME.enum_types = {}
REQCONFIRMENTERGAME.fields = {}
REQCONFIRMENTERGAME.is_extendable = false
REQCONFIRMENTERGAME.extensions = {}
RESPCONFIRMENTERGAME_USERID_FIELD.name = "userId"
RESPCONFIRMENTERGAME_USERID_FIELD.full_name = ".RespConfirmEnterGame.userId"
RESPCONFIRMENTERGAME_USERID_FIELD.number = 1
RESPCONFIRMENTERGAME_USERID_FIELD.index = 0
RESPCONFIRMENTERGAME_USERID_FIELD.label = 2
RESPCONFIRMENTERGAME_USERID_FIELD.has_default_value = false
RESPCONFIRMENTERGAME_USERID_FIELD.default_value = 0
RESPCONFIRMENTERGAME_USERID_FIELD.type = 13
RESPCONFIRMENTERGAME_USERID_FIELD.cpp_type = 3
RESPCONFIRMENTERGAME.name = "RespConfirmEnterGame"
RESPCONFIRMENTERGAME.full_name = ".RespConfirmEnterGame"
RESPCONFIRMENTERGAME.nested_types = {}
RESPCONFIRMENTERGAME.enum_types = {}
RESPCONFIRMENTERGAME.fields = {
	RESPCONFIRMENTERGAME_USERID_FIELD
}
RESPCONFIRMENTERGAME.is_extendable = false
RESPCONFIRMENTERGAME.extensions = {}
RESPKICKOUTUNCONFIRMEDUSER.name = "RespKickOutUnconfirmedUser"
RESPKICKOUTUNCONFIRMEDUSER.full_name = ".RespKickOutUnconfirmedUser"
RESPKICKOUTUNCONFIRMEDUSER.nested_types = {}
RESPKICKOUTUNCONFIRMEDUSER.enum_types = {}
RESPKICKOUTUNCONFIRMEDUSER.fields = {}
RESPKICKOUTUNCONFIRMEDUSER.is_extendable = false
RESPKICKOUTUNCONFIRMEDUSER.extensions = {}
TEAMMEMBERINFO_USERID_FIELD.name = "userId"
TEAMMEMBERINFO_USERID_FIELD.full_name = ".TeamMemberInfo.userId"
TEAMMEMBERINFO_USERID_FIELD.number = 1
TEAMMEMBERINFO_USERID_FIELD.index = 0
TEAMMEMBERINFO_USERID_FIELD.label = 2
TEAMMEMBERINFO_USERID_FIELD.has_default_value = false
TEAMMEMBERINFO_USERID_FIELD.default_value = 0
TEAMMEMBERINFO_USERID_FIELD.type = 13
TEAMMEMBERINFO_USERID_FIELD.cpp_type = 3
TEAMMEMBERINFO_NAME_FIELD.name = "name"
TEAMMEMBERINFO_NAME_FIELD.full_name = ".TeamMemberInfo.name"
TEAMMEMBERINFO_NAME_FIELD.number = 2
TEAMMEMBERINFO_NAME_FIELD.index = 1
TEAMMEMBERINFO_NAME_FIELD.label = 2
TEAMMEMBERINFO_NAME_FIELD.has_default_value = false
TEAMMEMBERINFO_NAME_FIELD.default_value = ""
TEAMMEMBERINFO_NAME_FIELD.type = 9
TEAMMEMBERINFO_NAME_FIELD.cpp_type = 9
TEAMMEMBERINFO_ICON_FIELD.name = "icon"
TEAMMEMBERINFO_ICON_FIELD.full_name = ".TeamMemberInfo.icon"
TEAMMEMBERINFO_ICON_FIELD.number = 3
TEAMMEMBERINFO_ICON_FIELD.index = 2
TEAMMEMBERINFO_ICON_FIELD.label = 2
TEAMMEMBERINFO_ICON_FIELD.has_default_value = false
TEAMMEMBERINFO_ICON_FIELD.default_value = 0
TEAMMEMBERINFO_ICON_FIELD.type = 13
TEAMMEMBERINFO_ICON_FIELD.cpp_type = 3
TEAMMEMBERINFO_ICONURL_FIELD.name = "iconUrl"
TEAMMEMBERINFO_ICONURL_FIELD.full_name = ".TeamMemberInfo.iconUrl"
TEAMMEMBERINFO_ICONURL_FIELD.number = 4
TEAMMEMBERINFO_ICONURL_FIELD.index = 3
TEAMMEMBERINFO_ICONURL_FIELD.label = 2
TEAMMEMBERINFO_ICONURL_FIELD.has_default_value = false
TEAMMEMBERINFO_ICONURL_FIELD.default_value = ""
TEAMMEMBERINFO_ICONURL_FIELD.type = 9
TEAMMEMBERINFO_ICONURL_FIELD.cpp_type = 9
TEAMMEMBERINFO_TEAMID_FIELD.name = "teamId"
TEAMMEMBERINFO_TEAMID_FIELD.full_name = ".TeamMemberInfo.teamId"
TEAMMEMBERINFO_TEAMID_FIELD.number = 5
TEAMMEMBERINFO_TEAMID_FIELD.index = 4
TEAMMEMBERINFO_TEAMID_FIELD.label = 2
TEAMMEMBERINFO_TEAMID_FIELD.has_default_value = false
TEAMMEMBERINFO_TEAMID_FIELD.default_value = 0
TEAMMEMBERINFO_TEAMID_FIELD.type = 13
TEAMMEMBERINFO_TEAMID_FIELD.cpp_type = 3
TEAMMEMBERINFO_HEROID_FIELD.name = "heroId"
TEAMMEMBERINFO_HEROID_FIELD.full_name = ".TeamMemberInfo.heroId"
TEAMMEMBERINFO_HEROID_FIELD.number = 6
TEAMMEMBERINFO_HEROID_FIELD.index = 5
TEAMMEMBERINFO_HEROID_FIELD.label = 2
TEAMMEMBERINFO_HEROID_FIELD.has_default_value = false
TEAMMEMBERINFO_HEROID_FIELD.default_value = 0
TEAMMEMBERINFO_HEROID_FIELD.type = 13
TEAMMEMBERINFO_HEROID_FIELD.cpp_type = 3
TEAMMEMBERINFO_PLAYERID_FIELD.name = "playerId"
TEAMMEMBERINFO_PLAYERID_FIELD.full_name = ".TeamMemberInfo.playerId"
TEAMMEMBERINFO_PLAYERID_FIELD.number = 7
TEAMMEMBERINFO_PLAYERID_FIELD.index = 6
TEAMMEMBERINFO_PLAYERID_FIELD.label = 2
TEAMMEMBERINFO_PLAYERID_FIELD.has_default_value = false
TEAMMEMBERINFO_PLAYERID_FIELD.default_value = 0
TEAMMEMBERINFO_PLAYERID_FIELD.type = 13
TEAMMEMBERINFO_PLAYERID_FIELD.cpp_type = 3
TEAMMEMBERINFO_PERCENT_FIELD.name = "percent"
TEAMMEMBERINFO_PERCENT_FIELD.full_name = ".TeamMemberInfo.percent"
TEAMMEMBERINFO_PERCENT_FIELD.number = 8
TEAMMEMBERINFO_PERCENT_FIELD.index = 7
TEAMMEMBERINFO_PERCENT_FIELD.label = 1
TEAMMEMBERINFO_PERCENT_FIELD.has_default_value = false
TEAMMEMBERINFO_PERCENT_FIELD.default_value = 0
TEAMMEMBERINFO_PERCENT_FIELD.type = 13
TEAMMEMBERINFO_PERCENT_FIELD.cpp_type = 3
TEAMMEMBERINFO.name = "TeamMemberInfo"
TEAMMEMBERINFO.full_name = ".TeamMemberInfo"
TEAMMEMBERINFO.nested_types = {}
TEAMMEMBERINFO.enum_types = {}
TEAMMEMBERINFO.fields = {
	TEAMMEMBERINFO_USERID_FIELD,
	TEAMMEMBERINFO_NAME_FIELD,
	TEAMMEMBERINFO_ICON_FIELD,
	TEAMMEMBERINFO_ICONURL_FIELD,
	TEAMMEMBERINFO_TEAMID_FIELD,
	TEAMMEMBERINFO_HEROID_FIELD,
	TEAMMEMBERINFO_PLAYERID_FIELD,
	TEAMMEMBERINFO_PERCENT_FIELD
}
TEAMMEMBERINFO.is_extendable = false
TEAMMEMBERINFO.extensions = {}
TEAMINFO_TEAMID_FIELD.name = "teamId"
TEAMINFO_TEAMID_FIELD.full_name = ".TeamInfo.teamId"
TEAMINFO_TEAMID_FIELD.number = 1
TEAMINFO_TEAMID_FIELD.index = 0
TEAMINFO_TEAMID_FIELD.label = 2
TEAMINFO_TEAMID_FIELD.has_default_value = false
TEAMINFO_TEAMID_FIELD.default_value = 0
TEAMINFO_TEAMID_FIELD.type = 13
TEAMINFO_TEAMID_FIELD.cpp_type = 3
TEAMINFO_TEAMMEMBERINFO_FIELD.name = "teamMemberInfo"
TEAMINFO_TEAMMEMBERINFO_FIELD.full_name = ".TeamInfo.teamMemberInfo"
TEAMINFO_TEAMMEMBERINFO_FIELD.number = 2
TEAMINFO_TEAMMEMBERINFO_FIELD.index = 1
TEAMINFO_TEAMMEMBERINFO_FIELD.label = 3
TEAMINFO_TEAMMEMBERINFO_FIELD.has_default_value = false
TEAMINFO_TEAMMEMBERINFO_FIELD.default_value = {}
TEAMINFO_TEAMMEMBERINFO_FIELD.message_type = TEAMMEMBERINFO
TEAMINFO_TEAMMEMBERINFO_FIELD.type = 11
TEAMINFO_TEAMMEMBERINFO_FIELD.cpp_type = 10
TEAMINFO.name = "TeamInfo"
TEAMINFO.full_name = ".TeamInfo"
TEAMINFO.nested_types = {}
TEAMINFO.enum_types = {}
TEAMINFO.fields = {
	TEAMINFO_TEAMID_FIELD,
	TEAMINFO_TEAMMEMBERINFO_FIELD
}
TEAMINFO.is_extendable = false
TEAMINFO.extensions = {}
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.name = "goNextTime"
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.full_name = ".RespBeginChoosingHero.goNextTime"
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.number = 1
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.index = 0
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.label = 2
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.has_default_value = false
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.default_value = 0
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.type = 13
RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD.cpp_type = 3
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.name = "teamInfo"
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.full_name = ".RespBeginChoosingHero.teamInfo"
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.number = 2
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.index = 1
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.label = 2
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.has_default_value = false
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.default_value = nil
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.message_type = TEAMINFO
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.type = 11
RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD.cpp_type = 10
RESPBEGINCHOOSINGHERO.name = "RespBeginChoosingHero"
RESPBEGINCHOOSINGHERO.full_name = ".RespBeginChoosingHero"
RESPBEGINCHOOSINGHERO.nested_types = {}
RESPBEGINCHOOSINGHERO.enum_types = {}
RESPBEGINCHOOSINGHERO.fields = {
	RESPBEGINCHOOSINGHERO_GONEXTTIME_FIELD,
	RESPBEGINCHOOSINGHERO_TEAMINFO_FIELD
}
RESPBEGINCHOOSINGHERO.is_extendable = false
RESPBEGINCHOOSINGHERO.extensions = {}
REQCHOOSEHERO_HEROID_FIELD.name = "heroId"
REQCHOOSEHERO_HEROID_FIELD.full_name = ".ReqChooseHero.heroId"
REQCHOOSEHERO_HEROID_FIELD.number = 1
REQCHOOSEHERO_HEROID_FIELD.index = 0
REQCHOOSEHERO_HEROID_FIELD.label = 2
REQCHOOSEHERO_HEROID_FIELD.has_default_value = false
REQCHOOSEHERO_HEROID_FIELD.default_value = 0
REQCHOOSEHERO_HEROID_FIELD.type = 13
REQCHOOSEHERO_HEROID_FIELD.cpp_type = 3
REQCHOOSEHERO.name = "ReqChooseHero"
REQCHOOSEHERO.full_name = ".ReqChooseHero"
REQCHOOSEHERO.nested_types = {}
REQCHOOSEHERO.enum_types = {}
REQCHOOSEHERO.fields = {
	REQCHOOSEHERO_HEROID_FIELD
}
REQCHOOSEHERO.is_extendable = false
REQCHOOSEHERO.extensions = {}
RESPCHOOSEHERO_USERID_FIELD.name = "userId"
RESPCHOOSEHERO_USERID_FIELD.full_name = ".RespChooseHero.userId"
RESPCHOOSEHERO_USERID_FIELD.number = 1
RESPCHOOSEHERO_USERID_FIELD.index = 0
RESPCHOOSEHERO_USERID_FIELD.label = 2
RESPCHOOSEHERO_USERID_FIELD.has_default_value = false
RESPCHOOSEHERO_USERID_FIELD.default_value = 0
RESPCHOOSEHERO_USERID_FIELD.type = 13
RESPCHOOSEHERO_USERID_FIELD.cpp_type = 3
RESPCHOOSEHERO_HEROID_FIELD.name = "heroId"
RESPCHOOSEHERO_HEROID_FIELD.full_name = ".RespChooseHero.heroId"
RESPCHOOSEHERO_HEROID_FIELD.number = 2
RESPCHOOSEHERO_HEROID_FIELD.index = 1
RESPCHOOSEHERO_HEROID_FIELD.label = 2
RESPCHOOSEHERO_HEROID_FIELD.has_default_value = false
RESPCHOOSEHERO_HEROID_FIELD.default_value = 0
RESPCHOOSEHERO_HEROID_FIELD.type = 13
RESPCHOOSEHERO_HEROID_FIELD.cpp_type = 3
RESPCHOOSEHERO.name = "RespChooseHero"
RESPCHOOSEHERO.full_name = ".RespChooseHero"
RESPCHOOSEHERO.nested_types = {}
RESPCHOOSEHERO.enum_types = {}
RESPCHOOSEHERO.fields = {
	RESPCHOOSEHERO_USERID_FIELD,
	RESPCHOOSEHERO_HEROID_FIELD
}
RESPCHOOSEHERO.is_extendable = false
RESPCHOOSEHERO.extensions = {}
REQCONFIRMHERO.name = "ReqConfirmHero"
REQCONFIRMHERO.full_name = ".ReqConfirmHero"
REQCONFIRMHERO.nested_types = {}
REQCONFIRMHERO.enum_types = {}
REQCONFIRMHERO.fields = {}
REQCONFIRMHERO.is_extendable = false
REQCONFIRMHERO.extensions = {}
RESPCONFIRMHERO_USERID_FIELD.name = "userId"
RESPCONFIRMHERO_USERID_FIELD.full_name = ".RespConfirmHero.userId"
RESPCONFIRMHERO_USERID_FIELD.number = 1
RESPCONFIRMHERO_USERID_FIELD.index = 0
RESPCONFIRMHERO_USERID_FIELD.label = 2
RESPCONFIRMHERO_USERID_FIELD.has_default_value = false
RESPCONFIRMHERO_USERID_FIELD.default_value = 0
RESPCONFIRMHERO_USERID_FIELD.type = 13
RESPCONFIRMHERO_USERID_FIELD.cpp_type = 3
RESPCONFIRMHERO_HEROID_FIELD.name = "heroId"
RESPCONFIRMHERO_HEROID_FIELD.full_name = ".RespConfirmHero.heroId"
RESPCONFIRMHERO_HEROID_FIELD.number = 2
RESPCONFIRMHERO_HEROID_FIELD.index = 1
RESPCONFIRMHERO_HEROID_FIELD.label = 2
RESPCONFIRMHERO_HEROID_FIELD.has_default_value = false
RESPCONFIRMHERO_HEROID_FIELD.default_value = 0
RESPCONFIRMHERO_HEROID_FIELD.type = 13
RESPCONFIRMHERO_HEROID_FIELD.cpp_type = 3
RESPCONFIRMHERO.name = "RespConfirmHero"
RESPCONFIRMHERO.full_name = ".RespConfirmHero"
RESPCONFIRMHERO.nested_types = {}
RESPCONFIRMHERO.enum_types = {}
RESPCONFIRMHERO.fields = {
	RESPCONFIRMHERO_USERID_FIELD,
	RESPCONFIRMHERO_HEROID_FIELD
}
RESPCONFIRMHERO.is_extendable = false
RESPCONFIRMHERO.extensions = {}
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.name = "goNextTime"
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.full_name = ".RespBeginGameLoading.goNextTime"
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.number = 1
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.index = 0
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.label = 2
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.has_default_value = false
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.default_value = 0
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.type = 13
RESPBEGINGAMELOADING_GONEXTTIME_FIELD.cpp_type = 3
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.name = "randomSeed"
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.full_name = ".RespBeginGameLoading.randomSeed"
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.number = 2
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.index = 1
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.label = 2
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.has_default_value = false
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.default_value = 0
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.type = 13
RESPBEGINGAMELOADING_RANDOMSEED_FIELD.cpp_type = 3
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.name = "playerInfo"
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.full_name = ".RespBeginGameLoading.playerInfo"
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.number = 3
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.index = 2
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.label = 3
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.has_default_value = false
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.default_value = {}
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.message_type = TEAMMEMBERINFO
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.type = 11
RESPBEGINGAMELOADING_PLAYERINFO_FIELD.cpp_type = 10
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.name = "frameLogCount"
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.full_name = ".RespBeginGameLoading.frameLogCount"
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.number = 4
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.index = 3
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.label = 1
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.has_default_value = false
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.default_value = 0
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.type = 13
RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD.cpp_type = 3
RESPBEGINGAMELOADING.name = "RespBeginGameLoading"
RESPBEGINGAMELOADING.full_name = ".RespBeginGameLoading"
RESPBEGINGAMELOADING.nested_types = {}
RESPBEGINGAMELOADING.enum_types = {}
RESPBEGINGAMELOADING.fields = {
	RESPBEGINGAMELOADING_GONEXTTIME_FIELD,
	RESPBEGINGAMELOADING_RANDOMSEED_FIELD,
	RESPBEGINGAMELOADING_PLAYERINFO_FIELD,
	RESPBEGINGAMELOADING_FRAMELOGCOUNT_FIELD
}
RESPBEGINGAMELOADING.is_extendable = false
RESPBEGINGAMELOADING.extensions = {}
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.name = "percent"
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.full_name = ".ReqClientLoadingUpdate.percent"
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.number = 1
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.index = 0
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.label = 2
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.has_default_value = false
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.default_value = 0
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.type = 13
REQCLIENTLOADINGUPDATE_PERCENT_FIELD.cpp_type = 3
REQCLIENTLOADINGUPDATE.name = "ReqClientLoadingUpdate"
REQCLIENTLOADINGUPDATE.full_name = ".ReqClientLoadingUpdate"
REQCLIENTLOADINGUPDATE.nested_types = {}
REQCLIENTLOADINGUPDATE.enum_types = {}
REQCLIENTLOADINGUPDATE.fields = {
	REQCLIENTLOADINGUPDATE_PERCENT_FIELD
}
REQCLIENTLOADINGUPDATE.is_extendable = false
REQCLIENTLOADINGUPDATE.extensions = {}
RESPCLIENTLOADINGUPDATE_USERID_FIELD.name = "userId"
RESPCLIENTLOADINGUPDATE_USERID_FIELD.full_name = ".RespClientLoadingUpdate.userId"
RESPCLIENTLOADINGUPDATE_USERID_FIELD.number = 1
RESPCLIENTLOADINGUPDATE_USERID_FIELD.index = 0
RESPCLIENTLOADINGUPDATE_USERID_FIELD.label = 2
RESPCLIENTLOADINGUPDATE_USERID_FIELD.has_default_value = false
RESPCLIENTLOADINGUPDATE_USERID_FIELD.default_value = 0
RESPCLIENTLOADINGUPDATE_USERID_FIELD.type = 13
RESPCLIENTLOADINGUPDATE_USERID_FIELD.cpp_type = 3
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.name = "percent"
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.full_name = ".RespClientLoadingUpdate.percent"
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.number = 2
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.index = 1
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.label = 2
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.has_default_value = false
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.default_value = 0
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.type = 13
RESPCLIENTLOADINGUPDATE_PERCENT_FIELD.cpp_type = 3
RESPCLIENTLOADINGUPDATE.name = "RespClientLoadingUpdate"
RESPCLIENTLOADINGUPDATE.full_name = ".RespClientLoadingUpdate"
RESPCLIENTLOADINGUPDATE.nested_types = {}
RESPCLIENTLOADINGUPDATE.enum_types = {}
RESPCLIENTLOADINGUPDATE.fields = {
	RESPCLIENTLOADINGUPDATE_USERID_FIELD,
	RESPCLIENTLOADINGUPDATE_PERCENT_FIELD
}
RESPCLIENTLOADINGUPDATE.is_extendable = false
RESPCLIENTLOADINGUPDATE.extensions = {}
RESPSTARTGAME.name = "RespStartGame"
RESPSTARTGAME.full_name = ".RespStartGame"
RESPSTARTGAME.nested_types = {}
RESPSTARTGAME.enum_types = {}
RESPSTARTGAME.fields = {}
RESPSTARTGAME.is_extendable = false
RESPSTARTGAME.extensions = {}
BATTLEROOMUSERINFO_USERID_FIELD.name = "userId"
BATTLEROOMUSERINFO_USERID_FIELD.full_name = ".BattleRoomUserInfo.userId"
BATTLEROOMUSERINFO_USERID_FIELD.number = 1
BATTLEROOMUSERINFO_USERID_FIELD.index = 0
BATTLEROOMUSERINFO_USERID_FIELD.label = 2
BATTLEROOMUSERINFO_USERID_FIELD.has_default_value = false
BATTLEROOMUSERINFO_USERID_FIELD.default_value = 0
BATTLEROOMUSERINFO_USERID_FIELD.type = 13
BATTLEROOMUSERINFO_USERID_FIELD.cpp_type = 3
BATTLEROOMUSERINFO_SERVERID_FIELD.name = "serverId"
BATTLEROOMUSERINFO_SERVERID_FIELD.full_name = ".BattleRoomUserInfo.serverId"
BATTLEROOMUSERINFO_SERVERID_FIELD.number = 2
BATTLEROOMUSERINFO_SERVERID_FIELD.index = 1
BATTLEROOMUSERINFO_SERVERID_FIELD.label = 2
BATTLEROOMUSERINFO_SERVERID_FIELD.has_default_value = false
BATTLEROOMUSERINFO_SERVERID_FIELD.default_value = 0
BATTLEROOMUSERINFO_SERVERID_FIELD.type = 13
BATTLEROOMUSERINFO_SERVERID_FIELD.cpp_type = 3
BATTLEROOMUSERINFO_PLAYERID_FIELD.name = "playerId"
BATTLEROOMUSERINFO_PLAYERID_FIELD.full_name = ".BattleRoomUserInfo.playerId"
BATTLEROOMUSERINFO_PLAYERID_FIELD.number = 3
BATTLEROOMUSERINFO_PLAYERID_FIELD.index = 2
BATTLEROOMUSERINFO_PLAYERID_FIELD.label = 2
BATTLEROOMUSERINFO_PLAYERID_FIELD.has_default_value = false
BATTLEROOMUSERINFO_PLAYERID_FIELD.default_value = 0
BATTLEROOMUSERINFO_PLAYERID_FIELD.type = 13
BATTLEROOMUSERINFO_PLAYERID_FIELD.cpp_type = 3
BATTLEROOMUSERINFO.name = "BattleRoomUserInfo"
BATTLEROOMUSERINFO.full_name = ".BattleRoomUserInfo"
BATTLEROOMUSERINFO.nested_types = {}
BATTLEROOMUSERINFO.enum_types = {}
BATTLEROOMUSERINFO.fields = {
	BATTLEROOMUSERINFO_USERID_FIELD,
	BATTLEROOMUSERINFO_SERVERID_FIELD,
	BATTLEROOMUSERINFO_PLAYERID_FIELD
}
BATTLEROOMUSERINFO.is_extendable = false
BATTLEROOMUSERINFO.extensions = {}
BATTLEROOMINFO_ROOMID_FIELD.name = "roomId"
BATTLEROOMINFO_ROOMID_FIELD.full_name = ".BattleRoomInfo.roomId"
BATTLEROOMINFO_ROOMID_FIELD.number = 1
BATTLEROOMINFO_ROOMID_FIELD.index = 0
BATTLEROOMINFO_ROOMID_FIELD.label = 2
BATTLEROOMINFO_ROOMID_FIELD.has_default_value = false
BATTLEROOMINFO_ROOMID_FIELD.default_value = 0
BATTLEROOMINFO_ROOMID_FIELD.type = 13
BATTLEROOMINFO_ROOMID_FIELD.cpp_type = 3
BATTLEROOMINFO_GAMETYPE_FIELD.name = "gameType"
BATTLEROOMINFO_GAMETYPE_FIELD.full_name = ".BattleRoomInfo.gameType"
BATTLEROOMINFO_GAMETYPE_FIELD.number = 2
BATTLEROOMINFO_GAMETYPE_FIELD.index = 1
BATTLEROOMINFO_GAMETYPE_FIELD.label = 2
BATTLEROOMINFO_GAMETYPE_FIELD.has_default_value = false
BATTLEROOMINFO_GAMETYPE_FIELD.default_value = 0
BATTLEROOMINFO_GAMETYPE_FIELD.type = 13
BATTLEROOMINFO_GAMETYPE_FIELD.cpp_type = 3
BATTLEROOMINFO_STATE_FIELD.name = "state"
BATTLEROOMINFO_STATE_FIELD.full_name = ".BattleRoomInfo.state"
BATTLEROOMINFO_STATE_FIELD.number = 3
BATTLEROOMINFO_STATE_FIELD.index = 2
BATTLEROOMINFO_STATE_FIELD.label = 2
BATTLEROOMINFO_STATE_FIELD.has_default_value = false
BATTLEROOMINFO_STATE_FIELD.default_value = 0
BATTLEROOMINFO_STATE_FIELD.type = 13
BATTLEROOMINFO_STATE_FIELD.cpp_type = 3
BATTLEROOMINFO_NEEDPLAYERS_FIELD.name = "needPlayers"
BATTLEROOMINFO_NEEDPLAYERS_FIELD.full_name = ".BattleRoomInfo.needPlayers"
BATTLEROOMINFO_NEEDPLAYERS_FIELD.number = 4
BATTLEROOMINFO_NEEDPLAYERS_FIELD.index = 3
BATTLEROOMINFO_NEEDPLAYERS_FIELD.label = 2
BATTLEROOMINFO_NEEDPLAYERS_FIELD.has_default_value = false
BATTLEROOMINFO_NEEDPLAYERS_FIELD.default_value = 0
BATTLEROOMINFO_NEEDPLAYERS_FIELD.type = 13
BATTLEROOMINFO_NEEDPLAYERS_FIELD.cpp_type = 3
BATTLEROOMINFO_GAMEID_FIELD.name = "gameId"
BATTLEROOMINFO_GAMEID_FIELD.full_name = ".BattleRoomInfo.gameId"
BATTLEROOMINFO_GAMEID_FIELD.number = 5
BATTLEROOMINFO_GAMEID_FIELD.index = 4
BATTLEROOMINFO_GAMEID_FIELD.label = 1
BATTLEROOMINFO_GAMEID_FIELD.has_default_value = false
BATTLEROOMINFO_GAMEID_FIELD.default_value = ""
BATTLEROOMINFO_GAMEID_FIELD.type = 9
BATTLEROOMINFO_GAMEID_FIELD.cpp_type = 9
BATTLEROOMINFO_USERS_FIELD.name = "users"
BATTLEROOMINFO_USERS_FIELD.full_name = ".BattleRoomInfo.users"
BATTLEROOMINFO_USERS_FIELD.number = 6
BATTLEROOMINFO_USERS_FIELD.index = 5
BATTLEROOMINFO_USERS_FIELD.label = 3
BATTLEROOMINFO_USERS_FIELD.has_default_value = false
BATTLEROOMINFO_USERS_FIELD.default_value = {}
BATTLEROOMINFO_USERS_FIELD.message_type = BATTLEROOMUSERINFO
BATTLEROOMINFO_USERS_FIELD.type = 11
BATTLEROOMINFO_USERS_FIELD.cpp_type = 10
BATTLEROOMINFO.name = "BattleRoomInfo"
BATTLEROOMINFO.full_name = ".BattleRoomInfo"
BATTLEROOMINFO.nested_types = {}
BATTLEROOMINFO.enum_types = {}
BATTLEROOMINFO.fields = {
	BATTLEROOMINFO_ROOMID_FIELD,
	BATTLEROOMINFO_GAMETYPE_FIELD,
	BATTLEROOMINFO_STATE_FIELD,
	BATTLEROOMINFO_NEEDPLAYERS_FIELD,
	BATTLEROOMINFO_GAMEID_FIELD,
	BATTLEROOMINFO_USERS_FIELD
}
BATTLEROOMINFO.is_extendable = false
BATTLEROOMINFO.extensions = {}
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.name = "roomInfos"
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.full_name = ".ReqUploadRoomInfosToSearch.roomInfos"
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.number = 1
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.index = 0
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.label = 3
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.has_default_value = false
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.default_value = {}
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.message_type = BATTLEROOMINFO
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.type = 11
REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD.cpp_type = 10
REQUPLOADROOMINFOSTOSEARCH.name = "ReqUploadRoomInfosToSearch"
REQUPLOADROOMINFOSTOSEARCH.full_name = ".ReqUploadRoomInfosToSearch"
REQUPLOADROOMINFOSTOSEARCH.nested_types = {}
REQUPLOADROOMINFOSTOSEARCH.enum_types = {}
REQUPLOADROOMINFOSTOSEARCH.fields = {
	REQUPLOADROOMINFOSTOSEARCH_ROOMINFOS_FIELD
}
REQUPLOADROOMINFOSTOSEARCH.is_extendable = false
REQUPLOADROOMINFOSTOSEARCH.extensions = {}
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.name = "roomInfo"
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.full_name = ".ReqUpdateRoomInfoToSearch.roomInfo"
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.number = 1
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.index = 0
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.label = 2
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.has_default_value = false
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.default_value = nil
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.message_type = BATTLEROOMINFO
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.type = 11
REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD.cpp_type = 10
REQUPDATEROOMINFOTOSEARCH.name = "ReqUpdateRoomInfoToSearch"
REQUPDATEROOMINFOTOSEARCH.full_name = ".ReqUpdateRoomInfoToSearch"
REQUPDATEROOMINFOTOSEARCH.nested_types = {}
REQUPDATEROOMINFOTOSEARCH.enum_types = {}
REQUPDATEROOMINFOTOSEARCH.fields = {
	REQUPDATEROOMINFOTOSEARCH_ROOMINFO_FIELD
}
REQUPDATEROOMINFOTOSEARCH.is_extendable = false
REQUPDATEROOMINFOTOSEARCH.extensions = {}
REQUSERLEAVEGAMEINZONE_USERID_FIELD.name = "userId"
REQUSERLEAVEGAMEINZONE_USERID_FIELD.full_name = ".ReqUserLeaveGameInZone.userId"
REQUSERLEAVEGAMEINZONE_USERID_FIELD.number = 1
REQUSERLEAVEGAMEINZONE_USERID_FIELD.index = 0
REQUSERLEAVEGAMEINZONE_USERID_FIELD.label = 2
REQUSERLEAVEGAMEINZONE_USERID_FIELD.has_default_value = false
REQUSERLEAVEGAMEINZONE_USERID_FIELD.default_value = 0
REQUSERLEAVEGAMEINZONE_USERID_FIELD.type = 13
REQUSERLEAVEGAMEINZONE_USERID_FIELD.cpp_type = 3
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.name = "roomId"
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.full_name = ".ReqUserLeaveGameInZone.roomId"
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.number = 2
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.index = 1
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.label = 2
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.has_default_value = false
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.default_value = 0
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.type = 13
REQUSERLEAVEGAMEINZONE_ROOMID_FIELD.cpp_type = 3
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.name = "rematch"
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.full_name = ".ReqUserLeaveGameInZone.rematch"
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.number = 3
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.index = 2
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.label = 2
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.has_default_value = false
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.default_value = false
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.type = 8
REQUSERLEAVEGAMEINZONE_REMATCH_FIELD.cpp_type = 7
REQUSERLEAVEGAMEINZONE.name = "ReqUserLeaveGameInZone"
REQUSERLEAVEGAMEINZONE.full_name = ".ReqUserLeaveGameInZone"
REQUSERLEAVEGAMEINZONE.nested_types = {}
REQUSERLEAVEGAMEINZONE.enum_types = {}
REQUSERLEAVEGAMEINZONE.fields = {
	REQUSERLEAVEGAMEINZONE_USERID_FIELD,
	REQUSERLEAVEGAMEINZONE_ROOMID_FIELD,
	REQUSERLEAVEGAMEINZONE_REMATCH_FIELD
}
REQUSERLEAVEGAMEINZONE.is_extendable = false
REQUSERLEAVEGAMEINZONE.extensions = {}
REQMATCHGAMEINZONE_GAMETYPE_FIELD.name = "gameType"
REQMATCHGAMEINZONE_GAMETYPE_FIELD.full_name = ".ReqMatchGameInZone.gameType"
REQMATCHGAMEINZONE_GAMETYPE_FIELD.number = 1
REQMATCHGAMEINZONE_GAMETYPE_FIELD.index = 0
REQMATCHGAMEINZONE_GAMETYPE_FIELD.label = 2
REQMATCHGAMEINZONE_GAMETYPE_FIELD.has_default_value = false
REQMATCHGAMEINZONE_GAMETYPE_FIELD.default_value = 0
REQMATCHGAMEINZONE_GAMETYPE_FIELD.type = 13
REQMATCHGAMEINZONE_GAMETYPE_FIELD.cpp_type = 3
REQMATCHGAMEINZONE_NAME_FIELD.name = "name"
REQMATCHGAMEINZONE_NAME_FIELD.full_name = ".ReqMatchGameInZone.name"
REQMATCHGAMEINZONE_NAME_FIELD.number = 2
REQMATCHGAMEINZONE_NAME_FIELD.index = 1
REQMATCHGAMEINZONE_NAME_FIELD.label = 1
REQMATCHGAMEINZONE_NAME_FIELD.has_default_value = false
REQMATCHGAMEINZONE_NAME_FIELD.default_value = ""
REQMATCHGAMEINZONE_NAME_FIELD.type = 9
REQMATCHGAMEINZONE_NAME_FIELD.cpp_type = 9
REQMATCHGAMEINZONE_ICON_FIELD.name = "icon"
REQMATCHGAMEINZONE_ICON_FIELD.full_name = ".ReqMatchGameInZone.icon"
REQMATCHGAMEINZONE_ICON_FIELD.number = 3
REQMATCHGAMEINZONE_ICON_FIELD.index = 2
REQMATCHGAMEINZONE_ICON_FIELD.label = 1
REQMATCHGAMEINZONE_ICON_FIELD.has_default_value = false
REQMATCHGAMEINZONE_ICON_FIELD.default_value = 0
REQMATCHGAMEINZONE_ICON_FIELD.type = 13
REQMATCHGAMEINZONE_ICON_FIELD.cpp_type = 3
REQMATCHGAMEINZONE_ICONURL_FIELD.name = "iconUrl"
REQMATCHGAMEINZONE_ICONURL_FIELD.full_name = ".ReqMatchGameInZone.iconUrl"
REQMATCHGAMEINZONE_ICONURL_FIELD.number = 4
REQMATCHGAMEINZONE_ICONURL_FIELD.index = 3
REQMATCHGAMEINZONE_ICONURL_FIELD.label = 1
REQMATCHGAMEINZONE_ICONURL_FIELD.has_default_value = false
REQMATCHGAMEINZONE_ICONURL_FIELD.default_value = ""
REQMATCHGAMEINZONE_ICONURL_FIELD.type = 9
REQMATCHGAMEINZONE_ICONURL_FIELD.cpp_type = 9
REQMATCHGAMEINZONE_PLAYERID_FIELD.name = "playerId"
REQMATCHGAMEINZONE_PLAYERID_FIELD.full_name = ".ReqMatchGameInZone.playerId"
REQMATCHGAMEINZONE_PLAYERID_FIELD.number = 5
REQMATCHGAMEINZONE_PLAYERID_FIELD.index = 4
REQMATCHGAMEINZONE_PLAYERID_FIELD.label = 1
REQMATCHGAMEINZONE_PLAYERID_FIELD.has_default_value = false
REQMATCHGAMEINZONE_PLAYERID_FIELD.default_value = 0
REQMATCHGAMEINZONE_PLAYERID_FIELD.type = 13
REQMATCHGAMEINZONE_PLAYERID_FIELD.cpp_type = 3
REQMATCHGAMEINZONE.name = "ReqMatchGameInZone"
REQMATCHGAMEINZONE.full_name = ".ReqMatchGameInZone"
REQMATCHGAMEINZONE.nested_types = {}
REQMATCHGAMEINZONE.enum_types = {}
REQMATCHGAMEINZONE.fields = {
	REQMATCHGAMEINZONE_GAMETYPE_FIELD,
	REQMATCHGAMEINZONE_NAME_FIELD,
	REQMATCHGAMEINZONE_ICON_FIELD,
	REQMATCHGAMEINZONE_ICONURL_FIELD,
	REQMATCHGAMEINZONE_PLAYERID_FIELD
}
REQMATCHGAMEINZONE.is_extendable = false
REQMATCHGAMEINZONE.extensions = {}
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.name = "battleServerHost"
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.full_name = ".RespMatchGameInZone.battleServerHost"
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.number = 1
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.index = 0
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.label = 2
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.has_default_value = false
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.default_value = ""
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.type = 9
RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD.cpp_type = 9
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.name = "battleServerPort"
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.full_name = ".RespMatchGameInZone.battleServerPort"
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.number = 2
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.index = 1
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.label = 2
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.has_default_value = false
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.default_value = 0
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.type = 13
RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD.cpp_type = 3
RESPMATCHGAMEINZONE_SIGN_FIELD.name = "sign"
RESPMATCHGAMEINZONE_SIGN_FIELD.full_name = ".RespMatchGameInZone.sign"
RESPMATCHGAMEINZONE_SIGN_FIELD.number = 3
RESPMATCHGAMEINZONE_SIGN_FIELD.index = 2
RESPMATCHGAMEINZONE_SIGN_FIELD.label = 2
RESPMATCHGAMEINZONE_SIGN_FIELD.has_default_value = false
RESPMATCHGAMEINZONE_SIGN_FIELD.default_value = 0
RESPMATCHGAMEINZONE_SIGN_FIELD.type = 13
RESPMATCHGAMEINZONE_SIGN_FIELD.cpp_type = 3
RESPMATCHGAMEINZONE.name = "RespMatchGameInZone"
RESPMATCHGAMEINZONE.full_name = ".RespMatchGameInZone"
RESPMATCHGAMEINZONE.nested_types = {}
RESPMATCHGAMEINZONE.enum_types = {}
RESPMATCHGAMEINZONE.fields = {
	RESPMATCHGAMEINZONE_BATTLESERVERHOST_FIELD,
	RESPMATCHGAMEINZONE_BATTLESERVERPORT_FIELD,
	RESPMATCHGAMEINZONE_SIGN_FIELD
}
RESPMATCHGAMEINZONE.is_extendable = false
RESPMATCHGAMEINZONE.extensions = {}
REQJOINGAMEINZONE_ROOMID_FIELD.name = "roomId"
REQJOINGAMEINZONE_ROOMID_FIELD.full_name = ".ReqJoinGameInZone.roomId"
REQJOINGAMEINZONE_ROOMID_FIELD.number = 1
REQJOINGAMEINZONE_ROOMID_FIELD.index = 0
REQJOINGAMEINZONE_ROOMID_FIELD.label = 2
REQJOINGAMEINZONE_ROOMID_FIELD.has_default_value = false
REQJOINGAMEINZONE_ROOMID_FIELD.default_value = 0
REQJOINGAMEINZONE_ROOMID_FIELD.type = 13
REQJOINGAMEINZONE_ROOMID_FIELD.cpp_type = 3
REQJOINGAMEINZONE_GAMETYPE_FIELD.name = "gameType"
REQJOINGAMEINZONE_GAMETYPE_FIELD.full_name = ".ReqJoinGameInZone.gameType"
REQJOINGAMEINZONE_GAMETYPE_FIELD.number = 2
REQJOINGAMEINZONE_GAMETYPE_FIELD.index = 1
REQJOINGAMEINZONE_GAMETYPE_FIELD.label = 2
REQJOINGAMEINZONE_GAMETYPE_FIELD.has_default_value = false
REQJOINGAMEINZONE_GAMETYPE_FIELD.default_value = 0
REQJOINGAMEINZONE_GAMETYPE_FIELD.type = 13
REQJOINGAMEINZONE_GAMETYPE_FIELD.cpp_type = 3
REQJOINGAMEINZONE_USERID_FIELD.name = "userId"
REQJOINGAMEINZONE_USERID_FIELD.full_name = ".ReqJoinGameInZone.userId"
REQJOINGAMEINZONE_USERID_FIELD.number = 3
REQJOINGAMEINZONE_USERID_FIELD.index = 2
REQJOINGAMEINZONE_USERID_FIELD.label = 2
REQJOINGAMEINZONE_USERID_FIELD.has_default_value = false
REQJOINGAMEINZONE_USERID_FIELD.default_value = 0
REQJOINGAMEINZONE_USERID_FIELD.type = 13
REQJOINGAMEINZONE_USERID_FIELD.cpp_type = 3
REQJOINGAMEINZONE_NAME_FIELD.name = "name"
REQJOINGAMEINZONE_NAME_FIELD.full_name = ".ReqJoinGameInZone.name"
REQJOINGAMEINZONE_NAME_FIELD.number = 4
REQJOINGAMEINZONE_NAME_FIELD.index = 3
REQJOINGAMEINZONE_NAME_FIELD.label = 2
REQJOINGAMEINZONE_NAME_FIELD.has_default_value = false
REQJOINGAMEINZONE_NAME_FIELD.default_value = ""
REQJOINGAMEINZONE_NAME_FIELD.type = 9
REQJOINGAMEINZONE_NAME_FIELD.cpp_type = 9
REQJOINGAMEINZONE_ICON_FIELD.name = "icon"
REQJOINGAMEINZONE_ICON_FIELD.full_name = ".ReqJoinGameInZone.icon"
REQJOINGAMEINZONE_ICON_FIELD.number = 5
REQJOINGAMEINZONE_ICON_FIELD.index = 4
REQJOINGAMEINZONE_ICON_FIELD.label = 2
REQJOINGAMEINZONE_ICON_FIELD.has_default_value = false
REQJOINGAMEINZONE_ICON_FIELD.default_value = 0
REQJOINGAMEINZONE_ICON_FIELD.type = 13
REQJOINGAMEINZONE_ICON_FIELD.cpp_type = 3
REQJOINGAMEINZONE_ICONURL_FIELD.name = "iconUrl"
REQJOINGAMEINZONE_ICONURL_FIELD.full_name = ".ReqJoinGameInZone.iconUrl"
REQJOINGAMEINZONE_ICONURL_FIELD.number = 6
REQJOINGAMEINZONE_ICONURL_FIELD.index = 5
REQJOINGAMEINZONE_ICONURL_FIELD.label = 2
REQJOINGAMEINZONE_ICONURL_FIELD.has_default_value = false
REQJOINGAMEINZONE_ICONURL_FIELD.default_value = ""
REQJOINGAMEINZONE_ICONURL_FIELD.type = 9
REQJOINGAMEINZONE_ICONURL_FIELD.cpp_type = 9
REQJOINGAMEINZONE_PLAYERID_FIELD.name = "playerId"
REQJOINGAMEINZONE_PLAYERID_FIELD.full_name = ".ReqJoinGameInZone.playerId"
REQJOINGAMEINZONE_PLAYERID_FIELD.number = 7
REQJOINGAMEINZONE_PLAYERID_FIELD.index = 6
REQJOINGAMEINZONE_PLAYERID_FIELD.label = 1
REQJOINGAMEINZONE_PLAYERID_FIELD.has_default_value = false
REQJOINGAMEINZONE_PLAYERID_FIELD.default_value = 0
REQJOINGAMEINZONE_PLAYERID_FIELD.type = 13
REQJOINGAMEINZONE_PLAYERID_FIELD.cpp_type = 3
REQJOINGAMEINZONE.name = "ReqJoinGameInZone"
REQJOINGAMEINZONE.full_name = ".ReqJoinGameInZone"
REQJOINGAMEINZONE.nested_types = {}
REQJOINGAMEINZONE.enum_types = {}
REQJOINGAMEINZONE.fields = {
	REQJOINGAMEINZONE_ROOMID_FIELD,
	REQJOINGAMEINZONE_GAMETYPE_FIELD,
	REQJOINGAMEINZONE_USERID_FIELD,
	REQJOINGAMEINZONE_NAME_FIELD,
	REQJOINGAMEINZONE_ICON_FIELD,
	REQJOINGAMEINZONE_ICONURL_FIELD,
	REQJOINGAMEINZONE_PLAYERID_FIELD
}
REQJOINGAMEINZONE.is_extendable = false
REQJOINGAMEINZONE.extensions = {}
RESPJOINGAMEINZONE_ROOMID_FIELD.name = "roomId"
RESPJOINGAMEINZONE_ROOMID_FIELD.full_name = ".RespJoinGameInZone.roomId"
RESPJOINGAMEINZONE_ROOMID_FIELD.number = 1
RESPJOINGAMEINZONE_ROOMID_FIELD.index = 0
RESPJOINGAMEINZONE_ROOMID_FIELD.label = 2
RESPJOINGAMEINZONE_ROOMID_FIELD.has_default_value = false
RESPJOINGAMEINZONE_ROOMID_FIELD.default_value = 0
RESPJOINGAMEINZONE_ROOMID_FIELD.type = 13
RESPJOINGAMEINZONE_ROOMID_FIELD.cpp_type = 3
RESPJOINGAMEINZONE_GAMETYPE_FIELD.name = "gameType"
RESPJOINGAMEINZONE_GAMETYPE_FIELD.full_name = ".RespJoinGameInZone.gameType"
RESPJOINGAMEINZONE_GAMETYPE_FIELD.number = 2
RESPJOINGAMEINZONE_GAMETYPE_FIELD.index = 1
RESPJOINGAMEINZONE_GAMETYPE_FIELD.label = 2
RESPJOINGAMEINZONE_GAMETYPE_FIELD.has_default_value = false
RESPJOINGAMEINZONE_GAMETYPE_FIELD.default_value = 0
RESPJOINGAMEINZONE_GAMETYPE_FIELD.type = 13
RESPJOINGAMEINZONE_GAMETYPE_FIELD.cpp_type = 3
RESPJOINGAMEINZONE_USERID_FIELD.name = "userId"
RESPJOINGAMEINZONE_USERID_FIELD.full_name = ".RespJoinGameInZone.userId"
RESPJOINGAMEINZONE_USERID_FIELD.number = 3
RESPJOINGAMEINZONE_USERID_FIELD.index = 2
RESPJOINGAMEINZONE_USERID_FIELD.label = 2
RESPJOINGAMEINZONE_USERID_FIELD.has_default_value = false
RESPJOINGAMEINZONE_USERID_FIELD.default_value = 0
RESPJOINGAMEINZONE_USERID_FIELD.type = 13
RESPJOINGAMEINZONE_USERID_FIELD.cpp_type = 3
RESPJOINGAMEINZONE_SIGN_FIELD.name = "sign"
RESPJOINGAMEINZONE_SIGN_FIELD.full_name = ".RespJoinGameInZone.sign"
RESPJOINGAMEINZONE_SIGN_FIELD.number = 4
RESPJOINGAMEINZONE_SIGN_FIELD.index = 3
RESPJOINGAMEINZONE_SIGN_FIELD.label = 2
RESPJOINGAMEINZONE_SIGN_FIELD.has_default_value = false
RESPJOINGAMEINZONE_SIGN_FIELD.default_value = 0
RESPJOINGAMEINZONE_SIGN_FIELD.type = 13
RESPJOINGAMEINZONE_SIGN_FIELD.cpp_type = 3
RESPJOINGAMEINZONE_SUCCESS_FIELD.name = "success"
RESPJOINGAMEINZONE_SUCCESS_FIELD.full_name = ".RespJoinGameInZone.success"
RESPJOINGAMEINZONE_SUCCESS_FIELD.number = 5
RESPJOINGAMEINZONE_SUCCESS_FIELD.index = 4
RESPJOINGAMEINZONE_SUCCESS_FIELD.label = 2
RESPJOINGAMEINZONE_SUCCESS_FIELD.has_default_value = false
RESPJOINGAMEINZONE_SUCCESS_FIELD.default_value = false
RESPJOINGAMEINZONE_SUCCESS_FIELD.type = 8
RESPJOINGAMEINZONE_SUCCESS_FIELD.cpp_type = 7
RESPJOINGAMEINZONE_PLAYERID_FIELD.name = "playerId"
RESPJOINGAMEINZONE_PLAYERID_FIELD.full_name = ".RespJoinGameInZone.playerId"
RESPJOINGAMEINZONE_PLAYERID_FIELD.number = 6
RESPJOINGAMEINZONE_PLAYERID_FIELD.index = 5
RESPJOINGAMEINZONE_PLAYERID_FIELD.label = 1
RESPJOINGAMEINZONE_PLAYERID_FIELD.has_default_value = false
RESPJOINGAMEINZONE_PLAYERID_FIELD.default_value = 0
RESPJOINGAMEINZONE_PLAYERID_FIELD.type = 13
RESPJOINGAMEINZONE_PLAYERID_FIELD.cpp_type = 3
RESPJOINGAMEINZONE_ERRORCODE_FIELD.name = "errorCode"
RESPJOINGAMEINZONE_ERRORCODE_FIELD.full_name = ".RespJoinGameInZone.errorCode"
RESPJOINGAMEINZONE_ERRORCODE_FIELD.number = 7
RESPJOINGAMEINZONE_ERRORCODE_FIELD.index = 6
RESPJOINGAMEINZONE_ERRORCODE_FIELD.label = 1
RESPJOINGAMEINZONE_ERRORCODE_FIELD.has_default_value = false
RESPJOINGAMEINZONE_ERRORCODE_FIELD.default_value = 0
RESPJOINGAMEINZONE_ERRORCODE_FIELD.type = 13
RESPJOINGAMEINZONE_ERRORCODE_FIELD.cpp_type = 3
RESPJOINGAMEINZONE.name = "RespJoinGameInZone"
RESPJOINGAMEINZONE.full_name = ".RespJoinGameInZone"
RESPJOINGAMEINZONE.nested_types = {}
RESPJOINGAMEINZONE.enum_types = {}
RESPJOINGAMEINZONE.fields = {
	RESPJOINGAMEINZONE_ROOMID_FIELD,
	RESPJOINGAMEINZONE_GAMETYPE_FIELD,
	RESPJOINGAMEINZONE_USERID_FIELD,
	RESPJOINGAMEINZONE_SIGN_FIELD,
	RESPJOINGAMEINZONE_SUCCESS_FIELD,
	RESPJOINGAMEINZONE_PLAYERID_FIELD,
	RESPJOINGAMEINZONE_ERRORCODE_FIELD
}
RESPJOINGAMEINZONE.is_extendable = false
RESPJOINGAMEINZONE.extensions = {}
REQCHECKISINZONE.name = "ReqCheckIsInZone"
REQCHECKISINZONE.full_name = ".ReqCheckIsInZone"
REQCHECKISINZONE.nested_types = {}
REQCHECKISINZONE.enum_types = {}
REQCHECKISINZONE.fields = {}
REQCHECKISINZONE.is_extendable = false
REQCHECKISINZONE.extensions = {}
RESPCHECKISINZONE_ISINZONE_FIELD.name = "isInZone"
RESPCHECKISINZONE_ISINZONE_FIELD.full_name = ".RespCheckIsInZone.isInZone"
RESPCHECKISINZONE_ISINZONE_FIELD.number = 1
RESPCHECKISINZONE_ISINZONE_FIELD.index = 0
RESPCHECKISINZONE_ISINZONE_FIELD.label = 2
RESPCHECKISINZONE_ISINZONE_FIELD.has_default_value = false
RESPCHECKISINZONE_ISINZONE_FIELD.default_value = false
RESPCHECKISINZONE_ISINZONE_FIELD.type = 8
RESPCHECKISINZONE_ISINZONE_FIELD.cpp_type = 7
RESPCHECKISINZONE_GAMETYPE_FIELD.name = "gameType"
RESPCHECKISINZONE_GAMETYPE_FIELD.full_name = ".RespCheckIsInZone.gameType"
RESPCHECKISINZONE_GAMETYPE_FIELD.number = 2
RESPCHECKISINZONE_GAMETYPE_FIELD.index = 1
RESPCHECKISINZONE_GAMETYPE_FIELD.label = 1
RESPCHECKISINZONE_GAMETYPE_FIELD.has_default_value = false
RESPCHECKISINZONE_GAMETYPE_FIELD.default_value = 0
RESPCHECKISINZONE_GAMETYPE_FIELD.type = 13
RESPCHECKISINZONE_GAMETYPE_FIELD.cpp_type = 3
RESPCHECKISINZONE.name = "RespCheckIsInZone"
RESPCHECKISINZONE.full_name = ".RespCheckIsInZone"
RESPCHECKISINZONE.nested_types = {}
RESPCHECKISINZONE.enum_types = {}
RESPCHECKISINZONE.fields = {
	RESPCHECKISINZONE_ISINZONE_FIELD,
	RESPCHECKISINZONE_GAMETYPE_FIELD
}
RESPCHECKISINZONE.is_extendable = false
RESPCHECKISINZONE.extensions = {}
REQBATTLERESULT_RESULT_FIELD.name = "result"
REQBATTLERESULT_RESULT_FIELD.full_name = ".ReqBattleResult.result"
REQBATTLERESULT_RESULT_FIELD.number = 1
REQBATTLERESULT_RESULT_FIELD.index = 0
REQBATTLERESULT_RESULT_FIELD.label = 1
REQBATTLERESULT_RESULT_FIELD.has_default_value = false
REQBATTLERESULT_RESULT_FIELD.default_value = 0
REQBATTLERESULT_RESULT_FIELD.type = 13
REQBATTLERESULT_RESULT_FIELD.cpp_type = 3
REQBATTLERESULT.name = "ReqBattleResult"
REQBATTLERESULT.full_name = ".ReqBattleResult"
REQBATTLERESULT.nested_types = {}
REQBATTLERESULT.enum_types = {}
REQBATTLERESULT.fields = {
	REQBATTLERESULT_RESULT_FIELD
}
REQBATTLERESULT.is_extendable = false
REQBATTLERESULT.extensions = {}
RESPBATTLERESULT_RESULT_FIELD.name = "result"
RESPBATTLERESULT_RESULT_FIELD.full_name = ".RespBattleResult.result"
RESPBATTLERESULT_RESULT_FIELD.number = 1
RESPBATTLERESULT_RESULT_FIELD.index = 0
RESPBATTLERESULT_RESULT_FIELD.label = 1
RESPBATTLERESULT_RESULT_FIELD.has_default_value = false
RESPBATTLERESULT_RESULT_FIELD.default_value = 0
RESPBATTLERESULT_RESULT_FIELD.type = 13
RESPBATTLERESULT_RESULT_FIELD.cpp_type = 3
RESPBATTLERESULT.name = "RespBattleResult"
RESPBATTLERESULT.full_name = ".RespBattleResult"
RESPBATTLERESULT.nested_types = {}
RESPBATTLERESULT.enum_types = {}
RESPBATTLERESULT.fields = {
	RESPBATTLERESULT_RESULT_FIELD
}
RESPBATTLERESULT.is_extendable = false
RESPBATTLERESULT.extensions = {}
BattleRoomInfo = protobuf.Message(BATTLEROOMINFO)
BattleRoomUserInfo = protobuf.Message(BATTLEROOMUSERINFO)
MatchedPlayerInfo = protobuf.Message(MATCHEDPLAYERINFO)
ReqBattleResult = protobuf.Message(REQBATTLERESULT)
ReqCancelMatchGame = protobuf.Message(REQCANCELMATCHGAME)
ReqCheckIsInZone = protobuf.Message(REQCHECKISINZONE)
ReqChooseHero = protobuf.Message(REQCHOOSEHERO)
ReqClientLoadingUpdate = protobuf.Message(REQCLIENTLOADINGUPDATE)
ReqConfirmEnterGame = protobuf.Message(REQCONFIRMENTERGAME)
ReqConfirmHero = protobuf.Message(REQCONFIRMHERO)
ReqJoinGameInZone = protobuf.Message(REQJOINGAMEINZONE)
ReqMatchGame = protobuf.Message(REQMATCHGAME)
ReqMatchGameInZone = protobuf.Message(REQMATCHGAMEINZONE)
ReqRejoinGame = protobuf.Message(REQREJOINGAME)
ReqUpdateRoomInfoToSearch = protobuf.Message(REQUPDATEROOMINFOTOSEARCH)
ReqUploadRoomInfosToSearch = protobuf.Message(REQUPLOADROOMINFOSTOSEARCH)
ReqUserLeaveGameInZone = protobuf.Message(REQUSERLEAVEGAMEINZONE)
RespBattleResult = protobuf.Message(RESPBATTLERESULT)
RespBeginChoosingHero = protobuf.Message(RESPBEGINCHOOSINGHERO)
RespBeginGameLoading = protobuf.Message(RESPBEGINGAMELOADING)
RespCheckIsInZone = protobuf.Message(RESPCHECKISINZONE)
RespChooseHero = protobuf.Message(RESPCHOOSEHERO)
RespClientLoadingUpdate = protobuf.Message(RESPCLIENTLOADINGUPDATE)
RespConfirmEnterGame = protobuf.Message(RESPCONFIRMENTERGAME)
RespConfirmHero = protobuf.Message(RESPCONFIRMHERO)
RespJoinGameInZone = protobuf.Message(RESPJOINGAMEINZONE)
RespKickOutUnconfirmedUser = protobuf.Message(RESPKICKOUTUNCONFIRMEDUSER)
RespMatchGameInProgress = protobuf.Message(RESPMATCHGAMEINPROGRESS)
RespMatchGameInZone = protobuf.Message(RESPMATCHGAMEINZONE)
RespMatchedPlayerList = protobuf.Message(RESPMATCHEDPLAYERLIST)
RespRematchGame = protobuf.Message(RESPREMATCHGAME)
RespStartGame = protobuf.Message(RESPSTARTGAME)
TeamInfo = protobuf.Message(TEAMINFO)
TeamMemberInfo = protobuf.Message(TEAMMEMBERINFO)
