-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Protocol/Protobuf/BattlePlayer_pb.lua

local protobuf = require("protobuf/protobuf")

module("LuaScript/Protocol/Protobuf/BattlePlayer_pb")

REQCREATEPLAYER = protobuf.Descriptor()

local REQCREATEPLAYER_NAME_FIELD = protobuf.FieldDescriptor()
local REQCREATEPLAYER_PROFESSION_FIELD = protobuf.FieldDescriptor()
local REQCREATEPLAYER_GENDER_FIELD = protobuf.FieldDescriptor()
local REQCREATEPLAYER_ICON_FIELD = protobuf.FieldDescriptor()
local REQCREATEPLAYER_ICONURL_FIELD = protobuf.FieldDescriptor()

PLAYERINFO = protobuf.Descriptor()

local PLAYERINFO_ID_FIELD = protobuf.FieldDescriptor()
local PLAYERINFO_NAME_FIELD = protobuf.FieldDescriptor()
local PLAYERINFO_PROFESSION_FIELD = protobuf.FieldDescriptor()
local PLAYERINFO_GENDER_FIELD = protobuf.FieldDescriptor()
local PLAYERINFO_ICON_FIELD = protobuf.FieldDescriptor()
local PLAYERINFO_ICONURL_FIELD = protobuf.FieldDescriptor()

PLAYERINITINFO = protobuf.Descriptor()

local PLAYERINITINFO_GAMESERVERID_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_ID_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_NAME_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_PROFESSION_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_GENDER_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_ICON_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_ICONURL_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_COIN_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_GOLD_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_TICKET_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_LEVEL_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_EXP_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_VIP_FIELD = protobuf.FieldDescriptor()
local PLAYERINITINFO_VIPEXP_FIELD = protobuf.FieldDescriptor()

PLAYERLIST = protobuf.Descriptor()

local PLAYERLIST_PLAYERS_FIELD = protobuf.FieldDescriptor()

REQPLAYERENTER = protobuf.Descriptor()

local REQPLAYERENTER_PLAYERID_FIELD = protobuf.FieldDescriptor()

UPDATECURRENCY = protobuf.Descriptor()

local UPDATECURRENCY_QTY_FIELD = protobuf.FieldDescriptor()
local UPDATECURRENCY_DIFF_FIELD = protobuf.FieldDescriptor()
local UPDATECURRENCY_SRC_FIELD = protobuf.FieldDescriptor()

CURRENCYNOTENOUGH = protobuf.Descriptor()

local CURRENCYNOTENOUGH_ITEMNO_FIELD = protobuf.FieldDescriptor()

CHARGELOGS = protobuf.Descriptor()

local CHARGELOGS_CHARGENO_FIELD = protobuf.FieldDescriptor()

ADDCHARGELOG = protobuf.Descriptor()

local ADDCHARGELOG_CHARGENO_FIELD = protobuf.FieldDescriptor()

UPDATEVIP = protobuf.Descriptor()

local UPDATEVIP_LEV_FIELD = protobuf.FieldDescriptor()
local UPDATEVIP_EXP_FIELD = protobuf.FieldDescriptor()
local UPDATEVIP_SRC_FIELD = protobuf.FieldDescriptor()

MAIL = protobuf.Descriptor()

local MAIL_ID_FIELD = protobuf.FieldDescriptor()
local MAIL_SUBJECT_FIELD = protobuf.FieldDescriptor()
local MAIL_CONTENT_FIELD = protobuf.FieldDescriptor()
local MAIL_ATTACHMENT_FIELD = protobuf.FieldDescriptor()
local MAIL_CREATETIME_FIELD = protobuf.FieldDescriptor()
local MAIL_EXPIREDTIME_FIELD = protobuf.FieldDescriptor()
local MAIL_ISREAD_FIELD = protobuf.FieldDescriptor()

MAILS = protobuf.Descriptor()

local MAILS_MAILS_FIELD = protobuf.FieldDescriptor()

REQREADMAIL = protobuf.Descriptor()

local REQREADMAIL_MAILID_FIELD = protobuf.FieldDescriptor()

REMOVEMAIL = protobuf.Descriptor()

local REMOVEMAIL_MAILID_FIELD = protobuf.FieldDescriptor()

EDITPLAYERINFO = protobuf.Descriptor()

local EDITPLAYERINFO_NAME_FIELD = protobuf.FieldDescriptor()
local EDITPLAYERINFO_ICON_FIELD = protobuf.FieldDescriptor()
local EDITPLAYERINFO_ICONURL_FIELD = protobuf.FieldDescriptor()

REQCREATEPLAYER_NAME_FIELD.name = "name"
REQCREATEPLAYER_NAME_FIELD.full_name = ".ReqCreatePlayer.name"
REQCREATEPLAYER_NAME_FIELD.number = 1
REQCREATEPLAYER_NAME_FIELD.index = 0
REQCREATEPLAYER_NAME_FIELD.label = 2
REQCREATEPLAYER_NAME_FIELD.has_default_value = false
REQCREATEPLAYER_NAME_FIELD.default_value = ""
REQCREATEPLAYER_NAME_FIELD.type = 9
REQCREATEPLAYER_NAME_FIELD.cpp_type = 9
REQCREATEPLAYER_PROFESSION_FIELD.name = "profession"
REQCREATEPLAYER_PROFESSION_FIELD.full_name = ".ReqCreatePlayer.profession"
REQCREATEPLAYER_PROFESSION_FIELD.number = 2
REQCREATEPLAYER_PROFESSION_FIELD.index = 1
REQCREATEPLAYER_PROFESSION_FIELD.label = 1
REQCREATEPLAYER_PROFESSION_FIELD.has_default_value = false
REQCREATEPLAYER_PROFESSION_FIELD.default_value = 0
REQCREATEPLAYER_PROFESSION_FIELD.type = 13
REQCREATEPLAYER_PROFESSION_FIELD.cpp_type = 3
REQCREATEPLAYER_GENDER_FIELD.name = "gender"
REQCREATEPLAYER_GENDER_FIELD.full_name = ".ReqCreatePlayer.gender"
REQCREATEPLAYER_GENDER_FIELD.number = 3
REQCREATEPLAYER_GENDER_FIELD.index = 2
REQCREATEPLAYER_GENDER_FIELD.label = 1
REQCREATEPLAYER_GENDER_FIELD.has_default_value = false
REQCREATEPLAYER_GENDER_FIELD.default_value = 0
REQCREATEPLAYER_GENDER_FIELD.type = 13
REQCREATEPLAYER_GENDER_FIELD.cpp_type = 3
REQCREATEPLAYER_ICON_FIELD.name = "icon"
REQCREATEPLAYER_ICON_FIELD.full_name = ".ReqCreatePlayer.icon"
REQCREATEPLAYER_ICON_FIELD.number = 4
REQCREATEPLAYER_ICON_FIELD.index = 3
REQCREATEPLAYER_ICON_FIELD.label = 1
REQCREATEPLAYER_ICON_FIELD.has_default_value = false
REQCREATEPLAYER_ICON_FIELD.default_value = 0
REQCREATEPLAYER_ICON_FIELD.type = 13
REQCREATEPLAYER_ICON_FIELD.cpp_type = 3
REQCREATEPLAYER_ICONURL_FIELD.name = "iconUrl"
REQCREATEPLAYER_ICONURL_FIELD.full_name = ".ReqCreatePlayer.iconUrl"
REQCREATEPLAYER_ICONURL_FIELD.number = 5
REQCREATEPLAYER_ICONURL_FIELD.index = 4
REQCREATEPLAYER_ICONURL_FIELD.label = 1
REQCREATEPLAYER_ICONURL_FIELD.has_default_value = false
REQCREATEPLAYER_ICONURL_FIELD.default_value = ""
REQCREATEPLAYER_ICONURL_FIELD.type = 9
REQCREATEPLAYER_ICONURL_FIELD.cpp_type = 9
REQCREATEPLAYER.name = "ReqCreatePlayer"
REQCREATEPLAYER.full_name = ".ReqCreatePlayer"
REQCREATEPLAYER.nested_types = {}
REQCREATEPLAYER.enum_types = {}
REQCREATEPLAYER.fields = {
	REQCREATEPLAYER_NAME_FIELD,
	REQCREATEPLAYER_PROFESSION_FIELD,
	REQCREATEPLAYER_GENDER_FIELD,
	REQCREATEPLAYER_ICON_FIELD,
	REQCREATEPLAYER_ICONURL_FIELD
}
REQCREATEPLAYER.is_extendable = false
REQCREATEPLAYER.extensions = {}
PLAYERINFO_ID_FIELD.name = "id"
PLAYERINFO_ID_FIELD.full_name = ".PlayerInfo.id"
PLAYERINFO_ID_FIELD.number = 1
PLAYERINFO_ID_FIELD.index = 0
PLAYERINFO_ID_FIELD.label = 2
PLAYERINFO_ID_FIELD.has_default_value = false
PLAYERINFO_ID_FIELD.default_value = 0
PLAYERINFO_ID_FIELD.type = 13
PLAYERINFO_ID_FIELD.cpp_type = 3
PLAYERINFO_NAME_FIELD.name = "name"
PLAYERINFO_NAME_FIELD.full_name = ".PlayerInfo.name"
PLAYERINFO_NAME_FIELD.number = 2
PLAYERINFO_NAME_FIELD.index = 1
PLAYERINFO_NAME_FIELD.label = 2
PLAYERINFO_NAME_FIELD.has_default_value = false
PLAYERINFO_NAME_FIELD.default_value = ""
PLAYERINFO_NAME_FIELD.type = 9
PLAYERINFO_NAME_FIELD.cpp_type = 9
PLAYERINFO_PROFESSION_FIELD.name = "profession"
PLAYERINFO_PROFESSION_FIELD.full_name = ".PlayerInfo.profession"
PLAYERINFO_PROFESSION_FIELD.number = 3
PLAYERINFO_PROFESSION_FIELD.index = 2
PLAYERINFO_PROFESSION_FIELD.label = 2
PLAYERINFO_PROFESSION_FIELD.has_default_value = false
PLAYERINFO_PROFESSION_FIELD.default_value = 0
PLAYERINFO_PROFESSION_FIELD.type = 13
PLAYERINFO_PROFESSION_FIELD.cpp_type = 3
PLAYERINFO_GENDER_FIELD.name = "gender"
PLAYERINFO_GENDER_FIELD.full_name = ".PlayerInfo.gender"
PLAYERINFO_GENDER_FIELD.number = 4
PLAYERINFO_GENDER_FIELD.index = 3
PLAYERINFO_GENDER_FIELD.label = 1
PLAYERINFO_GENDER_FIELD.has_default_value = false
PLAYERINFO_GENDER_FIELD.default_value = 0
PLAYERINFO_GENDER_FIELD.type = 13
PLAYERINFO_GENDER_FIELD.cpp_type = 3
PLAYERINFO_ICON_FIELD.name = "icon"
PLAYERINFO_ICON_FIELD.full_name = ".PlayerInfo.icon"
PLAYERINFO_ICON_FIELD.number = 5
PLAYERINFO_ICON_FIELD.index = 4
PLAYERINFO_ICON_FIELD.label = 1
PLAYERINFO_ICON_FIELD.has_default_value = false
PLAYERINFO_ICON_FIELD.default_value = 0
PLAYERINFO_ICON_FIELD.type = 13
PLAYERINFO_ICON_FIELD.cpp_type = 3
PLAYERINFO_ICONURL_FIELD.name = "iconUrl"
PLAYERINFO_ICONURL_FIELD.full_name = ".PlayerInfo.iconUrl"
PLAYERINFO_ICONURL_FIELD.number = 6
PLAYERINFO_ICONURL_FIELD.index = 5
PLAYERINFO_ICONURL_FIELD.label = 1
PLAYERINFO_ICONURL_FIELD.has_default_value = false
PLAYERINFO_ICONURL_FIELD.default_value = ""
PLAYERINFO_ICONURL_FIELD.type = 9
PLAYERINFO_ICONURL_FIELD.cpp_type = 9
PLAYERINFO.name = "PlayerInfo"
PLAYERINFO.full_name = ".PlayerInfo"
PLAYERINFO.nested_types = {}
PLAYERINFO.enum_types = {}
PLAYERINFO.fields = {
	PLAYERINFO_ID_FIELD,
	PLAYERINFO_NAME_FIELD,
	PLAYERINFO_PROFESSION_FIELD,
	PLAYERINFO_GENDER_FIELD,
	PLAYERINFO_ICON_FIELD,
	PLAYERINFO_ICONURL_FIELD
}
PLAYERINFO.is_extendable = false
PLAYERINFO.extensions = {}
PLAYERINITINFO_GAMESERVERID_FIELD.name = "gameServerId"
PLAYERINITINFO_GAMESERVERID_FIELD.full_name = ".PlayerInitInfo.gameServerId"
PLAYERINITINFO_GAMESERVERID_FIELD.number = 1
PLAYERINITINFO_GAMESERVERID_FIELD.index = 0
PLAYERINITINFO_GAMESERVERID_FIELD.label = 2
PLAYERINITINFO_GAMESERVERID_FIELD.has_default_value = false
PLAYERINITINFO_GAMESERVERID_FIELD.default_value = 0
PLAYERINITINFO_GAMESERVERID_FIELD.type = 13
PLAYERINITINFO_GAMESERVERID_FIELD.cpp_type = 3
PLAYERINITINFO_ID_FIELD.name = "id"
PLAYERINITINFO_ID_FIELD.full_name = ".PlayerInitInfo.id"
PLAYERINITINFO_ID_FIELD.number = 2
PLAYERINITINFO_ID_FIELD.index = 1
PLAYERINITINFO_ID_FIELD.label = 2
PLAYERINITINFO_ID_FIELD.has_default_value = false
PLAYERINITINFO_ID_FIELD.default_value = 0
PLAYERINITINFO_ID_FIELD.type = 13
PLAYERINITINFO_ID_FIELD.cpp_type = 3
PLAYERINITINFO_NAME_FIELD.name = "name"
PLAYERINITINFO_NAME_FIELD.full_name = ".PlayerInitInfo.name"
PLAYERINITINFO_NAME_FIELD.number = 3
PLAYERINITINFO_NAME_FIELD.index = 2
PLAYERINITINFO_NAME_FIELD.label = 2
PLAYERINITINFO_NAME_FIELD.has_default_value = false
PLAYERINITINFO_NAME_FIELD.default_value = ""
PLAYERINITINFO_NAME_FIELD.type = 9
PLAYERINITINFO_NAME_FIELD.cpp_type = 9
PLAYERINITINFO_PROFESSION_FIELD.name = "profession"
PLAYERINITINFO_PROFESSION_FIELD.full_name = ".PlayerInitInfo.profession"
PLAYERINITINFO_PROFESSION_FIELD.number = 4
PLAYERINITINFO_PROFESSION_FIELD.index = 3
PLAYERINITINFO_PROFESSION_FIELD.label = 2
PLAYERINITINFO_PROFESSION_FIELD.has_default_value = false
PLAYERINITINFO_PROFESSION_FIELD.default_value = 0
PLAYERINITINFO_PROFESSION_FIELD.type = 13
PLAYERINITINFO_PROFESSION_FIELD.cpp_type = 3
PLAYERINITINFO_GENDER_FIELD.name = "gender"
PLAYERINITINFO_GENDER_FIELD.full_name = ".PlayerInitInfo.gender"
PLAYERINITINFO_GENDER_FIELD.number = 5
PLAYERINITINFO_GENDER_FIELD.index = 4
PLAYERINITINFO_GENDER_FIELD.label = 1
PLAYERINITINFO_GENDER_FIELD.has_default_value = false
PLAYERINITINFO_GENDER_FIELD.default_value = 0
PLAYERINITINFO_GENDER_FIELD.type = 13
PLAYERINITINFO_GENDER_FIELD.cpp_type = 3
PLAYERINITINFO_ICON_FIELD.name = "icon"
PLAYERINITINFO_ICON_FIELD.full_name = ".PlayerInitInfo.icon"
PLAYERINITINFO_ICON_FIELD.number = 6
PLAYERINITINFO_ICON_FIELD.index = 5
PLAYERINITINFO_ICON_FIELD.label = 1
PLAYERINITINFO_ICON_FIELD.has_default_value = false
PLAYERINITINFO_ICON_FIELD.default_value = 0
PLAYERINITINFO_ICON_FIELD.type = 13
PLAYERINITINFO_ICON_FIELD.cpp_type = 3
PLAYERINITINFO_ICONURL_FIELD.name = "iconUrl"
PLAYERINITINFO_ICONURL_FIELD.full_name = ".PlayerInitInfo.iconUrl"
PLAYERINITINFO_ICONURL_FIELD.number = 7
PLAYERINITINFO_ICONURL_FIELD.index = 6
PLAYERINITINFO_ICONURL_FIELD.label = 1
PLAYERINITINFO_ICONURL_FIELD.has_default_value = false
PLAYERINITINFO_ICONURL_FIELD.default_value = ""
PLAYERINITINFO_ICONURL_FIELD.type = 9
PLAYERINITINFO_ICONURL_FIELD.cpp_type = 9
PLAYERINITINFO_COIN_FIELD.name = "coin"
PLAYERINITINFO_COIN_FIELD.full_name = ".PlayerInitInfo.coin"
PLAYERINITINFO_COIN_FIELD.number = 8
PLAYERINITINFO_COIN_FIELD.index = 7
PLAYERINITINFO_COIN_FIELD.label = 1
PLAYERINITINFO_COIN_FIELD.has_default_value = false
PLAYERINITINFO_COIN_FIELD.default_value = 0
PLAYERINITINFO_COIN_FIELD.type = 13
PLAYERINITINFO_COIN_FIELD.cpp_type = 3
PLAYERINITINFO_GOLD_FIELD.name = "gold"
PLAYERINITINFO_GOLD_FIELD.full_name = ".PlayerInitInfo.gold"
PLAYERINITINFO_GOLD_FIELD.number = 9
PLAYERINITINFO_GOLD_FIELD.index = 8
PLAYERINITINFO_GOLD_FIELD.label = 1
PLAYERINITINFO_GOLD_FIELD.has_default_value = false
PLAYERINITINFO_GOLD_FIELD.default_value = 0
PLAYERINITINFO_GOLD_FIELD.type = 13
PLAYERINITINFO_GOLD_FIELD.cpp_type = 3
PLAYERINITINFO_TICKET_FIELD.name = "ticket"
PLAYERINITINFO_TICKET_FIELD.full_name = ".PlayerInitInfo.ticket"
PLAYERINITINFO_TICKET_FIELD.number = 10
PLAYERINITINFO_TICKET_FIELD.index = 9
PLAYERINITINFO_TICKET_FIELD.label = 1
PLAYERINITINFO_TICKET_FIELD.has_default_value = false
PLAYERINITINFO_TICKET_FIELD.default_value = 0
PLAYERINITINFO_TICKET_FIELD.type = 13
PLAYERINITINFO_TICKET_FIELD.cpp_type = 3
PLAYERINITINFO_LEVEL_FIELD.name = "level"
PLAYERINITINFO_LEVEL_FIELD.full_name = ".PlayerInitInfo.level"
PLAYERINITINFO_LEVEL_FIELD.number = 11
PLAYERINITINFO_LEVEL_FIELD.index = 10
PLAYERINITINFO_LEVEL_FIELD.label = 1
PLAYERINITINFO_LEVEL_FIELD.has_default_value = false
PLAYERINITINFO_LEVEL_FIELD.default_value = 0
PLAYERINITINFO_LEVEL_FIELD.type = 13
PLAYERINITINFO_LEVEL_FIELD.cpp_type = 3
PLAYERINITINFO_EXP_FIELD.name = "exp"
PLAYERINITINFO_EXP_FIELD.full_name = ".PlayerInitInfo.exp"
PLAYERINITINFO_EXP_FIELD.number = 12
PLAYERINITINFO_EXP_FIELD.index = 11
PLAYERINITINFO_EXP_FIELD.label = 1
PLAYERINITINFO_EXP_FIELD.has_default_value = false
PLAYERINITINFO_EXP_FIELD.default_value = 0
PLAYERINITINFO_EXP_FIELD.type = 13
PLAYERINITINFO_EXP_FIELD.cpp_type = 3
PLAYERINITINFO_VIP_FIELD.name = "vip"
PLAYERINITINFO_VIP_FIELD.full_name = ".PlayerInitInfo.vip"
PLAYERINITINFO_VIP_FIELD.number = 13
PLAYERINITINFO_VIP_FIELD.index = 12
PLAYERINITINFO_VIP_FIELD.label = 1
PLAYERINITINFO_VIP_FIELD.has_default_value = false
PLAYERINITINFO_VIP_FIELD.default_value = 0
PLAYERINITINFO_VIP_FIELD.type = 13
PLAYERINITINFO_VIP_FIELD.cpp_type = 3
PLAYERINITINFO_VIPEXP_FIELD.name = "vipExp"
PLAYERINITINFO_VIPEXP_FIELD.full_name = ".PlayerInitInfo.vipExp"
PLAYERINITINFO_VIPEXP_FIELD.number = 14
PLAYERINITINFO_VIPEXP_FIELD.index = 13
PLAYERINITINFO_VIPEXP_FIELD.label = 1
PLAYERINITINFO_VIPEXP_FIELD.has_default_value = false
PLAYERINITINFO_VIPEXP_FIELD.default_value = 0
PLAYERINITINFO_VIPEXP_FIELD.type = 13
PLAYERINITINFO_VIPEXP_FIELD.cpp_type = 3
PLAYERINITINFO.name = "PlayerInitInfo"
PLAYERINITINFO.full_name = ".PlayerInitInfo"
PLAYERINITINFO.nested_types = {}
PLAYERINITINFO.enum_types = {}
PLAYERINITINFO.fields = {
	PLAYERINITINFO_GAMESERVERID_FIELD,
	PLAYERINITINFO_ID_FIELD,
	PLAYERINITINFO_NAME_FIELD,
	PLAYERINITINFO_PROFESSION_FIELD,
	PLAYERINITINFO_GENDER_FIELD,
	PLAYERINITINFO_ICON_FIELD,
	PLAYERINITINFO_ICONURL_FIELD,
	PLAYERINITINFO_COIN_FIELD,
	PLAYERINITINFO_GOLD_FIELD,
	PLAYERINITINFO_TICKET_FIELD,
	PLAYERINITINFO_LEVEL_FIELD,
	PLAYERINITINFO_EXP_FIELD,
	PLAYERINITINFO_VIP_FIELD,
	PLAYERINITINFO_VIPEXP_FIELD
}
PLAYERINITINFO.is_extendable = false
PLAYERINITINFO.extensions = {}
PLAYERLIST_PLAYERS_FIELD.name = "players"
PLAYERLIST_PLAYERS_FIELD.full_name = ".PlayerList.players"
PLAYERLIST_PLAYERS_FIELD.number = 1
PLAYERLIST_PLAYERS_FIELD.index = 0
PLAYERLIST_PLAYERS_FIELD.label = 3
PLAYERLIST_PLAYERS_FIELD.has_default_value = false
PLAYERLIST_PLAYERS_FIELD.default_value = {}
PLAYERLIST_PLAYERS_FIELD.message_type = PLAYERINFO
PLAYERLIST_PLAYERS_FIELD.type = 11
PLAYERLIST_PLAYERS_FIELD.cpp_type = 10
PLAYERLIST.name = "PlayerList"
PLAYERLIST.full_name = ".PlayerList"
PLAYERLIST.nested_types = {}
PLAYERLIST.enum_types = {}
PLAYERLIST.fields = {
	PLAYERLIST_PLAYERS_FIELD
}
PLAYERLIST.is_extendable = false
PLAYERLIST.extensions = {}
REQPLAYERENTER_PLAYERID_FIELD.name = "playerId"
REQPLAYERENTER_PLAYERID_FIELD.full_name = ".ReqPlayerEnter.playerId"
REQPLAYERENTER_PLAYERID_FIELD.number = 1
REQPLAYERENTER_PLAYERID_FIELD.index = 0
REQPLAYERENTER_PLAYERID_FIELD.label = 2
REQPLAYERENTER_PLAYERID_FIELD.has_default_value = false
REQPLAYERENTER_PLAYERID_FIELD.default_value = 0
REQPLAYERENTER_PLAYERID_FIELD.type = 13
REQPLAYERENTER_PLAYERID_FIELD.cpp_type = 3
REQPLAYERENTER.name = "ReqPlayerEnter"
REQPLAYERENTER.full_name = ".ReqPlayerEnter"
REQPLAYERENTER.nested_types = {}
REQPLAYERENTER.enum_types = {}
REQPLAYERENTER.fields = {
	REQPLAYERENTER_PLAYERID_FIELD
}
REQPLAYERENTER.is_extendable = false
REQPLAYERENTER.extensions = {}
UPDATECURRENCY_QTY_FIELD.name = "qty"
UPDATECURRENCY_QTY_FIELD.full_name = ".UpdateCurrency.qty"
UPDATECURRENCY_QTY_FIELD.number = 1
UPDATECURRENCY_QTY_FIELD.index = 0
UPDATECURRENCY_QTY_FIELD.label = 2
UPDATECURRENCY_QTY_FIELD.has_default_value = false
UPDATECURRENCY_QTY_FIELD.default_value = 0
UPDATECURRENCY_QTY_FIELD.type = 13
UPDATECURRENCY_QTY_FIELD.cpp_type = 3
UPDATECURRENCY_DIFF_FIELD.name = "diff"
UPDATECURRENCY_DIFF_FIELD.full_name = ".UpdateCurrency.diff"
UPDATECURRENCY_DIFF_FIELD.number = 2
UPDATECURRENCY_DIFF_FIELD.index = 1
UPDATECURRENCY_DIFF_FIELD.label = 2
UPDATECURRENCY_DIFF_FIELD.has_default_value = false
UPDATECURRENCY_DIFF_FIELD.default_value = 0
UPDATECURRENCY_DIFF_FIELD.type = 5
UPDATECURRENCY_DIFF_FIELD.cpp_type = 1
UPDATECURRENCY_SRC_FIELD.name = "src"
UPDATECURRENCY_SRC_FIELD.full_name = ".UpdateCurrency.src"
UPDATECURRENCY_SRC_FIELD.number = 3
UPDATECURRENCY_SRC_FIELD.index = 2
UPDATECURRENCY_SRC_FIELD.label = 2
UPDATECURRENCY_SRC_FIELD.has_default_value = false
UPDATECURRENCY_SRC_FIELD.default_value = 0
UPDATECURRENCY_SRC_FIELD.type = 13
UPDATECURRENCY_SRC_FIELD.cpp_type = 3
UPDATECURRENCY.name = "UpdateCurrency"
UPDATECURRENCY.full_name = ".UpdateCurrency"
UPDATECURRENCY.nested_types = {}
UPDATECURRENCY.enum_types = {}
UPDATECURRENCY.fields = {
	UPDATECURRENCY_QTY_FIELD,
	UPDATECURRENCY_DIFF_FIELD,
	UPDATECURRENCY_SRC_FIELD
}
UPDATECURRENCY.is_extendable = false
UPDATECURRENCY.extensions = {}
CURRENCYNOTENOUGH_ITEMNO_FIELD.name = "itemNo"
CURRENCYNOTENOUGH_ITEMNO_FIELD.full_name = ".CurrencyNotEnough.itemNo"
CURRENCYNOTENOUGH_ITEMNO_FIELD.number = 1
CURRENCYNOTENOUGH_ITEMNO_FIELD.index = 0
CURRENCYNOTENOUGH_ITEMNO_FIELD.label = 2
CURRENCYNOTENOUGH_ITEMNO_FIELD.has_default_value = false
CURRENCYNOTENOUGH_ITEMNO_FIELD.default_value = 0
CURRENCYNOTENOUGH_ITEMNO_FIELD.type = 13
CURRENCYNOTENOUGH_ITEMNO_FIELD.cpp_type = 3
CURRENCYNOTENOUGH.name = "CurrencyNotEnough"
CURRENCYNOTENOUGH.full_name = ".CurrencyNotEnough"
CURRENCYNOTENOUGH.nested_types = {}
CURRENCYNOTENOUGH.enum_types = {}
CURRENCYNOTENOUGH.fields = {
	CURRENCYNOTENOUGH_ITEMNO_FIELD
}
CURRENCYNOTENOUGH.is_extendable = false
CURRENCYNOTENOUGH.extensions = {}
CHARGELOGS_CHARGENO_FIELD.name = "chargeNo"
CHARGELOGS_CHARGENO_FIELD.full_name = ".ChargeLogs.chargeNo"
CHARGELOGS_CHARGENO_FIELD.number = 1
CHARGELOGS_CHARGENO_FIELD.index = 0
CHARGELOGS_CHARGENO_FIELD.label = 3
CHARGELOGS_CHARGENO_FIELD.has_default_value = false
CHARGELOGS_CHARGENO_FIELD.default_value = {}
CHARGELOGS_CHARGENO_FIELD.type = 9
CHARGELOGS_CHARGENO_FIELD.cpp_type = 9
CHARGELOGS.name = "ChargeLogs"
CHARGELOGS.full_name = ".ChargeLogs"
CHARGELOGS.nested_types = {}
CHARGELOGS.enum_types = {}
CHARGELOGS.fields = {
	CHARGELOGS_CHARGENO_FIELD
}
CHARGELOGS.is_extendable = false
CHARGELOGS.extensions = {}
ADDCHARGELOG_CHARGENO_FIELD.name = "chargeNo"
ADDCHARGELOG_CHARGENO_FIELD.full_name = ".AddChargeLog.chargeNo"
ADDCHARGELOG_CHARGENO_FIELD.number = 1
ADDCHARGELOG_CHARGENO_FIELD.index = 0
ADDCHARGELOG_CHARGENO_FIELD.label = 2
ADDCHARGELOG_CHARGENO_FIELD.has_default_value = false
ADDCHARGELOG_CHARGENO_FIELD.default_value = ""
ADDCHARGELOG_CHARGENO_FIELD.type = 9
ADDCHARGELOG_CHARGENO_FIELD.cpp_type = 9
ADDCHARGELOG.name = "AddChargeLog"
ADDCHARGELOG.full_name = ".AddChargeLog"
ADDCHARGELOG.nested_types = {}
ADDCHARGELOG.enum_types = {}
ADDCHARGELOG.fields = {
	ADDCHARGELOG_CHARGENO_FIELD
}
ADDCHARGELOG.is_extendable = false
ADDCHARGELOG.extensions = {}
UPDATEVIP_LEV_FIELD.name = "lev"
UPDATEVIP_LEV_FIELD.full_name = ".UpdateVip.lev"
UPDATEVIP_LEV_FIELD.number = 1
UPDATEVIP_LEV_FIELD.index = 0
UPDATEVIP_LEV_FIELD.label = 2
UPDATEVIP_LEV_FIELD.has_default_value = false
UPDATEVIP_LEV_FIELD.default_value = 0
UPDATEVIP_LEV_FIELD.type = 13
UPDATEVIP_LEV_FIELD.cpp_type = 3
UPDATEVIP_EXP_FIELD.name = "exp"
UPDATEVIP_EXP_FIELD.full_name = ".UpdateVip.exp"
UPDATEVIP_EXP_FIELD.number = 2
UPDATEVIP_EXP_FIELD.index = 1
UPDATEVIP_EXP_FIELD.label = 2
UPDATEVIP_EXP_FIELD.has_default_value = false
UPDATEVIP_EXP_FIELD.default_value = 0
UPDATEVIP_EXP_FIELD.type = 5
UPDATEVIP_EXP_FIELD.cpp_type = 1
UPDATEVIP_SRC_FIELD.name = "src"
UPDATEVIP_SRC_FIELD.full_name = ".UpdateVip.src"
UPDATEVIP_SRC_FIELD.number = 3
UPDATEVIP_SRC_FIELD.index = 2
UPDATEVIP_SRC_FIELD.label = 2
UPDATEVIP_SRC_FIELD.has_default_value = false
UPDATEVIP_SRC_FIELD.default_value = 0
UPDATEVIP_SRC_FIELD.type = 13
UPDATEVIP_SRC_FIELD.cpp_type = 3
UPDATEVIP.name = "UpdateVip"
UPDATEVIP.full_name = ".UpdateVip"
UPDATEVIP.nested_types = {}
UPDATEVIP.enum_types = {}
UPDATEVIP.fields = {
	UPDATEVIP_LEV_FIELD,
	UPDATEVIP_EXP_FIELD,
	UPDATEVIP_SRC_FIELD
}
UPDATEVIP.is_extendable = false
UPDATEVIP.extensions = {}
MAIL_ID_FIELD.name = "id"
MAIL_ID_FIELD.full_name = ".Mail.id"
MAIL_ID_FIELD.number = 1
MAIL_ID_FIELD.index = 0
MAIL_ID_FIELD.label = 2
MAIL_ID_FIELD.has_default_value = false
MAIL_ID_FIELD.default_value = 0
MAIL_ID_FIELD.type = 13
MAIL_ID_FIELD.cpp_type = 3
MAIL_SUBJECT_FIELD.name = "subject"
MAIL_SUBJECT_FIELD.full_name = ".Mail.subject"
MAIL_SUBJECT_FIELD.number = 2
MAIL_SUBJECT_FIELD.index = 1
MAIL_SUBJECT_FIELD.label = 2
MAIL_SUBJECT_FIELD.has_default_value = false
MAIL_SUBJECT_FIELD.default_value = ""
MAIL_SUBJECT_FIELD.type = 9
MAIL_SUBJECT_FIELD.cpp_type = 9
MAIL_CONTENT_FIELD.name = "content"
MAIL_CONTENT_FIELD.full_name = ".Mail.content"
MAIL_CONTENT_FIELD.number = 3
MAIL_CONTENT_FIELD.index = 2
MAIL_CONTENT_FIELD.label = 2
MAIL_CONTENT_FIELD.has_default_value = false
MAIL_CONTENT_FIELD.default_value = ""
MAIL_CONTENT_FIELD.type = 9
MAIL_CONTENT_FIELD.cpp_type = 9
MAIL_ATTACHMENT_FIELD.name = "attachment"
MAIL_ATTACHMENT_FIELD.full_name = ".Mail.attachment"
MAIL_ATTACHMENT_FIELD.number = 4
MAIL_ATTACHMENT_FIELD.index = 3
MAIL_ATTACHMENT_FIELD.label = 2
MAIL_ATTACHMENT_FIELD.has_default_value = false
MAIL_ATTACHMENT_FIELD.default_value = ""
MAIL_ATTACHMENT_FIELD.type = 9
MAIL_ATTACHMENT_FIELD.cpp_type = 9
MAIL_CREATETIME_FIELD.name = "createTime"
MAIL_CREATETIME_FIELD.full_name = ".Mail.createTime"
MAIL_CREATETIME_FIELD.number = 5
MAIL_CREATETIME_FIELD.index = 4
MAIL_CREATETIME_FIELD.label = 2
MAIL_CREATETIME_FIELD.has_default_value = false
MAIL_CREATETIME_FIELD.default_value = 0
MAIL_CREATETIME_FIELD.type = 13
MAIL_CREATETIME_FIELD.cpp_type = 3
MAIL_EXPIREDTIME_FIELD.name = "expiredTime"
MAIL_EXPIREDTIME_FIELD.full_name = ".Mail.expiredTime"
MAIL_EXPIREDTIME_FIELD.number = 6
MAIL_EXPIREDTIME_FIELD.index = 5
MAIL_EXPIREDTIME_FIELD.label = 2
MAIL_EXPIREDTIME_FIELD.has_default_value = false
MAIL_EXPIREDTIME_FIELD.default_value = 0
MAIL_EXPIREDTIME_FIELD.type = 13
MAIL_EXPIREDTIME_FIELD.cpp_type = 3
MAIL_ISREAD_FIELD.name = "isRead"
MAIL_ISREAD_FIELD.full_name = ".Mail.isRead"
MAIL_ISREAD_FIELD.number = 7
MAIL_ISREAD_FIELD.index = 6
MAIL_ISREAD_FIELD.label = 2
MAIL_ISREAD_FIELD.has_default_value = false
MAIL_ISREAD_FIELD.default_value = false
MAIL_ISREAD_FIELD.type = 8
MAIL_ISREAD_FIELD.cpp_type = 7
MAIL.name = "Mail"
MAIL.full_name = ".Mail"
MAIL.nested_types = {}
MAIL.enum_types = {}
MAIL.fields = {
	MAIL_ID_FIELD,
	MAIL_SUBJECT_FIELD,
	MAIL_CONTENT_FIELD,
	MAIL_ATTACHMENT_FIELD,
	MAIL_CREATETIME_FIELD,
	MAIL_EXPIREDTIME_FIELD,
	MAIL_ISREAD_FIELD
}
MAIL.is_extendable = false
MAIL.extensions = {}
MAILS_MAILS_FIELD.name = "mails"
MAILS_MAILS_FIELD.full_name = ".Mails.mails"
MAILS_MAILS_FIELD.number = 1
MAILS_MAILS_FIELD.index = 0
MAILS_MAILS_FIELD.label = 3
MAILS_MAILS_FIELD.has_default_value = false
MAILS_MAILS_FIELD.default_value = {}
MAILS_MAILS_FIELD.message_type = MAIL
MAILS_MAILS_FIELD.type = 11
MAILS_MAILS_FIELD.cpp_type = 10
MAILS.name = "Mails"
MAILS.full_name = ".Mails"
MAILS.nested_types = {}
MAILS.enum_types = {}
MAILS.fields = {
	MAILS_MAILS_FIELD
}
MAILS.is_extendable = false
MAILS.extensions = {}
REQREADMAIL_MAILID_FIELD.name = "mailId"
REQREADMAIL_MAILID_FIELD.full_name = ".ReqReadMail.mailId"
REQREADMAIL_MAILID_FIELD.number = 1
REQREADMAIL_MAILID_FIELD.index = 0
REQREADMAIL_MAILID_FIELD.label = 2
REQREADMAIL_MAILID_FIELD.has_default_value = false
REQREADMAIL_MAILID_FIELD.default_value = 0
REQREADMAIL_MAILID_FIELD.type = 13
REQREADMAIL_MAILID_FIELD.cpp_type = 3
REQREADMAIL.name = "ReqReadMail"
REQREADMAIL.full_name = ".ReqReadMail"
REQREADMAIL.nested_types = {}
REQREADMAIL.enum_types = {}
REQREADMAIL.fields = {
	REQREADMAIL_MAILID_FIELD
}
REQREADMAIL.is_extendable = false
REQREADMAIL.extensions = {}
REMOVEMAIL_MAILID_FIELD.name = "mailId"
REMOVEMAIL_MAILID_FIELD.full_name = ".RemoveMail.mailId"
REMOVEMAIL_MAILID_FIELD.number = 1
REMOVEMAIL_MAILID_FIELD.index = 0
REMOVEMAIL_MAILID_FIELD.label = 2
REMOVEMAIL_MAILID_FIELD.has_default_value = false
REMOVEMAIL_MAILID_FIELD.default_value = 0
REMOVEMAIL_MAILID_FIELD.type = 13
REMOVEMAIL_MAILID_FIELD.cpp_type = 3
REMOVEMAIL.name = "RemoveMail"
REMOVEMAIL.full_name = ".RemoveMail"
REMOVEMAIL.nested_types = {}
REMOVEMAIL.enum_types = {}
REMOVEMAIL.fields = {
	REMOVEMAIL_MAILID_FIELD
}
REMOVEMAIL.is_extendable = false
REMOVEMAIL.extensions = {}
EDITPLAYERINFO_NAME_FIELD.name = "name"
EDITPLAYERINFO_NAME_FIELD.full_name = ".EditPlayerInfo.name"
EDITPLAYERINFO_NAME_FIELD.number = 1
EDITPLAYERINFO_NAME_FIELD.index = 0
EDITPLAYERINFO_NAME_FIELD.label = 2
EDITPLAYERINFO_NAME_FIELD.has_default_value = false
EDITPLAYERINFO_NAME_FIELD.default_value = ""
EDITPLAYERINFO_NAME_FIELD.type = 9
EDITPLAYERINFO_NAME_FIELD.cpp_type = 9
EDITPLAYERINFO_ICON_FIELD.name = "icon"
EDITPLAYERINFO_ICON_FIELD.full_name = ".EditPlayerInfo.icon"
EDITPLAYERINFO_ICON_FIELD.number = 2
EDITPLAYERINFO_ICON_FIELD.index = 1
EDITPLAYERINFO_ICON_FIELD.label = 1
EDITPLAYERINFO_ICON_FIELD.has_default_value = false
EDITPLAYERINFO_ICON_FIELD.default_value = 0
EDITPLAYERINFO_ICON_FIELD.type = 13
EDITPLAYERINFO_ICON_FIELD.cpp_type = 3
EDITPLAYERINFO_ICONURL_FIELD.name = "iconUrl"
EDITPLAYERINFO_ICONURL_FIELD.full_name = ".EditPlayerInfo.iconUrl"
EDITPLAYERINFO_ICONURL_FIELD.number = 3
EDITPLAYERINFO_ICONURL_FIELD.index = 2
EDITPLAYERINFO_ICONURL_FIELD.label = 1
EDITPLAYERINFO_ICONURL_FIELD.has_default_value = false
EDITPLAYERINFO_ICONURL_FIELD.default_value = ""
EDITPLAYERINFO_ICONURL_FIELD.type = 9
EDITPLAYERINFO_ICONURL_FIELD.cpp_type = 9
EDITPLAYERINFO.name = "EditPlayerInfo"
EDITPLAYERINFO.full_name = ".EditPlayerInfo"
EDITPLAYERINFO.nested_types = {}
EDITPLAYERINFO.enum_types = {}
EDITPLAYERINFO.fields = {
	EDITPLAYERINFO_NAME_FIELD,
	EDITPLAYERINFO_ICON_FIELD,
	EDITPLAYERINFO_ICONURL_FIELD
}
EDITPLAYERINFO.is_extendable = false
EDITPLAYERINFO.extensions = {}
AddChargeLog = protobuf.Message(ADDCHARGELOG)
ChargeLogs = protobuf.Message(CHARGELOGS)
CurrencyNotEnough = protobuf.Message(CURRENCYNOTENOUGH)
EditPlayerInfo = protobuf.Message(EDITPLAYERINFO)
Mail = protobuf.Message(MAIL)
Mails = protobuf.Message(MAILS)
PlayerInfo = protobuf.Message(PLAYERINFO)
PlayerInitInfo = protobuf.Message(PLAYERINITINFO)
PlayerList = protobuf.Message(PLAYERLIST)
RemoveMail = protobuf.Message(REMOVEMAIL)
ReqCreatePlayer = protobuf.Message(REQCREATEPLAYER)
ReqPlayerEnter = protobuf.Message(REQPLAYERENTER)
ReqReadMail = protobuf.Message(REQREADMAIL)
UpdateCurrency = protobuf.Message(UPDATECURRENCY)
UpdateVip = protobuf.Message(UPDATEVIP)
