-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Protocol/Protobuf/BattleSystem_pb.lua

local protobuf = require("protobuf/protobuf")

module("LuaScript/Protocol/Protobuf/BattleSystem_pb")

REQLOGINBATTLE = protobuf.Descriptor()

local REQLOGINBATTLE_USERID_FIELD = protobuf.FieldDescriptor()
local REQLOGINBATTLE_USERNAME_FIELD = protobuf.FieldDescriptor()

RESPLOGINBATTLE = protobuf.Descriptor()

local RESPLOGINBATTLE_SIGN_FIELD = protobuf.FieldDescriptor()
local RESPLOGINBATTLE_ISINROOM_FIELD = protobuf.FieldDescriptor()

RESPLOGOFFBATTLE = protobuf.Descriptor()

local RESPLOGOFFBATTLE_CODE_FIELD = protobuf.FieldDescriptor()

RESPUSEROFFLINE = protobuf.Descriptor()

local RESPUSEROFFLINE_USERID_FIELD = protobuf.FieldDescriptor()

RESPUSERONLINE = protobuf.Descriptor()

local RESPUSERONLINE_USERID_FIELD = protobuf.FieldDescriptor()

REQUDPLOGIN = protobuf.Descriptor()
PING = protobuf.Descriptor()

local PING_INDEX_FIELD = protobuf.FieldDescriptor()

PONG = protobuf.Descriptor()

local PONG_INDEX_FIELD = protobuf.FieldDescriptor()
local PONG_TIME_FIELD = protobuf.FieldDescriptor()

HEARTBEAT = protobuf.Descriptor()
RESPHEARTBEAT = protobuf.Descriptor()

local RESPHEARTBEAT_TIME_FIELD = protobuf.FieldDescriptor()

REQLOGINGAME = protobuf.Descriptor()

local REQLOGINGAME_GLBACCID_FIELD = protobuf.FieldDescriptor()
local REQLOGINGAME_TIME_FIELD = protobuf.FieldDescriptor()
local REQLOGINGAME_SIGN_FIELD = protobuf.FieldDescriptor()
local REQLOGINGAME_CHANNELID_FIELD = protobuf.FieldDescriptor()
local REQLOGINGAME_CHANNELUSERID_FIELD = protobuf.FieldDescriptor()

RESPLOGOFFGAME = protobuf.Descriptor()

local RESPLOGOFFGAME_CODE_FIELD = protobuf.FieldDescriptor()

REQLOGINGAMETOSEARCH = protobuf.Descriptor()

local REQLOGINGAMETOSEARCH_SERVERID_FIELD = protobuf.FieldDescriptor()

RESPLOGINGAMETOSEARCH = protobuf.Descriptor()

local RESPLOGINGAMETOSEARCH_VALUE_FIELD = protobuf.FieldDescriptor()

REQLOGINGAMETOGLOBAL = protobuf.Descriptor()

local REQLOGINGAMETOGLOBAL_SERVERID_FIELD = protobuf.FieldDescriptor()

RESPLOGINGAMETOGLOBAL = protobuf.Descriptor()

local RESPLOGINGAMETOGLOBAL_VALUE_FIELD = protobuf.FieldDescriptor()

REQLOGINGAMETOCHAT = protobuf.Descriptor()

local REQLOGINGAMETOCHAT_SERVERID_FIELD = protobuf.FieldDescriptor()

RESPLOGINGAMETOCHAT = protobuf.Descriptor()

local RESPLOGINGAMETOCHAT_VALUE_FIELD = protobuf.FieldDescriptor()

REQLOGINBATTLETOSEARCH = protobuf.Descriptor()

local REQLOGINBATTLETOSEARCH_SERVERID_FIELD = protobuf.FieldDescriptor()

RESPLOGINBATTLETOSEARCH = protobuf.Descriptor()

local RESPLOGINBATTLETOSEARCH_VALUE_FIELD = protobuf.FieldDescriptor()

REQUSEROFFLINETOSEARCH = protobuf.Descriptor()

local REQUSEROFFLINETOSEARCH_USERID_FIELD = protobuf.FieldDescriptor()

REQUSEROFFLINETOBATTLE = protobuf.Descriptor()

local REQUSEROFFLINETOBATTLE_USERID_FIELD = protobuf.FieldDescriptor()

REQLOGINBATTLE_USERID_FIELD.name = "userId"
REQLOGINBATTLE_USERID_FIELD.full_name = ".ReqLoginBattle.userId"
REQLOGINBATTLE_USERID_FIELD.number = 1
REQLOGINBATTLE_USERID_FIELD.index = 0
REQLOGINBATTLE_USERID_FIELD.label = 2
REQLOGINBATTLE_USERID_FIELD.has_default_value = false
REQLOGINBATTLE_USERID_FIELD.default_value = 0
REQLOGINBATTLE_USERID_FIELD.type = 13
REQLOGINBATTLE_USERID_FIELD.cpp_type = 3
REQLOGINBATTLE_USERNAME_FIELD.name = "username"
REQLOGINBATTLE_USERNAME_FIELD.full_name = ".ReqLoginBattle.username"
REQLOGINBATTLE_USERNAME_FIELD.number = 2
REQLOGINBATTLE_USERNAME_FIELD.index = 1
REQLOGINBATTLE_USERNAME_FIELD.label = 2
REQLOGINBATTLE_USERNAME_FIELD.has_default_value = false
REQLOGINBATTLE_USERNAME_FIELD.default_value = ""
REQLOGINBATTLE_USERNAME_FIELD.type = 9
REQLOGINBATTLE_USERNAME_FIELD.cpp_type = 9
REQLOGINBATTLE.name = "ReqLoginBattle"
REQLOGINBATTLE.full_name = ".ReqLoginBattle"
REQLOGINBATTLE.nested_types = {}
REQLOGINBATTLE.enum_types = {}
REQLOGINBATTLE.fields = {
	REQLOGINBATTLE_USERID_FIELD,
	REQLOGINBATTLE_USERNAME_FIELD
}
REQLOGINBATTLE.is_extendable = false
REQLOGINBATTLE.extensions = {}
RESPLOGINBATTLE_SIGN_FIELD.name = "sign"
RESPLOGINBATTLE_SIGN_FIELD.full_name = ".RespLoginBattle.sign"
RESPLOGINBATTLE_SIGN_FIELD.number = 1
RESPLOGINBATTLE_SIGN_FIELD.index = 0
RESPLOGINBATTLE_SIGN_FIELD.label = 2
RESPLOGINBATTLE_SIGN_FIELD.has_default_value = false
RESPLOGINBATTLE_SIGN_FIELD.default_value = 0
RESPLOGINBATTLE_SIGN_FIELD.type = 13
RESPLOGINBATTLE_SIGN_FIELD.cpp_type = 3
RESPLOGINBATTLE_ISINROOM_FIELD.name = "isInRoom"
RESPLOGINBATTLE_ISINROOM_FIELD.full_name = ".RespLoginBattle.isInRoom"
RESPLOGINBATTLE_ISINROOM_FIELD.number = 2
RESPLOGINBATTLE_ISINROOM_FIELD.index = 1
RESPLOGINBATTLE_ISINROOM_FIELD.label = 2
RESPLOGINBATTLE_ISINROOM_FIELD.has_default_value = false
RESPLOGINBATTLE_ISINROOM_FIELD.default_value = false
RESPLOGINBATTLE_ISINROOM_FIELD.type = 8
RESPLOGINBATTLE_ISINROOM_FIELD.cpp_type = 7
RESPLOGINBATTLE.name = "RespLoginBattle"
RESPLOGINBATTLE.full_name = ".RespLoginBattle"
RESPLOGINBATTLE.nested_types = {}
RESPLOGINBATTLE.enum_types = {}
RESPLOGINBATTLE.fields = {
	RESPLOGINBATTLE_SIGN_FIELD,
	RESPLOGINBATTLE_ISINROOM_FIELD
}
RESPLOGINBATTLE.is_extendable = false
RESPLOGINBATTLE.extensions = {}
RESPLOGOFFBATTLE_CODE_FIELD.name = "code"
RESPLOGOFFBATTLE_CODE_FIELD.full_name = ".RespLogoffBattle.code"
RESPLOGOFFBATTLE_CODE_FIELD.number = 1
RESPLOGOFFBATTLE_CODE_FIELD.index = 0
RESPLOGOFFBATTLE_CODE_FIELD.label = 2
RESPLOGOFFBATTLE_CODE_FIELD.has_default_value = false
RESPLOGOFFBATTLE_CODE_FIELD.default_value = 0
RESPLOGOFFBATTLE_CODE_FIELD.type = 13
RESPLOGOFFBATTLE_CODE_FIELD.cpp_type = 3
RESPLOGOFFBATTLE.name = "RespLogoffBattle"
RESPLOGOFFBATTLE.full_name = ".RespLogoffBattle"
RESPLOGOFFBATTLE.nested_types = {}
RESPLOGOFFBATTLE.enum_types = {}
RESPLOGOFFBATTLE.fields = {
	RESPLOGOFFBATTLE_CODE_FIELD
}
RESPLOGOFFBATTLE.is_extendable = false
RESPLOGOFFBATTLE.extensions = {}
RESPUSEROFFLINE_USERID_FIELD.name = "userId"
RESPUSEROFFLINE_USERID_FIELD.full_name = ".RespUserOffline.userId"
RESPUSEROFFLINE_USERID_FIELD.number = 1
RESPUSEROFFLINE_USERID_FIELD.index = 0
RESPUSEROFFLINE_USERID_FIELD.label = 2
RESPUSEROFFLINE_USERID_FIELD.has_default_value = false
RESPUSEROFFLINE_USERID_FIELD.default_value = 0
RESPUSEROFFLINE_USERID_FIELD.type = 13
RESPUSEROFFLINE_USERID_FIELD.cpp_type = 3
RESPUSEROFFLINE.name = "RespUserOffline"
RESPUSEROFFLINE.full_name = ".RespUserOffline"
RESPUSEROFFLINE.nested_types = {}
RESPUSEROFFLINE.enum_types = {}
RESPUSEROFFLINE.fields = {
	RESPUSEROFFLINE_USERID_FIELD
}
RESPUSEROFFLINE.is_extendable = false
RESPUSEROFFLINE.extensions = {}
RESPUSERONLINE_USERID_FIELD.name = "userId"
RESPUSERONLINE_USERID_FIELD.full_name = ".RespUserOnline.userId"
RESPUSERONLINE_USERID_FIELD.number = 1
RESPUSERONLINE_USERID_FIELD.index = 0
RESPUSERONLINE_USERID_FIELD.label = 2
RESPUSERONLINE_USERID_FIELD.has_default_value = false
RESPUSERONLINE_USERID_FIELD.default_value = 0
RESPUSERONLINE_USERID_FIELD.type = 13
RESPUSERONLINE_USERID_FIELD.cpp_type = 3
RESPUSERONLINE.name = "RespUserOnline"
RESPUSERONLINE.full_name = ".RespUserOnline"
RESPUSERONLINE.nested_types = {}
RESPUSERONLINE.enum_types = {}
RESPUSERONLINE.fields = {
	RESPUSERONLINE_USERID_FIELD
}
RESPUSERONLINE.is_extendable = false
RESPUSERONLINE.extensions = {}
REQUDPLOGIN.name = "ReqUdpLogin"
REQUDPLOGIN.full_name = ".ReqUdpLogin"
REQUDPLOGIN.nested_types = {}
REQUDPLOGIN.enum_types = {}
REQUDPLOGIN.fields = {}
REQUDPLOGIN.is_extendable = false
REQUDPLOGIN.extensions = {}
PING_INDEX_FIELD.name = "index"
PING_INDEX_FIELD.full_name = ".Ping.index"
PING_INDEX_FIELD.number = 1
PING_INDEX_FIELD.index = 0
PING_INDEX_FIELD.label = 2
PING_INDEX_FIELD.has_default_value = false
PING_INDEX_FIELD.default_value = 0
PING_INDEX_FIELD.type = 13
PING_INDEX_FIELD.cpp_type = 3
PING.name = "Ping"
PING.full_name = ".Ping"
PING.nested_types = {}
PING.enum_types = {}
PING.fields = {
	PING_INDEX_FIELD
}
PING.is_extendable = false
PING.extensions = {}
PONG_INDEX_FIELD.name = "index"
PONG_INDEX_FIELD.full_name = ".Pong.index"
PONG_INDEX_FIELD.number = 1
PONG_INDEX_FIELD.index = 0
PONG_INDEX_FIELD.label = 2
PONG_INDEX_FIELD.has_default_value = false
PONG_INDEX_FIELD.default_value = 0
PONG_INDEX_FIELD.type = 13
PONG_INDEX_FIELD.cpp_type = 3
PONG_TIME_FIELD.name = "time"
PONG_TIME_FIELD.full_name = ".Pong.time"
PONG_TIME_FIELD.number = 2
PONG_TIME_FIELD.index = 1
PONG_TIME_FIELD.label = 2
PONG_TIME_FIELD.has_default_value = false
PONG_TIME_FIELD.default_value = 0
PONG_TIME_FIELD.type = 13
PONG_TIME_FIELD.cpp_type = 3
PONG.name = "Pong"
PONG.full_name = ".Pong"
PONG.nested_types = {}
PONG.enum_types = {}
PONG.fields = {
	PONG_INDEX_FIELD,
	PONG_TIME_FIELD
}
PONG.is_extendable = false
PONG.extensions = {}
HEARTBEAT.name = "Heartbeat"
HEARTBEAT.full_name = ".Heartbeat"
HEARTBEAT.nested_types = {}
HEARTBEAT.enum_types = {}
HEARTBEAT.fields = {}
HEARTBEAT.is_extendable = false
HEARTBEAT.extensions = {}
RESPHEARTBEAT_TIME_FIELD.name = "time"
RESPHEARTBEAT_TIME_FIELD.full_name = ".RespHeartbeat.time"
RESPHEARTBEAT_TIME_FIELD.number = 1
RESPHEARTBEAT_TIME_FIELD.index = 0
RESPHEARTBEAT_TIME_FIELD.label = 2
RESPHEARTBEAT_TIME_FIELD.has_default_value = false
RESPHEARTBEAT_TIME_FIELD.default_value = 0
RESPHEARTBEAT_TIME_FIELD.type = 13
RESPHEARTBEAT_TIME_FIELD.cpp_type = 3
RESPHEARTBEAT.name = "RespHeartbeat"
RESPHEARTBEAT.full_name = ".RespHeartbeat"
RESPHEARTBEAT.nested_types = {}
RESPHEARTBEAT.enum_types = {}
RESPHEARTBEAT.fields = {
	RESPHEARTBEAT_TIME_FIELD
}
RESPHEARTBEAT.is_extendable = false
RESPHEARTBEAT.extensions = {}
REQLOGINGAME_GLBACCID_FIELD.name = "glbAccId"
REQLOGINGAME_GLBACCID_FIELD.full_name = ".ReqLoginGame.glbAccId"
REQLOGINGAME_GLBACCID_FIELD.number = 1
REQLOGINGAME_GLBACCID_FIELD.index = 0
REQLOGINGAME_GLBACCID_FIELD.label = 2
REQLOGINGAME_GLBACCID_FIELD.has_default_value = false
REQLOGINGAME_GLBACCID_FIELD.default_value = 0
REQLOGINGAME_GLBACCID_FIELD.type = 13
REQLOGINGAME_GLBACCID_FIELD.cpp_type = 3
REQLOGINGAME_TIME_FIELD.name = "time"
REQLOGINGAME_TIME_FIELD.full_name = ".ReqLoginGame.time"
REQLOGINGAME_TIME_FIELD.number = 2
REQLOGINGAME_TIME_FIELD.index = 1
REQLOGINGAME_TIME_FIELD.label = 2
REQLOGINGAME_TIME_FIELD.has_default_value = false
REQLOGINGAME_TIME_FIELD.default_value = 0
REQLOGINGAME_TIME_FIELD.type = 13
REQLOGINGAME_TIME_FIELD.cpp_type = 3
REQLOGINGAME_SIGN_FIELD.name = "sign"
REQLOGINGAME_SIGN_FIELD.full_name = ".ReqLoginGame.sign"
REQLOGINGAME_SIGN_FIELD.number = 3
REQLOGINGAME_SIGN_FIELD.index = 2
REQLOGINGAME_SIGN_FIELD.label = 2
REQLOGINGAME_SIGN_FIELD.has_default_value = false
REQLOGINGAME_SIGN_FIELD.default_value = ""
REQLOGINGAME_SIGN_FIELD.type = 9
REQLOGINGAME_SIGN_FIELD.cpp_type = 9
REQLOGINGAME_CHANNELID_FIELD.name = "channelId"
REQLOGINGAME_CHANNELID_FIELD.full_name = ".ReqLoginGame.channelId"
REQLOGINGAME_CHANNELID_FIELD.number = 4
REQLOGINGAME_CHANNELID_FIELD.index = 3
REQLOGINGAME_CHANNELID_FIELD.label = 2
REQLOGINGAME_CHANNELID_FIELD.has_default_value = false
REQLOGINGAME_CHANNELID_FIELD.default_value = ""
REQLOGINGAME_CHANNELID_FIELD.type = 9
REQLOGINGAME_CHANNELID_FIELD.cpp_type = 9
REQLOGINGAME_CHANNELUSERID_FIELD.name = "channelUserId"
REQLOGINGAME_CHANNELUSERID_FIELD.full_name = ".ReqLoginGame.channelUserId"
REQLOGINGAME_CHANNELUSERID_FIELD.number = 5
REQLOGINGAME_CHANNELUSERID_FIELD.index = 4
REQLOGINGAME_CHANNELUSERID_FIELD.label = 2
REQLOGINGAME_CHANNELUSERID_FIELD.has_default_value = false
REQLOGINGAME_CHANNELUSERID_FIELD.default_value = ""
REQLOGINGAME_CHANNELUSERID_FIELD.type = 9
REQLOGINGAME_CHANNELUSERID_FIELD.cpp_type = 9
REQLOGINGAME.name = "ReqLoginGame"
REQLOGINGAME.full_name = ".ReqLoginGame"
REQLOGINGAME.nested_types = {}
REQLOGINGAME.enum_types = {}
REQLOGINGAME.fields = {
	REQLOGINGAME_GLBACCID_FIELD,
	REQLOGINGAME_TIME_FIELD,
	REQLOGINGAME_SIGN_FIELD,
	REQLOGINGAME_CHANNELID_FIELD,
	REQLOGINGAME_CHANNELUSERID_FIELD
}
REQLOGINGAME.is_extendable = false
REQLOGINGAME.extensions = {}
RESPLOGOFFGAME_CODE_FIELD.name = "code"
RESPLOGOFFGAME_CODE_FIELD.full_name = ".RespLogoffGame.code"
RESPLOGOFFGAME_CODE_FIELD.number = 1
RESPLOGOFFGAME_CODE_FIELD.index = 0
RESPLOGOFFGAME_CODE_FIELD.label = 2
RESPLOGOFFGAME_CODE_FIELD.has_default_value = false
RESPLOGOFFGAME_CODE_FIELD.default_value = 0
RESPLOGOFFGAME_CODE_FIELD.type = 13
RESPLOGOFFGAME_CODE_FIELD.cpp_type = 3
RESPLOGOFFGAME.name = "RespLogoffGame"
RESPLOGOFFGAME.full_name = ".RespLogoffGame"
RESPLOGOFFGAME.nested_types = {}
RESPLOGOFFGAME.enum_types = {}
RESPLOGOFFGAME.fields = {
	RESPLOGOFFGAME_CODE_FIELD
}
RESPLOGOFFGAME.is_extendable = false
RESPLOGOFFGAME.extensions = {}
REQLOGINGAMETOSEARCH_SERVERID_FIELD.name = "serverId"
REQLOGINGAMETOSEARCH_SERVERID_FIELD.full_name = ".ReqLoginGameToSearch.serverId"
REQLOGINGAMETOSEARCH_SERVERID_FIELD.number = 1
REQLOGINGAMETOSEARCH_SERVERID_FIELD.index = 0
REQLOGINGAMETOSEARCH_SERVERID_FIELD.label = 2
REQLOGINGAMETOSEARCH_SERVERID_FIELD.has_default_value = false
REQLOGINGAMETOSEARCH_SERVERID_FIELD.default_value = 0
REQLOGINGAMETOSEARCH_SERVERID_FIELD.type = 13
REQLOGINGAMETOSEARCH_SERVERID_FIELD.cpp_type = 3
REQLOGINGAMETOSEARCH.name = "ReqLoginGameToSearch"
REQLOGINGAMETOSEARCH.full_name = ".ReqLoginGameToSearch"
REQLOGINGAMETOSEARCH.nested_types = {}
REQLOGINGAMETOSEARCH.enum_types = {}
REQLOGINGAMETOSEARCH.fields = {
	REQLOGINGAMETOSEARCH_SERVERID_FIELD
}
REQLOGINGAMETOSEARCH.is_extendable = false
REQLOGINGAMETOSEARCH.extensions = {}
RESPLOGINGAMETOSEARCH_VALUE_FIELD.name = "value"
RESPLOGINGAMETOSEARCH_VALUE_FIELD.full_name = ".RespLoginGameToSearch.value"
RESPLOGINGAMETOSEARCH_VALUE_FIELD.number = 1
RESPLOGINGAMETOSEARCH_VALUE_FIELD.index = 0
RESPLOGINGAMETOSEARCH_VALUE_FIELD.label = 2
RESPLOGINGAMETOSEARCH_VALUE_FIELD.has_default_value = false
RESPLOGINGAMETOSEARCH_VALUE_FIELD.default_value = 0
RESPLOGINGAMETOSEARCH_VALUE_FIELD.type = 13
RESPLOGINGAMETOSEARCH_VALUE_FIELD.cpp_type = 3
RESPLOGINGAMETOSEARCH.name = "RespLoginGameToSearch"
RESPLOGINGAMETOSEARCH.full_name = ".RespLoginGameToSearch"
RESPLOGINGAMETOSEARCH.nested_types = {}
RESPLOGINGAMETOSEARCH.enum_types = {}
RESPLOGINGAMETOSEARCH.fields = {
	RESPLOGINGAMETOSEARCH_VALUE_FIELD
}
RESPLOGINGAMETOSEARCH.is_extendable = false
RESPLOGINGAMETOSEARCH.extensions = {}
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.name = "serverId"
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.full_name = ".ReqLoginGameToGlobal.serverId"
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.number = 1
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.index = 0
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.label = 2
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.has_default_value = false
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.default_value = 0
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.type = 13
REQLOGINGAMETOGLOBAL_SERVERID_FIELD.cpp_type = 3
REQLOGINGAMETOGLOBAL.name = "ReqLoginGameToGlobal"
REQLOGINGAMETOGLOBAL.full_name = ".ReqLoginGameToGlobal"
REQLOGINGAMETOGLOBAL.nested_types = {}
REQLOGINGAMETOGLOBAL.enum_types = {}
REQLOGINGAMETOGLOBAL.fields = {
	REQLOGINGAMETOGLOBAL_SERVERID_FIELD
}
REQLOGINGAMETOGLOBAL.is_extendable = false
REQLOGINGAMETOGLOBAL.extensions = {}
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.name = "value"
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.full_name = ".RespLoginGameToGlobal.value"
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.number = 1
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.index = 0
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.label = 2
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.has_default_value = false
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.default_value = 0
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.type = 13
RESPLOGINGAMETOGLOBAL_VALUE_FIELD.cpp_type = 3
RESPLOGINGAMETOGLOBAL.name = "RespLoginGameToGlobal"
RESPLOGINGAMETOGLOBAL.full_name = ".RespLoginGameToGlobal"
RESPLOGINGAMETOGLOBAL.nested_types = {}
RESPLOGINGAMETOGLOBAL.enum_types = {}
RESPLOGINGAMETOGLOBAL.fields = {
	RESPLOGINGAMETOGLOBAL_VALUE_FIELD
}
RESPLOGINGAMETOGLOBAL.is_extendable = false
RESPLOGINGAMETOGLOBAL.extensions = {}
REQLOGINGAMETOCHAT_SERVERID_FIELD.name = "serverId"
REQLOGINGAMETOCHAT_SERVERID_FIELD.full_name = ".ReqLoginGameToChat.serverId"
REQLOGINGAMETOCHAT_SERVERID_FIELD.number = 1
REQLOGINGAMETOCHAT_SERVERID_FIELD.index = 0
REQLOGINGAMETOCHAT_SERVERID_FIELD.label = 2
REQLOGINGAMETOCHAT_SERVERID_FIELD.has_default_value = false
REQLOGINGAMETOCHAT_SERVERID_FIELD.default_value = 0
REQLOGINGAMETOCHAT_SERVERID_FIELD.type = 13
REQLOGINGAMETOCHAT_SERVERID_FIELD.cpp_type = 3
REQLOGINGAMETOCHAT.name = "ReqLoginGameToChat"
REQLOGINGAMETOCHAT.full_name = ".ReqLoginGameToChat"
REQLOGINGAMETOCHAT.nested_types = {}
REQLOGINGAMETOCHAT.enum_types = {}
REQLOGINGAMETOCHAT.fields = {
	REQLOGINGAMETOCHAT_SERVERID_FIELD
}
REQLOGINGAMETOCHAT.is_extendable = false
REQLOGINGAMETOCHAT.extensions = {}
RESPLOGINGAMETOCHAT_VALUE_FIELD.name = "value"
RESPLOGINGAMETOCHAT_VALUE_FIELD.full_name = ".RespLoginGameToChat.value"
RESPLOGINGAMETOCHAT_VALUE_FIELD.number = 1
RESPLOGINGAMETOCHAT_VALUE_FIELD.index = 0
RESPLOGINGAMETOCHAT_VALUE_FIELD.label = 2
RESPLOGINGAMETOCHAT_VALUE_FIELD.has_default_value = false
RESPLOGINGAMETOCHAT_VALUE_FIELD.default_value = 0
RESPLOGINGAMETOCHAT_VALUE_FIELD.type = 13
RESPLOGINGAMETOCHAT_VALUE_FIELD.cpp_type = 3
RESPLOGINGAMETOCHAT.name = "RespLoginGameToChat"
RESPLOGINGAMETOCHAT.full_name = ".RespLoginGameToChat"
RESPLOGINGAMETOCHAT.nested_types = {}
RESPLOGINGAMETOCHAT.enum_types = {}
RESPLOGINGAMETOCHAT.fields = {
	RESPLOGINGAMETOCHAT_VALUE_FIELD
}
RESPLOGINGAMETOCHAT.is_extendable = false
RESPLOGINGAMETOCHAT.extensions = {}
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.name = "serverId"
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.full_name = ".ReqLoginBattleToSearch.serverId"
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.number = 1
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.index = 0
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.label = 2
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.has_default_value = false
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.default_value = 0
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.type = 13
REQLOGINBATTLETOSEARCH_SERVERID_FIELD.cpp_type = 3
REQLOGINBATTLETOSEARCH.name = "ReqLoginBattleToSearch"
REQLOGINBATTLETOSEARCH.full_name = ".ReqLoginBattleToSearch"
REQLOGINBATTLETOSEARCH.nested_types = {}
REQLOGINBATTLETOSEARCH.enum_types = {}
REQLOGINBATTLETOSEARCH.fields = {
	REQLOGINBATTLETOSEARCH_SERVERID_FIELD
}
REQLOGINBATTLETOSEARCH.is_extendable = false
REQLOGINBATTLETOSEARCH.extensions = {}
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.name = "value"
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.full_name = ".RespLoginBattleToSearch.value"
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.number = 1
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.index = 0
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.label = 2
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.has_default_value = false
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.default_value = 0
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.type = 13
RESPLOGINBATTLETOSEARCH_VALUE_FIELD.cpp_type = 3
RESPLOGINBATTLETOSEARCH.name = "RespLoginBattleToSearch"
RESPLOGINBATTLETOSEARCH.full_name = ".RespLoginBattleToSearch"
RESPLOGINBATTLETOSEARCH.nested_types = {}
RESPLOGINBATTLETOSEARCH.enum_types = {}
RESPLOGINBATTLETOSEARCH.fields = {
	RESPLOGINBATTLETOSEARCH_VALUE_FIELD
}
RESPLOGINBATTLETOSEARCH.is_extendable = false
RESPLOGINBATTLETOSEARCH.extensions = {}
REQUSEROFFLINETOSEARCH_USERID_FIELD.name = "userId"
REQUSEROFFLINETOSEARCH_USERID_FIELD.full_name = ".ReqUserOfflineToSearch.userId"
REQUSEROFFLINETOSEARCH_USERID_FIELD.number = 1
REQUSEROFFLINETOSEARCH_USERID_FIELD.index = 0
REQUSEROFFLINETOSEARCH_USERID_FIELD.label = 2
REQUSEROFFLINETOSEARCH_USERID_FIELD.has_default_value = false
REQUSEROFFLINETOSEARCH_USERID_FIELD.default_value = 0
REQUSEROFFLINETOSEARCH_USERID_FIELD.type = 13
REQUSEROFFLINETOSEARCH_USERID_FIELD.cpp_type = 3
REQUSEROFFLINETOSEARCH.name = "ReqUserOfflineToSearch"
REQUSEROFFLINETOSEARCH.full_name = ".ReqUserOfflineToSearch"
REQUSEROFFLINETOSEARCH.nested_types = {}
REQUSEROFFLINETOSEARCH.enum_types = {}
REQUSEROFFLINETOSEARCH.fields = {
	REQUSEROFFLINETOSEARCH_USERID_FIELD
}
REQUSEROFFLINETOSEARCH.is_extendable = false
REQUSEROFFLINETOSEARCH.extensions = {}
REQUSEROFFLINETOBATTLE_USERID_FIELD.name = "userId"
REQUSEROFFLINETOBATTLE_USERID_FIELD.full_name = ".ReqUserOfflineToBattle.userId"
REQUSEROFFLINETOBATTLE_USERID_FIELD.number = 1
REQUSEROFFLINETOBATTLE_USERID_FIELD.index = 0
REQUSEROFFLINETOBATTLE_USERID_FIELD.label = 2
REQUSEROFFLINETOBATTLE_USERID_FIELD.has_default_value = false
REQUSEROFFLINETOBATTLE_USERID_FIELD.default_value = 0
REQUSEROFFLINETOBATTLE_USERID_FIELD.type = 13
REQUSEROFFLINETOBATTLE_USERID_FIELD.cpp_type = 3
REQUSEROFFLINETOBATTLE.name = "ReqUserOfflineToBattle"
REQUSEROFFLINETOBATTLE.full_name = ".ReqUserOfflineToBattle"
REQUSEROFFLINETOBATTLE.nested_types = {}
REQUSEROFFLINETOBATTLE.enum_types = {}
REQUSEROFFLINETOBATTLE.fields = {
	REQUSEROFFLINETOBATTLE_USERID_FIELD
}
REQUSEROFFLINETOBATTLE.is_extendable = false
REQUSEROFFLINETOBATTLE.extensions = {}
Heartbeat = protobuf.Message(HEARTBEAT)
Ping = protobuf.Message(PING)
Pong = protobuf.Message(PONG)
ReqLoginBattle = protobuf.Message(REQLOGINBATTLE)
ReqLoginBattleToSearch = protobuf.Message(REQLOGINBATTLETOSEARCH)
ReqLoginGame = protobuf.Message(REQLOGINGAME)
ReqLoginGameToChat = protobuf.Message(REQLOGINGAMETOCHAT)
ReqLoginGameToGlobal = protobuf.Message(REQLOGINGAMETOGLOBAL)
ReqLoginGameToSearch = protobuf.Message(REQLOGINGAMETOSEARCH)
ReqUdpLogin = protobuf.Message(REQUDPLOGIN)
ReqUserOfflineToBattle = protobuf.Message(REQUSEROFFLINETOBATTLE)
ReqUserOfflineToSearch = protobuf.Message(REQUSEROFFLINETOSEARCH)
RespHeartbeat = protobuf.Message(RESPHEARTBEAT)
RespLoginBattle = protobuf.Message(RESPLOGINBATTLE)
RespLoginBattleToSearch = protobuf.Message(RESPLOGINBATTLETOSEARCH)
RespLoginGameToChat = protobuf.Message(RESPLOGINGAMETOCHAT)
RespLoginGameToGlobal = protobuf.Message(RESPLOGINGAMETOGLOBAL)
RespLoginGameToSearch = protobuf.Message(RESPLOGINGAMETOSEARCH)
RespLogoffBattle = protobuf.Message(RESPLOGOFFBATTLE)
RespLogoffGame = protobuf.Message(RESPLOGOFFGAME)
RespUserOffline = protobuf.Message(RESPUSEROFFLINE)
RespUserOnline = protobuf.Message(RESPUSERONLINE)
