-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Protocol/Protobuf/BattleHero_pb.lua

local protobuf = require("protobuf/protobuf")

module("LuaScript/Protocol/Protobuf/BattleHero_pb")

TALENTITEM = protobuf.Descriptor()

local TALENTITEM_ID_FIELD = protobuf.FieldDescriptor()
local TALENTITEM_VALUE_FIELD = protobuf.FieldDescriptor()

TALENTTREE = protobuf.Descriptor()

local TALENTTREE_SPECIAL_FIELD = protobuf.FieldDescriptor()
local TALENTTREE_PROP_FIELD = protobuf.FieldDescriptor()
local TALENTTREE_SMART_FIELD = protobuf.FieldDescriptor()
local TALENTTREE_STROM_FIELD = protobuf.FieldDescriptor()

SHORTCUT = protobuf.Descriptor()

local SHORTCUT_ID_FIELD = protobuf.FieldDescriptor()
local SHORTCUT_ITEMNO_FIELD = protobuf.FieldDescriptor()

SHORTCUTS = protobuf.Descriptor()

local SHORTCUTS_SHORTCUT_FIELD = protobuf.FieldDescriptor()
local SHORTCUTS_MAINSHORTCUTID_FIELD = protobuf.FieldDescriptor()

HEROINFO = protobuf.Descriptor()

local HEROINFO_ID_FIELD = protobuf.FieldDescriptor()
local HEROINFO_HERONO_FIELD = protobuf.FieldDescriptor()
local HEROINFO_LEVEL_FIELD = protobuf.FieldDescriptor()
local HEROINFO_EXP_FIELD = protobuf.FieldDescriptor()
local HEROINFO_STRENGTH_FIELD = protobuf.FieldDescriptor()
local HEROINFO_SPIRIT_FIELD = protobuf.FieldDescriptor()
local HEROINFO_BRAVE_FIELD = protobuf.FieldDescriptor()
local HEROINFO_DEXTEROUS_FIELD = protobuf.FieldDescriptor()
local HEROINFO_TOLERANT_FIELD = protobuf.FieldDescriptor()
local HEROINFO_GENEROUS_FIELD = protobuf.FieldDescriptor()
local HEROINFO_HIDDENATTRIB_FIELD = protobuf.FieldDescriptor()
local HEROINFO_ATTRIBPOINTS_FIELD = protobuf.FieldDescriptor()
local HEROINFO_TALENTPOINTS_FIELD = protobuf.FieldDescriptor()
local HEROINFO_TALENTTREE_FIELD = protobuf.FieldDescriptor()
local HEROINFO_SHORTCUTS_FIELD = protobuf.FieldDescriptor()

HEROINFOLIST = protobuf.Descriptor()

local HEROINFOLIST_LIST_FIELD = protobuf.FieldDescriptor()

ADDHEROINFO = protobuf.Descriptor()

local ADDHEROINFO_HEROINFO_FIELD = protobuf.FieldDescriptor()

REQUNLOCKHERO = protobuf.Descriptor()

local REQUNLOCKHERO_HERONO_FIELD = protobuf.FieldDescriptor()
local REQUNLOCKHERO_UNLOCKTIME_FIELD = protobuf.FieldDescriptor()
local REQUNLOCKHERO_SIGN_FIELD = protobuf.FieldDescriptor()

REQUSEEXPITEM = protobuf.Descriptor()

local REQUSEEXPITEM_HERONO_FIELD = protobuf.FieldDescriptor()
local REQUSEEXPITEM_ITEMNO_FIELD = protobuf.FieldDescriptor()
local REQUSEEXPITEM_USEQTY_FIELD = protobuf.FieldDescriptor()

HEROEXPLEVUPDATED = protobuf.Descriptor()

local HEROEXPLEVUPDATED_HERONO_FIELD = protobuf.FieldDescriptor()
local HEROEXPLEVUPDATED_LEV_FIELD = protobuf.FieldDescriptor()
local HEROEXPLEVUPDATED_EXP_FIELD = protobuf.FieldDescriptor()
local HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD = protobuf.FieldDescriptor()

HEROATTRIBUPDATED = protobuf.Descriptor()

local HEROATTRIBUPDATED_HERONO_FIELD = protobuf.FieldDescriptor()
local HEROATTRIBUPDATED_ATTRIB1_FIELD = protobuf.FieldDescriptor()
local HEROATTRIBUPDATED_ATTRIB2_FIELD = protobuf.FieldDescriptor()
local HEROATTRIBUPDATED_ATTRIB3_FIELD = protobuf.FieldDescriptor()
local HEROATTRIBUPDATED_ATTRIB4_FIELD = protobuf.FieldDescriptor()
local HEROATTRIBUPDATED_ATTRIB5_FIELD = protobuf.FieldDescriptor()
local HEROATTRIBUPDATED_ATTRIB6_FIELD = protobuf.FieldDescriptor()
local HEROATTRIBUPDATED_ATTRIB7_FIELD = protobuf.FieldDescriptor()
local HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD = protobuf.FieldDescriptor()

REQADDHEROATTRIB = protobuf.Descriptor()

local REQADDHEROATTRIB_HERONO_FIELD = protobuf.FieldDescriptor()
local REQADDHEROATTRIB_ATTRIB1_FIELD = protobuf.FieldDescriptor()
local REQADDHEROATTRIB_ATTRIB2_FIELD = protobuf.FieldDescriptor()
local REQADDHEROATTRIB_ATTRIB3_FIELD = protobuf.FieldDescriptor()
local REQADDHEROATTRIB_ATTRIB4_FIELD = protobuf.FieldDescriptor()
local REQADDHEROATTRIB_ATTRIB5_FIELD = protobuf.FieldDescriptor()
local REQADDHEROATTRIB_ATTRIB6_FIELD = protobuf.FieldDescriptor()
local REQADDHEROATTRIB_ATTRIB7_FIELD = protobuf.FieldDescriptor()

REQSETHEROTALENT = protobuf.Descriptor()

local REQSETHEROTALENT_HERONO_FIELD = protobuf.FieldDescriptor()
local REQSETHEROTALENT_TALENTTYPE_FIELD = protobuf.FieldDescriptor()
local REQSETHEROTALENT_TALENTID_FIELD = protobuf.FieldDescriptor()

REQREMOVEHEROTALENT = protobuf.Descriptor()

local REQREMOVEHEROTALENT_HERONO_FIELD = protobuf.FieldDescriptor()
local REQREMOVEHEROTALENT_TALENTTYPE_FIELD = protobuf.FieldDescriptor()
local REQREMOVEHEROTALENT_TALENTID_FIELD = protobuf.FieldDescriptor()

HEROTALENTUPDATED = protobuf.Descriptor()

local HEROTALENTUPDATED_HERONO_FIELD = protobuf.FieldDescriptor()
local HEROTALENTUPDATED_TALENTTYPE_FIELD = protobuf.FieldDescriptor()
local HEROTALENTUPDATED_TALENTID_FIELD = protobuf.FieldDescriptor()
local HEROTALENTUPDATED_ON_FIELD = protobuf.FieldDescriptor()

REQSAVEHEROSHORTCUT = protobuf.Descriptor()

local REQSAVEHEROSHORTCUT_HERONO_FIELD = protobuf.FieldDescriptor()
local REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD = protobuf.FieldDescriptor()

RESPSAVEHEROSHORTCUTDONE = protobuf.Descriptor()
TALENTITEM_ID_FIELD.name = "id"
TALENTITEM_ID_FIELD.full_name = ".TalentItem.id"
TALENTITEM_ID_FIELD.number = 1
TALENTITEM_ID_FIELD.index = 0
TALENTITEM_ID_FIELD.label = 2
TALENTITEM_ID_FIELD.has_default_value = false
TALENTITEM_ID_FIELD.default_value = 0
TALENTITEM_ID_FIELD.type = 13
TALENTITEM_ID_FIELD.cpp_type = 3
TALENTITEM_VALUE_FIELD.name = "value"
TALENTITEM_VALUE_FIELD.full_name = ".TalentItem.value"
TALENTITEM_VALUE_FIELD.number = 2
TALENTITEM_VALUE_FIELD.index = 1
TALENTITEM_VALUE_FIELD.label = 2
TALENTITEM_VALUE_FIELD.has_default_value = false
TALENTITEM_VALUE_FIELD.default_value = 0
TALENTITEM_VALUE_FIELD.type = 13
TALENTITEM_VALUE_FIELD.cpp_type = 3
TALENTITEM.name = "TalentItem"
TALENTITEM.full_name = ".TalentItem"
TALENTITEM.nested_types = {}
TALENTITEM.enum_types = {}
TALENTITEM.fields = {
	TALENTITEM_ID_FIELD,
	TALENTITEM_VALUE_FIELD
}
TALENTITEM.is_extendable = false
TALENTITEM.extensions = {}
TALENTTREE_SPECIAL_FIELD.name = "special"
TALENTTREE_SPECIAL_FIELD.full_name = ".TalentTree.special"
TALENTTREE_SPECIAL_FIELD.number = 1
TALENTTREE_SPECIAL_FIELD.index = 0
TALENTTREE_SPECIAL_FIELD.label = 3
TALENTTREE_SPECIAL_FIELD.has_default_value = false
TALENTTREE_SPECIAL_FIELD.default_value = {}
TALENTTREE_SPECIAL_FIELD.message_type = TALENTITEM
TALENTTREE_SPECIAL_FIELD.type = 11
TALENTTREE_SPECIAL_FIELD.cpp_type = 10
TALENTTREE_PROP_FIELD.name = "prop"
TALENTTREE_PROP_FIELD.full_name = ".TalentTree.prop"
TALENTTREE_PROP_FIELD.number = 2
TALENTTREE_PROP_FIELD.index = 1
TALENTTREE_PROP_FIELD.label = 3
TALENTTREE_PROP_FIELD.has_default_value = false
TALENTTREE_PROP_FIELD.default_value = {}
TALENTTREE_PROP_FIELD.message_type = TALENTITEM
TALENTTREE_PROP_FIELD.type = 11
TALENTTREE_PROP_FIELD.cpp_type = 10
TALENTTREE_SMART_FIELD.name = "smart"
TALENTTREE_SMART_FIELD.full_name = ".TalentTree.smart"
TALENTTREE_SMART_FIELD.number = 3
TALENTTREE_SMART_FIELD.index = 2
TALENTTREE_SMART_FIELD.label = 3
TALENTTREE_SMART_FIELD.has_default_value = false
TALENTTREE_SMART_FIELD.default_value = {}
TALENTTREE_SMART_FIELD.message_type = TALENTITEM
TALENTTREE_SMART_FIELD.type = 11
TALENTTREE_SMART_FIELD.cpp_type = 10
TALENTTREE_STROM_FIELD.name = "strom"
TALENTTREE_STROM_FIELD.full_name = ".TalentTree.strom"
TALENTTREE_STROM_FIELD.number = 4
TALENTTREE_STROM_FIELD.index = 3
TALENTTREE_STROM_FIELD.label = 3
TALENTTREE_STROM_FIELD.has_default_value = false
TALENTTREE_STROM_FIELD.default_value = {}
TALENTTREE_STROM_FIELD.message_type = TALENTITEM
TALENTTREE_STROM_FIELD.type = 11
TALENTTREE_STROM_FIELD.cpp_type = 10
TALENTTREE.name = "TalentTree"
TALENTTREE.full_name = ".TalentTree"
TALENTTREE.nested_types = {}
TALENTTREE.enum_types = {}
TALENTTREE.fields = {
	TALENTTREE_SPECIAL_FIELD,
	TALENTTREE_PROP_FIELD,
	TALENTTREE_SMART_FIELD,
	TALENTTREE_STROM_FIELD
}
TALENTTREE.is_extendable = false
TALENTTREE.extensions = {}
SHORTCUT_ID_FIELD.name = "id"
SHORTCUT_ID_FIELD.full_name = ".Shortcut.id"
SHORTCUT_ID_FIELD.number = 1
SHORTCUT_ID_FIELD.index = 0
SHORTCUT_ID_FIELD.label = 2
SHORTCUT_ID_FIELD.has_default_value = false
SHORTCUT_ID_FIELD.default_value = 0
SHORTCUT_ID_FIELD.type = 13
SHORTCUT_ID_FIELD.cpp_type = 3
SHORTCUT_ITEMNO_FIELD.name = "itemNo"
SHORTCUT_ITEMNO_FIELD.full_name = ".Shortcut.itemNo"
SHORTCUT_ITEMNO_FIELD.number = 2
SHORTCUT_ITEMNO_FIELD.index = 1
SHORTCUT_ITEMNO_FIELD.label = 2
SHORTCUT_ITEMNO_FIELD.has_default_value = false
SHORTCUT_ITEMNO_FIELD.default_value = 0
SHORTCUT_ITEMNO_FIELD.type = 13
SHORTCUT_ITEMNO_FIELD.cpp_type = 3
SHORTCUT.name = "Shortcut"
SHORTCUT.full_name = ".Shortcut"
SHORTCUT.nested_types = {}
SHORTCUT.enum_types = {}
SHORTCUT.fields = {
	SHORTCUT_ID_FIELD,
	SHORTCUT_ITEMNO_FIELD
}
SHORTCUT.is_extendable = false
SHORTCUT.extensions = {}
SHORTCUTS_SHORTCUT_FIELD.name = "shortcut"
SHORTCUTS_SHORTCUT_FIELD.full_name = ".Shortcuts.shortcut"
SHORTCUTS_SHORTCUT_FIELD.number = 1
SHORTCUTS_SHORTCUT_FIELD.index = 0
SHORTCUTS_SHORTCUT_FIELD.label = 3
SHORTCUTS_SHORTCUT_FIELD.has_default_value = false
SHORTCUTS_SHORTCUT_FIELD.default_value = {}
SHORTCUTS_SHORTCUT_FIELD.message_type = SHORTCUT
SHORTCUTS_SHORTCUT_FIELD.type = 11
SHORTCUTS_SHORTCUT_FIELD.cpp_type = 10
SHORTCUTS_MAINSHORTCUTID_FIELD.name = "mainShortcutId"
SHORTCUTS_MAINSHORTCUTID_FIELD.full_name = ".Shortcuts.mainShortcutId"
SHORTCUTS_MAINSHORTCUTID_FIELD.number = 2
SHORTCUTS_MAINSHORTCUTID_FIELD.index = 1
SHORTCUTS_MAINSHORTCUTID_FIELD.label = 2
SHORTCUTS_MAINSHORTCUTID_FIELD.has_default_value = false
SHORTCUTS_MAINSHORTCUTID_FIELD.default_value = 0
SHORTCUTS_MAINSHORTCUTID_FIELD.type = 13
SHORTCUTS_MAINSHORTCUTID_FIELD.cpp_type = 3
SHORTCUTS.name = "Shortcuts"
SHORTCUTS.full_name = ".Shortcuts"
SHORTCUTS.nested_types = {}
SHORTCUTS.enum_types = {}
SHORTCUTS.fields = {
	SHORTCUTS_SHORTCUT_FIELD,
	SHORTCUTS_MAINSHORTCUTID_FIELD
}
SHORTCUTS.is_extendable = false
SHORTCUTS.extensions = {}
HEROINFO_ID_FIELD.name = "id"
HEROINFO_ID_FIELD.full_name = ".HeroInfo.id"
HEROINFO_ID_FIELD.number = 1
HEROINFO_ID_FIELD.index = 0
HEROINFO_ID_FIELD.label = 2
HEROINFO_ID_FIELD.has_default_value = false
HEROINFO_ID_FIELD.default_value = 0
HEROINFO_ID_FIELD.type = 13
HEROINFO_ID_FIELD.cpp_type = 3
HEROINFO_HERONO_FIELD.name = "heroNo"
HEROINFO_HERONO_FIELD.full_name = ".HeroInfo.heroNo"
HEROINFO_HERONO_FIELD.number = 2
HEROINFO_HERONO_FIELD.index = 1
HEROINFO_HERONO_FIELD.label = 2
HEROINFO_HERONO_FIELD.has_default_value = false
HEROINFO_HERONO_FIELD.default_value = 0
HEROINFO_HERONO_FIELD.type = 13
HEROINFO_HERONO_FIELD.cpp_type = 3
HEROINFO_LEVEL_FIELD.name = "level"
HEROINFO_LEVEL_FIELD.full_name = ".HeroInfo.level"
HEROINFO_LEVEL_FIELD.number = 3
HEROINFO_LEVEL_FIELD.index = 2
HEROINFO_LEVEL_FIELD.label = 2
HEROINFO_LEVEL_FIELD.has_default_value = false
HEROINFO_LEVEL_FIELD.default_value = 0
HEROINFO_LEVEL_FIELD.type = 13
HEROINFO_LEVEL_FIELD.cpp_type = 3
HEROINFO_EXP_FIELD.name = "exp"
HEROINFO_EXP_FIELD.full_name = ".HeroInfo.exp"
HEROINFO_EXP_FIELD.number = 4
HEROINFO_EXP_FIELD.index = 3
HEROINFO_EXP_FIELD.label = 2
HEROINFO_EXP_FIELD.has_default_value = false
HEROINFO_EXP_FIELD.default_value = 0
HEROINFO_EXP_FIELD.type = 13
HEROINFO_EXP_FIELD.cpp_type = 3
HEROINFO_STRENGTH_FIELD.name = "strength"
HEROINFO_STRENGTH_FIELD.full_name = ".HeroInfo.strength"
HEROINFO_STRENGTH_FIELD.number = 5
HEROINFO_STRENGTH_FIELD.index = 4
HEROINFO_STRENGTH_FIELD.label = 2
HEROINFO_STRENGTH_FIELD.has_default_value = false
HEROINFO_STRENGTH_FIELD.default_value = 0
HEROINFO_STRENGTH_FIELD.type = 13
HEROINFO_STRENGTH_FIELD.cpp_type = 3
HEROINFO_SPIRIT_FIELD.name = "spirit"
HEROINFO_SPIRIT_FIELD.full_name = ".HeroInfo.spirit"
HEROINFO_SPIRIT_FIELD.number = 6
HEROINFO_SPIRIT_FIELD.index = 5
HEROINFO_SPIRIT_FIELD.label = 2
HEROINFO_SPIRIT_FIELD.has_default_value = false
HEROINFO_SPIRIT_FIELD.default_value = 0
HEROINFO_SPIRIT_FIELD.type = 13
HEROINFO_SPIRIT_FIELD.cpp_type = 3
HEROINFO_BRAVE_FIELD.name = "brave"
HEROINFO_BRAVE_FIELD.full_name = ".HeroInfo.brave"
HEROINFO_BRAVE_FIELD.number = 7
HEROINFO_BRAVE_FIELD.index = 6
HEROINFO_BRAVE_FIELD.label = 2
HEROINFO_BRAVE_FIELD.has_default_value = false
HEROINFO_BRAVE_FIELD.default_value = 0
HEROINFO_BRAVE_FIELD.type = 13
HEROINFO_BRAVE_FIELD.cpp_type = 3
HEROINFO_DEXTEROUS_FIELD.name = "dexterous"
HEROINFO_DEXTEROUS_FIELD.full_name = ".HeroInfo.dexterous"
HEROINFO_DEXTEROUS_FIELD.number = 8
HEROINFO_DEXTEROUS_FIELD.index = 7
HEROINFO_DEXTEROUS_FIELD.label = 2
HEROINFO_DEXTEROUS_FIELD.has_default_value = false
HEROINFO_DEXTEROUS_FIELD.default_value = 0
HEROINFO_DEXTEROUS_FIELD.type = 13
HEROINFO_DEXTEROUS_FIELD.cpp_type = 3
HEROINFO_TOLERANT_FIELD.name = "tolerant"
HEROINFO_TOLERANT_FIELD.full_name = ".HeroInfo.tolerant"
HEROINFO_TOLERANT_FIELD.number = 9
HEROINFO_TOLERANT_FIELD.index = 8
HEROINFO_TOLERANT_FIELD.label = 2
HEROINFO_TOLERANT_FIELD.has_default_value = false
HEROINFO_TOLERANT_FIELD.default_value = 0
HEROINFO_TOLERANT_FIELD.type = 13
HEROINFO_TOLERANT_FIELD.cpp_type = 3
HEROINFO_GENEROUS_FIELD.name = "generous"
HEROINFO_GENEROUS_FIELD.full_name = ".HeroInfo.generous"
HEROINFO_GENEROUS_FIELD.number = 10
HEROINFO_GENEROUS_FIELD.index = 9
HEROINFO_GENEROUS_FIELD.label = 2
HEROINFO_GENEROUS_FIELD.has_default_value = false
HEROINFO_GENEROUS_FIELD.default_value = 0
HEROINFO_GENEROUS_FIELD.type = 13
HEROINFO_GENEROUS_FIELD.cpp_type = 3
HEROINFO_HIDDENATTRIB_FIELD.name = "hiddenAttrib"
HEROINFO_HIDDENATTRIB_FIELD.full_name = ".HeroInfo.hiddenAttrib"
HEROINFO_HIDDENATTRIB_FIELD.number = 11
HEROINFO_HIDDENATTRIB_FIELD.index = 10
HEROINFO_HIDDENATTRIB_FIELD.label = 2
HEROINFO_HIDDENATTRIB_FIELD.has_default_value = false
HEROINFO_HIDDENATTRIB_FIELD.default_value = 0
HEROINFO_HIDDENATTRIB_FIELD.type = 13
HEROINFO_HIDDENATTRIB_FIELD.cpp_type = 3
HEROINFO_ATTRIBPOINTS_FIELD.name = "attribPoints"
HEROINFO_ATTRIBPOINTS_FIELD.full_name = ".HeroInfo.attribPoints"
HEROINFO_ATTRIBPOINTS_FIELD.number = 12
HEROINFO_ATTRIBPOINTS_FIELD.index = 11
HEROINFO_ATTRIBPOINTS_FIELD.label = 2
HEROINFO_ATTRIBPOINTS_FIELD.has_default_value = false
HEROINFO_ATTRIBPOINTS_FIELD.default_value = 0
HEROINFO_ATTRIBPOINTS_FIELD.type = 13
HEROINFO_ATTRIBPOINTS_FIELD.cpp_type = 3
HEROINFO_TALENTPOINTS_FIELD.name = "talentPoints"
HEROINFO_TALENTPOINTS_FIELD.full_name = ".HeroInfo.talentPoints"
HEROINFO_TALENTPOINTS_FIELD.number = 13
HEROINFO_TALENTPOINTS_FIELD.index = 12
HEROINFO_TALENTPOINTS_FIELD.label = 2
HEROINFO_TALENTPOINTS_FIELD.has_default_value = false
HEROINFO_TALENTPOINTS_FIELD.default_value = 0
HEROINFO_TALENTPOINTS_FIELD.type = 13
HEROINFO_TALENTPOINTS_FIELD.cpp_type = 3
HEROINFO_TALENTTREE_FIELD.name = "talentTree"
HEROINFO_TALENTTREE_FIELD.full_name = ".HeroInfo.talentTree"
HEROINFO_TALENTTREE_FIELD.number = 14
HEROINFO_TALENTTREE_FIELD.index = 13
HEROINFO_TALENTTREE_FIELD.label = 2
HEROINFO_TALENTTREE_FIELD.has_default_value = false
HEROINFO_TALENTTREE_FIELD.default_value = nil
HEROINFO_TALENTTREE_FIELD.message_type = TALENTTREE
HEROINFO_TALENTTREE_FIELD.type = 11
HEROINFO_TALENTTREE_FIELD.cpp_type = 10
HEROINFO_SHORTCUTS_FIELD.name = "shortcuts"
HEROINFO_SHORTCUTS_FIELD.full_name = ".HeroInfo.shortcuts"
HEROINFO_SHORTCUTS_FIELD.number = 15
HEROINFO_SHORTCUTS_FIELD.index = 14
HEROINFO_SHORTCUTS_FIELD.label = 2
HEROINFO_SHORTCUTS_FIELD.has_default_value = false
HEROINFO_SHORTCUTS_FIELD.default_value = nil
HEROINFO_SHORTCUTS_FIELD.message_type = SHORTCUTS
HEROINFO_SHORTCUTS_FIELD.type = 11
HEROINFO_SHORTCUTS_FIELD.cpp_type = 10
HEROINFO.name = "HeroInfo"
HEROINFO.full_name = ".HeroInfo"
HEROINFO.nested_types = {}
HEROINFO.enum_types = {}
HEROINFO.fields = {
	HEROINFO_ID_FIELD,
	HEROINFO_HERONO_FIELD,
	HEROINFO_LEVEL_FIELD,
	HEROINFO_EXP_FIELD,
	HEROINFO_STRENGTH_FIELD,
	HEROINFO_SPIRIT_FIELD,
	HEROINFO_BRAVE_FIELD,
	HEROINFO_DEXTEROUS_FIELD,
	HEROINFO_TOLERANT_FIELD,
	HEROINFO_GENEROUS_FIELD,
	HEROINFO_HIDDENATTRIB_FIELD,
	HEROINFO_ATTRIBPOINTS_FIELD,
	HEROINFO_TALENTPOINTS_FIELD,
	HEROINFO_TALENTTREE_FIELD,
	HEROINFO_SHORTCUTS_FIELD
}
HEROINFO.is_extendable = false
HEROINFO.extensions = {}
HEROINFOLIST_LIST_FIELD.name = "list"
HEROINFOLIST_LIST_FIELD.full_name = ".HeroInfoList.list"
HEROINFOLIST_LIST_FIELD.number = 1
HEROINFOLIST_LIST_FIELD.index = 0
HEROINFOLIST_LIST_FIELD.label = 3
HEROINFOLIST_LIST_FIELD.has_default_value = false
HEROINFOLIST_LIST_FIELD.default_value = {}
HEROINFOLIST_LIST_FIELD.message_type = HEROINFO
HEROINFOLIST_LIST_FIELD.type = 11
HEROINFOLIST_LIST_FIELD.cpp_type = 10
HEROINFOLIST.name = "HeroInfoList"
HEROINFOLIST.full_name = ".HeroInfoList"
HEROINFOLIST.nested_types = {}
HEROINFOLIST.enum_types = {}
HEROINFOLIST.fields = {
	HEROINFOLIST_LIST_FIELD
}
HEROINFOLIST.is_extendable = false
HEROINFOLIST.extensions = {}
ADDHEROINFO_HEROINFO_FIELD.name = "heroInfo"
ADDHEROINFO_HEROINFO_FIELD.full_name = ".AddHeroInfo.heroInfo"
ADDHEROINFO_HEROINFO_FIELD.number = 1
ADDHEROINFO_HEROINFO_FIELD.index = 0
ADDHEROINFO_HEROINFO_FIELD.label = 2
ADDHEROINFO_HEROINFO_FIELD.has_default_value = false
ADDHEROINFO_HEROINFO_FIELD.default_value = nil
ADDHEROINFO_HEROINFO_FIELD.message_type = HEROINFO
ADDHEROINFO_HEROINFO_FIELD.type = 11
ADDHEROINFO_HEROINFO_FIELD.cpp_type = 10
ADDHEROINFO.name = "AddHeroInfo"
ADDHEROINFO.full_name = ".AddHeroInfo"
ADDHEROINFO.nested_types = {}
ADDHEROINFO.enum_types = {}
ADDHEROINFO.fields = {
	ADDHEROINFO_HEROINFO_FIELD
}
ADDHEROINFO.is_extendable = false
ADDHEROINFO.extensions = {}
REQUNLOCKHERO_HERONO_FIELD.name = "heroNo"
REQUNLOCKHERO_HERONO_FIELD.full_name = ".ReqUnlockHero.heroNo"
REQUNLOCKHERO_HERONO_FIELD.number = 1
REQUNLOCKHERO_HERONO_FIELD.index = 0
REQUNLOCKHERO_HERONO_FIELD.label = 2
REQUNLOCKHERO_HERONO_FIELD.has_default_value = false
REQUNLOCKHERO_HERONO_FIELD.default_value = 0
REQUNLOCKHERO_HERONO_FIELD.type = 13
REQUNLOCKHERO_HERONO_FIELD.cpp_type = 3
REQUNLOCKHERO_UNLOCKTIME_FIELD.name = "unlockTime"
REQUNLOCKHERO_UNLOCKTIME_FIELD.full_name = ".ReqUnlockHero.unlockTime"
REQUNLOCKHERO_UNLOCKTIME_FIELD.number = 2
REQUNLOCKHERO_UNLOCKTIME_FIELD.index = 1
REQUNLOCKHERO_UNLOCKTIME_FIELD.label = 2
REQUNLOCKHERO_UNLOCKTIME_FIELD.has_default_value = false
REQUNLOCKHERO_UNLOCKTIME_FIELD.default_value = 0
REQUNLOCKHERO_UNLOCKTIME_FIELD.type = 13
REQUNLOCKHERO_UNLOCKTIME_FIELD.cpp_type = 3
REQUNLOCKHERO_SIGN_FIELD.name = "sign"
REQUNLOCKHERO_SIGN_FIELD.full_name = ".ReqUnlockHero.sign"
REQUNLOCKHERO_SIGN_FIELD.number = 3
REQUNLOCKHERO_SIGN_FIELD.index = 2
REQUNLOCKHERO_SIGN_FIELD.label = 2
REQUNLOCKHERO_SIGN_FIELD.has_default_value = false
REQUNLOCKHERO_SIGN_FIELD.default_value = ""
REQUNLOCKHERO_SIGN_FIELD.type = 9
REQUNLOCKHERO_SIGN_FIELD.cpp_type = 9
REQUNLOCKHERO.name = "ReqUnlockHero"
REQUNLOCKHERO.full_name = ".ReqUnlockHero"
REQUNLOCKHERO.nested_types = {}
REQUNLOCKHERO.enum_types = {}
REQUNLOCKHERO.fields = {
	REQUNLOCKHERO_HERONO_FIELD,
	REQUNLOCKHERO_UNLOCKTIME_FIELD,
	REQUNLOCKHERO_SIGN_FIELD
}
REQUNLOCKHERO.is_extendable = false
REQUNLOCKHERO.extensions = {}
REQUSEEXPITEM_HERONO_FIELD.name = "heroNo"
REQUSEEXPITEM_HERONO_FIELD.full_name = ".ReqUseExpItem.heroNo"
REQUSEEXPITEM_HERONO_FIELD.number = 1
REQUSEEXPITEM_HERONO_FIELD.index = 0
REQUSEEXPITEM_HERONO_FIELD.label = 2
REQUSEEXPITEM_HERONO_FIELD.has_default_value = false
REQUSEEXPITEM_HERONO_FIELD.default_value = 0
REQUSEEXPITEM_HERONO_FIELD.type = 13
REQUSEEXPITEM_HERONO_FIELD.cpp_type = 3
REQUSEEXPITEM_ITEMNO_FIELD.name = "itemNo"
REQUSEEXPITEM_ITEMNO_FIELD.full_name = ".ReqUseExpItem.itemNo"
REQUSEEXPITEM_ITEMNO_FIELD.number = 2
REQUSEEXPITEM_ITEMNO_FIELD.index = 1
REQUSEEXPITEM_ITEMNO_FIELD.label = 2
REQUSEEXPITEM_ITEMNO_FIELD.has_default_value = false
REQUSEEXPITEM_ITEMNO_FIELD.default_value = 0
REQUSEEXPITEM_ITEMNO_FIELD.type = 13
REQUSEEXPITEM_ITEMNO_FIELD.cpp_type = 3
REQUSEEXPITEM_USEQTY_FIELD.name = "useQty"
REQUSEEXPITEM_USEQTY_FIELD.full_name = ".ReqUseExpItem.useQty"
REQUSEEXPITEM_USEQTY_FIELD.number = 3
REQUSEEXPITEM_USEQTY_FIELD.index = 2
REQUSEEXPITEM_USEQTY_FIELD.label = 2
REQUSEEXPITEM_USEQTY_FIELD.has_default_value = false
REQUSEEXPITEM_USEQTY_FIELD.default_value = 0
REQUSEEXPITEM_USEQTY_FIELD.type = 13
REQUSEEXPITEM_USEQTY_FIELD.cpp_type = 3
REQUSEEXPITEM.name = "ReqUseExpItem"
REQUSEEXPITEM.full_name = ".ReqUseExpItem"
REQUSEEXPITEM.nested_types = {}
REQUSEEXPITEM.enum_types = {}
REQUSEEXPITEM.fields = {
	REQUSEEXPITEM_HERONO_FIELD,
	REQUSEEXPITEM_ITEMNO_FIELD,
	REQUSEEXPITEM_USEQTY_FIELD
}
REQUSEEXPITEM.is_extendable = false
REQUSEEXPITEM.extensions = {}
HEROEXPLEVUPDATED_HERONO_FIELD.name = "heroNo"
HEROEXPLEVUPDATED_HERONO_FIELD.full_name = ".HeroExpLevUpdated.heroNo"
HEROEXPLEVUPDATED_HERONO_FIELD.number = 1
HEROEXPLEVUPDATED_HERONO_FIELD.index = 0
HEROEXPLEVUPDATED_HERONO_FIELD.label = 2
HEROEXPLEVUPDATED_HERONO_FIELD.has_default_value = false
HEROEXPLEVUPDATED_HERONO_FIELD.default_value = 0
HEROEXPLEVUPDATED_HERONO_FIELD.type = 13
HEROEXPLEVUPDATED_HERONO_FIELD.cpp_type = 3
HEROEXPLEVUPDATED_LEV_FIELD.name = "lev"
HEROEXPLEVUPDATED_LEV_FIELD.full_name = ".HeroExpLevUpdated.lev"
HEROEXPLEVUPDATED_LEV_FIELD.number = 2
HEROEXPLEVUPDATED_LEV_FIELD.index = 1
HEROEXPLEVUPDATED_LEV_FIELD.label = 2
HEROEXPLEVUPDATED_LEV_FIELD.has_default_value = false
HEROEXPLEVUPDATED_LEV_FIELD.default_value = 0
HEROEXPLEVUPDATED_LEV_FIELD.type = 13
HEROEXPLEVUPDATED_LEV_FIELD.cpp_type = 3
HEROEXPLEVUPDATED_EXP_FIELD.name = "exp"
HEROEXPLEVUPDATED_EXP_FIELD.full_name = ".HeroExpLevUpdated.exp"
HEROEXPLEVUPDATED_EXP_FIELD.number = 3
HEROEXPLEVUPDATED_EXP_FIELD.index = 2
HEROEXPLEVUPDATED_EXP_FIELD.label = 2
HEROEXPLEVUPDATED_EXP_FIELD.has_default_value = false
HEROEXPLEVUPDATED_EXP_FIELD.default_value = 0
HEROEXPLEVUPDATED_EXP_FIELD.type = 13
HEROEXPLEVUPDATED_EXP_FIELD.cpp_type = 3
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.name = "attribPoints"
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.full_name = ".HeroExpLevUpdated.attribPoints"
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.number = 4
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.index = 3
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.label = 2
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.has_default_value = false
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.default_value = 0
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.type = 13
HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD.cpp_type = 3
HEROEXPLEVUPDATED.name = "HeroExpLevUpdated"
HEROEXPLEVUPDATED.full_name = ".HeroExpLevUpdated"
HEROEXPLEVUPDATED.nested_types = {}
HEROEXPLEVUPDATED.enum_types = {}
HEROEXPLEVUPDATED.fields = {
	HEROEXPLEVUPDATED_HERONO_FIELD,
	HEROEXPLEVUPDATED_LEV_FIELD,
	HEROEXPLEVUPDATED_EXP_FIELD,
	HEROEXPLEVUPDATED_ATTRIBPOINTS_FIELD
}
HEROEXPLEVUPDATED.is_extendable = false
HEROEXPLEVUPDATED.extensions = {}
HEROATTRIBUPDATED_HERONO_FIELD.name = "heroNo"
HEROATTRIBUPDATED_HERONO_FIELD.full_name = ".HeroAttribUpdated.heroNo"
HEROATTRIBUPDATED_HERONO_FIELD.number = 1
HEROATTRIBUPDATED_HERONO_FIELD.index = 0
HEROATTRIBUPDATED_HERONO_FIELD.label = 2
HEROATTRIBUPDATED_HERONO_FIELD.has_default_value = false
HEROATTRIBUPDATED_HERONO_FIELD.default_value = 0
HEROATTRIBUPDATED_HERONO_FIELD.type = 13
HEROATTRIBUPDATED_HERONO_FIELD.cpp_type = 3
HEROATTRIBUPDATED_ATTRIB1_FIELD.name = "attrib1"
HEROATTRIBUPDATED_ATTRIB1_FIELD.full_name = ".HeroAttribUpdated.attrib1"
HEROATTRIBUPDATED_ATTRIB1_FIELD.number = 2
HEROATTRIBUPDATED_ATTRIB1_FIELD.index = 1
HEROATTRIBUPDATED_ATTRIB1_FIELD.label = 2
HEROATTRIBUPDATED_ATTRIB1_FIELD.has_default_value = false
HEROATTRIBUPDATED_ATTRIB1_FIELD.default_value = 0
HEROATTRIBUPDATED_ATTRIB1_FIELD.type = 13
HEROATTRIBUPDATED_ATTRIB1_FIELD.cpp_type = 3
HEROATTRIBUPDATED_ATTRIB2_FIELD.name = "attrib2"
HEROATTRIBUPDATED_ATTRIB2_FIELD.full_name = ".HeroAttribUpdated.attrib2"
HEROATTRIBUPDATED_ATTRIB2_FIELD.number = 3
HEROATTRIBUPDATED_ATTRIB2_FIELD.index = 2
HEROATTRIBUPDATED_ATTRIB2_FIELD.label = 2
HEROATTRIBUPDATED_ATTRIB2_FIELD.has_default_value = false
HEROATTRIBUPDATED_ATTRIB2_FIELD.default_value = 0
HEROATTRIBUPDATED_ATTRIB2_FIELD.type = 13
HEROATTRIBUPDATED_ATTRIB2_FIELD.cpp_type = 3
HEROATTRIBUPDATED_ATTRIB3_FIELD.name = "attrib3"
HEROATTRIBUPDATED_ATTRIB3_FIELD.full_name = ".HeroAttribUpdated.attrib3"
HEROATTRIBUPDATED_ATTRIB3_FIELD.number = 4
HEROATTRIBUPDATED_ATTRIB3_FIELD.index = 3
HEROATTRIBUPDATED_ATTRIB3_FIELD.label = 2
HEROATTRIBUPDATED_ATTRIB3_FIELD.has_default_value = false
HEROATTRIBUPDATED_ATTRIB3_FIELD.default_value = 0
HEROATTRIBUPDATED_ATTRIB3_FIELD.type = 13
HEROATTRIBUPDATED_ATTRIB3_FIELD.cpp_type = 3
HEROATTRIBUPDATED_ATTRIB4_FIELD.name = "attrib4"
HEROATTRIBUPDATED_ATTRIB4_FIELD.full_name = ".HeroAttribUpdated.attrib4"
HEROATTRIBUPDATED_ATTRIB4_FIELD.number = 5
HEROATTRIBUPDATED_ATTRIB4_FIELD.index = 4
HEROATTRIBUPDATED_ATTRIB4_FIELD.label = 2
HEROATTRIBUPDATED_ATTRIB4_FIELD.has_default_value = false
HEROATTRIBUPDATED_ATTRIB4_FIELD.default_value = 0
HEROATTRIBUPDATED_ATTRIB4_FIELD.type = 13
HEROATTRIBUPDATED_ATTRIB4_FIELD.cpp_type = 3
HEROATTRIBUPDATED_ATTRIB5_FIELD.name = "attrib5"
HEROATTRIBUPDATED_ATTRIB5_FIELD.full_name = ".HeroAttribUpdated.attrib5"
HEROATTRIBUPDATED_ATTRIB5_FIELD.number = 6
HEROATTRIBUPDATED_ATTRIB5_FIELD.index = 5
HEROATTRIBUPDATED_ATTRIB5_FIELD.label = 2
HEROATTRIBUPDATED_ATTRIB5_FIELD.has_default_value = false
HEROATTRIBUPDATED_ATTRIB5_FIELD.default_value = 0
HEROATTRIBUPDATED_ATTRIB5_FIELD.type = 13
HEROATTRIBUPDATED_ATTRIB5_FIELD.cpp_type = 3
HEROATTRIBUPDATED_ATTRIB6_FIELD.name = "attrib6"
HEROATTRIBUPDATED_ATTRIB6_FIELD.full_name = ".HeroAttribUpdated.attrib6"
HEROATTRIBUPDATED_ATTRIB6_FIELD.number = 7
HEROATTRIBUPDATED_ATTRIB6_FIELD.index = 6
HEROATTRIBUPDATED_ATTRIB6_FIELD.label = 2
HEROATTRIBUPDATED_ATTRIB6_FIELD.has_default_value = false
HEROATTRIBUPDATED_ATTRIB6_FIELD.default_value = 0
HEROATTRIBUPDATED_ATTRIB6_FIELD.type = 13
HEROATTRIBUPDATED_ATTRIB6_FIELD.cpp_type = 3
HEROATTRIBUPDATED_ATTRIB7_FIELD.name = "attrib7"
HEROATTRIBUPDATED_ATTRIB7_FIELD.full_name = ".HeroAttribUpdated.attrib7"
HEROATTRIBUPDATED_ATTRIB7_FIELD.number = 8
HEROATTRIBUPDATED_ATTRIB7_FIELD.index = 7
HEROATTRIBUPDATED_ATTRIB7_FIELD.label = 2
HEROATTRIBUPDATED_ATTRIB7_FIELD.has_default_value = false
HEROATTRIBUPDATED_ATTRIB7_FIELD.default_value = 0
HEROATTRIBUPDATED_ATTRIB7_FIELD.type = 13
HEROATTRIBUPDATED_ATTRIB7_FIELD.cpp_type = 3
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.name = "attribPoints"
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.full_name = ".HeroAttribUpdated.attribPoints"
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.number = 9
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.index = 8
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.label = 2
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.has_default_value = false
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.default_value = 0
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.type = 13
HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD.cpp_type = 3
HEROATTRIBUPDATED.name = "HeroAttribUpdated"
HEROATTRIBUPDATED.full_name = ".HeroAttribUpdated"
HEROATTRIBUPDATED.nested_types = {}
HEROATTRIBUPDATED.enum_types = {}
HEROATTRIBUPDATED.fields = {
	HEROATTRIBUPDATED_HERONO_FIELD,
	HEROATTRIBUPDATED_ATTRIB1_FIELD,
	HEROATTRIBUPDATED_ATTRIB2_FIELD,
	HEROATTRIBUPDATED_ATTRIB3_FIELD,
	HEROATTRIBUPDATED_ATTRIB4_FIELD,
	HEROATTRIBUPDATED_ATTRIB5_FIELD,
	HEROATTRIBUPDATED_ATTRIB6_FIELD,
	HEROATTRIBUPDATED_ATTRIB7_FIELD,
	HEROATTRIBUPDATED_ATTRIBPOINTS_FIELD
}
HEROATTRIBUPDATED.is_extendable = false
HEROATTRIBUPDATED.extensions = {}
REQADDHEROATTRIB_HERONO_FIELD.name = "heroNo"
REQADDHEROATTRIB_HERONO_FIELD.full_name = ".ReqAddHeroAttrib.heroNo"
REQADDHEROATTRIB_HERONO_FIELD.number = 1
REQADDHEROATTRIB_HERONO_FIELD.index = 0
REQADDHEROATTRIB_HERONO_FIELD.label = 2
REQADDHEROATTRIB_HERONO_FIELD.has_default_value = false
REQADDHEROATTRIB_HERONO_FIELD.default_value = 0
REQADDHEROATTRIB_HERONO_FIELD.type = 13
REQADDHEROATTRIB_HERONO_FIELD.cpp_type = 3
REQADDHEROATTRIB_ATTRIB1_FIELD.name = "attrib1"
REQADDHEROATTRIB_ATTRIB1_FIELD.full_name = ".ReqAddHeroAttrib.attrib1"
REQADDHEROATTRIB_ATTRIB1_FIELD.number = 2
REQADDHEROATTRIB_ATTRIB1_FIELD.index = 1
REQADDHEROATTRIB_ATTRIB1_FIELD.label = 2
REQADDHEROATTRIB_ATTRIB1_FIELD.has_default_value = false
REQADDHEROATTRIB_ATTRIB1_FIELD.default_value = 0
REQADDHEROATTRIB_ATTRIB1_FIELD.type = 13
REQADDHEROATTRIB_ATTRIB1_FIELD.cpp_type = 3
REQADDHEROATTRIB_ATTRIB2_FIELD.name = "attrib2"
REQADDHEROATTRIB_ATTRIB2_FIELD.full_name = ".ReqAddHeroAttrib.attrib2"
REQADDHEROATTRIB_ATTRIB2_FIELD.number = 3
REQADDHEROATTRIB_ATTRIB2_FIELD.index = 2
REQADDHEROATTRIB_ATTRIB2_FIELD.label = 2
REQADDHEROATTRIB_ATTRIB2_FIELD.has_default_value = false
REQADDHEROATTRIB_ATTRIB2_FIELD.default_value = 0
REQADDHEROATTRIB_ATTRIB2_FIELD.type = 13
REQADDHEROATTRIB_ATTRIB2_FIELD.cpp_type = 3
REQADDHEROATTRIB_ATTRIB3_FIELD.name = "attrib3"
REQADDHEROATTRIB_ATTRIB3_FIELD.full_name = ".ReqAddHeroAttrib.attrib3"
REQADDHEROATTRIB_ATTRIB3_FIELD.number = 4
REQADDHEROATTRIB_ATTRIB3_FIELD.index = 3
REQADDHEROATTRIB_ATTRIB3_FIELD.label = 2
REQADDHEROATTRIB_ATTRIB3_FIELD.has_default_value = false
REQADDHEROATTRIB_ATTRIB3_FIELD.default_value = 0
REQADDHEROATTRIB_ATTRIB3_FIELD.type = 13
REQADDHEROATTRIB_ATTRIB3_FIELD.cpp_type = 3
REQADDHEROATTRIB_ATTRIB4_FIELD.name = "attrib4"
REQADDHEROATTRIB_ATTRIB4_FIELD.full_name = ".ReqAddHeroAttrib.attrib4"
REQADDHEROATTRIB_ATTRIB4_FIELD.number = 5
REQADDHEROATTRIB_ATTRIB4_FIELD.index = 4
REQADDHEROATTRIB_ATTRIB4_FIELD.label = 2
REQADDHEROATTRIB_ATTRIB4_FIELD.has_default_value = false
REQADDHEROATTRIB_ATTRIB4_FIELD.default_value = 0
REQADDHEROATTRIB_ATTRIB4_FIELD.type = 13
REQADDHEROATTRIB_ATTRIB4_FIELD.cpp_type = 3
REQADDHEROATTRIB_ATTRIB5_FIELD.name = "attrib5"
REQADDHEROATTRIB_ATTRIB5_FIELD.full_name = ".ReqAddHeroAttrib.attrib5"
REQADDHEROATTRIB_ATTRIB5_FIELD.number = 6
REQADDHEROATTRIB_ATTRIB5_FIELD.index = 5
REQADDHEROATTRIB_ATTRIB5_FIELD.label = 2
REQADDHEROATTRIB_ATTRIB5_FIELD.has_default_value = false
REQADDHEROATTRIB_ATTRIB5_FIELD.default_value = 0
REQADDHEROATTRIB_ATTRIB5_FIELD.type = 13
REQADDHEROATTRIB_ATTRIB5_FIELD.cpp_type = 3
REQADDHEROATTRIB_ATTRIB6_FIELD.name = "attrib6"
REQADDHEROATTRIB_ATTRIB6_FIELD.full_name = ".ReqAddHeroAttrib.attrib6"
REQADDHEROATTRIB_ATTRIB6_FIELD.number = 7
REQADDHEROATTRIB_ATTRIB6_FIELD.index = 6
REQADDHEROATTRIB_ATTRIB6_FIELD.label = 2
REQADDHEROATTRIB_ATTRIB6_FIELD.has_default_value = false
REQADDHEROATTRIB_ATTRIB6_FIELD.default_value = 0
REQADDHEROATTRIB_ATTRIB6_FIELD.type = 13
REQADDHEROATTRIB_ATTRIB6_FIELD.cpp_type = 3
REQADDHEROATTRIB_ATTRIB7_FIELD.name = "attrib7"
REQADDHEROATTRIB_ATTRIB7_FIELD.full_name = ".ReqAddHeroAttrib.attrib7"
REQADDHEROATTRIB_ATTRIB7_FIELD.number = 8
REQADDHEROATTRIB_ATTRIB7_FIELD.index = 7
REQADDHEROATTRIB_ATTRIB7_FIELD.label = 2
REQADDHEROATTRIB_ATTRIB7_FIELD.has_default_value = false
REQADDHEROATTRIB_ATTRIB7_FIELD.default_value = 0
REQADDHEROATTRIB_ATTRIB7_FIELD.type = 13
REQADDHEROATTRIB_ATTRIB7_FIELD.cpp_type = 3
REQADDHEROATTRIB.name = "ReqAddHeroAttrib"
REQADDHEROATTRIB.full_name = ".ReqAddHeroAttrib"
REQADDHEROATTRIB.nested_types = {}
REQADDHEROATTRIB.enum_types = {}
REQADDHEROATTRIB.fields = {
	REQADDHEROATTRIB_HERONO_FIELD,
	REQADDHEROATTRIB_ATTRIB1_FIELD,
	REQADDHEROATTRIB_ATTRIB2_FIELD,
	REQADDHEROATTRIB_ATTRIB3_FIELD,
	REQADDHEROATTRIB_ATTRIB4_FIELD,
	REQADDHEROATTRIB_ATTRIB5_FIELD,
	REQADDHEROATTRIB_ATTRIB6_FIELD,
	REQADDHEROATTRIB_ATTRIB7_FIELD
}
REQADDHEROATTRIB.is_extendable = false
REQADDHEROATTRIB.extensions = {}
REQSETHEROTALENT_HERONO_FIELD.name = "heroNo"
REQSETHEROTALENT_HERONO_FIELD.full_name = ".ReqSetHeroTalent.heroNo"
REQSETHEROTALENT_HERONO_FIELD.number = 1
REQSETHEROTALENT_HERONO_FIELD.index = 0
REQSETHEROTALENT_HERONO_FIELD.label = 2
REQSETHEROTALENT_HERONO_FIELD.has_default_value = false
REQSETHEROTALENT_HERONO_FIELD.default_value = 0
REQSETHEROTALENT_HERONO_FIELD.type = 13
REQSETHEROTALENT_HERONO_FIELD.cpp_type = 3
REQSETHEROTALENT_TALENTTYPE_FIELD.name = "talentType"
REQSETHEROTALENT_TALENTTYPE_FIELD.full_name = ".ReqSetHeroTalent.talentType"
REQSETHEROTALENT_TALENTTYPE_FIELD.number = 2
REQSETHEROTALENT_TALENTTYPE_FIELD.index = 1
REQSETHEROTALENT_TALENTTYPE_FIELD.label = 2
REQSETHEROTALENT_TALENTTYPE_FIELD.has_default_value = false
REQSETHEROTALENT_TALENTTYPE_FIELD.default_value = 0
REQSETHEROTALENT_TALENTTYPE_FIELD.type = 13
REQSETHEROTALENT_TALENTTYPE_FIELD.cpp_type = 3
REQSETHEROTALENT_TALENTID_FIELD.name = "talentId"
REQSETHEROTALENT_TALENTID_FIELD.full_name = ".ReqSetHeroTalent.talentId"
REQSETHEROTALENT_TALENTID_FIELD.number = 3
REQSETHEROTALENT_TALENTID_FIELD.index = 2
REQSETHEROTALENT_TALENTID_FIELD.label = 2
REQSETHEROTALENT_TALENTID_FIELD.has_default_value = false
REQSETHEROTALENT_TALENTID_FIELD.default_value = 0
REQSETHEROTALENT_TALENTID_FIELD.type = 13
REQSETHEROTALENT_TALENTID_FIELD.cpp_type = 3
REQSETHEROTALENT.name = "ReqSetHeroTalent"
REQSETHEROTALENT.full_name = ".ReqSetHeroTalent"
REQSETHEROTALENT.nested_types = {}
REQSETHEROTALENT.enum_types = {}
REQSETHEROTALENT.fields = {
	REQSETHEROTALENT_HERONO_FIELD,
	REQSETHEROTALENT_TALENTTYPE_FIELD,
	REQSETHEROTALENT_TALENTID_FIELD
}
REQSETHEROTALENT.is_extendable = false
REQSETHEROTALENT.extensions = {}
REQREMOVEHEROTALENT_HERONO_FIELD.name = "heroNo"
REQREMOVEHEROTALENT_HERONO_FIELD.full_name = ".ReqRemoveHeroTalent.heroNo"
REQREMOVEHEROTALENT_HERONO_FIELD.number = 1
REQREMOVEHEROTALENT_HERONO_FIELD.index = 0
REQREMOVEHEROTALENT_HERONO_FIELD.label = 2
REQREMOVEHEROTALENT_HERONO_FIELD.has_default_value = false
REQREMOVEHEROTALENT_HERONO_FIELD.default_value = 0
REQREMOVEHEROTALENT_HERONO_FIELD.type = 13
REQREMOVEHEROTALENT_HERONO_FIELD.cpp_type = 3
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.name = "talentType"
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.full_name = ".ReqRemoveHeroTalent.talentType"
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.number = 2
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.index = 1
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.label = 2
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.has_default_value = false
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.default_value = 0
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.type = 13
REQREMOVEHEROTALENT_TALENTTYPE_FIELD.cpp_type = 3
REQREMOVEHEROTALENT_TALENTID_FIELD.name = "talentId"
REQREMOVEHEROTALENT_TALENTID_FIELD.full_name = ".ReqRemoveHeroTalent.talentId"
REQREMOVEHEROTALENT_TALENTID_FIELD.number = 3
REQREMOVEHEROTALENT_TALENTID_FIELD.index = 2
REQREMOVEHEROTALENT_TALENTID_FIELD.label = 2
REQREMOVEHEROTALENT_TALENTID_FIELD.has_default_value = false
REQREMOVEHEROTALENT_TALENTID_FIELD.default_value = 0
REQREMOVEHEROTALENT_TALENTID_FIELD.type = 13
REQREMOVEHEROTALENT_TALENTID_FIELD.cpp_type = 3
REQREMOVEHEROTALENT.name = "ReqRemoveHeroTalent"
REQREMOVEHEROTALENT.full_name = ".ReqRemoveHeroTalent"
REQREMOVEHEROTALENT.nested_types = {}
REQREMOVEHEROTALENT.enum_types = {}
REQREMOVEHEROTALENT.fields = {
	REQREMOVEHEROTALENT_HERONO_FIELD,
	REQREMOVEHEROTALENT_TALENTTYPE_FIELD,
	REQREMOVEHEROTALENT_TALENTID_FIELD
}
REQREMOVEHEROTALENT.is_extendable = false
REQREMOVEHEROTALENT.extensions = {}
HEROTALENTUPDATED_HERONO_FIELD.name = "heroNo"
HEROTALENTUPDATED_HERONO_FIELD.full_name = ".HeroTalentUpdated.heroNo"
HEROTALENTUPDATED_HERONO_FIELD.number = 1
HEROTALENTUPDATED_HERONO_FIELD.index = 0
HEROTALENTUPDATED_HERONO_FIELD.label = 2
HEROTALENTUPDATED_HERONO_FIELD.has_default_value = false
HEROTALENTUPDATED_HERONO_FIELD.default_value = 0
HEROTALENTUPDATED_HERONO_FIELD.type = 13
HEROTALENTUPDATED_HERONO_FIELD.cpp_type = 3
HEROTALENTUPDATED_TALENTTYPE_FIELD.name = "talentType"
HEROTALENTUPDATED_TALENTTYPE_FIELD.full_name = ".HeroTalentUpdated.talentType"
HEROTALENTUPDATED_TALENTTYPE_FIELD.number = 2
HEROTALENTUPDATED_TALENTTYPE_FIELD.index = 1
HEROTALENTUPDATED_TALENTTYPE_FIELD.label = 2
HEROTALENTUPDATED_TALENTTYPE_FIELD.has_default_value = false
HEROTALENTUPDATED_TALENTTYPE_FIELD.default_value = 0
HEROTALENTUPDATED_TALENTTYPE_FIELD.type = 13
HEROTALENTUPDATED_TALENTTYPE_FIELD.cpp_type = 3
HEROTALENTUPDATED_TALENTID_FIELD.name = "talentId"
HEROTALENTUPDATED_TALENTID_FIELD.full_name = ".HeroTalentUpdated.talentId"
HEROTALENTUPDATED_TALENTID_FIELD.number = 3
HEROTALENTUPDATED_TALENTID_FIELD.index = 2
HEROTALENTUPDATED_TALENTID_FIELD.label = 2
HEROTALENTUPDATED_TALENTID_FIELD.has_default_value = false
HEROTALENTUPDATED_TALENTID_FIELD.default_value = 0
HEROTALENTUPDATED_TALENTID_FIELD.type = 13
HEROTALENTUPDATED_TALENTID_FIELD.cpp_type = 3
HEROTALENTUPDATED_ON_FIELD.name = "on"
HEROTALENTUPDATED_ON_FIELD.full_name = ".HeroTalentUpdated.on"
HEROTALENTUPDATED_ON_FIELD.number = 4
HEROTALENTUPDATED_ON_FIELD.index = 3
HEROTALENTUPDATED_ON_FIELD.label = 2
HEROTALENTUPDATED_ON_FIELD.has_default_value = false
HEROTALENTUPDATED_ON_FIELD.default_value = false
HEROTALENTUPDATED_ON_FIELD.type = 8
HEROTALENTUPDATED_ON_FIELD.cpp_type = 7
HEROTALENTUPDATED.name = "HeroTalentUpdated"
HEROTALENTUPDATED.full_name = ".HeroTalentUpdated"
HEROTALENTUPDATED.nested_types = {}
HEROTALENTUPDATED.enum_types = {}
HEROTALENTUPDATED.fields = {
	HEROTALENTUPDATED_HERONO_FIELD,
	HEROTALENTUPDATED_TALENTTYPE_FIELD,
	HEROTALENTUPDATED_TALENTID_FIELD,
	HEROTALENTUPDATED_ON_FIELD
}
HEROTALENTUPDATED.is_extendable = false
HEROTALENTUPDATED.extensions = {}
REQSAVEHEROSHORTCUT_HERONO_FIELD.name = "heroNo"
REQSAVEHEROSHORTCUT_HERONO_FIELD.full_name = ".ReqSaveHeroShortcut.heroNo"
REQSAVEHEROSHORTCUT_HERONO_FIELD.number = 1
REQSAVEHEROSHORTCUT_HERONO_FIELD.index = 0
REQSAVEHEROSHORTCUT_HERONO_FIELD.label = 2
REQSAVEHEROSHORTCUT_HERONO_FIELD.has_default_value = false
REQSAVEHEROSHORTCUT_HERONO_FIELD.default_value = 0
REQSAVEHEROSHORTCUT_HERONO_FIELD.type = 13
REQSAVEHEROSHORTCUT_HERONO_FIELD.cpp_type = 3
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.name = "shortcuts"
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.full_name = ".ReqSaveHeroShortcut.shortcuts"
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.number = 2
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.index = 1
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.label = 2
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.has_default_value = false
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.default_value = nil
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.message_type = SHORTCUTS
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.type = 11
REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD.cpp_type = 10
REQSAVEHEROSHORTCUT.name = "ReqSaveHeroShortcut"
REQSAVEHEROSHORTCUT.full_name = ".ReqSaveHeroShortcut"
REQSAVEHEROSHORTCUT.nested_types = {}
REQSAVEHEROSHORTCUT.enum_types = {}
REQSAVEHEROSHORTCUT.fields = {
	REQSAVEHEROSHORTCUT_HERONO_FIELD,
	REQSAVEHEROSHORTCUT_SHORTCUTS_FIELD
}
REQSAVEHEROSHORTCUT.is_extendable = false
REQSAVEHEROSHORTCUT.extensions = {}
RESPSAVEHEROSHORTCUTDONE.name = "RespSaveHeroShortcutDone"
RESPSAVEHEROSHORTCUTDONE.full_name = ".RespSaveHeroShortcutDone"
RESPSAVEHEROSHORTCUTDONE.nested_types = {}
RESPSAVEHEROSHORTCUTDONE.enum_types = {}
RESPSAVEHEROSHORTCUTDONE.fields = {}
RESPSAVEHEROSHORTCUTDONE.is_extendable = false
RESPSAVEHEROSHORTCUTDONE.extensions = {}
AddHeroInfo = protobuf.Message(ADDHEROINFO)
HeroAttribUpdated = protobuf.Message(HEROATTRIBUPDATED)
HeroExpLevUpdated = protobuf.Message(HEROEXPLEVUPDATED)
HeroInfo = protobuf.Message(HEROINFO)
HeroInfoList = protobuf.Message(HEROINFOLIST)
HeroTalentUpdated = protobuf.Message(HEROTALENTUPDATED)
ReqAddHeroAttrib = protobuf.Message(REQADDHEROATTRIB)
ReqRemoveHeroTalent = protobuf.Message(REQREMOVEHEROTALENT)
ReqSaveHeroShortcut = protobuf.Message(REQSAVEHEROSHORTCUT)
ReqSetHeroTalent = protobuf.Message(REQSETHEROTALENT)
ReqUnlockHero = protobuf.Message(REQUNLOCKHERO)
ReqUseExpItem = protobuf.Message(REQUSEEXPITEM)
RespSaveHeroShortcutDone = protobuf.Message(RESPSAVEHEROSHORTCUTDONE)
Shortcut = protobuf.Message(SHORTCUT)
Shortcuts = protobuf.Message(SHORTCUTS)
TalentItem = protobuf.Message(TALENTITEM)
TalentTree = protobuf.Message(TALENTTREE)
