-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Protocol/Protobuf/BattleChat_pb.lua

local protobuf = require("protobuf/protobuf")

module("LuaScript/Protocol/Protobuf/BattleChat_pb")

CHATINFO = protobuf.Descriptor()

local CHATINFO_CHATTYPE_FIELD = protobuf.FieldDescriptor()
local CHATINFO_CONTENT_FIELD = protobuf.FieldDescriptor()
local CHATINFO_CHATTIME_FIELD = protobuf.FieldDescriptor()
local CHATINFO_FROMID_FIELD = protobuf.FieldDescriptor()
local CHATINFO_FROMNAME_FIELD = protobuf.FieldDescriptor()
local CHATINFO_FROMSERVERID_FIELD = protobuf.FieldDescriptor()
local CHATINFO_FROMICON_FIELD = protobuf.FieldDescriptor()
local CHATINFO_FROMICONURL_FIELD = protobuf.FieldDescriptor()
local CHATINFO_TOID_FIELD = protobuf.FieldDescriptor()
local CHATINFO_TONAME_FIELD = protobuf.FieldDescriptor()
local CHATINFO_TOSERVERID_FIELD = protobuf.FieldDescriptor()
local CHATINFO_TOUNIONID_FIELD = protobuf.FieldDescriptor()

CHATINFOS = protobuf.Descriptor()

local CHATINFOS_CHATINFOLIST_FIELD = protobuf.FieldDescriptor()

CHATINFO_CHATTYPE_FIELD.name = "chatType"
CHATINFO_CHATTYPE_FIELD.full_name = ".ChatInfo.chatType"
CHATINFO_CHATTYPE_FIELD.number = 1
CHATINFO_CHATTYPE_FIELD.index = 0
CHATINFO_CHATTYPE_FIELD.label = 2
CHATINFO_CHATTYPE_FIELD.has_default_value = false
CHATINFO_CHATTYPE_FIELD.default_value = 0
CHATINFO_CHATTYPE_FIELD.type = 13
CHATINFO_CHATTYPE_FIELD.cpp_type = 3
CHATINFO_CONTENT_FIELD.name = "content"
CHATINFO_CONTENT_FIELD.full_name = ".ChatInfo.content"
CHATINFO_CONTENT_FIELD.number = 2
CHATINFO_CONTENT_FIELD.index = 1
CHATINFO_CONTENT_FIELD.label = 2
CHATINFO_CONTENT_FIELD.has_default_value = false
CHATINFO_CONTENT_FIELD.default_value = ""
CHATINFO_CONTENT_FIELD.type = 9
CHATINFO_CONTENT_FIELD.cpp_type = 9
CHATINFO_CHATTIME_FIELD.name = "chatTime"
CHATINFO_CHATTIME_FIELD.full_name = ".ChatInfo.chatTime"
CHATINFO_CHATTIME_FIELD.number = 3
CHATINFO_CHATTIME_FIELD.index = 2
CHATINFO_CHATTIME_FIELD.label = 1
CHATINFO_CHATTIME_FIELD.has_default_value = false
CHATINFO_CHATTIME_FIELD.default_value = 0
CHATINFO_CHATTIME_FIELD.type = 13
CHATINFO_CHATTIME_FIELD.cpp_type = 3
CHATINFO_FROMID_FIELD.name = "fromId"
CHATINFO_FROMID_FIELD.full_name = ".ChatInfo.fromId"
CHATINFO_FROMID_FIELD.number = 4
CHATINFO_FROMID_FIELD.index = 3
CHATINFO_FROMID_FIELD.label = 1
CHATINFO_FROMID_FIELD.has_default_value = false
CHATINFO_FROMID_FIELD.default_value = 0
CHATINFO_FROMID_FIELD.type = 13
CHATINFO_FROMID_FIELD.cpp_type = 3
CHATINFO_FROMNAME_FIELD.name = "fromName"
CHATINFO_FROMNAME_FIELD.full_name = ".ChatInfo.fromName"
CHATINFO_FROMNAME_FIELD.number = 5
CHATINFO_FROMNAME_FIELD.index = 4
CHATINFO_FROMNAME_FIELD.label = 1
CHATINFO_FROMNAME_FIELD.has_default_value = false
CHATINFO_FROMNAME_FIELD.default_value = ""
CHATINFO_FROMNAME_FIELD.type = 9
CHATINFO_FROMNAME_FIELD.cpp_type = 9
CHATINFO_FROMSERVERID_FIELD.name = "fromServerId"
CHATINFO_FROMSERVERID_FIELD.full_name = ".ChatInfo.fromServerId"
CHATINFO_FROMSERVERID_FIELD.number = 6
CHATINFO_FROMSERVERID_FIELD.index = 5
CHATINFO_FROMSERVERID_FIELD.label = 1
CHATINFO_FROMSERVERID_FIELD.has_default_value = false
CHATINFO_FROMSERVERID_FIELD.default_value = 0
CHATINFO_FROMSERVERID_FIELD.type = 13
CHATINFO_FROMSERVERID_FIELD.cpp_type = 3
CHATINFO_FROMICON_FIELD.name = "fromIcon"
CHATINFO_FROMICON_FIELD.full_name = ".ChatInfo.fromIcon"
CHATINFO_FROMICON_FIELD.number = 7
CHATINFO_FROMICON_FIELD.index = 6
CHATINFO_FROMICON_FIELD.label = 1
CHATINFO_FROMICON_FIELD.has_default_value = false
CHATINFO_FROMICON_FIELD.default_value = 0
CHATINFO_FROMICON_FIELD.type = 13
CHATINFO_FROMICON_FIELD.cpp_type = 3
CHATINFO_FROMICONURL_FIELD.name = "fromIconUrl"
CHATINFO_FROMICONURL_FIELD.full_name = ".ChatInfo.fromIconUrl"
CHATINFO_FROMICONURL_FIELD.number = 8
CHATINFO_FROMICONURL_FIELD.index = 7
CHATINFO_FROMICONURL_FIELD.label = 1
CHATINFO_FROMICONURL_FIELD.has_default_value = false
CHATINFO_FROMICONURL_FIELD.default_value = ""
CHATINFO_FROMICONURL_FIELD.type = 9
CHATINFO_FROMICONURL_FIELD.cpp_type = 9
CHATINFO_TOID_FIELD.name = "toId"
CHATINFO_TOID_FIELD.full_name = ".ChatInfo.toId"
CHATINFO_TOID_FIELD.number = 9
CHATINFO_TOID_FIELD.index = 8
CHATINFO_TOID_FIELD.label = 1
CHATINFO_TOID_FIELD.has_default_value = false
CHATINFO_TOID_FIELD.default_value = 0
CHATINFO_TOID_FIELD.type = 13
CHATINFO_TOID_FIELD.cpp_type = 3
CHATINFO_TONAME_FIELD.name = "toName"
CHATINFO_TONAME_FIELD.full_name = ".ChatInfo.toName"
CHATINFO_TONAME_FIELD.number = 10
CHATINFO_TONAME_FIELD.index = 9
CHATINFO_TONAME_FIELD.label = 1
CHATINFO_TONAME_FIELD.has_default_value = false
CHATINFO_TONAME_FIELD.default_value = ""
CHATINFO_TONAME_FIELD.type = 9
CHATINFO_TONAME_FIELD.cpp_type = 9
CHATINFO_TOSERVERID_FIELD.name = "toServerId"
CHATINFO_TOSERVERID_FIELD.full_name = ".ChatInfo.toServerId"
CHATINFO_TOSERVERID_FIELD.number = 11
CHATINFO_TOSERVERID_FIELD.index = 10
CHATINFO_TOSERVERID_FIELD.label = 1
CHATINFO_TOSERVERID_FIELD.has_default_value = false
CHATINFO_TOSERVERID_FIELD.default_value = 0
CHATINFO_TOSERVERID_FIELD.type = 13
CHATINFO_TOSERVERID_FIELD.cpp_type = 3
CHATINFO_TOUNIONID_FIELD.name = "toUnionId"
CHATINFO_TOUNIONID_FIELD.full_name = ".ChatInfo.toUnionId"
CHATINFO_TOUNIONID_FIELD.number = 12
CHATINFO_TOUNIONID_FIELD.index = 11
CHATINFO_TOUNIONID_FIELD.label = 1
CHATINFO_TOUNIONID_FIELD.has_default_value = false
CHATINFO_TOUNIONID_FIELD.default_value = 0
CHATINFO_TOUNIONID_FIELD.type = 13
CHATINFO_TOUNIONID_FIELD.cpp_type = 3
CHATINFO.name = "ChatInfo"
CHATINFO.full_name = ".ChatInfo"
CHATINFO.nested_types = {}
CHATINFO.enum_types = {}
CHATINFO.fields = {
	CHATINFO_CHATTYPE_FIELD,
	CHATINFO_CONTENT_FIELD,
	CHATINFO_CHATTIME_FIELD,
	CHATINFO_FROMID_FIELD,
	CHATINFO_FROMNAME_FIELD,
	CHATINFO_FROMSERVERID_FIELD,
	CHATINFO_FROMICON_FIELD,
	CHATINFO_FROMICONURL_FIELD,
	CHATINFO_TOID_FIELD,
	CHATINFO_TONAME_FIELD,
	CHATINFO_TOSERVERID_FIELD,
	CHATINFO_TOUNIONID_FIELD
}
CHATINFO.is_extendable = false
CHATINFO.extensions = {}
CHATINFOS_CHATINFOLIST_FIELD.name = "chatInfoList"
CHATINFOS_CHATINFOLIST_FIELD.full_name = ".ChatInfos.chatInfoList"
CHATINFOS_CHATINFOLIST_FIELD.number = 1
CHATINFOS_CHATINFOLIST_FIELD.index = 0
CHATINFOS_CHATINFOLIST_FIELD.label = 3
CHATINFOS_CHATINFOLIST_FIELD.has_default_value = false
CHATINFOS_CHATINFOLIST_FIELD.default_value = {}
CHATINFOS_CHATINFOLIST_FIELD.message_type = CHATINFO
CHATINFOS_CHATINFOLIST_FIELD.type = 11
CHATINFOS_CHATINFOLIST_FIELD.cpp_type = 10
CHATINFOS.name = "ChatInfos"
CHATINFOS.full_name = ".ChatInfos"
CHATINFOS.nested_types = {}
CHATINFOS.enum_types = {}
CHATINFOS.fields = {
	CHATINFOS_CHATINFOLIST_FIELD
}
CHATINFOS.is_extendable = false
CHATINFOS.extensions = {}
ChatInfo = protobuf.Message(CHATINFO)
ChatInfos = protobuf.Message(CHATINFOS)
