-- chunkname: @f:/unity/pascalswager_steam1/assets/LuaScript/Server/Code/BattleCodeToRoom.lua

local BattleCodeToRoom = {
	USER_ALREADY_IN_ROOM = 2,
	SAME_GLB_ACCOUNT_ALREADY_EXISTED = 12,
	GAME_IS_BEGINNING = 5,
	CANCEL_MATCH_GAME_IN_ZONE_FAILED = 13,
	CANT_CONNECT_TO_SEARCH_BATTLE = 11,
	USER_IS_MATCHING = 6,
	CANT_FIND_ROOM = 3,
	CONFIRM_ENTER_GAME_TIMEOUT = 7,
	ALREADY_CONFIRMED_HERO = 9,
	NO_MATCHED_ROOM = 1,
	CHOOSE_HERO_TIMEOUT = 8,
	CANT_CONNECT_TO_SEARCH_SERVER = 10,
	CANT_FIND_USER_IN_ROOM = 4
}

return BattleCodeToRoom
